### ISSUE TITLE
Lỗi - Hàng hóa không thuộc kho

### ISSUE THREAD

**Issue by le-an-87** [dh-hos/dhg.hosptaltreatment#100]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.1: Phiếu ghi nhận lỗi phát sinh DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN LỖI PHÁT SINH</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Ân**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **10/04/2023**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `Tất cả`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **Tất cả**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `an_phusan_hhktk_005263`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`](link_csdl)

###### ![chi_tiet_loi](https://img.shields.io/badge/Chi%20tiết%20lỗi%20phát%20sinh-:-blue?style=for-the-badge&logo=github)

-  ![loi_benh_nhan](https://img.shields.io/badge/Chi%20tiết%20bệnh%20nhân-:-blue?style=plastic&logo=github)
   > _**MaBN**_: `2023025627` - _**MaKB**_: `2303018892` - _**MaBA**_: `005263` _**NgayKCB**_: `07/04/2023` - _**MaDV**_: `16` - _**ThangKT**_: `04` - _**NamKT**_: `2023`
-  ![loi_thuoc](https://img.shields.io/badge/Chi%20tiết%20thuốc-:-blue?style=plastic&logo=github)
   > _**KhoChan**_: `13` - _**TuTruc**_: `NT8` - _**MaHH**_: `GA74` - _**SoHD**_: `M91.X23.0407.142502` - _**NgayHD**_: `07/04/2023` - _**ThangKT**_: `04` - _**NamKT**_: `2023`

###### ![mo_ta_loi](https://img.shields.io/badge/Mô%20tả%20thông%20tin%20lỗi-:-blue?style=for-the-badge&logo=github)

```
Chức năng lấy lại toa củ:
khi sử dụng chức năng Lấy lại toa này treat ghi nhận sai lô so với tủ trực ra toa hiện tại.

```
chức năng lấy lại toa thuốc
![image](https://user-images.githubusercontent.com/96155021/230841706-5794c125-f1ef-4891-bb83-97345bea4e4a.png)

tồn kho tủ trực hiện tại
![image](https://user-images.githubusercontent.com/96155021/230841839-22fcab5d-6e78-48b2-957d-aaf96c506033.png)

**Comment by vuongdh** [comment]
@le-an-87 [Bản fix lỗi](http://www.fsend.vn/download/ge-_fljhS0CToTBfQGpo38Oco-QuHFb5)

**Comment by le-an-87** [comment]
Đa fix!
