### ISSUE TITLE
Lỗi - Sai thành tiền khi trả thuốc.

### ISSUE THREAD

**Issue by lqbinh1987** [dh-hos/dhg.hosptaltreatment#102]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.1: Phiếu ghi nhận lỗi phát sinh DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN LỖI PHÁT SINH</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Bình**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **11/04/2023**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `92004`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **BV ĐKTP CT**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `duc_dktp_lechtien01`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`](link_csdl)

###### ![chi_tiet_loi](https://img.shields.io/badge/Chi%20tiết%20lỗi%20phát%20sinh-:-blue?style=for-the-badge&logo=github)

-  ![loi_benh_nhan](https://img.shields.io/badge/Chi%20tiết%20bệnh%20nhân-:-blue?style=plastic&logo=github)
   > _**MaBN**_: `2023000126` - _**MaKB**_: `MaKB` - _**MaBA**_: `004404` _**NgayKCB**_: `NgayKCB` - _**MaPhong**_: `MaPhong` - _**MaDV**_: `43` - _**ThangKT**_: `04` - _**NamKT**_: `2023`
-  ![loi_thuoc](https://img.shields.io/badge/Chi%20tiết%20thuốc-:-blue?style=plastic&logo=github)
   > _**KhoChan**_: `KhoChan` - _**KhoLe**_: `KhoLe` - _**MaHH**_: `MaHH` - _**SoHD**_: `SoHD` - _**NgayHD**_: `NgayHD` - _**ThangKT**_: `ThangKT` - _**NamKT**_: `NamKT`
-  ![loi_cls](https://img.shields.io/badge/Chi%20tiết%20CLS-:-blue?style=plastic&logo=github)
   > _**MaCLS**_: `MaCLS` - _**PhieuYC**_: `PhieuYC`
-  ![loi_bo_sung](https://img.shields.io/badge/Chi%20tiết%20bổ%20sung-:-blue?style=plastic&logo=github)
   > _**Khac**_: `Khac`

###### ![mo_ta_loi](https://img.shields.io/badge/Mô%20tả%20thông%20tin%20lỗi-:-blue?style=for-the-badge&logo=github)

Khi trả toa thuốc(trả thuốc lẻ, **KHÔNG PHẢI TRẢ cả toa**), thì thành tiền của BH và BN cùng chi trả bị sai, **số tiền BN cùng chi trả không thay đổi** so với trước khi trả, dẫn đến tổng tiền bh thanh toán và bn cùng chi trả bị sai.
_**Chú ý:**_ 
- **Toa nhận** là **trước** thời điểm được ghi nhận chứng nhận miễn.
- **Toa trả** là **sau** thời điểm được ghi nhận chứng nhận miễn.

Số chứng từ toa trả: GHH.T23.0315.075740
Chỉ cần thay đổi giá trị cột pshdxn.xoa 1 mặt hàng trong toa để xác định nhanh.

Trước khi trả
![image](https://user-images.githubusercontent.com/99630883/231375480-602e4829-7736-44d1-873c-634574a38cae.png)

Sau khi trả
![image](https://user-images.githubusercontent.com/99630883/231376595-2e206d0f-e2d8-4ff6-aacb-8ae228399bf0.png)

**Comment by vuongdh** [comment]
@lqbinh1987 em xem -
- ngày trả là ngày nào? thuộc dạng miễn hay không? 
- nếu trả khác tháng là không lấy đúng ngày trả được
- gõ cả toa (đúng số lượng xuất) nhưng nó sẽ khác với trả cả toa bằng cách lấy chứng từ xuất (chỉ tác dụng trong tháng)

**Comment by lqbinh1987** [comment]
- Ngày lập phiếu trả thuốc là ngày đang đang được miễn.
Ngày được chứng nhận miễn là 05/03/2023, các ngày nhận thuốc là tháng 02, ngày trả thuốc là ngày 13/03/2023.
- Hiện không cần lấy đúng ngày trả.
Này anh xem có hướng nào giải quyết cho BV, vì hiện tại đang lệch không đối chiếu được.

**Comment by vuongdh** [comment]
@lqbinh1987 Vậy là không được rồi, trong tháng còn hỗ trợ đc giờ sang tháng rồi hỗ trợ trả đúng ngày miễn thì sẽ lệch tồn kho

**Comment by vuongdh** [comment]
@lqbinh1987 Em hỏi bệnh viện xem, nếu đồng ý cập nhật tồn kho tháng 2, cắt chuyển lại toàn bộ thì tồn kho tháng 3, giờ ảnh hưởng đến tháng 4 luôn rồi ==> đồng ý làm như vậy thì mới hỗ trợ được

**Comment by vuongdh** [comment]
@lqbinh1987 anh thấy chổ hỗ trợ rồi: em chỉ cần chỉnh ngày trả lại thành ngày 4/3 là được

**Comment by vuongdh** [comment]
@lqbinh1987 nếu bệnh viện đồng ý chỉnh ngày trả lên trước ngày miễn (cho khớp dữ liệu xuất) thì em chỉnh ngày trả <= ngày miễn (5/3/2023) là được. 
Nếu chỉnh khác tháng thì phải làm các bước như anh nói ở trên
