### ISSUE TITLE
Yêu cầu - Thêm chức năng cấu hình thuốc kèm theo và chống chỉ định thuốc, cls kèm theo ICD 10 BV Phước Long Bạc Liêu

### ISSUE THREAD

**Issue by hvtuan1987** [dh-hos/dhg.hosptaltreatment#104]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.2: Phiếu ghi nhận Yêu cầu mới DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN YÊU CẦU CHỨC NĂNG MỚI</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Hà Văn Tuấn**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **17/04/2023**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `95006`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **Bệnh viện đa khoa huyện Phước Long**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `tuan_dbphuoclongbl`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`](link_csdl)

Yêu cầu -
- Thêm chức năng cấu hình thuốc kèm theo ICD 10  và chống chỉ định thuốc với ICD 10,
 - Cấu hình cls kèm theo ICD 10 BV Phước Long Bạc Liêu 

```

**Comment by vuongdh** [comment]
@hvtuan1987 này là yêu cầu bật chức năng: chỉ định, chống chỉ định cho BV Phước Long - Bạc Liêu phải không?

**Comment by vuongdh** [comment]
@hvtuan1987 đọc yêu cầu không biết làm thì luôn :D

**Comment by hvtuan1987** [comment]
@vuongdh : này là yêu cầu bật chức năng: chỉ định, chống chỉ định cho BV Phước Long - Bạc Liêu phải không?
Đúng rồi á anh !

**Comment by vuongdh** [comment]
@hvtuan1987 OK em

**Comment by vuongdh** [comment]
@hvtuan1987 [Bảng cập nhật](http://www.fsend.vn/download/VZ52DY_SN8n5Ki8-eZ9blOcD13J-Kp4E)
