### ISSUE TITLE
Lỗi - Chức năng chỉnh đối tượng không chọn check CN Miễn bị ẩn

### ISSUE THREAD

**Issue by le-an-87** [dh-hos/dhg.hosptaltreatment#105]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.1: Phiếu ghi nhận lỗi phát sinh DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN LỖI PHÁT SINH</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **ÂN**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **20/04/2023**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `Tất cả`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **Tất cả**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `an_ungbuou_chinh_cnmien`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`](link_csdl)

###### ![chi_tiet_loi](https://img.shields.io/badge/Chi%20tiết%20lỗi%20phát%20sinh-:-blue?style=for-the-badge&logo=github)

-  ![loi_benh_nhan](https://img.shields.io/badge/Chi%20tiết%20bệnh%20nhân-:-blue?style=plastic&logo=github)
   > _**MaBN**_: `2022047007` - _**MaKB**_: `2304008730` - _**MaBA**_: `006882` _**NgayKCB**_: `19/04/2023` - _**MaPhong**_: `NO13` - _**MaDV**_: `23` - _**ThangKT**_: `04` - _**NamKT**_: `2023`

###### ![mo_ta_loi](https://img.shields.io/badge/Mô%20tả%20thông%20tin%20lỗi-:-blue?style=for-the-badge&logo=github)

```
Chức năng chỉnh đối tượng - check CN miễn bị ẩn
-> không cập nhật đc giấy chứng nhận miễn cho bệnh nhân

```
![image](https://user-images.githubusercontent.com/96155021/233257286-d4cf4469-295a-4284-afed-886754eada48.png)

**Comment by vuongdh** [comment]
[Bản fix lỗi](http://www.fsend.vn/download/BTE2IyLGFKyCJkiHz3ICwUPhXhRD1Cxb)

Lưu ý thêm tham số: nt.cnmien cho phép người dùng tùy chọn áp dụng chứng nhận miễn cho bệnh nhân trái tuyến (theo NĐ 146)

**Comment by le-an-87** [comment]
bệnh nhân ở trạng thái đúng tuyến nhe anh!
bệnh có giấy chuyển viện mà bệnh nhân trái tuyến theo NĐ 146 gì

**Comment by le-an-87** [comment]
đã fix!
