### ISSUE TITLE
Yêu cầu - Hỗ trợ gửi dữ liệu Giấy chứng sinh, Giấy báo tử và giấy Khám sức khỏe lái xe theo đề án 06

### ISSUE THREAD

**Issue by nghivanbi** [dh-hos/dhg.hosptaltreatment#106]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.2: Phiếu ghi nhận Yêu cầu mới DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN YÊU CẦU CHỨC NĂNG MỚI</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Nghị Văn Bi**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **25/04/2023**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `ALL`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **Tất cả**

###### ![chi_tiet_yeu_cau](https://img.shields.io/badge/Chi%20tiết%20yêu%20cầu%20-:-blue?style=for-the-badge&logo=github)

```

[Thong - Mo ta goi thong tin ksk, gcs, gbt 20230425.pdf](https://github.com/dh-hos/dhg.hosptaltreatment/files/11320505/Thong.-.Mo.ta.goi.thong.tin.ksk.gcs.gbt.20230425.pdf)

```

**Comment by vuongdh** [comment]
Bản cập nhật [Treatment](http://www.fsend.vn/download/5szrtPDHvF0T-qCFJien0Lwzi-4vPlL9)

**Comment by le-an-87** [comment]
bản cập nhật treatment anh thiết kế ở đâu vậy anh?
bao gồm chức năng nào vậy?

**Comment by vuongdh** [comment]
![image](https://user-images.githubusercontent.com/32563776/234776595-ae7a8ef4-8cd5-44b7-8121-2429229da7d3.png)
![image](https://user-images.githubusercontent.com/32563776/234776653-59e431c1-d788-4e73-af28-86b621433409.png)
@le-an-87 Anh có gửi 1 lần cho em mà em quên rồi đó

**Comment by le-an-87** [comment]
1. alo anh @nghivanbi ơi!
chổ tham số này hiện tại là chưa tạo phải không anh!
![image](https://user-images.githubusercontent.com/96155021/234778859-b3d4601a-3396-4d31-afa1-9352c0a869a6.png)

đang gửi thế nào vậy @lequocthong29 !

2. Chổ cân nặng và chiều cao không nhập gửi không được anh @vuongdh
chổ này anh với Thống coi lại xem cần bắt chổ đó không nhe anh, bắt buộc hoặc không thì mình làm thống nhất với nhau luôn anh ơi!

3. Hiện tại bấm gửi GCS báo lỗi này đó anh!
![image](https://user-images.githubusercontent.com/96155021/234780813-62000d0a-12a6-42f0-86b7-d96e020a0ac6.png)

**Comment by le-an-87** [comment]
4. Giấy báo tử cổng lỗi nhe anh
![image](https://user-images.githubusercontent.com/96155021/234781821-1145903d-8381-413f-a91b-698c7f4cc4fd.png)

**Comment by nghivanbi** [comment]
Cập nhật và chạy lên để tạo tham số
Register: [v3.23.0427.1](http://www.fsend.vn/download/7uyX43SuCa1wHW8lZMG2lQCvsKjsIywY)

**Comment by nghivanbi** [comment]
@lequocthong29 hỗ trợ xử lý lỗi

**Comment by lequocthong29** [comment]
@vuongdh e cập nhật lại dll
![image](https://user-images.githubusercontent.com/110148171/234811604-82c08de3-a60d-4275-973c-983a49563748.png)

**Comment by le-an-87** [comment]
![image](https://user-images.githubusercontent.com/96155021/234816837-b9a8093c-ee27-4de9-9d65-5bf2974cd117.png)
bên anh không bị hả anh

**Comment by le-an-87** [comment]
alo @lequocthong29 em coi lại trước mấy chổ này nhe!
1. check ký theo bs em canh trái luôn hay tự giản gì đó.
2. mabn không tự tạo nhưng nhập không được.
3. Mã dân tộc nếu nhập sai thì cho thông báo nhe!

**Comment by lequocthong29** [comment]
![image](https://user-images.githubusercontent.com/110148171/235045685-72e2fda8-1cfb-4cc9-8fdb-623546c2cf76.png)
- Em cập nhật dll, fix lỗi version status.dll, cố định checkbox ký theo bác sỹ, thông báo nhập sai mã dân tộc, đổi combobox chọn tháng, tắt button chỉnh khi không có dữ liệu. @vuongdh @le-an-87

**Comment by vuongdh** [comment]
[Bảng cập nhật](https://gofile.me/78TQg/pceJMaMw9)

**Comment by le-an-87** [comment]
Các vấn đề ở đây chưa giải quyết nhe mấy anh!
-> 2. Chổ cân nặng và chiều cao không nhập gửi không được

Phát sinh lỗi mới
1.  chức năng xem báo lỗi
![image](https://user-images.githubusercontent.com/96155021/235342365-ade10239-1760-4ee9-ba30-50d8f0618eed.png)
2.  chức năng gửi báo lỗi
![image](https://user-images.githubusercontent.com/96155021/235342408-3b775d73-3f15-4971-a741-9e883743dd91.png)
3. Các trường dữ liệu bắt buộc đề xuất các module kết hợp bắt buộc nhập cho đồng bộ
![image](https://user-images.githubusercontent.com/96155021/235342461-a6122932-b5df-4973-a81c-0c7abc2ad969.png)
4. Lỗi chính tả
![image](https://user-images.githubusercontent.com/96155021/235342601-53152902-d5bd-4dc2-a25a-df3e9a677914.png)

5. Một số trường dữ liệu đã nhập hiện tại form gửi giấy chứng sinh chưa lấy đc & Lưu báo lỗi
![image](https://user-images.githubusercontent.com/96155021/235343050-9c8f1a6c-7597-4d1f-bdc6-1ba6e80da4ca.png)

**Comment by le-an-87** [comment]
Lỗi Treatment
1. Form Thông tin con: Mã đối tượng không bị ràng buộc cho phép nhập tùy ý
![image](https://user-images.githubusercontent.com/96155021/235343411-c50d3ea5-921e-48f1-b454-d221b492f0fb.png)
2. From Thông tin thẻ 2:
 - Mã đối tượng không bị ràng buộc cho phép nhập tùy ý
 - Lưu thông tin thẻ 2 báo lỗi
![image](https://user-images.githubusercontent.com/96155021/235343388-cce11902-a339-4602-999d-baec6654bbf3.png)

**Comment by le-an-87** [comment]
Giấy chứng từ
1. Gửi báo lỗi
![image](https://user-images.githubusercontent.com/96155021/235344339-4dfe7c80-30db-4c01-af30-d73f776e836b.png)

2. Một số trường dữ liệu chưa lấy được
![image](https://user-images.githubusercontent.com/96155021/235344427-39c2a592-0b47-4152-b1de-a82573b0e222.png)

**Comment by le-an-87** [comment]
alo @lequocthong29 chổ chức năng gửi và Ký XML là làm sao vậy @lequocthong29 !
chưa hiểu chức năng này em giải thích nó 1 chút nhe!
1. Gửi: gửi GCS, GBT lên cổng BHXH phải không?
2. Ký XML: tác dụng để làm gì vậy em và dùng chữ ký số của đơn vị phải ko
3. Cấu hình ký số như thế nào vậy.
4. Hiện tại khi test em đang gửi lên đâu vậy? có gửi test được hay không? kiểm tra xem có gửi được hay không thì phải lên cổng kiểm tra hay sao?
5. Module Treatment có được phép gửi dữ liệu này không mấy anh?
6. Đề nghị ghi nhận nhật ký gửi và tạo form theo dõi danh sách gửi.

**Comment by lequocthong29** [comment]
@le-an-87 
- hiện tại khi ấn ký xml phần mêm sẽ tự chuyển dữ liệu sang xml rồi tiến hành ký, sau đó lưu lại dạng chuỗi base64, khi ấn gửi chuỗi base64 đó sẽ được gửi lên cổng BHXH.
- Cấu hình chữ ký số hiện tại e có cài chữ ký số của softdream trên server mình nên a cứ cấu hình cks.donvi_api_ksk = 1 là dùng được. kiểm tra tham số cks.url nếu chưa có thì a thêm = "http://192.168.10.79:3000/kyso/softdream".
- hiện tại là đang gửi trực tiếp lên cổng , không gửi test được nha a, muốn kiểm tra dữ liệu gửi có lỗi hay không phải lên cổng kiểm tra.

**Comment by le-an-87** [comment]
vậy không ký XML có được phép gửi lên cổng hay không?
có chổ nào phân biệt được dòng dữ liệu nào có ký số rồi dòng dữ liệu nào chưa để thực hiện ký số.
Trường hợp giấy đã gửi rồi thì người dùng phân biệt thế nào để không cần gửi nữa!

* Trường hợp gửi trực tiếp thế này thì đâu test gửi cổng được đâu anh @nghivanbi

**Comment by lequocthong29** [comment]
- Ấn ký xong mới gửi lên cổng được a, sau khi ký thành công cột signdata sẽ có dữ liệu, sau khi gửi thành công thì thông tin đó sẽ không hiển thị trên form nữa a.

**Comment by lequocthong29** [comment]
e cập nhật lại dll. @vuongdh
- Fix lỗi khi load thông tin giấy chứng sinh.
- Fix lỗi version dll Newtonsoft.json.
- Fix lỗi chính tả người đở đẻ.
- Cập nhật, load lại các thông tin chưa lấy được trên form giấy chứng sinh: người đở đẻ, ngày sinh con, tình trạng, thủ trưởng đơn vị.
- Fix lỗi không lưu được.
- Cập nhật load lại các thông tin chưa lấy được trên form giấy báo tử: bhyt, tình trạng tử vong, nguyên nhân tử vong, thủ trưởng đơn vị, số giấy báo, số quyển.
- Tắt button ký và gửi khi kyso = 0.
- Thêm chức năng xuất excel.

![image](https://user-images.githubusercontent.com/110148171/236118206-600844c6-45b1-413a-a888-7f1ed3c5b17d.png)

**Comment by vuongdh** [comment]
Cập nhật [Treatment4.2023.05.04v1](https://gofile.me/78TQg/1a0Yb1rcm)

**Comment by lequocthong29** [comment]
@vuongdh  e cập nhật lại dll.
- fix lỗi sai đường dẫn tới file xml.

![image](https://user-images.githubusercontent.com/110148171/236360980-d7cddaaa-57eb-46c3-8ad4-7e8fe4830f67.png)

**Comment by vuongdh** [comment]
Cập nhật [Treatment4.2023.05.05v1](https://gofile.me/78TQg/OCOAe1UKX)

**Comment by le-an-87** [comment]
nhập và lưu GCS và GCT đã được rồi!
nhưng còn 1 số vấn đề nhé @lequocthong29 !
1. form vẫn còn hiển thị được ký xml và gửi.
![image](https://user-images.githubusercontent.com/96155021/236421419-9ee874f0-abb1-4ab8-9960-0ef402480910.png)
2. Một số nội dung không đúng với công văn mô tả!

**Comment by lequocthong29** [comment]
Cập nhật dll DH.ThongTinKSK.dll
- Fix lỗi hiển thị nút gửi và ký XML khi ấn bỏ qua.
- Tạm thời cho nhập tay các nội dung chưa đồng bộ với mô tả của công văn.

![image](https://user-images.githubusercontent.com/110148171/236714764-d4134a83-bf72-4a2a-ace1-25467cc0d466.png)

**Comment by vuongdh** [comment]
Bản cập nhật [Treatment3.2023.05.08v1](https://gofile.me/78TQg/EvatbgAtl)

**Comment by lequocthong29** [comment]
Cập nhật dll DH.ThongTinKSK.dll
- Cho nhật mã dân tộc

![image](https://user-images.githubusercontent.com/110148171/236770975-4451ffd0-9c30-4a51-abb0-ee23b6bd1c99.png)

**Comment by vuongdh** [comment]
Bản cập nhật [Treatment3.2023.05.08v2](https://gofile.me/78TQg/1TIQYrVNq)

**Comment by le-an-87** [comment]
Giấy chứng sinh đã nhập vào lưu được rồi.
Giấy chứng tử còn lỗi nhe @lequocthong29.

![image](https://user-images.githubusercontent.com/96155021/236987701-508cf7c4-6c00-464b-a097-1eaddd6412a3.png)

1. bị trùng giấy chứng tử
2. mã tỉnh, huyện, xã em cho nhập nhé
3. Giới tính lấy theo thông tin bệnh nhân và không chỉnh ở đây nhe!

**Comment by lequocthong29** [comment]
Cập nhật dll DH.ThongTinKSK.dll
- fix lỗi trùng giấy chứng tử
- cho nhập tay mã tỉnh, huyện, xã hiện tại trên form giấy báo tử.
- không cho chỉnh giới tính.
![image](https://github.com/dh-hos/dhg.hosptaltreatment/assets/110148171/60b227a1-e21a-4245-9fe1-29412053ad1a)

**Comment by vuongdh** [comment]
Bản cập nhật [Treat4.2023.05.10v1](https://gofile.me/78TQg/a6C4TYFoS)

**Comment by le-an-87** [comment]
Giấy báo tử và giấy chứng sinh đã nhập và lưu thành công!

***Vấn đề phát sinh***
Khi xóa thì không mất bên danh sách gửi.
Khi chỉnh thì không cập nhật.

-> gây chênh lệch giữa các báo cáo trên phần mềm và danh sách gửi cổng

**Comment by nghivanbi** [comment]
@vuongdh kết hợp @lequocthong29  chỗ này nha, để đảm bảo tính đồng bộ 2 danh sách. Bổ sung các kiểm tra đổi chiếu sau khi gởi không cho chỉnh sửa chẳng hạn...

**Comment by vuongdh** [comment]
Bản cập nhật (kyso = 0) [Treat4.2023.05.10v3](https://gofile.me/78TQg/EilZjsSGo)

**Comment by le-an-87** [comment]
Bản cập nhật này giải quyết chổ nào vậy anh @vuongdh ?

**Comment by vuongdh** [comment]
@lequocthong29 giải thích cho @le-an-87 nha

**Comment by lqbinh1987** [comment]
Anh @nghivanbi 
Em đề nghị:
Bổ sung chức map mã tỉnh, huyện, xã gấp.
Bổ sung tham số mã định danh của thủ trưởng đơn vị để tự động load lên.
Bổ sung tính năng cho tự sinh **Mã giấy chứng sinh** , nếu thứ tự tăng dần ko đúng phải cho chỉnh lại.

3 vấn đề trên  nếu nhạp tay sẽ rất lâu, không khác gì nhập trên cổng.

**Comment by lequocthong29** [comment]
Cập nhật dll Dh.ThongTinKSK.dll
- Khi xóa GCS, GBT, GKSK sẽ đồng thời xóa trên các form liên thông.
- khi cập nhật GCS, GBT, GKSK, thông tin sẽ được cập nhật lại trên các form liên thông.
- thêm hàm hổ trợ kiểm tra xem thông tin đã gửi cổng chưa, để tiến hành cho phép xóa, sửa.
[Mô tả](https://gofile.me/78TQg/tfPaFRYVa)

![image](https://github.com/dh-hos/dhg.hosptaltreatment/assets/110148171/772eee7c-6158-40db-a4b1-9ee6ff619cf5)

**Comment by vuongdh** [comment]
Bản cập nhât [Treat4.2023.05.15v1](https://gofile.me/78TQg/dpH18tPvU)

**Comment by vuongdh** [comment]
Cập nhật mô tả giấy chứng sinh [2023.05.17v1](https://gofile.me/78TQg/v5z3E5yL2)
@lequocthong29 em xem cách lấy thông tin anh có làm sẵn SQL, em chỉ cập nhật các thông tin còn thiếu để đảm bảo thông tin thống nhất

**Comment by vuongdh** [comment]
Cập nhật mô tả giấy chứng tử [2023.05.17v2](https://gofile.me/78TQg/pc4Oh9XTS)
@lequocthong29 em xem cách lấy thông tin anh có làm sẵn SQL, em chỉ cập nhật các thông tin còn thiếu để đảm bảo thông tin thống nhất

**Comment by lequocthong29** [comment]
Cập nhật dll DH.ThongTinKSK.dll
- Cập nhật chức năng load một bệnh nhân trên form GCS, GBT.
- Cập nhật dagui = 1 sau khi gửi thành công.
- [mô tả](https://gofile.me/78TQg/EYPoxqCUk).

**Comment by nghivanbi** [comment]
@vuongdh tranh thủ cập nhật để các nhóm hỗ trợ: BV Ô Môn, Sản Nhi ST kịp thời theo hợp đồng với BV nhé.

**Comment by le-an-87** [comment]
1. Mô tả chổ mục 3 này: Hiện tại khi gửi lên cổng sẽ đánh dấu ttcon.gui = 1. nhưng không có chức năng để mở khóa ttcon.gui = 0
 -> nên khi đã gửi rồi sẽ không chỉnh sửa được nữa.
---> đề nghị bổ sung thêm chức năng mở khóa gcs đã gửi.
![image](https://github.com/dh-hos/dhg.hosptaltreatment/assets/96155021/669ce419-f9f0-4918-924a-73d6efb87e05)

2. Về mã GCS và GBT: qui định cấu trúc không được phép trùng trong năm.
-> trường hợp lấy theo 5 ký tự cuối của giấy chứng sinh thì phải ràng buộc các số này không được phép trùng trong năm.
![image](https://github.com/dh-hos/dhg.hosptaltreatment/assets/96155021/cbb9f3bc-725c-4574-ad95-b11e441cd2c8)

3. Với khi map danh mục tỉnh, huyện, xã ... đề xuất thêm chức năng cho chỉnh hoặc thêm để khi thay đổi đơn vị hành chính thì đơn vị có thể chỉnh sửa lại được.

Góp ý cá nhân: Đề xuất đặt tên các trường dữ liệu: ví dụ như ttcon.gui khi nhìn vào mình không biết là đánh dấu đó để làm gì hay gửi đi đâu. mình có thể thêm guibh .... khi nhìn vào ở gốc độ nào đó cũng hiểu được ý nghĩa của nó.
như sau này phát sinh thêm gửi cổng sở y tế mình phát sinh thêm trường guisyt cũng dễ phân biệt được 2 trường này.

**Comment by vuongdh** [comment]
Bản cập nhật: [Treat4.2023.05.19v1](https://gofile.me/78TQg/1JNkr2wrN)
![image](https://github.com/dh-hos/dhg.hosptaltreatment/assets/32563776/9e24bd92-b288-4a2c-89f7-78aca2677722)
<= này đã nói Thống cập nhật thêm năm (do mô tả bị thiếu năm)

**Comment by vuongdh** [comment]
![image](https://github.com/dh-hos/dhg.hosptaltreatment/assets/32563776/53bff2a3-a7e1-4cb8-b3e3-e6e5f855f39b)
Phần này mô tả bị sai ==> ttcon.dagui mới đúng

**Comment by vuongdh** [comment]
Bản cập nhật [Treat4.20230519v2](https://gofile.me/78TQg/9NmvdCBLM)

**Comment by nqhoa1005** [comment]
Phát sinh khi test
- Hiện trạng sk con đã có nhập > Load lên form Giấy chứng sinh
- Chưa load tên người ghi phiếu
- Chưa load tên Trưởng đơn vị.
![image](https://github.com/dh-hos/dhg.hosptaltreatment/assets/130281806/977d8cf1-56c5-43cd-a795-4bd4580f39ba)
- Trường Phẫu thuật và Dưới 32 tuần không bắt buộc nhưng lúc lưu sẽ báo lỗi nếu không chọn.
![image](https://github.com/dh-hos/dhg.hosptaltreatment/assets/130281806/d097fa45-8cdc-419a-8663-e0997e50155b)

**Comment by lequocthong29** [comment]
Update dll DH.ThongTinKSK.dll
- Load hiện trạng sức khỏe con, thủ trưởng đơn vị, người ghi phiếu.
- Fix báo lỗi khi không chọn phẩu thuật và dưới 32 tuần.
![image](https://github.com/dh-hos/dhg.hosptaltreatment/assets/110148171/df5e4a78-8ae0-4116-8e5b-31f518c8568b)

**Comment by vuongdh** [comment]
Bản cập nhật [Treat4.20230519v3](https://gofile.me/78TQg/TlmobcKXe)

**Comment by le-an-87** [comment]
1. Chưa sửa thông báo: vào chức năng này dùng để nhập thông tin.
![image](https://github.com/dh-hos/dhg.hosptaltreatment/assets/96155021/119545c1-54fb-40e9-83c1-dc3dea6e5d2c)
2. các trường nhập thông tin bị khóa lại nhưng chưa map được thông tin đúng:
- Trùng mã chứng sinh.
- mã chứng sinh không load được đúng theo mô tả
- các trường mã dân tộc, quốc gia, tỉnh, ... chưa đúng theo công văn qui định.
- Nơi cấp CCCD bắt buộc nhập nhưng không nhập được.
![image](https://github.com/dh-hos/dhg.hosptaltreatment/assets/96155021/fadfe50c-6d0d-4a5f-aaf4-c712b974d880)

**Comment by lequocthong29** [comment]
Update dll Dh.ThongTinKSK.dll
- fix lỗi mã chứng sinh không load được đúng theo mô tả.
- cho phép chỉnh sửa trường thủ trưởng đơn vị.

![image](https://github.com/dh-hos/dhg.hosptaltreatment/assets/110148171/65c58c1d-2cf9-4f7b-bee6-b12d3022d269)

**Comment by vuongdh** [comment]
Bản cập nhật [Treat4.2023.05.22v1](https://gofile.me/78TQg/EXLAqvip7)

**Comment by lequocthong29** [comment]
Update dll DH.ThongTinKSK.dll
- Cập nhật SQL -> lấy mã quốc gia, mã dân tộc từ cột ma_medisoft trong table current.dmquocgia, current.dmdantoc

![image](https://github.com/dh-hos/dhg.hosptaltreatment/assets/110148171/a80a12a9-a82d-40f9-a358-73a1a47f7686)

**Comment by vuongdh** [comment]
Bản cập nhật theo dll [Treat4.2023.05.23v1](https://gofile.me/78TQg/dDGQjMPW5)

**Comment by lequocthong29** [comment]
Update dll DH.ThongTinKSK.dll
- Thêm tham số ma_ttdv để lưu mã định danh form GCS.
- Load mã định danh theo giá trị tham số ma_ttdv
[Mô tả](https://gofile.me/78TQg/LMo6uhmC3)

**Comment by lqbinh1987** [comment]
Build theo mô tả chổ Thống dùm em cái nhe a @vuongdh, để cập nhật cho mấy BV lun, cho kịp hợp đồng á.

**Comment by vuongdh** [comment]
Bản cập nhật [Treat4.2023.05.24v1](https://gofile.me/78TQg/W3tpo52wt)

**Comment by lqbinh1987** [comment]
Giấy báo tử, đề nghị:

- Đổi nhãn lại là "Giấy chứng tử Đề án 06"(1), bỏ cấu thông báo liên thông giấy chứng tử(2)...(Hình 1).
- Bổ sung mã Quốc gia và mã Dân tộc, thông tin người thân (Hình 2).
- Ngày giờ tử vong bổ sung thêm giờ phút cho đúng với quy định (Hình 2).
- Bổ sung người lập phiếu chính là tên tài khoản đăng nhập (Hình 2).


Hình 1.
![image](https://github.com/dh-hos/dhg.hosptaltreatment/assets/99630883/e724a6d9-606f-4694-bdfb-cee097cc62cf)

Hình 2:
![image](https://github.com/dh-hos/dhg.hosptaltreatment/assets/99630883/b1bcd85f-d19c-4b68-a209-c161aa5d838d)

**Comment by vuongdh** [comment]
Bản cập nhật theo dll đã chỉnh sửa [Treat4.2023.05.25v2](https://gofile.me/78TQg/AvbknHvQE)

**Comment by lequocthong29** [comment]
Cập nhật dll DH.ThongTinKSK.dll
- sửa lỗi định ngạy ngayct khi gửi cổng sai định dạng.
- sữa lỗi load dữ liệu.
![image](https://github.com/dh-hos/dhg.hosptaltreatment/assets/110148171/c37e02dd-ffaa-4ebb-b529-e343f109a5a3)

**Comment by lqbinh1987** [comment]
build dùm em cái nhe anh @vuongdh

**Comment by vuongdh** [comment]
Bản cập nhật [Treat4.2023.05.29v1](https://gofile.me/78TQg/asu1yXidz)

**Comment by lqbinh1987** [comment]
Build report lại dùm em nhen anh @vinh-dh 

> Cập nhật dll DH.ThongTinKSK.dll
> 
> * sửa lỗi định ngạy ngayct khi gửi cổng sai định dạng.
> * sữa lỗi load dữ liệu.
>   ![image](https://user-images.githubusercontent.com/110148171/241172381-c37e02dd-ffaa-4ebb-b529-e343f109a5a3.png)

**Comment by vinh-dh** [comment]
@lqbinh1987: [Yêu cầu - Hỗ trợ gửi dữ liệu Giấy chứng sinh, Giấy báo tử và giấy Khám sức khỏe lái xe theo đề án 06 #47](https://github.com/dh-hos/dhg.hospitalreports/issues/47)

**Comment by nghivanbi** [comment]
@ongtrieuhau hỗ trợ @lequocthong29 mô tả thêm phần map thông tin địa phương nha, để người dùng không phải nhập lại thông tin khi đẩy xml lên cổng.

**Comment by ongtrieuhau** [comment]
cái này @lequocthong29 mô tả thêm cột mới để xử lý cái này nhé, vì HIV cũng cột mới để xử lý rồi, cái này phụ thuộc vào nơi yêu cầu gửi dữ liệu (mỗi nơi mỗi khác) nên tạo cột mới để xử lý khỏi phụ thuộc nhé. Khi tạo mới thì lấy giá trị mặc định có sẵn cột mã của dữ liệu có sẵn làm giá trị, khi nào cần thay đổi thì bệnh viện sẽ chỉnh phần này.

**Comment by lequocthong29** [comment]
Cập nhật mô tả và dll.
- thêm cột ma_lienthong vào các bảng current.dmtinh, current.dmhuyen, current.dmxa.
- [mô tả](https://gofile.me/78TQg/bHQwLKUvs)

![image](https://github.com/dh-hos/dhg.hosptaltreatment/assets/110148171/627b05aa-6f3a-4f77-a800-f02b10a13364)

**Comment by vuongdh** [comment]
Bản cập nhật theo dll [Treat4.2023.05.30v1](https://gofile.me/78TQg/KPTLIUbIN)

**Comment by le-an-87** [comment]
![image](https://github.com/dh-hos/dhg.hosptaltreatment/assets/96155021/3492b91a-54ca-485e-89b3-4fa542f2d6cd)

Đề xuất các trường thông tin không cố định cho phép chỉnh sửa khi nhập thông tin giấy chứng sinh đề án 06!
ví dụ như trường:
MA_BHXH_NND : Mã BHXH của mẹ hoặc người nuôi dưỡng.
các trường này bhxh không bắt buộc là phải của bệnh nhân nên đề xuất cho bv có thể chỉnh sửa lại.

* BV Ô môn đề nghị cho chỉnh sửa trường NOI_CU_TRU_NND.

**Comment by lequocthong29** [comment]
Cập nhật dll DH.ThongTinKSK.dll
- tích hợp chức năng ký số của VNPT.

![image](https://github.com/dh-hos/dhg.hosptaltreatment/assets/110148171/e51e2af9-9905-4e92-953e-7e5a0d832af9)

**Comment by lequocthong29** [comment]
Cập nhật dll DH.ThongTinKSK.dll
- bổ sung tham số ma_diachibv để lưu địa chỉ bv theo bản cập nhật API từ cổng.
- [mota](https://gofile.me/78TQg/F8SYv4EZJ)

![image](https://github.com/dh-hos/dhg.hosptaltreatment/assets/110148171/5cc29a1c-00dd-42cf-b6fc-16febed25a70)

**Comment by vuongdh** [comment]
Bản cập nhật theo dll mới [Treat4.2023.06.19v1](https://gofile.me/78TQg/sbyyqlZ6g)

**Comment by vuongdh** [comment]
[Treatment4.2023.06.23v1](https://gofile.me/78TQg/MBx8AYg94)

**Comment by lequocthong29** [comment]
Update dll DH.ThongTinKSK.dll
- Thêm lựa chọn tại trường loại giấy tờ trên GBT

![image](https://github.com/dh-hos/dhg.hosptaltreatment/assets/110148171/9cad7370-cbf5-4f74-846b-5514aaad5439)

**Comment by lqbinh1987** [comment]
Anh @vinh-dh cập nhật bản mới dùm em.

**Comment by vinh-dh** [comment]
> @lqbinh1987: [Yêu cầu - Hỗ trợ gửi dữ liệu Giấy chứng sinh, Giấy báo tử và giấy Khám sức khỏe lái xe theo đề án 06 #47](https://github.com/dh-hos/dhg.hospitalreports/issues/47)

**Comment by lequocthong29** [comment]
Update dll DH.ThongTinKSK.dll
- Cập nhật lỗi không thể lưu khi chọn không có giấy tờ trên form GBT
- Cập nhật lỗi không thể ký liên tục VNPT trên form GCS
- Cập nhật lỗi không gửi được trên form KSK
- Đặt một số giá trị mặc định trên form KSK

nhờ anh @vuongdh và anh @vinh-dh cập nhật lại Treat và Report cập nhật bản mới dùm e

![image](https://github.com/dh-hos/dhg.hosptaltreatment/assets/110148171/429ceb83-d156-4d6f-bb5d-552be359dd84)

**Comment by vuongdh** [comment]
[Bản cập nhật Treat4.2023.07.19v2](https://gofile.me/78TQg/5fPN1yqXZ)

Lưu ý: cập nhật script và cấu trúc liên quan

**Comment by lequocthong29** [comment]
Update DLL DH.ThongTinKSK
- Sửa lỗi sai định dạng thời gian trên form GCS, GBT.
- Sửa lỗi sai định dạng XML giấy KSK.
- Sửa lỗi không được ký khi bỏ trống số giấy tờ trên form GBT

![image](https://github.com/dh-hos/dhg.hosptaltreatment/assets/110148171/e8cb5f80-4e36-4317-b191-a16d319ae577)

**Comment by vuongdh** [comment]
[Bản cập nhật Treat4.2023.07.20v1](https://gofile.me/78TQg/5m3kupHTz)

**Comment by lequocthong29** [comment]
Update dll DH.ThongTinKSK.dll
- Sửa lỗi sai giới tính trên form KSK.
![image](https://github.com/dh-hos/dhg.hosptaltreatment/assets/110148171/fd15edc9-f7da-4f91-8b6f-06a302960ceb)

**Comment by vuongdh** [comment]
[Bản cập nhật Treat4.2023.08.03v1](https://gofile.me/78TQg/gIiFElMZO)

**Comment by lequocthong29** [comment]
Update dll DH.ThongTinKSK.dll
- Fix lỗi mã chứng từ không thay đổi sau khi đã chỉnh trên form Giấy chứng sinh.

![image](https://github.com/dh-hos/dhg.hosptaltreatment/assets/110148171/f566ebd3-d356-4f06-9f5b-6f91862f7628)

**Comment by le-an-87** [comment]
Đã có các bản hỗ trợ!
