### ISSUE TITLE
Yêu cầu - Bổ sung chức năng Quản lý danh sách đơn thuốc và gửi lại đơn thuốc ngày cũ lên cổng donthuocquocgia.vn

### ISSUE THREAD

**Issue by chauthanhtra** [dh-hos/dhg.hosptaltreatment#108]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.2: Phiếu ghi nhận Yêu cầu mới DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN YÊU CẦU CHỨC NĂNG MỚI</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Châu Thanh Trà **
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **08/05/2023**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `95007`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **BV Đông Hải**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `ten_csdl`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`](link_csdl)

###### ![chi_tiet_yeu_cau](https://img.shields.io/badge/Chi%20tiết%20yêu%20cầu%20-:-blue?style=for-the-badge&logo=github)

```
Do nhiều đơn thuốc ngày cũ phần mềm không gửi được hoặc gửi bị thiếu trên cổng đơn thuốc quốc gia nên BV Đông Hải có yêu cầu thêm các chức năng như:
- Chức năng quản lý danh sách các đơn thuốc như đơn đã gửi, đơn chưa gửi, đơn gửi lỗi.
- Chức năng gửi lại các đơn thuốc phần mềm chưa gửi được theo ngày được chọn. Do hiện tại phần mềm chỉ gửi tự động các đơn thuốc ngày hiện tại, BV không biết đơn thuốc nào đã được gửi thành công, đơn thuốc nào chưa gửi được.

```

**Comment by vuongdh** [comment]
@chauthanhtra em xin dữ liệu hén

**Comment by chauthanhtra** [comment]
Em gửi anh data full của BV
Data: tra_donghai_epr

**Comment by vuongdh** [comment]
Bản cập nhật [Quanly_EPR_2023.05.23v1](https://gofile.me/78TQg/VTOVVvVMH)
