### ISSUE TITLE
Yêu cầu - Bổ sung phiếu chỉ định CLS tự thiết kế

### ISSUE THREAD

**Issue by nghivanbi** [dh-hos/dhg.hosptaltreatment#11]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.2: Phiếu ghi nhận Yêu cầu mới DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN YÊU CẦU CHỨC NĂNG MỚI</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Nghị Văn Bi**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **19/08/2022**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) ``
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **Tất cả**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) 
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) 

###### ![chi_tiet_yeu_cau](https://img.shields.io/badge/Chi%20tiết%20yêu%20cầu%20-:-blue?style=for-the-badge&logo=github)

```
Bổ sung phiếu chỉ định cận lâm sàng tự thiết kế theo nội dung tham số: phieuycchuan Phiếu yêu cầu khi chỉ định cls theo mẫu chuẩn (Mặc định 0: không chuẩn; 1: mẫu chuẩn; 2: mẫu tự thiết kế)

```

**Comment by vuongdh** [comment]
@lqbinh1987 [Đã cập nhật ](http://www.fsend.vn/download/1PfckbE4K58iw_TeAUrOsiex3BNpXWVf)
