### ISSUE TITLE
Lỗi - Form Tổng kết chi phí # Form tổng kết chi phí theo 6556 (bao gồm bảng kê)

### ISSUE THREAD

**Issue by le-an-87** [dh-hos/dhg.hosptaltreatment#111]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.1: Phiếu ghi nhận lỗi phát sinh DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN LỖI PHÁT SINH</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Ân**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **17/05/2023**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `Tất cả`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **Tất cả**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `an_thotnot_bangke02_20230517`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`](https://gofile.me/78TQg/trY5RfQmP)

###### ![chi_tiet_loi](https://img.shields.io/badge/Chi%20tiết%20lỗi%20phát%20sinh-:-blue?style=for-the-badge&logo=github)

-  ![loi_benh_nhan](https://img.shields.io/badge/Chi%20tiết%20bệnh%20nhân-:-blue?style=plastic&logo=github)
   > _**MaBN**_: `2023018765` - _**MaKB**_: `2305008934` - _**MaBA**_: `2023008586` _**NgayKCB**_: `17/05/2023` - _**MaPhong**_: `219` - _**MaDV**_: `07` - _**ThangKT**_: `05` - _**NamKT**_: `2023`
-  ![loi_thuoc](https://img.shields.io/badge/Chi%20tiết%20thuốc-:-blue?style=plastic&logo=github)
   > _**KhoChan**_: `14` - _**KhoLe**_: `02` - _**SoHD**_: `TH3.X23.0516.224652` - _**NgayHD**_: `16/05/2023`

###### ![mo_ta_loi](https://img.shields.io/badge/Mô%20tả%20thông%20tin%20lỗi-:-blue?style=for-the-badge&logo=github)

```
Tổng kết chi phí điều trị lệch tiền thuốc so với tổng kết chi phí theo QD 6556

```
Tổng kết chi phí điều trị
![image](https://github.com/dh-hos/dhg.hosptaltreatment/assets/96155021/aea75cc5-605b-4b61-a9f6-62cb802862cb)

Tổng kết chi phí điều trị theo 6556
![image](https://github.com/dh-hos/dhg.hosptaltreatment/assets/96155021/ed4f90e3-09c2-445f-b627-bf6f65d965e0)

Toa thuốc lệch
![image](https://github.com/dh-hos/dhg.hosptaltreatment/assets/96155021/d5d2cca6-d852-4453-b1b9-89e5c0bcd431)

**Comment by vuongdh** [comment]
Bảng cập nhật [Treat4.2023.05.18v2](https://gofile.me/78TQg/CSBAVVX1E)

**Comment by le-an-87** [comment]
Đã fix!
