### ISSUE TITLE
Yêu cầu - Cảnh báo chống chỉ định.

### ISSUE THREAD

**Issue by lqbinh1987** [dh-hos/dhg.hosptaltreatment#113]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.2: Phiếu ghi nhận Yêu cầu mới DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN YÊU CẦU CHỨC NĂNG MỚI</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Hòa**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **19/05/2023**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `70071`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **khach_hang**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `hoa_bvbinhlong_chongchidinh`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`](link_csdl)

###### ![chi_tiet_yeu_cau](https://img.shields.io/badge/Chi%20tiết%20yêu%20cầu%20-:-blue?style=for-the-badge&logo=github)

Khi thực hiện ra thuốc mà có chống chỉ định hoặc bắt buộc chỉ định thì hiện tại Treatment chỉ thông báo chung như **hình 1**.
Đề nghị hiển thị cảnh báo tương tự như ngoại trú, khi đó người dùng mới xác định được đó là chống chỉ định hoặc chỉ định của thuốc đó đối với ICD nào, **hình 2.**
Vì nếu thông báo như Treatment như hiện tại là người dùng không biết đang bị chống chỉ định hay bắt buộc chỉ định, người dùng không có hướng xử lý, phải liên hệ IT mở phần cấu hình lên mới biết được.
Hình 1.
![image](https://github.com/dh-hos/dhg.hosptaltreatment/assets/99630883/9e413efe-f80b-4d17-8836-4597b5182dc9)

Hình 2.
![image](https://github.com/dh-hos/dhg.hosptaltreatment/assets/99630883/edcb7ae4-2014-478b-804c-23b45c44aac5)

**Comment by vuongdh** [comment]
@nghivanbi cho xin cái form thông báo để làm cho giống

**Comment by lqbinh1987** [comment]
Anh @nghivanbi .

> @nghivanbi cho xin cái form thông báo để làm cho giống

**Comment by nghivanbi** [comment]
anh gởi @vuongdh rồi

**Comment by vuongdh** [comment]
@lqbinh1987 bổ sung thông tin, bệnh nhân thuộc khoa nào vậy?

**Comment by vuongdh** [comment]
Bản cập nhật [Treat4.2023.05.25v1](https://gofile.me/78TQg/vsLnXZIrA)
