### ISSUE TITLE
Yêu cầu - bổ sung tên loại cls vào mẫu phiếu chỉ định cls tự thiết kế

### ISSUE THREAD

**Issue by le-an-87** [dh-hos/dhg.hosptaltreatment#116]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.2: Phiếu ghi nhận Yêu cầu mới DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN YÊU CẦU CHỨC NĂNG MỚI</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Ân**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **06/06/2023**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `92118`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **BV Phụ sản**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `an_phusan_ct_dutru_tutruc`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`](link_csdl)

###### ![chi_tiet_yeu_cau](https://img.shields.io/badge/Chi%20tiết%20yêu%20cầu%20-:-blue?style=for-the-badge&logo=github)

```
BV Phụ sản yêu cầu bổ sung trường tên loại cls vào mẫu thiết kế phiếu chỉ định cls.

hiện tại có trường maloai nhưng chưa có trường tên loại cls
```
![image](https://github.com/dh-hos/dhg.hosptaltreatment/assets/96155021/e59affae-4f21-4f18-b86e-1ca90d3b3f54)
loại cls
![image](https://github.com/dh-hos/dhg.hosptaltreatment/assets/96155021/527f3b0a-05b2-4877-8bb6-03fc03dc9de7)

**Comment by vuongdh** [comment]
Bảng cập nhật [Treat4.2023.07.17v1](https://gofile.me/78TQg/yoABVILNg)

**Comment by le-an-87** [comment]
Đã hỗ trợ!
