### ISSUE TITLE
Yêu cầu - Add mã 2 Phòng khám Cà Mau sử dụng module EPR

### ISSUE THREAD

**Issue by hvtuan1987** [dh-hos/dhg.hosptaltreatment#117]
Nhờ anhVương Add mã hai đơn vị yêu cầu sử dụng module EPR  

Mã:  96148 Phòng Khám Phương Nam Cà Mau
Mã 96152:  Phòng Khám Nam Phương Cà Mau

**Comment by vuongdh** [comment]
@hvtuan1987 Bản cập nhật
- Dùng để cấu hình và gửi lại [Cấu hình](https://gofile.me/78TQg/iLvrzx41F)
- Dùng để gửi tự động [gửi tự động](https://gofile.me/78TQg/Jwo99JCSR)
