### ISSUE TITLE
Lỗi - Không nhập được mã thẻ tạm thông tin con

### ISSUE THREAD

**Issue by chauthanhtra** [dh-hos/dhg.hosptaltreatment#118]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.1: Phiếu ghi nhận lỗi phát sinh DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN LỖI PHÁT SINH</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Châu Thanh Trà**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **19/6/2023**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `92092`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **BV Quân Dân Y CT**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `tra_quandanytp_ct_treatment_mathecon`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`](https://gofile.me/78TQg/gLT3js8Fl)

###### ![chi_tiet_loi](https://img.shields.io/badge/Chi%20tiết%20lỗi%20phát%20sinh-:-blue?style=for-the-badge&logo=github)

-  ![loi_benh_nhan](https://img.shields.io/badge/Chi%20tiết%20bệnh%20nhân-:-blue?style=plastic&logo=github)
   > _**MaBN**_: `2023007179` - _**MaKB**_: `MaKB` - _**MaBA**_: `2023003472` _**NgayKCB**_: `NgayKCB` - _**MaPhong**_: `MaPhong` - _**MaDV**_: `02` - _**ThangKT**_: `06` - _**NamKT**_: `2023`
-  ![loi_thuoc](https://img.shields.io/badge/Chi%20tiết%20thuốc-:-blue?style=plastic&logo=github)
   > _**KhoChan**_: `KhoChan` - _**KhoLe**_: `KhoLe` - _**MaHH**_: `MaHH` - _**SoHD**_: `SoHD` - _**NgayHD**_: `NgayHD` - _**ThangKT**_: `ThangKT` - _**NamKT**_: `NamKT`
-  ![loi_cls](https://img.shields.io/badge/Chi%20tiết%20CLS-:-blue?style=plastic&logo=github)
   > _**MaCLS**_: `MaCLS` - _**PhieuYC**_: `PhieuYC`
-  ![loi_bo_sung](https://img.shields.io/badge/Chi%20tiết%20bổ%20sung-:-blue?style=plastic&logo=github)
   > _**Khac**_: `Khac`

###### ![mo_ta_loi](https://img.shields.io/badge/Mô%20tả%20thông%20tin%20lỗi-:-blue?style=for-the-badge&logo=github)

Phần mềm Treatment không cho nhập tay thông tin thẻ tạm của con
- Hiện tại thông tin thẻ tạm phải được nhập theo thông tin thẻ do cổng BHXH tạo

![ảnh](https://github.com/dh-hos/dhg.hosptaltreatment/assets/97272332/864230d3-4c48-4088-9e3d-3f816eaef53b)

**Comment by vuongdh** [comment]
@chauthanhtra muốn nhập được mã thẻ cho trẻ em thì
- Không nhập giấy chứng sinh
- Không check Thẻ tạm

**Comment by vuongdh** [comment]
@chauthanhtra Nếu check thẻ tạm vẫn cho thay đổi thông tin thẻ
- mã thẻ, hạn dùng thẻ
- KHÔNG cho đổi nơi đăng ký

**Comment by chauthanhtra** [comment]
Là sao anh. em chưa hiểu?
anh giải thích lại giúp em nha

**Comment by le-an-87** [comment]
alo anh @vuongdh chổ thẻ tạm giờ bệnh viện tạo thẻ tạm trực tiếp từ cổng BHXH rồi mới nhập vào phần mềm!
mà giờ chổ đó không cho nhập rồi sao bv nhập được anh.
Trường hợp không check thẻ tạm mới cho nhập thông tin thẻ thì báo cáo thẻ tạm đâu lấy được!
anh coi kiểm tra lại trường hợp này đi.

**Comment by vuongdh** [comment]
@le-an-87 @chauthanhtra 
- Nhập giấy chứng sinh thì không nhập được thẻ bảo hiểm (chỉ sài 1 trong 2)
- Check thẻ tạm thì gõ được mã thẻ và hạn dùng --> nhưng không chỉnh được nơi đăng ký thẻ tạm (do mã nơi đăng ký thẻ tạm được tính từ địa chỉ được chọn (có qui định))

Hiện tại là như vậy, nếu có qui định mới hoặc có đề xuất thì đề xuất để hiệu chỉnh cho phù hợp. Này là do báo lỗi nên anh test và phản hồi

**Comment by vuongdh** [comment]
@le-an-87 @chauthanhtra Cho anh một thông tin đầy đủ của thẻ tạm sinh từ cổng, để anh test

**Comment by chauthanhtra** [comment]
alo anh @vuongdh 
- Sao không vừa cấp giấy chứng sinh vừa nhập thẻ tạm luôn vậy anh mà phải chọn 1 trong 2 ?

Hiện tại BHXH chỉ cho đăng ký thông tin để cấp mã BHXH tạm
BV lấy mã BHXH đó để làm thông tin thẻ tạm cho trẻ em
![ảnh](https://github.com/dh-hos/dhg.hosptaltreatment/assets/97272332/03350a4d-bc19-42d3-b9ba-f7ba8447875d)
![ảnh](https://github.com/dh-hos/dhg.hosptaltreatment/assets/97272332/f76fc49a-5e17-4618-a9e4-4cf3a0db1892)
![ảnh](https://github.com/dh-hos/dhg.hosptaltreatment/assets/97272332/91cabc4f-a0af-46d8-93cd-517e23551130)
