### ISSUE TITLE
Lỗi - Mẫu giấy chứng sinh bị mất chữ

### ISSUE THREAD

**Issue by le-an-87** [dh-hos/dhg.hosptaltreatment#120]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.1: Phiếu ghi nhận lỗi phát sinh DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN LỖI PHÁT SINH</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Ân**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **2306/2023**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `Tất cả`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **Tất cả**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `an_omon_gcs`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`](https://gofile.me/78TQg/lQlLL5ZHa)

###### ![chi_tiet_loi](https://img.shields.io/badge/Chi%20tiết%20lỗi%20phát%20sinh-:-blue?style=for-the-badge&logo=github)

-  ![loi_benh_nhan](https://img.shields.io/badge/Chi%20tiết%20bệnh%20nhân-:-blue?style=plastic&logo=github)
   > _**MaBN**_: `2023020066` - _**MaKB**_: `2306014397` - _**MaBA**_: `2023007762` _**NgayKCB**_: `23/06/2023` - _**MaPhong**_: `21` - _**MaDV**_: `04` - _**ThangKT**_: `06` - _**NamKT**_: `2023`

###### ![mo_ta_loi](https://img.shields.io/badge/Mô%20tả%20thông%20tin%20lỗi-:-blue?style=for-the-badge&logo=github)

```
Mẫu giấy chứng sinh khi in bị che khuất nơi sinh con

```
![image](https://github.com/dh-hos/dhg.hosptaltreatment/assets/96155021/c0b30920-a4a4-4b26-9abc-69e54f261e97)

**Comment by vuongdh** [comment]
@le-an-87 Bản cập nhật [Treat4.2023.06.26v3](https://gofile.me/78TQg/E5Tf3OycD)

**Comment by le-an-87** [comment]
Đã chỉnh được bệnh nhân báo lỗi!
anh coi chổ đó có cách nào tốt hơn không anh. chứ nếu nhập địa chỉ dài hơn là bị mất nữa
![image](https://github.com/dh-hos/dhg.hosptaltreatment/assets/96155021/b49f92dd-e49b-4a78-9dff-21f1a92f18e4)
