### ISSUE TITLE
Yêu cầu - Bổ sung mẫu GIẤY CHỨNG NHẬN NẰM VIỆN

### ISSUE THREAD

**Issue by lqbinh1987** [dh-hos/dhg.hosptaltreatment#121]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.2: Phiếu ghi nhận Yêu cầu mới DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN YÊU CẦU CHỨC NĂNG MỚI</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Bình**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **23/06/2023**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `92117`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **BV Huyết Học và Truyền Máu CT**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `binh_bvhuyethoc_ct`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`](link_csdl)

###### ![chi_tiet_yeu_cau](https://img.shields.io/badge/Chi%20tiết%20yêu%20cầu%20-:-blue?style=for-the-badge&logo=github)

BV yêu cầu phần mềm hỗ trợ mẫu GIẤY CHỨNG NHẬN NẰM VIỆN trong quá trình BN còn đang nằm điều trị tại BV.
Ngày chổ ký tên là ngày lập phiếu. 
Chẩn đoán thì lấy tất cả chẩn đoán chính và cả chẩn đoán phụ cách nhau bởi dấu chấm phẩy ";" .

![image](https://github.com/dh-hos/dhg.hosptaltreatment/assets/99630883/31c05608-8e09-4c70-8e1e-01fd10197963)

**Comment by nghivanbi** [comment]
- Hỗ trợ thiết kế bằng Xtrareport nhé!

**Comment by vuongdh** [comment]
@lqbinh1987 
![image](https://github.com/dh-hos/dhg.hosptaltreatment/assets/32563776/bc5b69b3-1b15-4628-87b3-d4758ae94f8f)
mẫu này đã có, em xem coi phù hợp không? tự thiết kế luôn

**Comment by vuongdh** [comment]
Form danh sách điều trị
![image](https://github.com/dh-hos/dhg.hosptaltreatment/assets/32563776/2d3e583f-4fcb-4563-9f9d-72c25aef8043)

**Comment by lqbinh1987** [comment]
ok đã dáp ứng được. Thanks các anh.
