### ISSUE TITLE
Yêu cầu - Quản lý số lưu trữ theo Mã BN.

### ISSUE THREAD

**Issue by lqbinh1987** [dh-hos/dhg.hosptaltreatment#123]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.2: Phiếu ghi nhận Yêu cầu mới DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN YÊU CẦU CHỨC NĂNG MỚI</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Bình**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **23/06/2023**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `92117`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **BV Huyết Học Truyền Máu CT**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `binh_bvhuyethoc_ct`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`](link_csdl)

###### ![chi_tiet_yeu_cau](https://img.shields.io/badge/Chi%20tiết%20yêu%20cầu%20-:-blue?style=for-the-badge&logo=github)

Theo nhu cầu của BV thì quản lý số lưu trữ theo BN, trong 1 năm 1 BN có thể có nhiều lần điều trị nội trú tại BV, nhưng có thể chỉ có 1 số lưu trữ hoặc có thể có nhiều số lưu trữ.
Nên em đề nghị hướng làm mà a Bi đưa ra trong cuộc họp tuần: Lúc thao tác xuất viện, bổ sung thêm option để load số lưu trữ cũ(nếu có), nếu người dùng muốn lưu số cũ thì chọn ra và lưu, ngược lại thì nhập số mới để lưu, số mới này không trùng với số dã cấp, và số mới người dùng có sổ tay ở ngoài để quản lý nên biết số nào chưa cấp.

**Comment by nghivanbi** [comment]
- Option cho người dùng có thể chọn lại số lưu trữ trong năm của bệnh nhân hiện tại.

**Comment by ongtrieuhau** [comment]
@vuongdh thực hiện chỗ này nhé a

**Comment by lqbinh1987** [comment]
Anh @vuongdh  coi chổ này sớm dùm em nhe, vì BV cần sớm có chức năng nay để chạy chính thức. Ráng tranh thủ dùm em ngày mốt 02/08/2023 có đc hông anh, vì ngày mai BV chạy chính thức.

**Comment by vuongdh** [comment]
có bệnh nhận nào, có nhiều bệnh án không? không có tạo ra dùm anh

**Comment by vuongdh** [comment]
em nhập đăng ký mới rồi nhập viện 1 trong 2 bn này dùm anh
![image](https://github.com/dh-hos/dhg.hosptaltreatment/assets/32563776/cbb79d86-f8b0-46c3-806e-d54897163626)

**Comment by lqbinh1987** [comment]
Anh @vuongdh , em nhâp rồi nhe anh

![image](https://github.com/dh-hos/dhg.hosptaltreatment/assets/99630883/ca2d3aa0-8686-4fca-ae73-5fd77c958543)

**Comment by vuongdh** [comment]
[Bản cập nhật Treat4.2023.08.01v1](https://gofile.me/78TQg/P4LQG6iiz)
