### ISSUE TITLE
Yêu cầu - Xóa phiếu lĩnh theo tài khoản lập.

### ISSUE THREAD

**Issue by lqbinh1987** [dh-hos/dhg.hosptaltreatment#124]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.2: Phiếu ghi nhận Yêu cầu mới DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN YÊU CẦU CHỨC NĂNG MỚI</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Bình**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **23/06/2023**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `92117`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **BV Huyết Học Truyền Máu CT**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `binh_bvhuyethoc_ct`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`](link_csdl)

###### ![chi_tiet_yeu_cau](https://img.shields.io/badge/Chi%20tiết%20yêu%20cầu%20-:-blue?style=for-the-badge&logo=github)

Theo nhu cầu quản lý của BV, chức năng xóa phiếu lĩnh thuốc như sau:
Chỉ có tài khoản tạo phiếu lĩnh thuốc đó thì mới được xóa phiếu, nếu tài khoản đăng nhập khác với tài khoản lập phiếu lĩnh thì không cho xóa.

**Comment by nghivanbi** [comment]
- Bổ sung thêm ghi nhận nhật ký nếu chưa có nhé.

**Comment by ongtrieuhau** [comment]
Nhờ anh @vuongdh check yêu cầu này giúp em nhé

**Comment by vuongdh** [comment]
Hiện tại database chưa có cấu trúc để ghi nhận theo yêu cầu. Cần phải bổ sung cấu trúc để thực hiện theo yêu cầu

**Comment by ongtrieuhau** [comment]
Vậy anh @vuongdh mô tả bổ sung cấu trúc và thực hiện nhé a

**Comment by vuongdh** [comment]
[Vuong_Mo_ta_phieu_xoa_phieu_tong_hop_tai_khoa.docx](https://github.com/dh-hos/dhg.hosptaltreatment/files/12078375/Vuong_Mo_ta_phieu_xoa_phieu_tong_hop_tai_khoa.docx)

**Comment by vuongdh** [comment]
[Bản cập nhật Treat4.2023.07.19v1](https://gofile.me/78TQg/Yfk5R0T57)
Lưu ý: chạy các script/update struct hỗ trợ trước khi sử dụng
