### ISSUE TITLE
Lỗi - Chỉ định CLS ngày cũ.

### ISSUE THREAD

**Issue by lqbinh1987** [dh-hos/dhg.hosptaltreatment#125]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.1: Phiếu ghi nhận lỗi phát sinh DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN LỖI PHÁT SINH</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Bình**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **28/06/2023**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `92117`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **BV Huyết Học CT**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `binh_bvhuyethoc_ct`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`](link_csdl)

###### ![chi_tiet_loi](https://img.shields.io/badge/Chi%20tiết%20lỗi%20phát%20sinh-:-blue?style=for-the-badge&logo=github)

-  ![loi_benh_nhan](https://img.shields.io/badge/Chi%20tiết%20bệnh%20nhân-:-blue?style=plastic&logo=github)
   > _**MaBN**_: `2023000022` - _**MaKB**_: `MaKB` - _**MaBA**_: `000002` _**NgayKCB**_: `NgayKCB` - _**MaPhong**_: `MaPhong` - _**MaDV**_: `20` - _**ThangKT**_: `03` - _**NamKT**_: `2023`
-  ![loi_thuoc](https://img.shields.io/badge/Chi%20tiết%20thuốc-:-blue?style=plastic&logo=github)
   > _**KhoChan**_: `KhoChan` - _**KhoLe**_: `KhoLe` - _**MaHH**_: `MaHH` - _**SoHD**_: `SoHD` - _**NgayHD**_: `NgayHD` - _**ThangKT**_: `ThangKT` - _**NamKT**_: `NamKT`
-  ![loi_cls](https://img.shields.io/badge/Chi%20tiết%20CLS-:-blue?style=plastic&logo=github)
   > _**MaCLS**_: `MaCLS` - _**PhieuYC**_: `PhieuYC`
-  ![loi_bo_sung](https://img.shields.io/badge/Chi%20tiết%20bổ%20sung-:-blue?style=plastic&logo=github)
   > _**Khac**_: `Khac`

###### ![mo_ta_loi](https://img.shields.io/badge/Mô%20tả%20thông%20tin%20lỗi-:-blue?style=for-the-badge&logo=github)

Cả 2 tham số **nt.cdlui_cls** và **nt.chidinhcls** đều bằng **0**, nhưng khi đăng nhập vào ngày cũ, mặc dù phần mềm có cảnh báo đăng nhập không đúng ngày nhưng vẫn cho chỉ định cls được, vẫn ghi nhận ngày đăng nhập cũ.

![image](https://github.com/dh-hos/dhg.hosptaltreatment/assets/99630883/614ba654-ed48-467d-9d34-420f8adf252e)

**Comment by vuongdh** [comment]
em kiểm tra tham số này: nt.luingayravien

**Comment by vuongdh** [comment]
nếu = 1 sẽ cho cho cls

**Comment by vuongdh** [comment]
ngày cũ

**Comment by vuongdh** [comment]
@lqbinh1987 em lấy dữ liệu của bv nào áp cho đơn vị này vậy?

**Comment by lqbinh1987** [comment]
em lấy dữ liệu của đa khoa thành phố, chỉnh mã bv lại, mà dữ liệu ở bv khác cũng bị anh. bị như e đang test trên dl này.

**Comment by lqbinh1987** [comment]
Em chuyển qua test dữ liệu này cũng bị nhe anh, tất cả tham số lùi ngày đề không sử dụng.
Tên data: an_thanhtri_st_2023_02_10
Thông tin BN: 
![image](https://github.com/dh-hos/dhg.hosptaltreatment/assets/99630883/957f3497-2dfc-464b-8d2e-9a388cfad70c)
![image](https://github.com/dh-hos/dhg.hosptaltreatment/assets/99630883/2fedd2ac-acf1-46ab-9c81-7f09724157db)

**Comment by lqbinh1987** [comment]
Em chuyển qua dữ liệu khác test cũng bị hà anh.
Tên data: an_thanhtri_st_2023_02_10
Thông tin: 
![image](https://github.com/dh-hos/dhg.hosptaltreatment/assets/99630883/f2fb8e82-bbd4-4adb-bd51-c63a634b1eea)
![image](https://github.com/dh-hos/dhg.hosptaltreatment/assets/99630883/5b82ee3e-0197-4c27-9261-e087b416fb12)

**Comment by vuongdh** [comment]
![image](https://github.com/dh-hos/dhg.hosptaltreatment/assets/32563776/24f1dc51-87d0-4e7f-b78c-aa8edc6eb35d)
Anh đăng nhập ngày cũ đâu có cho được CLS @lqbinh1987

**Comment by lqbinh1987** [comment]
Do ngày hiện tại anh chưa thay đổi diển biến đó anh, anh thay đổi diễn biến ngày hiện tại xong anh đăng nhập ngày cũ là chỉ điịnh được. Anh @vuongdh 
![image](https://github.com/dh-hos/dhg.hosptaltreatment/assets/99630883/9a71902d-5ae7-46ff-b568-25f65b5a017b)

**Comment by vuongdh** [comment]
sao em làm dc vậy? có diễn biến mà

**Comment by vuongdh** [comment]
@lqbinh1987 mô tả cách làm của em xem

**Comment by vuongdh** [comment]
Bản cập nhật [Treat4.2023.07.03v1](https://gofile.me/78TQg/VLmTgZYI4)
