### ISSUE TITLE
Lỗi - Sổ xuất viện không lấy được thông tin giải phẫu bệnh

### ISSUE THREAD

**Issue by le-an-87** [dh-hos/dhg.hosptaltreatment#127]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.1: Phiếu ghi nhận lỗi phát sinh DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN LỖI PHÁT SINH</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Ân**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **11/07/2023**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `Tất cả`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **Tất cả**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `an_ungbuou_sxv_gpb`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`](https://gofile.me/78TQg/lzDBL3T9r)

###### ![chi_tiet_loi](https://img.shields.io/badge/Chi%20tiết%20lỗi%20phát%20sinh-:-blue?style=for-the-badge&logo=github)

-  ![loi_benh_nhan](https://img.shields.io/badge/Chi%20tiết%20bệnh%20nhân-:-blue?style=plastic&logo=github)
   > _**MaBN**_: `2023017174` - _**MaKB**_: `2306005718` - _**MaBA**_: `010459` _**NgayKCB**_: `03/07/2023` - _**MaPhong**_: `N23` - _**MaDV**_: `06` - _**ThangKT**_: `07` - _**NamKT**_: `2023`

-  ![loi_cls](https://img.shields.io/badge/Chi%20tiết%20CLS-:-blue?style=plastic&logo=github)
   > _**MaCLS**_: `XE101` - _**PhieuYC**_: `Sổ xuất viện`

###### ![mo_ta_loi](https://img.shields.io/badge/Mô%20tả%20thông%20tin%20lỗi-:-blue?style=for-the-badge&logo=github)

```
Sổ xuất viện không load được thông tin giải phẫu bệnh

```
Sổ xuất viện Treatment
![image](https://github.com/dh-hos/dhg.hosptaltreatment/assets/96155021/09ba0006-3f18-4bba-a1c3-caa16fa3ad78)

bệnh nhân có kết quả sinh thiết
![image](https://github.com/dh-hos/dhg.hosptaltreatment/assets/96155021/f4956875-dce5-4430-a501-ce4bfb04a757)

Sổ xuất viện Reports
![image](https://github.com/dh-hos/dhg.hosptaltreatment/assets/96155021/7afe22b7-6eb1-4464-b708-2da16c2679d1)

**Comment by vinh-dh** [comment]
Cách lấy cột `[Khoa GPB (nếu có)]` của Reports: `kqcdoankgp`

`SELECT nt.mabn,nt.makb,gpb.kqcdoankgp`
`FROM current.bnnoitru nt`
`           LEFT JOIN`
`           (`
`                    SELECT	mabn,makb,current.sumtext(TRIM(chandoangiaiphaubenh) || '\n') AS kqcdoankgp `
`                    FROM	current.pssinhthiet`
`                    WHERE	TRIM(COALESCE(chandoangiaiphaubenh,'')) != ''`
`                    GROUP BY mabn,makb `
`           ) gpb ON nt.mabn = gpb.mabn AND nt.makb = gpb.makb`

**Comment by vuongdh** [comment]
Bản cập nhật lỗi không hiển thị cột GPB [Treat4.2023.07.13v1](https://gofile.me/78TQg/mAQnhcMW8)

**Comment by le-an-87** [comment]
Trang in không hiển thị nội dung GPB anh ơi
Form không kéo rộng được cột để xem nội dung. anh coi lại chổ đó với
![image](https://github.com/dh-hos/dhg.hosptaltreatment/assets/96155021/99883398-6f23-4797-a48a-bfd9fd3c55a0)
