### ISSUE TITLE
Lỗi - EPR cấu hình gửi toa BHYT nhưng vẫn gửi toa nhà thuốc

### ISSUE THREAD

**Issue by le-an-87** [dh-hos/dhg.hosptaltreatment#130]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.1: Phiếu ghi nhận lỗi phát sinh DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN LỖI PHÁT SINH</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Ân**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **11/07/2023**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `Tất cả`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **Tất cả**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `an_phucgiakhanh_epr`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`](https://gofile.me/78TQg/i800K4V4q)

###### ![chi_tiet_loi](https://img.shields.io/badge/Chi%20tiết%20lỗi%20phát%20sinh-:-blue?style=for-the-badge&logo=github)

-  ![loi_benh_nhan](https://img.shields.io/badge/Chi%20tiết%20bệnh%20nhân-:-blue?style=plastic&logo=github)
   > _**MaBN**_: `2023002732` - _**MaKB**_: `2307000824` - _**NgayKCB**_: `11/07/2023` - _**MaPhong**_: `P02` - _**MaDV**_: `03.18` - _**ThangKT**_: `07` - _**NamKT**_: `2023`
-  ![loi_thuoc](https://img.shields.io/badge/Chi%20tiết%20thuốc-:-blue?style=plastic&logo=github)
   > _**KhoChan**_: `13` - _**KhoLe**_: `13` - _**SoHD**_: `N3.00157/202307` - _**MaDonThuoc**_: `771560002836-C` - _**NgayHD**_: `11/07/2023` - _**ThangKT**_: `07` - _**NamKT**_: `2023`

###### ![mo_ta_loi](https://img.shields.io/badge/Mô%20tả%20thông%20tin%20lỗi-:-blue?style=for-the-badge&logo=github)

```
EPR cấu hình tham số guitoa_epr = 2: gửi toa bảo hiểm
 1. phần mềm vẫn load các toa thuốc nhà thuốc lên và cho phép gửi lên cổng.
 2. Phần mềm gửi tự động vẫn gửi các toa thuốc thuộc kho nhà thuốc

* Đề xuất phân tích lại các trường hợp: toa nhà thuốc, toa khoa dược không thanh bhyt, toa thanh bhyt, đối tượng thu phí, đối tượng bảo hiểm.
```
Bệnh nhân có toa mua ngoài thuộc kho 13
![image](https://github.com/dh-hos/dhg.hosptaltreatment/assets/96155021/1128cafa-f290-429a-ab70-9636cad7d489)
Cấu hình gửi EPR
![image](https://github.com/dh-hos/dhg.hosptaltreatment/assets/96155021/a8f85a5b-fe5a-4186-aabd-a9284beec3db)
Toa nhà thuốc vẫn load lên chức năng TOA THUỐC và cho phép gửi lên cổng đơn thuốc điện tử
![image](https://github.com/dh-hos/dhg.hosptaltreatment/assets/96155021/2c374d7c-7636-4914-812f-1805c021fab9)
nhật ký gửi đơn thuốc điện tử
![image](https://github.com/dh-hos/dhg.hosptaltreatment/assets/96155021/6be2626a-b96e-41ce-be22-9a4963e60771)
[FIle nhật ký ngày 11/07/2023](https://github.com/dh-hos/dhg.hosptaltreatment/files/12012532/2023_07_11_SuccessFile.txt)

**Comment by vuongdh** [comment]
@le-an-87 trường hợp này toa thuốc có đối tượng là 03 (thuộc đối tượng bảo hiểm: dmdoituong.bhyt =2) nên được được tính là toa bảo hiểm đó em

**Comment by le-an-87** [comment]
![image](https://github.com/dh-hos/dhg.hosptaltreatment/assets/96155021/61baea30-132c-48f7-9ec5-bbef256cc44f)
chổ này là toa thu phí, toa bảo hiểm mà anh.
chứ đâu có nói là theo đối tượng.

**Comment by le-an-87** [comment]
Với lại anh coi mấy cái đề xuất của em ở trên đó anh cái nào thực hiện , cái nào không để em biết hỗ trợ bv nha!

**Comment by vuongdh** [comment]
Anh bổ sung thêm trường hợp: loại bỏ toa mua ngoài nếu chỉ gửi toa bảo hiểm
Module [Cấu hình](https://gofile.me/78TQg/6xxzJI6q7)
Module gửi Auto [Auto](https://gofile.me/78TQg/6JqR25N3e)

**Comment by chauthanhtra** [comment]
Alo anh @vuongdh 
Toa mua ngoài anh cho gửi chung với toa thu phí được không anh
Hiện tại nếu chọn gửi toa thu phí tham số = 1 thì phần mềm không load toa mua ngoài lên danh sách

**Comment by vuongdh** [comment]
@chauthanhtra OK em, nhưng hiện tại anh chưa thấy đơn vị nào chỉ gửi toa thu phí mà không gửi toa bảo hiểm nên chưa làm

**Comment by vuongdh** [comment]
@chauthanhtra Bảng cập nhật, em test lại hén [Cấu hình EPR](https://gofile.me/78TQg/MaswDQgf5)

**Comment by chauthanhtra** [comment]
Tham số bằng 1 (gửi toa thu phí)
- Phần mềm load luôn toa ngày cũ và toa mua ngoài đã xóa lên danh sách
- Danh sách đã gửi và gửi lỗi cũng load sai thông tin

![image](https://github.com/dh-hos/dhg.hosptaltreatment/assets/97272332/1dec1a23-9bbe-41cd-a0e3-c6f818e1598d)
![image](https://github.com/dh-hos/dhg.hosptaltreatment/assets/97272332/be447c9c-c7a8-45a9-8861-85b312b04b80)

**Comment by chauthanhtra** [comment]
Data: tra_phucgiakhang_guiloi
toa ngày 13/7/2023
Phần mềm gửi tay báo lỗi không gửi được

![image](https://github.com/dh-hos/dhg.hosptaltreatment/assets/97272332/4227c486-5ee3-42f7-b9c2-da56bf37dd79)

**Comment by vuongdh** [comment]
@chauthanhtra Cập nhật [Cấu hình gửi EPR](https://gofile.me/78TQg/lUfNPSxyD)
- Fix lỗi tham số gửi toa = 1
- Fix lỗi gửi không được ( nguyên nhân: tài khoản bác sĩ ra toa KHÔNG đăng nhập cổng thành công): fix bật thông báo cho người dùng và dừng gửi.

**Comment by chauthanhtra** [comment]
phần mềm autoEPR có cần bản mới không anh @vuongdh

**Comment by vuongdh** [comment]
không em
