### ISSUE TITLE
Lỗi - Giấy ra viện TT18 mẫu tự thiết kế - thiếu thông tin mã số BHXH

### ISSUE THREAD

**Issue by le-an-87** [dh-hos/dhg.hosptaltreatment#135]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.1: Phiếu ghi nhận lỗi phát sinh DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN LỖI PHÁT SINH</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Ân**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **19/07/2023**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `Tất cả`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **Tất cả**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `an_lapvo_full_16062023`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`]()

###### ![chi_tiet_loi](https://img.shields.io/badge/Chi%20tiết%20lỗi%20phát%20sinh-:-blue?style=for-the-badge&logo=github)

-  ![loi_benh_nhan](https://img.shields.io/badge/Chi%20tiết%20bệnh%20nhân-:-blue?style=plastic&logo=github)
   > _**MaBN**_: `2023002173` - _**MaKB**_: `2306007506` - _**MaBA**_: `2023005875` _**NgayKCB**_: `19/07/2023` - _**MaDV**_: `DY` - _**ThangKT**_: `06` - _**NamKT**_: `2023`

###### ![mo_ta_loi](https://img.shields.io/badge/Mô%20tả%20thông%20tin%20lỗi-:-blue?style=for-the-badge&logo=github)

```
Mẫu giấy ra viện theo TT18 chưa load được số BHXH của bệnh nhân.
bệnh viện yêu cầu bổ sung theo thông tin BHXH theo mẫu TT18.

```
Giấy ra viện theo tt18
![image](https://github.com/dh-hos/dhg.hosptaltreatment/assets/96155021/39e9f171-fa13-41b3-a7f3-f1b40739101f)
Thông tin bệnh nhân
![image](https://github.com/dh-hos/dhg.hosptaltreatment/assets/96155021/2383ac94-3a45-4232-9070-ee85b5f8c0fe)

**Comment by vuongdh** [comment]
Chổ đó là hoặc đó em. Ý em là muốn để cả 2: thẻ BHYT và BHXH hay sao?

**Comment by le-an-87** [comment]
thì là hoặc nhưng mà hiện tại nếu bệnh viện không lấy thẻ bhyt mà muốn lấy mã BHXH thì Treatment đâu lấy được.
BV muốn bổ sung thêm trường đó thôi.

- Theo ý em thì chổ Treatment cho thêm cái para BHXH và 1 cái bao gồm thẻ bhyt/BHXH luôn.
bệnh viện cần cái nào tự thiết kế lại thôi, mình khỏi chỉnh sửa nữa.

**Comment by vuongdh** [comment]
[Bản cập nhật Treat4.2023.07.20v2](https://gofile.me/78TQg/kB3SCyAvQ)
Bổ sung parameter: bhxh vào giấy xuất viện thông tư 18

**Comment by le-an-87** [comment]
Đã bổ sung mã BHXH!
