### ISSUE TITLE
Lỗi - Phiếu chỉ định cls tự thiết kế không hiển thị được mộc KHẨN

### ISSUE THREAD

**Issue by le-an-87** [dh-hos/dhg.hosptaltreatment#136]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.1: Phiếu ghi nhận lỗi phát sinh DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN LỖI PHÁT SINH</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **ÂN**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **19/07/2023**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `92118`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **BV Phụ Sản CT**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `an_phusan_nxt_at45`

###### ![chi_tiet_loi](https://img.shields.io/badge/Chi%20tiết%20lỗi%20phát%20sinh-:-blue?style=for-the-badge&logo=github)

-  ![loi_benh_nhan](https://img.shields.io/badge/Chi%20tiết%20bệnh%20nhân-:-blue?style=plastic&logo=github)
   > _**MaBN**_: `2023054224` - _**MaKB**_: `2306018974` - _**MaBA**_: `010876` _**NgayKCB**_: `19/07/2023` - _**MaPhong**_: `35` - _**MaDV**_: `12` - _**ThangKT**_: `07` - _**NamKT**_: `2023`

   > _**MaCLS**_: `DI95` - _**PhieuYC**_: `Phiếu chỉ định cls`
###### ![mo_ta_loi](https://img.shields.io/badge/Mô%20tả%20thông%20tin%20lỗi-:-blue?style=for-the-badge&logo=github)

```
CLS DI95 được chỉ định và có check khẩn
Mẫu thiết kế chỉ định cls cũng đã thêm para Khẩn
nhưng in phiếu chỉ định cls thì lại không hiển thị mộc KHẨN
```
![image](https://github.com/dh-hos/dhg.hosptaltreatment/assets/96155021/63d326fb-14df-440c-a985-8d2138521c28)

**Comment by vuongdh** [comment]
[Bản cập nhật Treat4.2023.07.20v1](https://gofile.me/78TQg/5m3kupHTz)

**Comment by le-an-87** [comment]
Đã fix!
