### ISSUE TITLE
Lỗi - In chi phí hằng ngày theo danh sách

### ISSUE THREAD

**Issue by lqbinh1987** [dh-hos/dhg.hosptaltreatment#138]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.1: Phiếu ghi nhận lỗi phát sinh DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN LỖI PHÁT SINH</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Bình**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **28/07/2023**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `92117`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **BV Huyết Học**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `binh_huyethoc_t7_binh`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`](link_csdl)

###### ![chi_tiet_loi](https://img.shields.io/badge/Chi%20tiết%20lỗi%20phát%20sinh-:-blue?style=for-the-badge&logo=github)

-  ![loi_benh_nhan](https://img.shields.io/badge/Chi%20tiết%20bệnh%20nhân-:-blue?style=plastic&logo=github)
   > _**MaBN**_: `MaBN` - _**MaKB**_: `MaKB` - _**MaBA**_: `MaBA` _**NgayKCB**_: `NgayKCB` - _**MaPhong**_: `MaPhong` - _**MaDV**_: `MaDV` - _**ThangKT**_: `ThangKT` - _**NamKT**_: `NamKT`
-  ![loi_thuoc](https://img.shields.io/badge/Chi%20tiết%20thuốc-:-blue?style=plastic&logo=github)
   > _**KhoChan**_: `KhoChan` - _**KhoLe**_: `KhoLe` - _**MaHH**_: `MaHH` - _**SoHD**_: `SoHD` - _**NgayHD**_: `NgayHD` - _**ThangKT**_: `ThangKT` - _**NamKT**_: `NamKT`
-  ![loi_cls](https://img.shields.io/badge/Chi%20tiết%20CLS-:-blue?style=plastic&logo=github)
   > _**MaCLS**_: `MaCLS` - _**PhieuYC**_: `PhieuYC`
-  ![loi_bo_sung](https://img.shields.io/badge/Chi%20tiết%20bổ%20sung-:-blue?style=plastic&logo=github)
   > _**Khac**_: `Khac`

###### ![mo_ta_loi](https://img.shields.io/badge/Mô%20tả%20thông%20tin%20lỗi-:-blue?style=for-the-badge&logo=github)

Ở chức năng mới bổ sung, in TK CP ngày(danh sách)(hình 1), khi mới mở form lên chọn ds tên bn in lần đầu thì được, nhưng khi in xong rồi chọn lại tên BN đó in lại thì báo lỗi(hình 2), Bấm Continue rồi bấm in tiếp thì có khi nó bị Not respond....rồi tắt pm luôn, có khi nó báo lỗi tiếp(hình 3), rồi cứ thế bấm in lại bn đó hoặc bn khác thì lại tiếp tục báo lỗi như hình 2 và hình 4 và hình 5

Hình 1
![image](https://github.com/dh-hos/dhg.hosptaltreatment/assets/99630883/65eaccef-c068-4cd5-a2c5-dbc8853a7950)

Hình 2
![image](https://github.com/dh-hos/dhg.hosptaltreatment/assets/99630883/7f728202-9dab-4448-b75d-6b3217c5d1a1)

Hình 3
![image](https://github.com/dh-hos/dhg.hosptaltreatment/assets/99630883/61e70ebe-8c95-4902-a173-f9232507e42b)

Hình 4
![image](https://github.com/dh-hos/dhg.hosptaltreatment/assets/99630883/b17e75e2-0bb9-433f-8267-736f75698c7a)

Hình 5
![image](https://github.com/dh-hos/dhg.hosptaltreatment/assets/99630883/499b5171-da11-49c8-8de8-d8eb47b7f677)

**Comment by vuongdh** [comment]
[Bảng cập nhật Treat4.2023.07.31v1](https://gofile.me/78TQg/AdcMcHSvl)

**Comment by lqbinh1987** [comment]
Anh @vuongdh, chổ in chi phí hằng ngày đồng loạt đã ok, nhưng chưa đúng ý ban đầu e nói, có nghĩa là ví dụ khi chọn danh sách 10 BN từ ngày 01/08 đến 03/08, 10 Bn được chọn đó đều có chi phí từ ngày 01/08 đến 03/08 thì mỗi BN phải in 3 tờ của 3 ngày. Và cái ngày chổ Kế toán viện phí phía dưới là ngày của phát sinh chi phí chứ ko phải ngày in phiếu(hiện tại đang lấy ngày in phiếu), vì theo e mô tả phía trên thì mỗi ngày là 1 phiếu.

![image](https://github.com/dh-hos/dhg.hosptaltreatment/assets/99630883/b35556e1-66aa-4fea-afdf-23b828ebca73)

**Comment by vuongdh** [comment]
[Bản cập nhật Treat4.2023.08.02v2](https://gofile.me/78TQg/oCvCDe3uH)

**Comment by vuongdh** [comment]
@lqbinh1987 bổ sung trên form thôi phải không?

**Comment by lqbinh1987** [comment]
Dạ đúng rồi anh @vuongdh 

> @lqbinh1987 bổ sung trên form thôi phải không?

**Comment by vuongdh** [comment]
[Bản cập nhật Treat4.2023.08.08v1](https://gofile.me/78TQg/udpNR3Ysc)
