### ISSUE TITLE
Lỗi - CLS có cấu hình mẫu chẩn nhưng in chỉ định không lên.

### ISSUE THREAD

**Issue by lqbinh1987** [dh-hos/dhg.hosptaltreatment#14]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.1: Phiếu ghi nhận lỗi phát sinh DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN LỖI PHÁT SINH</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Lâm Quốc Bình**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **23/08/2022**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `92003`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **BV Nhi Đồng CT**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `dbnhidong20`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`](link_csdl)

###### ![chi_tiet_loi](https://img.shields.io/badge/Chi%20tiết%20lỗi%20phát%20sinh-:-blue?style=for-the-badge&logo=github)

-  ![loi_benh_nhan](https://img.shields.io/badge/Chi%20tiết%20bệnh%20nhân-:-blue?style=plastic&logo=github)
   > _**MaBN**_: `2022120773` - _**MaKB**_: `MaKB` - _**MaBA**_: `2022018972` _**NgayKCB**_: `NgayKCB` - _**MaPhong**_: `MaPhong` - _**MaDV**_: `12` - _**ThangKT**_: `08` - _**NamKT**_: `2022`
-  ![loi_thuoc](https://img.shields.io/badge/Chi%20tiết%20thuốc-:-blue?style=plastic&logo=github)
   > _**KhoChan**_: `KhoChan` - _**KhoLe**_: `KhoLe` - _**MaHH**_: `MaHH` - _**SoHD**_: `SoHD` - _**NgayHD**_: `NgayHD` - _**ThangKT**_: `ThangKT` - _**NamKT**_: `NamKT`
-  ![loi_cls](https://img.shields.io/badge/Chi%20tiết%20CLS-:-blue?style=plastic&logo=github)
   > _**MaCLS**_: `VI03` - _**PhieuYC**_: `PhieuYC`
-  ![loi_bo_sung](https://img.shields.io/badge/Chi%20tiết%20bổ%20sung-:-blue?style=plastic&logo=github)
   > _**Khac**_: `Khac`

###### ![mo_ta_loi](https://img.shields.io/badge/Mô%20tả%20thông%20tin%20lỗi-:-blue?style=for-the-badge&logo=github)

CSL thuộc Loại kho là Vi Sinh(VS1) đã được cấu hình mẫu chuẩn, nhưng khi in mẫu chỉ định CLS thì nó không lên, đúng ra phải lên mẫu Vi sinh.
Mấy kho HH, NT, SH nếu có cấu hình mẫu chuẩn thì in lên theo mẫu bình thường.
![image](https://user-images.githubusercontent.com/99630883/186097463-b4baf4c1-65b1-4aae-b145-ec472671a109.png)
![image](https://user-images.githubusercontent.com/99630883/186097557-7e4bf667-4f93-4d53-b957-ebba67d9d54d.png)

**Comment by vuongdh** [comment]
@lqbinh1987 không hình dung nó ở mẫu nào?

**Comment by lqbinh1987** [comment]
Mẫu Vi Sinh(35/BV-01) nhe anh @vuongdh .

**Comment by vuongdh** [comment]
@lqbinh1987 gửi anh cái mẫu xem

**Comment by vuongdh** [comment]
@lqbinh1987 trên treatment chưa có mẫu vi sinh chuẩn

**Comment by vuongdh** [comment]
@lqbinh1987 em in từ labo rồi gửi anh xem

**Comment by lqbinh1987** [comment]
Nè anh @vuongdh .
![image](https://user-images.githubusercontent.com/99630883/187344645-e99c82ac-4654-419f-b2d6-b1f6c9525d6e.png)

**Comment by lqbinh1987** [comment]
Nhờ anh @vuongdh xem fix dùm em in mẫu vi sinh như trên nhé anh

**Comment by lqbinh1987** [comment]
Thực hiện theo quy chế và nội quy mới ngày 25/08/2022.

**Comment by lqbinh1987** [comment]
Còn lỗi chổ này nè a @vuongdh, những CLS nào không có xn con và không thuộc Loại kho xn khác thì khi in phiếu Xét nghiệm khác(mẫu 27) bị double tên CLS.
![image](https://user-images.githubusercontent.com/99630883/188528165-fe7ae34b-a959-4c85-b684-3c6613111f61.png)

**Comment by vuongdh** [comment]
@lqbinh1987 để anh xem

**Comment by vuongdh** [comment]
@lqbinh1987 Có bản cập nhật [version 0907v1] (http://www.fsend.vn/download/nt3QUbNiu5BSYZ4i1p2VKeQyiOFBR2nY)
