### ISSUE TITLE
Lỗi - In toa VTYT kèm theo - Phiếu công khai luôn hiển thị Phiếu in lại

### ISSUE THREAD

**Issue by le-an-87** [dh-hos/dhg.hosptaltreatment#140]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.1: Phiếu ghi nhận lỗi phát sinh DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN LỖI PHÁT SINH</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Ân**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **02/08/2023**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `Tất cả`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **Tất cả**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `an_thotnot_phieucongkhai`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`](https://gofile.me/78TQg/AAB2SYGTh)

###### ![chi_tiet_loi](https://img.shields.io/badge/Chi%20tiết%20lỗi%20phát%20sinh-:-blue?style=for-the-badge&logo=github)

-  ![loi_benh_nhan](https://img.shields.io/badge/Chi%20tiết%20bệnh%20nhân-:-blue?style=plastic&logo=github)
   > _**MaBN**_: `2020022158` - _**MaKB**_: `2307017217` - _**MaBA**_: `2023012949` _**NgayKCB**_: `02/08/2023` -  _**MaDV**_: `03` - _**ThangKT**_: `08` - _**NamKT**_: `2023`

###### ![mo_ta_loi](https://img.shields.io/badge/Mô%20tả%20thông%20tin%20lỗi-:-blue?style=for-the-badge&logo=github)

```
Chức năng toa vật tư kèm theo
1. chức năng in báo lỗi.
2. Phiếu công khai toa VTKT luôn hiển thị mộc PHIẾU IN LẠI.

```
1. lỗi chức năng in toa
![image](https://github.com/dh-hos/dhg.hosptaltreatment/assets/96155021/0f577c68-2669-42ae-aead-aaf3be565314)
2. Phiếu công khai
![image](https://github.com/dh-hos/dhg.hosptaltreatment/assets/96155021/3aa45218-6b20-46a8-a8d4-659bafe6401f)

**Comment by vuongdh** [comment]
[Bản cập nhật Treat4.2023.08.02v2](https://gofile.me/78TQg/oCvCDe3uH)

**Comment by le-an-87** [comment]
Bản Treatment mới hết lỗi in toa rồi.
Nhưng in toa nào cũng không có mộc Phiếu in lại hết anh
chổ này toa thuốc thế nào mới hiển thị mộc Phiếu in lại vậy anh?
