### ISSUE TITLE
Lỗi - BV CÁI RĂNG LỖI KHI CHO TOA NỘI TRÚ NHÀ THUỐC NẾU NHẬP SỐ LƯỢNG = TỒN CUỐI

### ISSUE THREAD

**Issue by nqhoa1005** [dh-hos/dhg.hosptaltreatment#141]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.1: Phiếu ghi nhận lỗi phát sinh DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN LỖI PHÁT SINH</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **NGUYỄN QUỐC HÒA**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **02/08/2023**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `92006`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **TTYT QUẬN CÁI RĂNG**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `hoa_bvcr08`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`](link_csdl)

###### ![chi_tiet_loi](https://img.shields.io/badge/Chi%20tiết%20lỗi%20phát%20sinh-:-blue?style=for-the-badge&logo=github)

-  ![loi_benh_nhan](https://img.shields.io/badge/Chi%20tiết%20bệnh%20nhân-:-blue?style=plastic&logo=github)
   > _**MaBN**_: `MaBN` - _**MaKB**_: `MaKB` - _**MaBA**_: `MaBA` _**NgayKCB**_: `NgayKCB` - _**MaPhong**_: `MaPhong` - _**MaDV**_: `MaDV` - _**ThangKT**_: `ThangKT` - _**NamKT**_: `NamKT`
-  ![loi_thuoc](https://img.shields.io/badge/Chi%20tiết%20thuốc-:-blue?style=plastic&logo=github)
   > _**KhoChan**_: `KhoChan` - _**KhoLe**_: `KhoLe` - _**MaHH**_: `MaHH` - _**SoHD**_: `SoHD` - _**NgayHD**_: `NgayHD` - _**ThangKT**_: `ThangKT` - _**NamKT**_: `NamKT`
-  ![loi_cls](https://img.shields.io/badge/Chi%20tiết%20CLS-:-blue?style=plastic&logo=github)
   > _**MaCLS**_: `MaCLS` - _**PhieuYC**_: `PhieuYC`
-  ![loi_bo_sung](https://img.shields.io/badge/Chi%20tiết%20bổ%20sung-:-blue?style=plastic&logo=github)
   > _**Khac**_: `Khac`

###### ![mo_ta_loi](https://img.shields.io/badge/Mô%20tả%20thông%20tin%20lỗi-:-blue?style=for-the-badge&logo=github)

Phát sinh lỗi nếu nhập số lượng thuốc  = tồn cuối khi cho toa nhà thuốc
![image](https://github.com/dh-hos/dhg.hosptaltreatment/assets/130281806/6287d000-1fef-4715-b1e7-314d7bddb9c8)

**Comment by vuongdh** [comment]
@nqhoa1005 em nói bv đóng và cho lại xem, lỗi này ko phải do bằng đâu, để anh xem lại

**Comment by nqhoa1005** [comment]
trường hợp trong kho có 2 lô khi nhập số lượng = tồn cuối hoặc cao hơn tồn cuối của 1 lô trong kho cũng bị anh,
em test tắt mở lại rồi vẫn lỗi

![image](https://github.com/dh-hos/dhg.hosptaltreatment/assets/130281806/cbf5ff82-236e-4363-bb2a-528f47e6b45e)
![image](https://github.com/dh-hos/dhg.hosptaltreatment/assets/130281806/54951ef4-b677-4169-91bb-491df23f1698)

**Comment by vuongdh** [comment]
em chạy cập nhật nhập, cập nhật xuất dùm anh hén

**Comment by vuongdh** [comment]
Đang vướng cái check âm kho
