### ISSUE TITLE
Lỗi - Chọn số lưu trữ bệnh án.

### ISSUE THREAD

**Issue by lqbinh1987** [dh-hos/dhg.hosptaltreatment#142]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.1: Phiếu ghi nhận lỗi phát sinh DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN LỖI PHÁT SINH</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Bình**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **02/08/2023**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `92117`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **BV Huyết Học**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `hh_082023`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`](link_csdl)

###### ![chi_tiet_loi](https://img.shields.io/badge/Chi%20tiết%20lỗi%20phát%20sinh-:-blue?style=for-the-badge&logo=github)

-  ![loi_benh_nhan](https://img.shields.io/badge/Chi%20tiết%20bệnh%20nhân-:-blue?style=plastic&logo=github)
   > _**MaBN**_: `2023000086` - _**MaKB**_: `MaKB` - _**MaBA**_: `003026` _**NgayKCB**_: `NgayKCB` - _**MaPhong**_: `MaPhong` - _**MaDV**_: `20` - _**ThangKT**_: `08` - _**NamKT**_: `2023`
-  ![loi_thuoc](https://img.shields.io/badge/Chi%20tiết%20thuốc-:-blue?style=plastic&logo=github)
   > _**KhoChan**_: `KhoChan` - _**KhoLe**_: `KhoLe` - _**MaHH**_: `MaHH` - _**SoHD**_: `SoHD` - _**NgayHD**_: `NgayHD` - _**ThangKT**_: `ThangKT` - _**NamKT**_: `NamKT`
-  ![loi_cls](https://img.shields.io/badge/Chi%20tiết%20CLS-:-blue?style=plastic&logo=github)
   > _**MaCLS**_: `MaCLS` - _**PhieuYC**_: `PhieuYC`
-  ![loi_bo_sung](https://img.shields.io/badge/Chi%20tiết%20bổ%20sung-:-blue?style=plastic&logo=github)
   > _**Khac**_: `Khac`

###### ![mo_ta_loi](https://img.shields.io/badge/Mô%20tả%20thông%20tin%20lỗi-:-blue?style=for-the-badge&logo=github)

Cho chọn số lưu trữ đã ok, nhưng còn phần lỗi 2 chổ này:
- Khi không nhập giá trị gì vào ô Số Lưu trữ thì bấm vô nút [...] sẽ xuất hiện lỗi như Hình dưới, còn nếu gõ đại 1 số nào đó vô thì bấm nút [...] mới load được. 
![image](https://github.com/dh-hos/dhg.hosptaltreatment/assets/99630883/57b118d6-499c-4e7d-9312-a6905416b482)

- Mặc dù cho người dùng tự gõ số lưu trữ nhưng phải bắt lại không được trùng với số lưu trữ của BN khác đang có, hiện cấp số lưu trữ cho BN rồi, nhưng cấp số đó lại cho BN khác vẫn được.. Đề nghị khi nhập vô số lưu trữ thì cảnh báo không cho nhập nếu số đó đã cấp cho Mã BN khác rồi
![image](https://github.com/dh-hos/dhg.hosptaltreatment/assets/99630883/babfe032-6806-4433-9e77-d97cbcdad097)
![image](https://github.com/dh-hos/dhg.hosptaltreatment/assets/99630883/5ba5c883-59e3-420c-9969-ad2d695c16bf)

**Comment by vuongdh** [comment]
[Bản cập nhật Treat4.2023.08.02v2](https://gofile.me/78TQg/oCvCDe3uH)

**Comment by lqbinh1987** [comment]
Anh @vuongdh  vẫn còn lỗi đã cấp số lưu trữ cho BN này rồi mà vẫn cấp cho mã BN khác nhe anh

**Comment by vuongdh** [comment]
em nêu cụ thể hơn nhé

**Comment by vuongdh** [comment]
em xài số lưu tự gõ hay phần mềm cấp, nêu cụ thể cách thực hiện để anh test hén

**Comment by lqbinh1987** [comment]
Hiện tại quy trình là cho người dùng chọn lại số lưu trữ BN có trước đó và tự gõ á anh, là đã ok. Nhưng phát sinh cái lỗi lúc tự gõ là có thể trùng vứi số lưu trữ đã cấp rồi á anh @vuongdh.

**Comment by vuongdh** [comment]
[Bản cập nhật Treat4.2023.08.03v2](https://gofile.me/78TQg/IW4RhDfIq)
