### ISSUE TITLE
Lỗi - Phiếu tổng hợp in dư 1 trang trống VTYT

### ISSUE THREAD

**Issue by le-an-87** [dh-hos/dhg.hosptaltreatment#147]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.1: Phiếu ghi nhận lỗi phát sinh DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN LỖI PHÁT SINH</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Ân**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **21/08/2023**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `Tất cả`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **Tất cả**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `an_thotnot_phieucongkhai`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`](https://gofile.me/78TQg/AAB2SYGTh)

###### ![chi_tiet_loi](https://img.shields.io/badge/Chi%20tiết%20lỗi%20phát%20sinh-:-blue?style=for-the-badge&logo=github)

-  ![loi_benh_nhan](https://img.shields.io/badge/Chi%20tiết%20bệnh%20nhân-:-blue?style=plastic&logo=github)
   > _**MaBN**_: `2020022158` - _**MaKB**_: `2307017217` - _**MaBA**_: `2023012949` _**NgayKCB**_: `01/08/2023` - _**MaDV**_: `03` - _**ThangKT**_: `08` - _**NamKT**_: `2023`
-  ![loi_thuoc](https://img.shields.io/badge/Chi%20tiết%20thuốc-:-blue?style=plastic&logo=github)
   > _**SoCTNB**_: `069005`

###### ![mo_ta_loi](https://img.shields.io/badge/Mô%20tả%20thông%20tin%20lỗi-:-blue?style=for-the-badge&logo=github)

```
Khi in phiếu tổng hợp phần mềm in thêm 1 trang trống VTYT.

```
![image](https://github.com/dh-hos/dhg.hosptaltreatment/assets/96155021/17eb6251-9691-4c2b-a47b-0cf65af885cb)

**Comment by chauthanhtra** [comment]
Thêm BV Gia Rai báo lỗi đó nữa nha anh @vuongdh

**Comment by le-an-87** [comment]
Đã chỉnh xong cho đơn vị
* bệnh nhân có toa thuốc ở khoa dược -> chỉnh đối tượng sang 06 thuốc vẫn ở khoa Dược.

**Comment by vuongdh** [comment]
[Bảng cập nhật Treat4.2023.09.22v3 - Fix lỗi in dư trang](https://gofile.me/78TQg/0bnFME03g)

**Comment by le-an-87** [comment]
đã fix!
