### ISSUE TITLE
Yêu cầu - Giấy chứng nhận Phẫu thuật ngày ký lấy ngày ra viện

### ISSUE THREAD

**Issue by minhduc2it** [dh-hos/dhg.hosptaltreatment#150]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.2: Phiếu ghi nhận Yêu cầu mới DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN YÊU CẦU CHỨC NĂNG MỚI</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Đức**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **25/08/2023**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `92007`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **BV Ô Môn**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `duc_omon_chungnhanpt`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`] https://gofile.me/78TQg/vnxuFMnSv

###### ![chi_tiet_yeu_cau](https://img.shields.io/badge/Chi%20tiết%20yêu%20cầu%20-:-blue?style=for-the-badge&logo=github)

```
1. Giấy chứng nhận Phẫu thuật: ngày ký hiện tại lấy theo ngày phẫu thuật
Nhưng so với ngày ra viện thì ngày ký nhỏ hơn ngày ra viện 
Nên ngày ký hiện tại lấy theo ngày phẫu thuật thì ngày ký chưa hợp lý
BV yêu cầu Ngày ký lấy theo ngày ra viện
```
![image](https://github.com/dh-hos/dhg.hosptaltreatment/assets/98437757/7f0c4c8c-c46d-40ab-9f78-3c26784ddbad)

2. Trường hợp BN đã làm Phẫu thuật mà chưa ra viện. Khi in Giấy chứng nhận phẫu thuật chỗ Ngày ra viện thể hiện ngày hiện tại
Bv yêu cầu để trống ngày ra viện khi BN chưa ra viện nếu in Giấy chứng nhận phẫu thuật
![image](https://github.com/dh-hos/dhg.hosptaltreatment/assets/98437757/5814ac24-705e-4ae4-9d8b-888d93c15b95)

**Comment by vuongdh** [comment]
[Bản cập nhật Treat4.2023.08.28v1](https://gofile.me/78TQg/9D4a0WrBC)

**Comment by minhduc2it** [comment]
Còn trường hợp 2: Nếu BN chưa ra viện mà in Giấy chứng nhận thì Ngày ra viện để trống

**Comment by minhduc2it** [comment]
Trường hợp 2: BN chưa ra viện in Giấy chứng nhận phẫu thuật thì chỗ Ra viện lúc: để trống

**Comment by vuongdh** [comment]
[Bản cập nhật Treat4.2023.08.29v1](https://gofile.me/78TQg/Lce1ybFAA)
