### ISSUE TITLE
Lỗi - Giấy chứng nhận Phẫu thuật không thể hiện hết nội dung Cách thức phẫu thuật

### ISSUE THREAD

**Issue by minhduc2it** [dh-hos/dhg.hosptaltreatment#152]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.1: Phiếu ghi nhận lỗi phát sinh DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN LỖI PHÁT SINH</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Đức**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **05/09/2023**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `92086`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **BV Ung bướu**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `duc_ungbuou_giaycnpt`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`] https://gofile.me/78TQg/NsKpeZHhX

###### ![chi_tiet_loi](https://img.shields.io/badge/Chi%20tiết%20lỗi%20phát%20sinh-:-blue?style=for-the-badge&logo=github)

-  ![loi_benh_nhan](https://img.shields.io/badge/Chi%20tiết%20bệnh%20nhân-:-blue?style=plastic&logo=github)
   > _**MaBN**_: `2023035158` - _**MaKB**_: `2308011098` - _**MaBA**_: `015368` - _ **ThangKT**_: `09` - _**NamKT**_: `2023`

###### ![mo_ta_loi](https://img.shields.io/badge/Mô%20tả%20thông%20tin%20lỗi-:-blue?style=for-the-badge&logo=github)

```
Giấy chứng nhận Phẫu thuật không thể hiện hết nội dung Cách thức phẫu thuật khi có những PT nội dung quá dài

```
![image](https://github.com/dh-hos/dhg.hosptaltreatment/assets/98437757/b49e896d-c979-431f-b32c-b04351f676bf)

**Comment by vuongdh** [comment]
@minhduc2it em hỏi bv trường hợp vậy xử lý thế nào để mình hỗ trợ, vì mẫu có bao nhiêu khoản trống để mình điền chữ vào thôi

**Comment by vuongdh** [comment]
Chữ nhỏ thì cũng giới hạn thôi, chứ nội dung nhiều quá thì cũng thiếu à

**Comment by minhduc2it** [comment]
![image](https://github.com/dh-hos/dhg.hosptaltreatment/assets/98437757/f99a55f9-329a-4490-b6a4-606529f8ae82)

BV yêu cầu hỗ trợ chỉnh vầy anh

**Comment by vuongdh** [comment]
@minhduc2it bệnh nhân ở khoa nào vậy em?

**Comment by minhduc2it** [comment]
![image](https://github.com/dh-hos/dhg.hosptaltreatment/assets/98437757/d9be7015-30cf-4fc3-9795-f905e6f55d93)

Đơn vị: 06 - KHOA NGOẠI NHŨ HỌC - TIÊU HÓA (NGOẠI II)

**Comment by vuongdh** [comment]
[Bản cập nhật Treat4.2023.09.08v1](https://gofile.me/78TQg/dLlRGDd7A)
