### ISSUE TITLE
Lỗi - Phiếu chỉ định CLS mẫu chuẩn in thiếu chẩn đoán hoặc bị chồng lên thông tin khác

### ISSUE THREAD

**Issue by chauthanhtra** [dh-hos/dhg.hosptaltreatment#154]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.1: Phiếu ghi nhận lỗi phát sinh DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN LỖI PHÁT SINH</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Châu Thanh Trà **
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **11/9/2023**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `92086`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **BV Ung Bướu CT**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `tra_ungbuou_11092023_treatment_incls`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`](https://gofile.me/78TQg/FrmMpFBkZ)

###### ![chi_tiet_loi](https://img.shields.io/badge/Chi%20tiết%20lỗi%20phát%20sinh-:-blue?style=for-the-badge&logo=github)

-  ![loi_benh_nhan](https://img.shields.io/badge/Chi%20tiết%20bệnh%20nhân-:-blue?style=plastic&logo=github)
   > _**MaBN**_: `2023036022` - _**MaKB**_: `MaKB` - _**MaBA**_: `014832` _**NgayKCB**_: `11/9/2023` - _**MaPhong**_: `MaPhong` - _**MaDV**_: `22` - _**ThangKT**_: `09` - _**NamKT**_: `2023`
-  ![loi_thuoc](https://img.shields.io/badge/Chi%20tiết%20thuốc-:-blue?style=plastic&logo=github)
   > _**KhoChan**_: `KhoChan` - _**KhoLe**_: `KhoLe` - _**MaHH**_: `MaHH` - _**SoHD**_: `SoHD` - _**NgayHD**_: `NgayHD` - _**ThangKT**_: `ThangKT` - _**NamKT**_: `NamKT`
-  ![loi_cls](https://img.shields.io/badge/Chi%20tiết%20CLS-:-blue?style=plastic&logo=github)
   > _**MaCLS**_: `MaCLS` - _**PhieuYC**_: `PhieuYC`
-  ![loi_bo_sung](https://img.shields.io/badge/Chi%20tiết%20bổ%20sung-:-blue?style=plastic&logo=github)
   > _**Khac**_: `Khac`

###### ![mo_ta_loi](https://img.shields.io/badge/Mô%20tả%20thông%20tin%20lỗi-:-blue?style=for-the-badge&logo=github)

Mẫu phiếu chỉ định CLS bị ẩn 1 phần chẩn đoán hoặc bị chồng lên thông tin khác khi chẩn đoán dài

- Ngày giờ chỉ định: 11h28' 11/09/2023

- 1 số mẫu in thiếu chẩn đoán: X-Quang, Siêu âm, Nội soi, TT-PT, Dịch vụ

![ảnh](https://github.com/dh-hos/dhg.hosptaltreatment/assets/97272332/766c766d-bc99-487e-a059-31e148d3f83d)
![ảnh](https://github.com/dh-hos/dhg.hosptaltreatment/assets/97272332/2d43e681-2ad4-45e8-88f7-e0ad8a79b030)
![ảnh](https://github.com/dh-hos/dhg.hosptaltreatment/assets/97272332/05ac3ebd-3918-4597-b706-37cc54f4342c)
![ảnh](https://github.com/dh-hos/dhg.hosptaltreatment/assets/97272332/eb3253b2-67ad-4ccb-92b2-2a1ed1a1b517)
![ảnh](https://github.com/dh-hos/dhg.hosptaltreatment/assets/97272332/159dc717-9f6d-4d15-871a-dedb8ddbbc09)

- 1 số mẫu in bị chồng lên thông tin khác: Điện tim, Hóa sinh máu, Huyết học, Hóa sinh, Xét nghiệm khác

![ảnh](https://github.com/dh-hos/dhg.hosptaltreatment/assets/97272332/ad6298da-97c3-4826-a8bd-03e5d3367cd4)
![ảnh](https://github.com/dh-hos/dhg.hosptaltreatment/assets/97272332/c10db452-e0d5-46f0-a377-9ac9c59cd71e)
![ảnh](https://github.com/dh-hos/dhg.hosptaltreatment/assets/97272332/99882d35-261d-4e9b-8df0-252075f25d5d)
![ảnh](https://github.com/dh-hos/dhg.hosptaltreatment/assets/97272332/17497b23-26bb-4dba-a8ab-b789c63dfa34)
![ảnh](https://github.com/dh-hos/dhg.hosptaltreatment/assets/97272332/fdfba5e4-a678-4195-b6ca-730af32a3cfc)

**Comment by vuongdh** [comment]
Chẩn đoán quá dài, hỗ trợ phải thiết kế lại mẫu in

**Comment by vuongdh** [comment]
Nói đơn vị tách chẩn choán theo từng mẫu in coi được không? Này là gom tất cả chẩn đoán cho 1 lần chỉ định

**Comment by chauthanhtra** [comment]
Là mỗi khi chỉ định CLS phải chỉnh diễn biến cho ngắn lại hay sao anh? vậy khó cho BV,

**Comment by chauthanhtra** [comment]
- mình có thể thu nhỏ chữ hay gom gọn lại các thông tin khác như phần footer chữ ký,... để có thêm vài dòng được không anh
- 1 vài bệnh thì tách chẩn đoán theo CLS được nhiều sau làm nổi. mỗi lần in phải xem nó dư không nếu dư phải xóa CLS chỉnh chẩn đoán chỉ định lại thì khó lắm

**Comment by vuongdh** [comment]
ok

**Comment by vuongdh** [comment]
[Bản fix lỗi Treat4.2023.09.14v1](https://gofile.me/78TQg/T7vD3l8Nz)
