### ISSUE TITLE
Lỗi - Sai tiền bệnh nhân phải trả - bệnh nội trú

### ISSUE THREAD

**Issue by le-an-87** [dh-hos/dhg.hosptaltreatment#156]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.1: Phiếu ghi nhận lỗi phát sinh DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN LỖI PHÁT SINH</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Ân**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **12/09/2023**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `92118`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **BV Phụ Sản**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `an_phusan_lechtien_fees_treat`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`](https://gofile.me/78TQg/1QalzU7r7)

###### ![chi_tiet_loi](https://img.shields.io/badge/Chi%20tiết%20lỗi%20phát%20sinh-:-blue?style=for-the-badge&logo=github)

-  ![loi_benh_nhan](https://img.shields.io/badge/Chi%20tiết%20bệnh%20nhân-:-blue?style=plastic&logo=github)
   > _**MaBN**_: `2023077443` - _**MaKB**_: `2309000416` - _**MaBA**_: `015085` _**NgayKCB**_: `11/09/2023` - _**MaPhong**_: `ĐTTYC_KHU C` - _**MaDV**_: `25` - _**ThangKT**_: `09` - _**NamKT**_: `2023`

###### ![mo_ta_loi](https://img.shields.io/badge/Mô%20tả%20thông%20tin%20lỗi-:-blue?style=for-the-badge&logo=github)

```
FEES tính sai tiền bệnh nhân phải trả
Tổng PS:                    20,900,993
BHYT đã thanh toán: 4,154,554
Tiền bệnh nhân trả:  18,346,439

Chênh lệch tiền  BN trả + BHYT thanh # Tổng PS
chênh lệch 1,600,000

```
Fees
![image](https://github.com/dh-hos/dhg.hospitalfees/assets/96155021/43d5a6b8-9d23-4738-9f6d-ed1120f05e2d)

em có xuất excel danh sách file tính thử cũng chênh lệch so với fees
![image](https://github.com/dh-hos/dhg.hospitalfees/assets/96155021/8e188f61-9325-4fed-971a-019b481961e7)

**Comment by le-an-87** [comment]
Lỗi này bv Phụ sản mới báo thêm 3 cas tương tự vậy nữa nhe anh @vuongdh !

**Comment by vuongdh** [comment]
@le-an-87 anh test không thấy ra số tiền như em báo ta,
em thử lại với bản này xem sao hén 
link: https://gofile.me/78TQg/fpVMKLE7P
![image](https://github.com/dh-hos/dhg.hosptaltreatment/assets/32563776/ee2315f3-0a64-4135-a354-e955f5e56c9f)
![image](https://github.com/dh-hos/dhg.hosptaltreatment/assets/32563776/319f47bd-d908-4ff6-9f69-20b84915c4b6)

**Comment by le-an-87** [comment]
anh cho tỷ lệ 50 % nhe

**Comment by vuongdh** [comment]
Thanh 50% thì có đâu cột chênh lệch

**Comment by vuongdh** [comment]
![image](https://github.com/dh-hos/dhg.hosptaltreatment/assets/32563776/24cfe64c-cc3a-4f76-b7e1-4266182b5dd3)

**Comment by le-an-87** [comment]
anh bỏ check dv ra rồi

**Comment by vuongdh** [comment]
Chổ này cần mô tả để thống nhất cách ghi nhận dữ liệu

**Comment by vuongdh** [comment]
Hiện tại chỉ đáp ứng 1 trong 2 chức năng: làm cùng lúc ghi nhận dữ liệu sẽ bị sai

**Comment by vuongdh** [comment]
[Bảng cập nhật Treat4.2023.09.26v1](https://gofile.me/78TQg/y9asUsejd)
Cập nhật; 
- Lỗi vừa check dv và giảm tỉ lệ thanh toán
- Chỉ định CLS (Thông tin con)

Mô tả chỉ định CLS khi có check dịch vụ, thu phí:
Tham số ảnh hưởng: laygiadv, laygiadan, laygiamp

Đối tượng thu phí:
- check dịch vụ:
	+ dongia = giadv * tỉ lệ thanh thanh toán
	+ giabh  = giadv * tỉ lệ thanh thanh toán
	+ thanhtien = giadv * tỉ lệ thanh thanh toán * số lượng
	+ chenhlech = 0
- không check dịch vụ:
	+ dongia = dongia * tỉ lệ thanh thanh toán
	+ giabh  = giá bh theo danh mục * tỉ lệ thanh thanh toán
	+ thanhtien = dongia * tỉ lệ thanh thanh toán * số lượng
	+ chenhlech = 0
	p/s: dongia lấy theo tham số
	
Đối tượng miễn phí:
- check dịch vụ:
	+ dongia = dongia * tỉ lệ thanh thanh toán
	+ giabh  = giabhdm * tỉ lệ thanh thanh toán
	+ thanhtien = dongia * tỉ lệ thanh thanh toán * số lượng
	+ chenhlech = giadv - giabhdm
	
- không check dịch vụ:
	+ dongia = dongia * tỉ lệ thanh thanh toán
	+ giabh  = giabhdm * tỉ lệ thanh thanh toán
	+ thanhtien = dongia * tỉ lệ thanh thanh toán * số lượng
	+ chenhlech = 0
	p/s: dongia lấy theo tham số
	
Đối tượng bảo hiểm:
- check dịch vụ:
	+ dongia = dongia * tỉ lệ thanh thanh toán
	+ giabh  = giabhdm * tỉ lệ thanh thanh toán
	+ thanhtien = giabhdm * tỉ lệ thanh thanh toán * số lượng
	+ chenhlech = giadv - giabhdm
	
- không check dịch vụ:
	+ dongia = dongia * tỉ lệ thanh thanh toán
	+ giabh  = giabhdm * tỉ lệ thanh thanh toán
	+ thanhtien = giabhdm * tỉ lệ thanh thanh toán * số lượng
	+ chenhlech = 0
	p/s: dongia lấy theo tham số

**Comment by le-an-87** [comment]
test thử bản Treatment mới thì cách ghi nhận không đúng theo cách làm từ trước đến giờ và cũng không đúng theo yêu cầu của bệnh viện nhe anh @vuongdh !
![image](https://github.com/dh-hos/dhg.hosptaltreatment/assets/96155021/bbf0501b-8421-4168-ae75-038fabc1b651)
![image](https://github.com/dh-hos/dhg.hosptaltreatment/assets/96155021/9c9caf38-75a9-4a2d-ab95-7c43b38e31e7)

**Comment by vuongdh** [comment]
Em nếu cụ thể dùm anh hén

**Comment by le-an-87** [comment]
mã PH122
Giá BH: 2,945,000.00
Giá DV: 4,400,000.00
chỉ định dịch vụ + thanh bhyt với tỷ lệ thanh toán 50
sao thành tiền lại = 1,472,500 => thành tiền này là có tính dịch vụ chưa anh.

chênh lệch 1,455,000 ? 
đơn giá = 1,472,500, giá BH = 1,472,500 -> giữa giá BH và DV như vậy sao ra số chênh lệch này?

**Comment by vuongdh** [comment]
chênh lệch 1,455,000 = 4,400,000 - 2,945,000 (tính theo check dịch vụ)
đơn giá = 1,472,500, giá BH = 1,472,500 = 2,945,000 x 50% (tính theo giá quyết toán tỉ lệ)

**Comment by le-an-87** [comment]
Đã fix với bản [Treat4.2023.12.05v2](https://gofile.me/78TQg/j0Ce3dnCB)
