### ISSUE TITLE
Lỗi - Sai ngày ký phiếu Thủ thuật - Phẫu thuật

### ISSUE THREAD

**Issue by chauthanhtra** [dh-hos/dhg.hosptaltreatment#158]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.1: Phiếu ghi nhận lỗi phát sinh DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN LỖI PHÁT SINH</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Châu Thanh Trà **
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **18/9/2023**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `92007`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **BV Ô Môn**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `tra_omon_ngaykyphieuthuthuat`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`](https://gofile.me/78TQg/2VLTEW7Kv)

###### ![chi_tiet_loi](https://img.shields.io/badge/Chi%20tiết%20lỗi%20phát%20sinh-:-blue?style=for-the-badge&logo=github)

-  ![loi_benh_nhan](https://img.shields.io/badge/Chi%20tiết%20bệnh%20nhân-:-blue?style=plastic&logo=github)
   > _**MaBN**_: `2018029789` - _**MaKB**_: `MaKB` - _**MaBA**_: `2023011818` _**NgayKCB**_: `18/09/2023` - _**MaPhong**_: `MaPhong` - _**MaDV**_: `03` - _**ThangKT**_: `09` - _**NamKT**_: `2023`
-  ![loi_thuoc](https://img.shields.io/badge/Chi%20tiết%20thuốc-:-blue?style=plastic&logo=github)
   > _**KhoChan**_: `KhoChan` - _**KhoLe**_: `KhoLe` - _**MaHH**_: `MaHH` - _**SoHD**_: `SoHD` - _**NgayHD**_: `NgayHD` - _**ThangKT**_: `ThangKT` - _**NamKT**_: `NamKT`
-  ![loi_cls](https://img.shields.io/badge/Chi%20tiết%20CLS-:-blue?style=plastic&logo=github)
   > _**MaCLS**_: `CA233` - _**PhieuYC**_: `PhieuYC`
-  ![loi_bo_sung](https://img.shields.io/badge/Chi%20tiết%20bổ%20sung-:-blue?style=plastic&logo=github)
   > _**Khac**_: `Khac`

###### ![mo_ta_loi](https://img.shields.io/badge/Mô%20tả%20thông%20tin%20lỗi-:-blue?style=for-the-badge&logo=github)

Từ khi cập nhật phần mềm Treatment hỗ trợ mẫu Giấy chứng nhận PT-TT thì ngày ký trên Phiếu TT-PT bị cập nhật lại thành ngày ra viện nếu bệnh nhân ra viện hoặc ngày hiện tại nếu bệnh nhân chưa ra viện
-> BV Muốn chỉnh lại mẫu Phiếu  PT-TT như cũ: lấy ngày kết thúc PT-TT làm ngày ký như lúc trước (chỉ chỉnh ngày ký trên mẫu phiếu PT-TT)

![ảnh](https://github.com/dh-hos/dhg.hosptaltreatment/assets/97272332/faca0698-673d-4dd6-8eaa-a78662eee3d1)
![ảnh](https://github.com/dh-hos/dhg.hosptaltreatment/assets/97272332/739f35ab-50d2-46ca-8fae-03e745b0a41b)

**Comment by vuongdh** [comment]
@chauthanhtra Em xem lại chổ này dùm anh, nếu tách bạch thì ghi git lại hén
https://github.com/dh-hos/dhg.hosptaltreatment/issues/150

**Comment by vuongdh** [comment]
Cùng một đơn vị

**Comment by chauthanhtra** [comment]
Cái git của anh Đức là ngày ký trên Giấy chứng nhận PT-TT
Còn git của em là ngày ký trên Phiếu PT-TT
2 yêu cầu khác nhau nha anh

![ảnh](https://github.com/dh-hos/dhg.hosptaltreatment/assets/97272332/982ea822-294b-4fb5-9e6c-e88a00bf89e2)

**Comment by vuongdh** [comment]
[Bản cập nhật Treat4.2023.09.20v1](https://gofile.me/78TQg/HWN0kQPj7)

Lấy ngày kết thúc phẫu thuật làm ngày ký trên phiếu phẫu thuật/thủ thuật
