### ISSUE TITLE
Lỗi - Chặn ko cho xuất viện khi thời gian điều trị <4h.

### ISSUE THREAD

**Issue by lqbinh1987** [dh-hos/dhg.hosptaltreatment#159]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.1: Phiếu ghi nhận lỗi phát sinh DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN LỖI PHÁT SINH</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Bình**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **22/09/2023**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `94006`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **TTYT Thạnh Trị**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `tuan_dbthanhtri_full`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`](link_csdl)

###### ![chi_tiet_loi](https://img.shields.io/badge/Chi%20tiết%20lỗi%20phát%20sinh-:-blue?style=for-the-badge&logo=github)

-  ![loi_benh_nhan](https://img.shields.io/badge/Chi%20tiết%20bệnh%20nhân-:-blue?style=plastic&logo=github)
   > _**MaBN**_: `2023012020` - _**MaKB**_: `MaKB` - _**MaBA**_: `2023006920` _**NgayKCB**_: `22/09/2023` - _**MaPhong**_: `MaPhong` - _**MaDV**_: `18` - _**ThangKT**_: `09` - _**NamKT**_: `2023`
-  ![loi_thuoc](https://img.shields.io/badge/Chi%20tiết%20thuốc-:-blue?style=plastic&logo=github)
   > _**KhoChan**_: `KhoChan` - _**KhoLe**_: `KhoLe` - _**MaHH**_: `MaHH` - _**SoHD**_: `SoHD` - _**NgayHD**_: `NgayHD` - _**ThangKT**_: `ThangKT` - _**NamKT**_: `NamKT`
-  ![loi_cls](https://img.shields.io/badge/Chi%20tiết%20CLS-:-blue?style=plastic&logo=github)
   > _**MaCLS**_: `MaCLS` - _**PhieuYC**_: `PhieuYC`
-  ![loi_bo_sung](https://img.shields.io/badge/Chi%20tiết%20bổ%20sung-:-blue?style=plastic&logo=github)
   > _**Khac**_: `Khac`

###### ![mo_ta_loi](https://img.shields.io/badge/Mô%20tả%20thông%20tin%20lỗi-:-blue?style=for-the-badge&logo=github)

Hiện tại trường BN xuất viện có thời gian nằm điều trị <4h mà có chỉ định tiền giường thì phần mềm cảnh báo ko cho xuất viện, hiện theo [TT39](https://thuvienphapluat.vn/van-ban/Bao-hiem/Thong-tu-39-2018-TT-BYT-thong-nhat-gia-kham-chua-benh-bao-hiem-y-te-giua-benh-vien-cung-hang-401940.aspx) phần này áp cho đối tượng BHYT, nhưng hiện phần mềm chặn luôn đối tượng thu phí gây khó khăn cho người dùng. Như hình dưới đây là đối tượng thu phí mà cũng bị chặn.

![image](https://github.com/dh-hos/dhg.hosptaltreatment/assets/99630883/94f5afe6-8ecb-4f7f-a449-c4feeceacd36)

**Comment by vuongdh** [comment]
[Bảng cập nhật Treat4.2023.09.22.v1](https://gofile.me/78TQg/iM3jo8V7O)

Cập nhật trường hợp BN xuất viện có thời gian nằm điều trị <4h mà có chỉ định tiền giường: CHỈ TÁC DỤNG đối với BN BHYT
