### ISSUE TITLE
Lỗi - Lỗi in phiếu tử vong tt24

### ISSUE THREAD

**Issue by le-an-87** [dh-hos/dhg.hosptaltreatment#162]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.1: Phiếu ghi nhận lỗi phát sinh DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN LỖI PHÁT SINH</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Ân**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **24/10/2023**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `Tất cả`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **Tất cả**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `an_timmach_ag_gbt`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`](https://gofile.me/78TQg/Y1LC4czYJ)

###### ![chi_tiet_loi](https://img.shields.io/badge/Chi%20tiết%20lỗi%20phát%20sinh-:-blue?style=for-the-badge&logo=github)

-  ![loi_benh_nhan](https://img.shields.io/badge/Chi%20tiết%20bệnh%20nhân-:-blue?style=plastic&logo=github)
   > _**MaBN**_: `2023028399` - _**MaKB**_: `2310016388` - _**MaBA**_: `2023015211` _**NgayKCB**_: `24/10/2023` - _**MaPhong**_: `P100` - _**MaDV**_: `02` - _**ThangKT**_: `10` - _**NamKT**_: `2023`

###### ![mo_ta_loi](https://img.shields.io/badge/Mô%20tả%20thông%20tin%20lỗi-:-blue?style=for-the-badge&logo=github)

```
Lỗi in phiếu tử vong theo TT24.

```
![image](https://github.com/dh-hos/dhg.hosptaltreatment/assets/96155021/f65e6b7a-1e2f-4d80-a4e0-173edc02b3c4)

**Comment by vuongdh** [comment]
**Lỗi khi sử dụng DLL**
XtraRPT.Xtra.PrintPreviewDialogWithDefault("treat_phieutuvong24", "In phiếu tử vong TT24", "Treatment", this.username, this, xtraCDTuVong);
+ Load mẫu mặc định ==> **xảy ra lỗi**
 
![image](https://github.com/dh-hos/dhg.hosptaltreatment/assets/32563776/60304fd3-f5e0-4a1a-ad57-7a0c90ea30e8)

+ Save xtrareport sang sạng .repx và sử dụng load from file ==> **KHÔNG XẢY RA LỖI**
@ongtrieuhau em xem lại dùm anh

**Comment by vuongdh** [comment]
[File xtrareport](https://gofile.me/78TQg/F33yhQ6e8)

**Comment by ongtrieuhau** [comment]
Anh coi lại chỗ thiết kế xtra đừng thêm tham số ở hàm khởi tạo. Vì dll không biết truyền tham số vào. Hoặc anh phải thiết kế có hàm khởi tạo mà không truyền tham số vào.

**Comment by vuongdh** [comment]
Cập nhật: [Treat4.2023.10.24v1](https://gofile.me/78TQg/zaZQXoAkL)

[Nội dung cập nhật](https://github.com/dh-hos/dhg.hosptaltreatment/blob/main/README.md)

**Comment by le-an-87** [comment]
![image](https://github.com/dh-hos/dhg.hosptaltreatment/assets/96155021/131e16e6-f514-442e-8473-f7f753c26a6f)
chổ đơn vị tính không hiển thị được anh @vuongdh ơi

**Comment by vuongdh** [comment]
Cập nhật: [Treat4.2023.10.25v1](https://gofile.me/78TQg/491cE434B)

[Nội dung cập nhật](https://github.com/dh-hos/dhg.hosptaltreatment/blob/main/README.md)

**Comment by le-an-87** [comment]
Đã fix lỗi in và không hiển thị đơn vị.
(Phiên bản này không cho tự thiết kế phiếu tử vong tt24)
![image](https://github.com/dh-hos/dhg.hosptaltreatment/assets/96155021/5d18f0f8-0145-4ed6-9571-b8248d9586c6)
