### ISSUE TITLE
Lỗi - Không xuất viện được trường hợp bệnh nhân có toa và trả toa sau thời gian ra viện. (BV Thạnh Trị)

### ISSUE THREAD

**Issue by le-an-87** [dh-hos/dhg.hosptaltreatment#163]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.1: Phiếu ghi nhận lỗi phát sinh DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN LỖI PHÁT SINH</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Ân**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **27/10/2023**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `94006`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **BV Thạnh Trị**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `an_thanhtri_chiphi_xuatvien`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`](https://gofile.me/78TQg/QtZECbV7X)

###### ![chi_tiet_loi](https://img.shields.io/badge/Chi%20tiết%20lỗi%20phát%20sinh-:-blue?style=for-the-badge&logo=github)

-  ![loi_benh_nhan](https://img.shields.io/badge/Chi%20tiết%20bệnh%20nhân-:-blue?style=plastic&logo=github)
   > _**MaBN**_: `2019012623` - _**MaKB**_: `2310010721` - _**MaBA**_: `2023008306` _**NgayKCB**_: `27/10/2023` - _**MaPhong**_: `NO7` - _**MaDV**_: `18` - _**ThangKT**_: `10` - _**NamKT**_: `2023`

###### ![mo_ta_loi](https://img.shields.io/badge/Mô%20tả%20thông%20tin%20lỗi-:-blue?style=for-the-badge&logo=github)

```
Bệnh nhân có toa thuốc sau ngày cho ra viện và đã trả nguyên toa.
Treatment vẫn báo có chi phí sau ngày ra viện không cho xuất viện được.
```
![image](https://github.com/dh-hos/dhg.hosptaltreatment/assets/96155021/2ebdd752-5e88-4197-99fd-923ea51cf8a5)

các toa sau thời gian ra viện
![image](https://github.com/dh-hos/dhg.hosptaltreatment/assets/96155021/2482df18-78c4-4f40-9201-e532bf849e73)
Đã trả nguyên toa
![image](https://github.com/dh-hos/dhg.hosptaltreatment/assets/96155021/5cdf844a-2902-445f-b254-6b0f121f7924)

**Comment by vuongdh** [comment]
Cập nhật [Treat4.2023.10.31v1](https://gofile.me/78TQg/0k9rudZeC)

<div align="left">

[![View](https://img.shields.io/badge/-Xem%20chi%20ti%E1%BA%BFt%20c%E1%BA%ADp%20nh%E1%BA%ADt-informational?logo=github)](https://github.com/dh-hos/dhg.hosptaltreatment/blob/main/README.md)

</div>

**Comment by le-an-87** [comment]
Đã fix!
