### ISSUE TITLE
Lỗi - Giấy hẹn tái khám in bị lấp chữ, bị thiếu chữ

### ISSUE THREAD

**Issue by chauthanhtra** [dh-hos/dhg.hosptaltreatment#167]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.1: Phiếu ghi nhận lỗi phát sinh DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN LỖI PHÁT SINH</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Châu Thanh Trà **
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **20/11/2023**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `92001`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **BV Tim Mạch CT**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `tra_timmach_ct_hentaikham`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`](https://gofile.me/78TQg/7WCI0Akxvhttps://gofile.me/78TQg/7WCI0Akxv)

###### ![chi_tiet_loi](https://img.shields.io/badge/Chi%20tiết%20lỗi%20phát%20sinh-:-blue?style=for-the-badge&logo=github)

-  ![loi_benh_nhan](https://img.shields.io/badge/Chi%20tiết%20bệnh%20nhân-:-blue?style=plastic&logo=github)
   > _**MaBN**_: `19038333` - _**MaKB**_: `2311009140` - _**MaBA**_: `23004652` _**NgayKCB**_: `20/11/2023` - _**MaPhong**_: `MaPhong` - _**MaDV**_: `18` - _**ThangKT**_: `11` - _**NamKT**_: `2023`
-  ![loi_thuoc](https://img.shields.io/badge/Chi%20tiết%20thuốc-:-blue?style=plastic&logo=github)
   > _**KhoChan**_: `KhoChan` - _**KhoLe**_: `KhoLe` - _**MaHH**_: `MaHH` - _**SoHD**_: `SoHD` - _**NgayHD**_: `NgayHD` - _**ThangKT**_: `ThangKT` - _**NamKT**_: `NamKT`
-  ![loi_cls](https://img.shields.io/badge/Chi%20tiết%20CLS-:-blue?style=plastic&logo=github)
   > _**MaCLS**_: `MaCLS` - _**PhieuYC**_: `PhieuYC`
-  ![loi_bo_sung](https://img.shields.io/badge/Chi%20tiết%20bổ%20sung-:-blue?style=plastic&logo=github)
   > _**Khac**_: `Khac`

###### ![mo_ta_loi](https://img.shields.io/badge/Mô%20tả%20thông%20tin%20lỗi-:-blue?style=for-the-badge&logo=github)

- Mẫu giấy hẹn tái khám A5 in ngang có tách chẩn đoán chính và chẩn đoán phụ ghi đè chữ lên thông tin khác khi chẩn đoán phụ dài. 
- Tiêu đề người đại diện cơ sở khám bệnh chữa bệnh in thiếu chữ

![ảnh](https://github.com/dh-hos/dhg.hosptaltreatment/assets/97272332/a81b82ea-cbce-42d6-916a-b4bff2921de6)

**Comment by vuongdh** [comment]
Cập nhật <b>Treat4.2023.11.21v1 </b>- vào chi tiết để tải bản cập nhật

<div align="left">

[![View](https://img.shields.io/badge/-Xem%20chi%20ti%E1%BA%BFt%20c%E1%BA%ADp%20nh%E1%BA%ADt-informational?logo=github)](https://github.com/dh-hos/dhg.hosptaltreatment/blob/main/README.md)

</div>
