### ISSUE TITLE
Lỗi - Chức năng chỉnh chi phí BH 1 không cập nhật cột giá bảo hiểm theo danh mục chidinhcls.giabhdm

### ISSUE THREAD

**Issue by chauthanhtra** [dh-hos/dhg.hosptaltreatment#168]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.1: Phiếu ghi nhận lỗi phát sinh DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN LỖI PHÁT SINH</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Châu Thanh Trà **
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **21/11/2023**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `92001`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **BV Tim Mạch CT**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `tra_timmach_ct_112023_chinhgiacls`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`](https://gofile.me/78TQg/b7Y909McN)

###### ![chi_tiet_loi](https://img.shields.io/badge/Chi%20tiết%20lỗi%20phát%20sinh-:-blue?style=for-the-badge&logo=github)

-  ![loi_benh_nhan](https://img.shields.io/badge/Chi%20tiết%20bệnh%20nhân-:-blue?style=plastic&logo=github)
   > _**MaBN**_: `23023355` - _**MaKB**_: `MaKB` - _**MaBA**_: `23004841` _**NgayKCB**_: `22/11/2023` - _**MaPhong**_: `MaPhong` - _**MaDV**_: `17` - _**ThangKT**_: `11` - _**NamKT**_: `2023`
-  ![loi_thuoc](https://img.shields.io/badge/Chi%20tiết%20thuốc-:-blue?style=plastic&logo=github)
   > _**KhoChan**_: `KhoChan` - _**KhoLe**_: `KhoLe` - _**MaHH**_: `MaHH` - _**SoHD**_: `SoHD` - _**NgayHD**_: `NgayHD` - _**ThangKT**_: `ThangKT` - _**NamKT**_: `NamKT`
-  ![loi_cls](https://img.shields.io/badge/Chi%20tiết%20CLS-:-blue?style=plastic&logo=github)
   > _**MaCLS**_: `DI03` - _**PhieuYC**_: `PhieuYC`
-  ![loi_bo_sung](https://img.shields.io/badge/Chi%20tiết%20bổ%20sung-:-blue?style=plastic&logo=github)
   > _**Khac**_: `Khac`

###### ![mo_ta_loi](https://img.shields.io/badge/Mô%20tả%20thông%20tin%20lỗi-:-blue?style=for-the-badge&logo=github)

Bệnh nhân nhập viện sau ngày 17/11/2023 đã chỉ định CLS giá cũ  
Sau đó BV cập nhật giá mới cho danh mục CLS theo thông tư 22/2023 ngày áp dụng là ngày 17/11/2023
Khi vào chức năng chuyển chi phí bệnh nhân để cập nhập nhật lại giá mới cho các CLS đã chỉ định thì phần mềm không cập nhật được cột giá chidinhcls.giabhdm (các cột giá khác cập nhật đầy đủ)
-> Cho cập nhật lại giá mới cột giá chidinhcls.giabhdm

Ví dụ: Bệnh nhân chỉ định CLS DI03 giá 32 800đ -> khi BV cập nhật giá mới cho danh mục CLS vào chức năng Chuyển chi phí bệnh nhân  -> Chỉnh chi phí BH1 -> đồng ý cập nhật thì giá CLS được chuyển sang giá mới là 35 400đ ở đơn giá và thành tiền đúng nhưng giá bảo hiển danh mục thì vẫn giữ giá cũ là 32 800đ

- Trước khi chuyển chi phí

![ảnh](https://github.com/dh-hos/dhg.hosptaltreatment/assets/97272332/a2fa5fc8-a9c1-48d9-821a-f904ed537cd0)

![ảnh](https://github.com/dh-hos/dhg.hosptaltreatment/assets/97272332/f61f7e51-1e8e-4218-87ad-dd36699ff095)

![ảnh](https://github.com/dh-hos/dhg.hosptaltreatment/assets/97272332/14df5f49-56fe-4570-bfe6-44e43f5b82f8)

![ảnh](https://github.com/dh-hos/dhg.hosptaltreatment/assets/97272332/a40f485c-9aef-442f-ab57-de80e65390b4)

![ảnh](https://github.com/dh-hos/dhg.hosptaltreatment/assets/97272332/a86ee8fb-22e3-4408-8557-1a1c8ae231df)

- Sau khi chuyển chi phí

![ảnh](https://github.com/dh-hos/dhg.hosptaltreatment/assets/97272332/31348105-ae63-4575-8ef2-546cafefdb9e)

![ảnh](https://github.com/dh-hos/dhg.hosptaltreatment/assets/97272332/89b3334d-7553-41fc-8911-294c32991139)

![ảnh](https://github.com/dh-hos/dhg.hosptaltreatment/assets/97272332/625a4874-63c7-4c3f-bc9a-503b9d08566e)

**Comment by vuongdh** [comment]
Chức năng chuyển chi phí bệnh nhân, không liên quan đến cột giabhdm. Cột này chỉ ghi nhận giabh trên dmcls tại thời điểm chỉ định

**Comment by chauthanhtra** [comment]
Alo anh @vuongdh 
Thêm chổ này nữa nha anh

Sau khi chuyển chi phí bệnh nhân CLS cập nhật giá CLS mới (chidinhcls.giabhdm vẫn giữ giá cũ) khi nào chức năng tổng kết tổng hơp thì phần mềm cập nhật lại giá cũ cho CLS theo giá bảo hiểm danh mục và tỉ lệ thanh toán của CLS (giabhdm*tile/100) đối với các CLS bảo hiểm thanh toán chưa thu tiền. Bệnh nhân chưa xuất viện và "đã xuất viện" đều bị cập nhật -> dẫn đến lệch bảng kê, XML đã gửi, các báo cáo có giá CLS do CLS quay về giá củ

![ảnh](https://github.com/dh-hos/dhg.hosptaltreatment/assets/97272332/dcd967ca-825c-4dca-8298-872c38a30d70)
![ảnh](https://github.com/dh-hos/dhg.hosptaltreatment/assets/97272332/57001bf2-35af-452d-9c0d-4a8aee660e15)
![ảnh](https://github.com/dh-hos/dhg.hosptaltreatment/assets/97272332/22e87e8e-f51d-42de-9295-776c3462e62f)

**Comment by vuongdh** [comment]
Script anh gửi em hôm qua, hỗ trợ cho từng bệnh nhân. Do giá dm lấy lúc chỉnh định CLS, chỉnh chi phí chỉ hỗ trợ cập nhật đơn giá theo đúng với đối tượng.
Nguyên nhân: đơn chỉ giá danh mục lại sau khi đã chỉ định CLS

**Comment by chauthanhtra** [comment]
Chỉnh giá CLS khi giá CLS thay đổi là bình thường mà anh

Em thấy có lỗi này nên báo cho anh biết để chặn lại ở các bản phần mềm sau. để các BV khác không biết rồi bị sai nhiều

**Comment by chauthanhtra** [comment]
Script anh gửi em có cập nhật mấy bệnh nhân còn nằm viện cho BV rồi còn các bệnh nhân đã xuất viện rồi thì vẫn để đó. 
BV thắc mắc là sau giá lúc mới lúc củ. bệnh nhân đã xuất viện in ra rồi mà giờ đổi giá.

Theo em giá CLS cập nhật mới là bình thường nếu phần mềm hỗ trợ cập nhật lại giá thì anh hỗ trợ thêm chức năng cập nhật thêm giá BH danh mục cho đúng luôn đi anh hoặc chức năng cập nhật giá CLS theo giá mới . Như thông tư 22 mới nhiều BV sẽ cần cập nhật lại giá mới cho các bệnh nhân

**Comment by vuongdh** [comment]
Khi kiểm tra tham số:
![image](https://github.com/dh-hos/dhg.hosptaltreatment/assets/32563776/abea19d1-4fba-4f71-984e-7d69fa079784)
Sau khi chỉnh tham số này: Khi chỉ định CLS, chỉnh lùi chi phí, ...
- Các bệnh nhân nhập viện trước ngày 17/11/2023: sẽ lấy giá tháng 3
- Các bệnh nhân nhập viện từ ngày 17/11/2023: sẽ lấy giá tháng 7

**Comment by chauthanhtra** [comment]
Dạ. Đúng rồi anh. 
Nên anh Tuấn mới có hướng dẫn để BV chuyển giá hiện tại qua giá tháng 3, giá TT22 áp vào giá tháng 7 để BV sử dụng tham số này
Mình chỉ bị vướng các CLS đã chỉ định rồi cần cập nhật giá mới

**Comment by vuongdh** [comment]
Mình chỉ bị vướng các CLS đã chỉ định rồi cần cập nhật giá mới <= cụ thể hỗ trợ thế nào thì viết script hỗ hén.

P/s: script hôm qua anh gửi em cũng hỗ trợ được rồi đó. (bỏ điều kiện mabn, maba) là chạy cho tất cả bn nhập viện từ ngày 17/11/2023

**Comment by chauthanhtra** [comment]
Cái script đó chỉ sử dụng được khi bệnh nhân đã chuyển chi phí qua giá mới vào chuyển chi phí từng bệnh nhân rồi mới chay nên dễ bị thiếu sót do bệnh nhân ở nhiều khoa và thao tác của bác sĩ như vào tổng kết tổng hợp ở trên. phải kiểm tra từng bệnh nhân do không biết bệnh nhân có cập nhật giá mới chưa,. rồi bệnh nhân đã xuất viện hay đã thu tiền nữa

Anh có thể chỉnh giúp em cái  script lại cho lấy giá mới từ danh mục CLS luôn được không, tính tiền theo tỉ lệ thanh toán luôn? áp dụng cho các bệnh nhân nội trú chưa xuất viện, chưa thu tiền, nhập viện từ ngày tham số áp dụng giá tháng 7
Hoặc chỉnh chức năng Chuyển chi phí bệnh nhân cho nó cập nhật giabhdm theo giá mới luôn để BV tự chỉnh

**Comment by chauthanhtra** [comment]
> Alo anh @vuongdh Thêm chổ này nữa nha anh
> 
> Sau khi chuyển chi phí bệnh nhân CLS cập nhật giá CLS mới (chidinhcls.giabhdm vẫn giữ giá cũ) khi nào chức năng tổng kết tổng hơp thì phần mềm cập nhật lại giá cũ cho CLS theo giá bảo hiểm danh mục và tỉ lệ thanh toán của CLS (giabhdm*tile/100) đối với các CLS bảo hiểm thanh toán chưa thu tiền. Bệnh nhân chưa xuất viện và "đã xuất viện" đều bị cập nhật -> dẫn đến lệch bảng kê, XML đã gửi, các báo cáo có giá CLS do CLS quay về giá củ
> 
>     * Do có 1 số bệnh nhân cập nhật giá đã cho xuất viện rồi
> 
> 
> ![ảnh](https://user-images.githubusercontent.com/97272332/285079370-dcd967ca-825c-4dca-8298-872c38a30d70.png) ![ảnh](https://user-images.githubusercontent.com/97272332/285079390-57001bf2-35af-452d-9c0d-4a8aee660e15.png) ![ảnh](https://user-images.githubusercontent.com/97272332/285079397-22e87e8e-f51d-42de-9295-776c3462e62f.png)

Với chổ này mình nên chỉnh lại cho đúng. Chuyển chi phí thì chỉnh qua giá mới . rồi vào tổng kết tổng hợp thì chạy về giá cũ theo giá giá bảo hiểm danh mục
-> Theo em thì nếu chuyển chi phí cho cập nhật nhật giá mới thì phải cập nhật thêm giá BH danh mục thì chức năng Tổng kết tổng hợp không chỉnh lại giá cũ.

**Comment by chauthanhtra** [comment]
Git này anh có chỉnh gì không anh @vuongdh ?
nếu không chỉnh gì trên phần mềm thì em close nó nha
