### ISSUE TITLE
Lỗi - Gửi giấy chứng sinh theo đề án 06 (BV Sadec)

### ISSUE THREAD

**Issue by le-an-87** [dh-hos/dhg.hosptaltreatment#169]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.1: Phiếu ghi nhận lỗi phát sinh DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN LỖI PHÁT SINH</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Ân**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **28/11/2023**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `Tất cả`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **Tất cả**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `an_sadec_gcs_27112023`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`](https://gofile.me/78TQg/aUxrtdChO)

###### ![chi_tiet_loi](https://img.shields.io/badge/Chi%20tiết%20lỗi%20phát%20sinh-:-blue?style=for-the-badge&logo=github)

-  ![loi_benh_nhan](https://img.shields.io/badge/Chi%20tiết%20bệnh%20nhân-:-blue?style=plastic&logo=github)
   > _**MaBN**_: `2023066103` - _**MaKB**_: `2311022723` - _**MaBA**_: `2023044190` _**NgayKCB**_: `23/11/2023` - _**MaPhong**_: `SAN_B` - _**MaDV**_: `SAN` - _**ThangKT**_: `11` - _**NamKT**_: `2023`

###### ![mo_ta_loi](https://img.shields.io/badge/Mô%20tả%20thông%20tin%20lỗi-:-blue?style=for-the-badge&logo=github)

```
Giấy chứng sinh theo đề án 06 sử dụng tham số nt.diachi_gsc = 1
1. Khi chọn tỉnh, huyện, xã phần mềm lấy mã tỉnh chứ không lấy mã liên thông để gửi cổng BH
2. không có chức năng để chỉnh sửa những giấy chứng sinh đã gửi cổng sai muốn sửa và gửi lại.
```
![image](https://github.com/dh-hos/dhg.hosptaltreatment/assets/96155021/99dcf912-728c-4ed3-aa1c-51883abebdcd)

**Comment by lequocthong29** [comment]
Update dll [DH.ThongTinKSK.dll](https://github.com/dh-hos/oLibraries/blob/main/DH.ThongTinKSK.dll)

- Fix lỗi Khi chọn tỉnh, huyện, xã phần mềm lấy mã tỉnh chứ không lấy mã liên thông để gửi cổng BH.
- Cập nhật lại cột ttcon.dagui = 0 khi chọn gửi lại để có thể chỉnh sửa GCS

**Comment by lequocthong29** [comment]
*2. không có chức năng để chỉnh sửa những giấy chứng sinh đã gửi cổng sai muốn sửa và gửi lại. 
@le-an-87  này trên danh sách đã gửi mình chọn ca đó rồi chọn gửi lại, là nó chuyển ca đó về danh sách chưa gửi, chỉnh sửa được á a.

**Comment by vuongdh** [comment]
Cập nhật <b>Treat4.2023.11.28v1 </b>- vào chi tiết để tải bản cập nhật

<div align="left">

[![View](https://img.shields.io/badge/-Xem%20chi%20ti%E1%BA%BFt%20c%E1%BA%ADp%20nh%E1%BA%ADt-informational?logo=github)](https://github.com/dh-hos/dhg.hosptaltreatment/blob/main/README.md)

</div>

**Comment by lequocthong29** [comment]
Cập nhật DLL [DH.ThongTinKSK.dll](https://github.com/dh-hos/oLibraries/blob/main/DH.ThongTinKSK.dll)
- Fix lỗi load danh sách tỉnh huyện xã bị sai.

**Comment by vuongdh** [comment]
Cập nhật <b>Treat4.2023.11.29v1 </b>- vào chi tiết để tải bản cập nhật

<div align="left">

[![View](https://img.shields.io/badge/-Xem%20chi%20ti%E1%BA%BFt%20c%E1%BA%ADp%20nh%E1%BA%ADt-informational?logo=github)](https://github.com/dh-hos/dhg.hosptaltreatment/blob/main/README.md)

</div>

**Comment by vuongdh** [comment]
Cập nhật <b>Treat4.2023.11.29v2 </b>- vào chi tiết để tải bản cập nhật

<div align="left">

[![View](https://img.shields.io/badge/-Xem%20chi%20ti%E1%BA%BFt%20c%E1%BA%ADp%20nh%E1%BA%ADt-informational?logo=github)](https://github.com/dh-hos/dhg.hosptaltreatment/blob/main/README.md)

</div>

**Comment by le-an-87** [comment]
Đã hỗ trợ!
