### ISSUE TITLE
Lỗi - Toa xuất viện chẩn đoán bị lập lại

### ISSUE THREAD

**Issue by minhduc2it** [dh-hos/dhg.hosptaltreatment#170]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.1: Phiếu ghi nhận lỗi phát sinh DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN LỖI PHÁT SINH</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Đức*
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **29/11/2023**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `92007`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **BV Ô Môn**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `duc_omon_cdoan`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`] https://gofile.me/78TQg/gOn59nRlF

###### ![chi_tiet_loi](https://img.shields.io/badge/Chi%20tiết%20lỗi%20phát%20sinh-:-blue?style=for-the-badge&logo=github)

-  ![loi_benh_nhan](https://img.shields.io/badge/Chi%20tiết%20bệnh%20nhân-:-blue?style=plastic&logo=github)
   > _**MaBN**_: `2021008155` - _**MaKB**_: `2311023511` - _**MaBA**_: `2023015548` _**NgayKCB**_: `29/11/2023` - _**MaPhong**_: `P1` - _**MaDV**_: `07` - _**ThangKT**_: `11` - _**NamKT**_: `2023`

###### ![mo_ta_loi](https://img.shields.io/badge/Mô%20tả%20thông%20tin%20lỗi-:-blue?style=for-the-badge&logo=github)

```
Toa xuất viện ngày 29/11/2023 (chứng từ: KN.X23.1129.101810) lập lại chẩn đoán
Bảng chungtu.kqcdoan lấy cả chẩn đoán chính + phụ nên khi in toa bị lập lại chẩn đoán

```
![image](https://github.com/dh-hos/dhg.hosptaltreatment/assets/98437757/58ca44a8-00f5-4925-974e-028bd0aea0b0)

![image](https://github.com/dh-hos/dhg.hosptaltreatment/assets/98437757/e625f66b-3704-4d5c-847d-1328ecebd085)

**Comment by vuongdh** [comment]
@nghivanbi xem lại chổ này dùm
Dữ liệu truyền vô bên dưới và dữ liệu hiển thị trên toa
![image](https://github.com/dh-hos/dhg.hosptaltreatment/assets/32563776/9c231746-46e7-40fd-9cf0-18cfaacb2898)

**Comment by vuongdh** [comment]
HospitalToaThuoc.XtraReports.ClsInToaThuoc.Chandoan = this.txtTenICD.Text.Trim();

**Comment by nghivanbi** [comment]
Get lại cái @vuongdh 
![image](https://github.com/dh-hos/dhg.hosptaltreatment/assets/91751241/21ab5a94-bf0d-463b-90f3-84f2f9144691)

**Comment by vuongdh** [comment]
Cập nhật <b>Treat4.2023.11.29v2 </b>- vào chi tiết để tải bản cập nhật

<div align="left">

[![View](https://img.shields.io/badge/-Xem%20chi%20ti%E1%BA%BFt%20c%E1%BA%ADp%20nh%E1%BA%ADt-informational?logo=github)](https://github.com/dh-hos/dhg.hosptaltreatment/blob/main/README.md)

</div>

**Comment by minhduc2it** [comment]
đã kiểm tra ok
