### ISSUE TITLE
Lỗi - Nút in Chỉ định CLS chuyển tuyến trên không tác dụng và Cập nhật nội dung Lý do chuyển theo NĐ75

### ISSUE THREAD

**Issue by minhduc2it** [dh-hos/dhg.hosptaltreatment#171]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.1: Phiếu ghi nhận lỗi phát sinh DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN LỖI PHÁT SINH</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Đức**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **04/12/2023**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `92086`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **BV Ung Bướu**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `duc_ungbuou_giaycvcls`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`] https://gofile.me/78TQg/SCJvkCIOp

###### ![chi_tiet_loi](https://img.shields.io/badge/Chi%20tiết%20lỗi%20phát%20sinh-:-blue?style=for-the-badge&logo=github)

-  ![loi_benh_nhan](https://img.shields.io/badge/Chi%20tiết%20bệnh%20nhân-:-blue?style=plastic&logo=github)
   > _**MaBN**_: `2023043964` - _**MaKB**_: `2311000859` - _**MaBA**_: `020013` _**NgayKCB**_: `02/11/2023` - _**MaPhong**_: `CSGN` - _**MaDV**_: `22` - _**ThangKT**_: `  ` - _**NamKT**_: `2023`

###### ![mo_ta_loi](https://img.shields.io/badge/Mô%20tả%20thông%20tin%20lỗi-:-blue?style=for-the-badge&logo=github)

```
Chỉ định CLS  > Bv Tuyến trên khi bấm IN giấy chuyển không tác dụng (bấm in im ru)

```
![image](https://github.com/dh-hos/dhg.hosptaltreatment/assets/98437757/6a954a21-009e-4a9d-ac33-6768c62d5cfd)

![image](https://github.com/dh-hos/dhg.hosptaltreatment/assets/98437757/e8eed6eb-71e1-4e03-8579-de3436848d0b)

**Cập nhật nội dung Lý do chuyển theo NĐ75**
![image](https://github.com/dh-hos/dhg.hosptaltreatment/assets/98437757/50651226-8513-4745-b8e6-706260afdf92)

**Comment by vuongdh** [comment]
Cập nhật <b>Treat4.2023.12.04v2 </b>- vào chi tiết để tải bản cập nhật

<div align="left">

[![View](https://img.shields.io/badge/-Xem%20chi%20ti%E1%BA%BFt%20c%E1%BA%ADp%20nh%E1%BA%ADt-informational?logo=github)](https://github.com/dh-hos/dhg.hosptaltreatment/blob/main/README.md)

</div>

**Comment by vuongdh** [comment]
Cập nhật <b>Treat4.2023.12.05v1 </b>- vào chi tiết để tải bản cập nhật

<div align="left">

[![View](https://img.shields.io/badge/-Xem%20chi%20ti%E1%BA%BFt%20c%E1%BA%ADp%20nh%E1%BA%ADt-informational?logo=github)](https://github.com/dh-hos/dhg.hosptaltreatment/blob/main/README.md)

</div>

**Comment by minhduc2it** [comment]
anh bổ sung chỗ này nữa
![image](https://github.com/dh-hos/dhg.hosptaltreatment/assets/98437757/8444df35-3e76-40f2-99ce-020bfb57b8b6)

![image](https://github.com/dh-hos/dhg.hosptaltreatment/assets/98437757/77081b32-6f79-413a-b980-f8c54672ad2f)

![image](https://github.com/dh-hos/dhg.hosptaltreatment/assets/98437757/0b39f154-38c9-4c74-b1a8-984ce5974b3c)

**Comment by vuongdh** [comment]
Cập nhật <b>Treat4.2023.12.05v2 </b>- vào chi tiết để tải bản cập nhật

<div align="left">

[![View](https://img.shields.io/badge/-Xem%20chi%20ti%E1%BA%BFt%20c%E1%BA%ADp%20nh%E1%BA%ADt-informational?logo=github)](https://github.com/dh-hos/dhg.hosptaltreatment/blob/main/README.md)

</div>
 lấy bản mới nhất và tham số sử dụng đúng thông tư

**Comment by minhduc2it** [comment]
Đang sử dụng bản Treat4.20231205v2
Tham số nt.giayhena5= 4 chưa lấy đúng nội dung giấy chuyển theo NĐ 75
Mục số 2 Lý do điều kiện chuyển tuyến: Không đủ điều kiện chuyển tuyến (vượt tuyến) **chỉnh thành** _Theo yêu cầu của người bệnh hoặc người đại diện hợp pháp của người bệnh._
Nếu chọn Mục số 2 thì dòng Đủ điều kiện ẩn đi không cho chọn (tránh người dùng chọn nhầm thêm điều kiện a và b sẽ bị sai)

Bệnh viện yêu cầu chỉnh 2 chỗ đó nữa đó anh

![image](https://github.com/dh-hos/dhg.hosptaltreatment/assets/98437757/f4c01589-196e-4823-bb49-8b5ff1c19543)

![image](https://github.com/dh-hos/dhg.hosptaltreatment/assets/98437757/448fe4bc-0d41-42da-9078-230433ca83ce)

![image](https://github.com/dh-hos/dhg.hosptaltreatment/assets/98437757/09ad8a8e-5c7e-4a8c-9acf-18a660bff44d)

**Comment by vuongdh** [comment]
tham số cv.thongtu14 = 3 (dành cho phiếu chuyện viện) 
tham số nt.giayhena5 = 4 (dành cho phiếu hẹn tái khám)

**Comment by vuongdh** [comment]
Tham số nt.giayhena5= 4 
DÙNG CHO PHIẾU HẸN TÁI KHÁM

**Comment by vuongdh** [comment]
Nội dung thể theo thông tư 75. Không có thiết kế riêng nha em

**Comment by vuongdh** [comment]
Cập nhật <b>Treat4.2023.12.05v4 </b>- vào chi tiết để tải bản cập nhật

<div align="left">

[![View](https://img.shields.io/badge/-Xem%20chi%20ti%E1%BA%BFt%20c%E1%BA%ADp%20nh%E1%BA%ADt-informational?logo=github)](https://github.com/dh-hos/dhg.hosptaltreatment/blob/main/README.md)

</div>

**Comment by vuongdh** [comment]
Em thử lại bản này

**Comment by minhduc2it** [comment]
Chưa được anh

**Comment by minhduc2it** [comment]
Còn chỗ này nữa là ok rồi đó anh

![image](https://github.com/dh-hos/dhg.hosptaltreatment/assets/98437757/008079be-44ff-4e26-9648-2b2503e7f2a1)

**Comment by vuongdh** [comment]
cho chọn thoái mái luôn em, nhưng khi lưu thì sẽ lưu đúng điều kiện
