### ISSUE TITLE
Lỗi - Thành tiền tính sai đối với CLS DV

### ISSUE THREAD

**Issue by lqbinh1987** [dh-hos/dhg.hosptaltreatment#172]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.1: Phiếu ghi nhận lỗi phát sinh DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN LỖI PHÁT SINH</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Bình**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **04/12/2023**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `94029`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **BV Sản Nhi ST**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `binh_sannhist_sai_6556`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`](link_csdl)

###### ![chi_tiet_loi](https://img.shields.io/badge/Chi%20tiết%20lỗi%20phát%20sinh-:-blue?style=for-the-badge&logo=github)

-  ![loi_benh_nhan](https://img.shields.io/badge/Chi%20tiết%20bệnh%20nhân-:-blue?style=plastic&logo=github)
   > _**MaBN**_: `2023062866` - _**MaKB**_: `MaKB` - _**MaBA**_: `2023021307` _**NgayKCB**_: `04/12/2023` - _**MaPhong**_: `MaPhong` - _**MaDV**_: `KD016` - _**ThangKT**_: `10` - _**NamKT**_: `2023`
-  ![loi_thuoc](https://img.shields.io/badge/Chi%20tiết%20thuốc-:-blue?style=plastic&logo=github)
   > _**KhoChan**_: `KhoChan` - _**KhoLe**_: `KhoLe` - _**MaHH**_: `MaHH` - _**SoHD**_: `SoHD` - _**NgayHD**_: `NgayHD` - _**ThangKT**_: `ThangKT` - _**NamKT**_: `NamKT`
-  ![loi_cls](https://img.shields.io/badge/Chi%20tiết%20CLS-:-blue?style=plastic&logo=github)
   > _**MaCLS**_: `MaCLS` - _**PhieuYC**_: `PhieuYC`
-  ![loi_bo_sung](https://img.shields.io/badge/Chi%20tiết%20bổ%20sung-:-blue?style=plastic&logo=github)
   > _**Khac**_: `Khac`

###### ![mo_ta_loi](https://img.shields.io/badge/Mô%20tả%20thông%20tin%20lỗi-:-blue?style=for-the-badge&logo=github)

Khi chỉ định những CLS mà **check DV**, thì cột **Thành tiền** tính sai, đúng là phải **Thành tiền = Giá DV * SL** , hiện tại nó đang lấy Thành tiền = Giá BH * SL
![image](https://github.com/dh-hos/dhg.hosptaltreatment/assets/99630883/065e395b-e81b-44e0-b48a-6abe875b14ce)

**Comment by vuongdh** [comment]
Cập nhật <b>Treat4.2023.12.04v2 </b>- vào chi tiết để tải bản cập nhật

<div align="left">

[![View](https://img.shields.io/badge/-Xem%20chi%20ti%E1%BA%BFt%20c%E1%BA%ADp%20nh%E1%BA%ADt-informational?logo=github)](https://github.com/dh-hos/dhg.hosptaltreatment/blob/main/README.md)

</div>

**Comment by vuongdh** [comment]
Thử lại với bản này

**Comment by lqbinh1987** [comment]
Anh @vuongdh, Nó lấy đúng rồi, **nhưng khi bỏ check DV ra lại thì thành tiền nó ko thay đổi,** đúng ra bỏ check DV nó phải cập nhật lại thành tiền theo Thành tiền = Giá BHYT * SL.

**Comment by lqbinh1987** [comment]
Coi dùm em này nhe anh @vuongdh.

> Anh @vuongdh, Nó lấy đúng rồi, **nhưng khi bỏ check DV ra lại thì thành tiền nó ko thay đổi,** đúng ra bỏ check DV nó phải cập nhật lại thành tiền theo Thành tiền = Giá BHYT * SL.

**Comment by vuongdh** [comment]
Cập nhật <b>Treat4.2023.12.05v1 </b>- vào chi tiết để tải bản cập nhật

<div align="left">

[![View](https://img.shields.io/badge/-Xem%20chi%20ti%E1%BA%BFt%20c%E1%BA%ADp%20nh%E1%BA%ADt-informational?logo=github)](https://github.com/dh-hos/dhg.hosptaltreatment/blob/main/README.md)

</div>
