### ISSUE TITLE
Lỗi - Tổng kết chi phí và bảng kê 6556 sai số tiền BV ( khi vật tư y tế có trần thanh toán)

### ISSUE THREAD

**Issue by chauthanhtra** [dh-hos/dhg.hosptaltreatment#173]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.1: Phiếu ghi nhận lỗi phát sinh DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN LỖI PHÁT SINH</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Châu Thanh Trà **
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **04/12/2023**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `83600`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **BV Cù Lao Minh**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `tra_clm_treatment_bangke6556_thanhtienbv`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`](https://gofile.me/78TQg/SquHy5Ww4)

###### ![chi_tiet_loi](https://img.shields.io/badge/Chi%20tiết%20lỗi%20phát%20sinh-:-blue?style=for-the-badge&logo=github)

-  ![loi_benh_nhan](https://img.shields.io/badge/Chi%20tiết%20bệnh%20nhân-:-blue?style=plastic&logo=github)
   > _**MaBN**_: `2022023113` - _**MaKB**_: `2312000210` - _**MaBA**_: `2023021679` _**NgayKCB**_: `NgayKCB` - _**MaPhong**_: `MaPhong` - _**MaDV**_: `28` - _**ThangKT**_: `12` - _**NamKT**_: `2023`
-  ![loi_thuoc](https://img.shields.io/badge/Chi%20tiết%20thuốc-:-blue?style=plastic&logo=github)
   > _**KhoChan**_: `KhoChan` - _**KhoLe**_: `KhoLe` - _**MaHH**_: `VT22-05` - _**SoHD**_: `SoHD` - _**NgayHD**_: `NgayHD` - _**ThangKT**_: `ThangKT` - _**NamKT**_: `NamKT`
-  ![loi_cls](https://img.shields.io/badge/Chi%20tiết%20CLS-:-blue?style=plastic&logo=github)
   > _**MaCLS**_: `MaCLS` - _**PhieuYC**_: `PhieuYC`
-  ![loi_bo_sung](https://img.shields.io/badge/Chi%20tiết%20bổ%20sung-:-blue?style=plastic&logo=github)
   > _**Khac**_: `Khac`

###### ![mo_ta_loi](https://img.shields.io/badge/Mô%20tả%20thông%20tin%20lỗi-:-blue?style=for-the-badge&logo=github)

Tổng kết chi phí sai tổng số tiền và bảng kê 6556 sai Tổng tiền BV, thành tiền BV
Bệnh nhân có vật tư VT22-05 có trần thanh toán 3 000 000

![ảnh](https://github.com/dh-hos/dhg.hosptaltreatment/assets/97272332/5c60b490-deb1-411b-a700-56bada59a835)

![ảnh](https://github.com/dh-hos/dhg.hosptaltreatment/assets/97272332/0e7f725b-9b38-48d1-b3b5-27200613255d)

**Comment by chauthanhtra** [comment]
Hình full bảng kê BH
![ảnh](https://github.com/dh-hos/dhg.hosptaltreatment/assets/97272332/d5b21153-ec75-4005-9e45-93d2297de537)
![ảnh](https://github.com/dh-hos/dhg.hosptaltreatment/assets/97272332/ff065900-063c-4f09-8729-c7e6797d1836)

Hình full bảng kê DV
![ảnh](https://github.com/dh-hos/dhg.hosptaltreatment/assets/97272332/a64fc4b9-3de6-4026-bcda-4884517f2879)
![ảnh](https://github.com/dh-hos/dhg.hosptaltreatment/assets/97272332/4b486456-7d2d-42a2-bea5-dd0b68520fd3)

**Comment by vuongdh** [comment]
Cập nhật <b>Treat4.2023.12.05v2 </b>- vào chi tiết để tải bản cập nhật

<div align="left">

[![View](https://img.shields.io/badge/-Xem%20chi%20ti%E1%BA%BFt%20c%E1%BA%ADp%20nh%E1%BA%ADt-informational?logo=github)](https://github.com/dh-hos/dhg.hosptaltreatment/blob/main/README.md)

</div>

**Comment by chauthanhtra** [comment]
Alo anh @vuongdh 
Cột Thành tiền BV vẫn chưa lấy giá gốc của vật tư vẫn còn lấy giá BHYT

![ảnh](https://github.com/dh-hos/dhg.hosptaltreatment/assets/97272332/11cc59be-4007-4af3-aa5e-6a46a5ed908a)

**Comment by vuongdh** [comment]
cái này để anh rà lại kỹ mới được. Ảnh hưởng nhiều đơn vị

**Comment by chauthanhtra** [comment]
Em thấy có tham số cho cột thành tiền này luôn mà chỉnh lấy giá gốc vẫn không được
nt.6556thanhtienbv

![ảnh](https://github.com/dh-hos/dhg.hosptaltreatment/assets/97272332/86ac8a19-63c5-48bf-9127-faab83f02a19)

**Comment by chauthanhtra** [comment]
Alo anh @vuongdh 
Làm sớm giúp em chổ này nha anh. BV hối quá

**Comment by vuongdh** [comment]
[Bản cập nhật Treatment.2023.12.07v1](https://gofile.me/78TQg/y5cSjDWXd)

**Comment by chauthanhtra** [comment]
đã fix lỗi
