### ISSUE TITLE
Lỗi - Toa thuốc nhà thuốc không thể hiện tuổi bệnh nhân 

### ISSUE THREAD

**Issue by chauthanhtra** [dh-hos/dhg.hosptaltreatment#176]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.1: Phiếu ghi nhận lỗi phát sinh DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN LỖI PHÁT SINH</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Châu Thanh Trà **
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **5/12/2023**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `92015`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **BV TMH**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `tra_tmh_toathuoc_tuoitreem`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`](https://gofile.me/78TQg/gySvRn2mc)

###### ![chi_tiet_loi](https://img.shields.io/badge/Chi%20tiết%20lỗi%20phát%20sinh-:-blue?style=for-the-badge&logo=github)

-  ![loi_benh_nhan](https://img.shields.io/badge/Chi%20tiết%20bệnh%20nhân-:-blue?style=plastic&logo=github)
   > _**MaBN**_: `2023031456` - _**MaKB**_: `2311004684` - _**MaBA**_: `2023002984` _**NgayKCB**_: `5/12/2023` - _**MaPhong**_: `MaPhong` - _**MaDV**_: `09` - _**ThangKT**_: `12` - _**NamKT**_: `2023`
-  ![loi_thuoc](https://img.shields.io/badge/Chi%20tiết%20thuốc-:-blue?style=plastic&logo=github)
   > _**KhoChan**_: `13` - _**KhoLe**_: `KhoLe` - _**MaHH**_: `MaHH` - _**SoHD**_: `IT.TMN.1205.065456` - _**NgayHD**_: `5/12/2023` - _**ThangKT**_: `12` - _**NamKT**_: `2023`
-  ![loi_cls](https://img.shields.io/badge/Chi%20tiết%20CLS-:-blue?style=plastic&logo=github)
   > _**MaCLS**_: `MaCLS` - _**PhieuYC**_: `PhieuYC`
-  ![loi_bo_sung](https://img.shields.io/badge/Chi%20tiết%20bổ%20sung-:-blue?style=plastic&logo=github)
   > _**Khac**_: `Khac`

###### ![mo_ta_loi](https://img.shields.io/badge/Mô%20tả%20thông%20tin%20lỗi-:-blue?style=for-the-badge&logo=github)

In toa thuốc bệnh nhân trong chức năng ra toa nhà thuốc không thể hiện tuổi bệnh nhân 

![ảnh](https://github.com/dh-hos/dhg.hosptaltreatment/assets/97272332/a2f99e5e-143a-42c0-a1b0-85dfc7ef25a4)
![ảnh](https://github.com/dh-hos/dhg.hosptaltreatment/assets/97272332/33c1bbbb-706e-4049-997f-d5735c304263)

**Comment by vuongdh** [comment]
@nghivanbi Xem lại chổ này dùm --> truyền tham số vậy đúng hông
![image](https://github.com/dh-hos/dhg.hosptaltreatment/assets/32563776/5be2c286-64f6-4cfc-9322-8c86f62a9124)

**Comment by chauthanhtra** [comment]
Xem giúp em cái lỗi này nha anh @nghivanbi
