### ISSUE TITLE
Lỗi - Giấy chuyển tuyến Chỉ định CLS sai tiêu đề

### ISSUE THREAD

**Issue by minhduc2it** [dh-hos/dhg.hosptaltreatment#177]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.1: Phiếu ghi nhận lỗi phát sinh DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN LỖI PHÁT SINH</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Đức**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **11/12/2023**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `92086`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **BV Ung Bướu**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `duc_ungbuou_giaycvcls`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`] https://gofile.me/78TQg/SCJvkCIOp

###### ![chi_tiet_loi](https://img.shields.io/badge/Chi%20tiết%20lỗi%20phát%20sinh-:-blue?style=for-the-badge&logo=github)

-  ![loi_benh_nhan](https://img.shields.io/badge/Chi%20tiết%20bệnh%20nhân-:-blue?style=plastic&logo=github)
   >MaBN: 2023043964 - MaKB: 2311000859 - MaBA: 020013 - NgayKCB: 02/11/2023 - MaPhong: CSGN - MaDV: 22 - ThangKT:    - NamKT: 2023

###### ![mo_ta_loi](https://img.shields.io/badge/Mô%20tả%20thông%20tin%20lỗi-:-blue?style=for-the-badge&logo=github)

```
- Giấy chuyển tuyến Chỉ định CLS sai tiêu đề
   BN đối tượng BHYT: Tiêu đề giấy chuyển lấy theo tham số đối tượng thu phí nt.tieude_cttp= GIẤY CHUYỂN TUYẾN

```
![image](https://github.com/dh-hos/dhg.hosptaltreatment/assets/98437757/7d4a2252-1963-422b-a2c0-d1f8f24bc88c)

![image](https://github.com/dh-hos/dhg.hosptaltreatment/assets/98437757/7c944b7c-f43b-4209-82f3-35783d21a9b7)

![image](https://github.com/dh-hos/dhg.hosptaltreatment/assets/98437757/a780fd63-bb5d-45cf-92b2-ee7125ffaf5e)

- Câu **Cơ sở khám bệnh, chữa bệnh: ................................. Trân trọng giới thiệu** trong NĐ75: Para chưa hiển thị đúng nội dung và không load tên bệnh viện
![image](https://github.com/dh-hos/dhg.hosptaltreatment/assets/98437757/cc9bf0b0-def8-4346-828e-fa8d8530a9d4)

**Comment by vuongdh** [comment]
@minhduc2it mẫu tự thiết kế, em kéo para benhvien vô thêm  hén

**Comment by vuongdh** [comment]
và xem thêm tham số cv.bvortrungtam để điều chỉnh cho phù hợp

**Comment by minhduc2it** [comment]
còn cái tiêu đề Giấy chuyển nha anh

**Comment by vuongdh** [comment]
vậy em chỉnh cứng tiêu đề luôn nha @minhduc2it. Vì thông tư 75 có 1 tiêu đề thôi

**Comment by minhduc2it** [comment]
nếu chỉnh cứng tiêu đề thì đối tượng thu phí chuyển tuyến Tiêu đề không phù hợp với tiêu đề NĐ 75

**Comment by vuongdh** [comment]
Cập nhật <b>Treat4.2023.12.11v2 </b>- vào chi tiết để tải bản cập nhật

<div align="left">

[![View](https://img.shields.io/badge/-Xem%20chi%20ti%E1%BA%BFt%20c%E1%BA%ADp%20nh%E1%BA%ADt-informational?logo=github)](https://github.com/dh-hos/dhg.hosptaltreatment/blob/main/README.md)

</div>

**Comment by minhduc2it** [comment]
đã test ok
