### ISSUE TITLE
Lỗi - Không cho nhập số con còn sống có độ dài > 1

### ISSUE THREAD

**Issue by lqbinh1987** [dh-hos/dhg.hosptaltreatment#179]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.1: Phiếu ghi nhận lỗi phát sinh DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN LỖI PHÁT SINH</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Bình**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **20/12/2023**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `ALL`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **ALL**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `hoa_tmdtiengiang`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`](link_csdl)

###### ![chi_tiet_loi](https://img.shields.io/badge/Chi%20tiết%20lỗi%20phát%20sinh-:-blue?style=for-the-badge&logo=github)

-  ![loi_benh_nhan](https://img.shields.io/badge/Chi%20tiết%20bệnh%20nhân-:-blue?style=plastic&logo=github)
   > _**MaBN**_: `2023005592` - _**MaKB**_: `MaKB` - _**MaBA**_: `2023000203` _**NgayKCB**_: `NgayKCB` - _**MaPhong**_: `MaPhong` - _**MaDV**_: `20` - _**ThangKT**_: `12` - _**NamKT**_: `2023`
-  ![loi_thuoc](https://img.shields.io/badge/Chi%20tiết%20thuốc-:-blue?style=plastic&logo=github)
   > _**KhoChan**_: `KhoChan` - _**KhoLe**_: `KhoLe` - _**MaHH**_: `MaHH` - _**SoHD**_: `SoHD` - _**NgayHD**_: `NgayHD` - _**ThangKT**_: `ThangKT` - _**NamKT**_: `NamKT`
-  ![loi_cls](https://img.shields.io/badge/Chi%20tiết%20CLS-:-blue?style=plastic&logo=github)
   > _**MaCLS**_: `MaCLS` - _**PhieuYC**_: `PhieuYC`
-  ![loi_bo_sung](https://img.shields.io/badge/Chi%20tiết%20bổ%20sung-:-blue?style=plastic&logo=github)
   > _**Khac**_: `Khac`

###### ![mo_ta_loi](https://img.shields.io/badge/Mô%20tả%20thông%20tin%20lỗi-:-blue?style=for-the-badge&logo=github)

Hiện tại khi BN sinh có mà có số lượng con lên tới 10 thì **Số con hiện sống** phần mềm không cho nhập. Do trên form không cho nhập số có độ dài > 1. Chỉ nhập từ 1 đến 9 thì đc, 10 trở lên không được.
![image](https://github.com/dh-hos/dhg.hosptaltreatment/assets/99630883/23a2fddc-8ecc-44fe-8189-784809b2815d)

**Comment by vuongdh** [comment]
Ok, để anh mở lên 99 con

**Comment by vuongdh** [comment]
@lqbinh1987 anh có cập nhật script mở rộng dữ liệu lưu số con, con thứ, số con còn sống lên 2 con số. Em em hỗ trợ cập nhật số lượng cho đúng. Anh gửi bản cập nhật sau

**Comment by lqbinh1987** [comment]
> @lqbinh1987 anh có cập nhật script mở rộng dữ liệu lưu số con, con thứ, số con còn sống lên 2 con số. Em em hỗ trợ cập nhật số lượng cho đúng. Anh gửi bản cập nhật sau

OK ANH

**Comment by vuongdh** [comment]
Cập nhật <b>Treat4.2023.12.20v2 </b>- vào chi tiết để tải bản cập nhật

<div align="left">

[![View](https://img.shields.io/badge/-Xem%20chi%20ti%E1%BA%BFt%20c%E1%BA%ADp%20nh%E1%BA%ADt-informational?logo=github)](https://github.com/dh-hos/dhg.hosptaltreatment/blob/main/README.md)

</div>
