### ISSUE TITLE
Lỗi - Không cập nhật được giá khi chuyển giá.

### ISSUE THREAD

**Issue by lqbinh1987** [dh-hos/dhg.hosptaltreatment#180]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.1: Phiếu ghi nhận lỗi phát sinh DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN LỖI PHÁT SINH</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Bình**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **21/12/2023**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `92916`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **ALL**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `tuan_dbphusan_dutru`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`](link_csdl)

###### ![chi_tiet_loi](https://img.shields.io/badge/Chi%20tiết%20lỗi%20phát%20sinh-:-blue?style=for-the-badge&logo=github)

-  ![loi_benh_nhan](https://img.shields.io/badge/Chi%20tiết%20bệnh%20nhân-:-blue?style=plastic&logo=github)
   > _**MaBN**_: `2023110260` - _**MaKB**_: `MaKB` - _**MaBA**_: `022289` _**NgayKCB**_: `NgayKCB` - _**MaPhong**_: `MaPhong` - _**MaDV**_: `22` - _**ThangKT**_: `12` - _**NamKT**_: `2023`
-  ![loi_thuoc](https://img.shields.io/badge/Chi%20tiết%20thuốc-:-blue?style=plastic&logo=github)
   > _**KhoChan**_: `KhoChan` - _**KhoLe**_: `KhoLe` - _**MaHH**_: `MaHH` - _**SoHD**_: `SoHD` - _**NgayHD**_: `NgayHD` - _**ThangKT**_: `ThangKT` - _**NamKT**_: `NamKT`
-  ![loi_cls](https://img.shields.io/badge/Chi%20tiết%20CLS-:-blue?style=plastic&logo=github)
   > _**MaCLS**_: `MaCLS` - _**PhieuYC**_: `PhieuYC`
-  ![loi_bo_sung](https://img.shields.io/badge/Chi%20tiết%20bổ%20sung-:-blue?style=plastic&logo=github)
   > _**Khac**_: `Khac`

###### ![mo_ta_loi](https://img.shields.io/badge/Mô%20tả%20thông%20tin%20lỗi-:-blue?style=for-the-badge&logo=github)

Bệnh nhân BHYT, Khi chỉ định CLS, lưu xong, chọn lại cls đã lưu và click chuột phải chọn **Đánh dấu thu phí**, thì trên form có thay đổi sang giá thu phí, dấu check cột TP cũng được check, dữ liệu thì có cập nhật chidinhcls.bhyt=0, **nhưng chidinhcls.dongia không được cập nhật** => đóng form mở lại nó load lại giá BHYT

Tất cả BV đều bị lỗi này.

![image](https://github.com/dh-hos/dhg.hosptaltreatment/assets/99630883/df96163b-5387-4e9f-8fae-58183f6b0f89)
![image](https://github.com/dh-hos/dhg.hosptaltreatment/assets/99630883/583d3c62-fb61-499c-b4bf-9991e17a4f07)

**Comment by vuongdh** [comment]
đang xài phiên bản mấy vậy @lqbinh1987

**Comment by vuongdh** [comment]
thao tác này: nhưng chidinhcls.dongia không được cập nhật => đóng form mở lại nó load lại giá BHYT ==> thực hiện chổ nào vây ?

**Comment by lqbinh1987** [comment]
![image](https://github.com/dh-hos/dhg.hosptaltreatment/assets/99630883/9fc69293-e8d0-4cd9-acb1-fbf57c8a5bd9)

chọn lại cls đã lưu và click chuột phải chọn Đánh dấu thu phí. Anh @vuongdh

**Comment by vuongdh** [comment]
mấy hình em add, bấm vào xem không đc

**Comment by vuongdh** [comment]
Cập nhật <b>Treat4.2023.12.22v2 </b>- vào chi tiết để tải bản cập nhật

<div align="left">

[![View](https://img.shields.io/badge/-Xem%20chi%20ti%E1%BA%BFt%20c%E1%BA%ADp%20nh%E1%BA%ADt-informational?logo=github)](https://github.com/dh-hos/dhg.hosptaltreatment/blob/main/README.md)

</div>
