### ISSUE TITLE
Lỗi - Trình tự TT/PT quá dài phiếu Phẫu thuật không hiển thị hết nội dung 

### ISSUE THREAD

**Issue by hvtuan1987** [dh-hos/dhg.hosptaltreatment#185]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.1: Phiếu ghi nhận lỗi phát sinh DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN LỖI PHÁT SINH</h1>  
</div>

#
-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Hà Văn Tuấn**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **29/12/2023**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `79029`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **Bệnh viện Quận 12**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `tuan_dbquan12_sieuam`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`](link_csdl)

###### ![chi_tiet_loi](https://img.shields.io/badge/Chi%20tiết%20lỗi%20phát%20sinh-:-blue?style=for-the-badge&logo=github)

-  ![loi_benh_nhan](https://img.shields.io/badge/Chi%20tiết%20bệnh%20nhân-:-blue?style=plastic&logo=github)
   > _**MaBN**_: `2023112367` - _**MaKB**_: `2312000009` - _**MaBA**_: `2023000002` _**NgayKCB**_: `29/12/2023` - _**MaPhong**_: `MaPhong` - _**MaDV**_: `04` - _**ThangKT**_: `12` - _**NamKT**_: `2023`
-  ![loi_thuoc](https://img.shields.io/badge/Chi%20tiết%20thuốc-:-blue?style=plastic&logo=github)
   > _**KhoChan**_: `KhoChan` - _**KhoLe**_: `KhoLe` - _**MaHH**_: `MaHH` - _**SoHD**_: `SoHD` - _**NgayHD**_: `NgayHD` - _**ThangKT**_: `ThangKT` - _**NamKT**_: `NamKT`
-  ![loi_cls](https://img.shields.io/badge/Chi%20tiết%20CLS-:-blue?style=plastic&logo=github)
   > _**MaCLS**_: `MaCLS` - _**PhieuYC**_: `PhieuYC`
-  ![loi_bo_sung](https://img.shields.io/badge/Chi%20tiết%20bổ%20sung-:-blue?style=plastic&logo=github)
   > _**Khac**_: `Khac`

Trình tự TT/PT người dùng gõ quá dài khi in phiếu Phẫu Thuật không hiển thị hết phần nội dung của Trình tự TT/PT.
Bệnh viện yêu cầu hỗ trợ khi nội dung quá dài hiển thị sang trang tiếp theo.
Hình mô tả người dùng gõ trình tự TT/PT và in ra như hình dưới
![image](https://github.com/dh-hos/dhg.hosptaltreatment/assets/97272364/932b169f-d6e7-424b-bca8-1b11755eeb16)
![image](https://github.com/dh-hos/dhg.hosptaltreatment/assets/97272364/2c48d379-82ae-406e-b604-8ee0a0a4fb60)

**Comment by vuongdh** [comment]
Lượt đồ này làm thiệt hay làm chơi mà dài dữ vậy

**Comment by hvtuan1987** [comment]
Dạ bên Bệnh viện là thiệt á, còn dữ liệu này em test để xem có sang trang mới nếu dài hong á !

**Comment by vuongdh** [comment]
Cập nhật <b>Treat4.2024.01.10v1 </b>- vào chi tiết để tải bản cập nhật

<div align="left">

[![View](https://img.shields.io/badge/-Xem%20chi%20ti%E1%BA%BFt%20c%E1%BA%ADp%20nh%E1%BA%ADt-informational?logo=github)](https://github.com/dh-hos/dhg.hosptaltreatment/blob/main/README.md)

</div>
Em test lại hén, anh chuyển qua mẫu tự thiết kế

**Comment by hvtuan1987** [comment]
ok anh !
