### ISSUE TITLE
Lỗi - Toa thuốc tủ trực, chỉ định cls (BV Thốt Nốt)

### ISSUE THREAD

**Issue by le-an-87** [dh-hos/dhg.hosptaltreatment#188]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.1: Phiếu ghi nhận lỗi phát sinh DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN LỖI PHÁT SINH</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Ân**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **02/01/2024**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `92010`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **BV Thốt Nốt**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `an_thotnot_phieutonghop`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`an_thotnot_phieutonghop`](https://gofile.me/78TQg/hswcQ4S0Y)

###### ![chi_tiet_loi](https://img.shields.io/badge/Chi%20tiết%20lỗi%20phát%20sinh-:-blue?style=for-the-badge&logo=github)

-  ![loi_benh_nhan](https://img.shields.io/badge/Chi%20tiết%20bệnh%20nhân-:-blue?style=plastic&logo=github)
   > _**MaBN**_: `2023049256` - _**MaKB**_: `2312016637` - _**MaBA**_: `2023021739` _**NgayKCB**_: `02/01/2024` - _**MaPhong**_: `244` - _**MaDV**_: `03` - _**ThangKT**_: `01` - _**NamKT**_: `2024`
-  ![loi_thuoc](https://img.shields.io/badge/Chi%20tiết%20thuốc-:-blue?style=plastic&logo=github)
   > _**Tutruc**_: `VTNGOAI`- _**SoHD**_: `G5.X24.0102.133253` - _**NgayHD**_: `02/01/2024` - _**ThangKT**_: `01` - _**NamKT**_: `2024`

###### ![mo_ta_loi](https://img.shields.io/badge/Mô%20tả%20thông%20tin%20lỗi-:-blue?style=for-the-badge&logo=github)

```
1. Xóa thuốc khi đang ra toa báo lỗi: khi ra toa chọn nhằm thuốc -> thực hiện xóa thuốc chọn nhằm phần mềm báo lỗi.
2. Phiếu công khai tủ trực VTYT: in luôn hiển thị mộc PHIẾU IN LẠI.
3. Chức năng bỏ qua khi chỉ định cls báo lỗi: trường hợp thêm cls xong rồi -> lick qua dòng cls củ -> lick chọn vào cls mới đã chỉ định -> chọn bỏ qua =>phần mềm phát sinh lỗi.

```
Hình lỗi.
1. 
![image](https://github.com/dh-hos/dhg.hosptaltreatment/assets/96155021/d4b3faeb-7bf5-4eaa-872c-abc085b4213c)
2. In lần đầu vẫn hiển thị mộc phiếu in lại
![image](https://github.com/dh-hos/dhg.hosptaltreatment/assets/96155021/381c2427-2096-47a8-8d0a-d62a89a3c524)

3. Lỗi bỏ qua chỉ định cls
![image](https://github.com/dh-hos/dhg.hosptaltreatment/assets/96155021/f8b16417-e5e7-4b74-9810-ea94d735cd00)

**Comment by vuongdh** [comment]
Ok em, để anh kiểm tra

**Comment by vuongdh** [comment]
Cập nhật <b>Treat4.2024.01.03v4 </b>- vào chi tiết để tải bản cập nhật

<div align="left">

[![View](https://img.shields.io/badge/-Xem%20chi%20ti%E1%BA%BFt%20c%E1%BA%ADp%20nh%E1%BA%ADt-informational?logo=github)](https://github.com/dh-hos/dhg.hosptaltreatment/blob/main/README.md)

</div>

**Comment by le-an-87** [comment]
2. In lần đầu vẫn hiển thị mộc phiếu in lại

chổ này hiện tại mất mộc in lại luôn rồi anh.

**Comment by vuongdh** [comment]
Toa tủ trực mặc định khi ra toa đã check đã in = 1 (dù chưa in ) ==> hiển thị phiếu đã in.

**Comment by vuongdh** [comment]
dain = 1 ==> "PHIẾU IN LẠI"

**Comment by le-an-87** [comment]
anh nói gì em không hiểu.
hiện tại bản mới không có mộc in lại nữa. in nhiều lần vẫn vậy

**Comment by vuongdh** [comment]
Trước đây tao thuốc nào cột dain =1 điều hiểu hiện phiếu "PHIẾU IN LẠI".  Toa tủ trực khi ra toa dain luon = 1 nên khi in lần đầu hay lần sau điều hiển thị "PHIẾU IN LẠI". không phân biệt đc nên bỏ luôn. Để anh coi có cách nào khác không? rồi cập nhật và hướng dẫn lại

**Comment by vuongdh** [comment]
Cập nhật <b>Treat4.2024.01.04v2 </b>- vào chi tiết để tải bản cập nhật

<div align="left">

[![View](https://img.shields.io/badge/-Xem%20chi%20ti%E1%BA%BFt%20c%E1%BA%ADp%20nh%E1%BA%ADt-informational?logo=github)](https://github.com/dh-hos/dhg.hosptaltreatment/blob/main/README.md)

</div>
@le-an-87  Em test lại bản này: Fix lỗi mất "Phiếu in lại" khi in lần 2
