### ISSUE TITLE
Lỗi - Lấy lại toa sai kho cấp phát thuốc khi check lấy tủ trực nhà thuốc

### ISSUE THREAD

**Issue by chauthanhtra** [dh-hos/dhg.hosptaltreatment#189]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.1: Phiếu ghi nhận lỗi phát sinh DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN LỖI PHÁT SINH</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Châu Thanh Trà**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **2/1/2023**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `92118`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **BV Phụ Sản CT**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `tra_phusan_thuockhackho_nxt_02012024`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`](https://gofile.me/78TQg/rlKlSoFpt)

###### ![chi_tiet_loi](https://img.shields.io/badge/Chi%20tiết%20lỗi%20phát%20sinh-:-blue?style=for-the-badge&logo=github)

-  ![loi_benh_nhan](https://img.shields.io/badge/Chi%20tiết%20bệnh%20nhân-:-blue?style=plastic&logo=github)
   > _**MaBN**_: `2023099585` - _**MaKB**_: `2312007601` - _**MaBA**_: `022243` _**NgayKCB**_: `3/1/2024` - _**MaPhong**_: `MaPhong` - _**MaDV**_: `12` - _**ThangKT**_: `01` - _**NamKT**_: `2024`
-  ![loi_thuoc](https://img.shields.io/badge/Chi%20tiết%20thuốc-:-blue?style=plastic&logo=github)
   > _**KhoChan**_: `KhoChan` - _**KhoLe**_: `KhoLe` - _**MaHH**_: `NI78` - _**SoHD**_: `C80.X23.1216.115412` - _**NgayHD**_: `17/12/2023` - _**ThangKT**_: `12` - _**NamKT**_: `2023`
-  ![loi_cls](https://img.shields.io/badge/Chi%20tiết%20CLS-:-blue?style=plastic&logo=github)
   > _**MaCLS**_: `MaCLS` - _**PhieuYC**_: `PhieuYC`
-  ![loi_bo_sung](https://img.shields.io/badge/Chi%20tiết%20bổ%20sung-:-blue?style=plastic&logo=github)
   > _**Khac**_: `Khac`

###### ![mo_ta_loi](https://img.shields.io/badge/Mô%20tả%20thông%20tin%20lỗi-:-blue?style=for-the-badge&logo=github)

Thuốc NI78 thuộc kho 14 (kho dược) nhưng dữ liệu ghi nhận thuốc xuất từ tủ trực NT12 kho 13 (nhà thuốc)

Nguyên nhân là do chức năng lấy lại toa khi chọn lấy lại toa người dùng có thể check vào ô lấy thuốc từ tủ trực nhà thuốc phần mềm không kiểm tra mà vẫn cho phép lưu
-> mã thuốc của kho 14 nhưng kho xuất thuốc là tủ trực kho 13

![ảnh](https://github.com/dh-hos/dhg.hosptaltreatment/assets/97272332/bf54b0ca-9f4d-4600-9598-61a429937fff)
![ảnh](https://github.com/dh-hos/dhg.hosptaltreatment/assets/97272332/9dc721eb-93ef-4c8a-b437-59ab44705f8c)
![ảnh](https://github.com/dh-hos/dhg.hosptaltreatment/assets/97272332/17a3f8cf-4b2c-4e6b-9920-e1b100b2c6ee)

**Comment by vuongdh** [comment]
Cập nhật <b>Treat4.2024.01.03v2 </b>- vào chi tiết để tải bản cập nhật

<div align="left">

[![View](https://img.shields.io/badge/-Xem%20chi%20ti%E1%BA%BFt%20c%E1%BA%ADp%20nh%E1%BA%ADt-informational?logo=github)](https://github.com/dh-hos/dhg.hosptaltreatment/blob/main/README.md)

</div>
