### ISSUE TITLE
Yêu cầu - Gõ số lượng lẻ khi lập toa mẫu.

### ISSUE THREAD

**Issue by lqbinh1987** [dh-hos/dhg.hosptaltreatment#19]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.2: Phiếu ghi nhận Yêu cầu mới DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN YÊU CẦU CHỨC NĂNG MỚI</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Lâm Quốc Bình**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **06/09/2022**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `92014`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **BV Mắt CT**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `binh_matct_`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`](link_csdl)

###### ![chi_tiet_yeu_cau](https://img.shields.io/badge/Chi%20tiết%20yêu%20cầu%20-:-blue?style=for-the-badge&logo=github)

Yêu cầu chức năng lập toa mẫu cho phép gõ số lượng thuốc là số lẻ.

![image](https://user-images.githubusercontent.com/99630883/188569004-3a76c2e9-33cc-4263-99e5-a54d3a422f87.png)

**Comment by vuongdh** [comment]
@lqbinh1987 Có bảng cập nhật (http://www.fsend.vn/download/nt3QUbNiu5BSYZ4i1p2VKeQyiOFBR2nY)

**Comment by vuongdh** [comment]
@lqbinh1987 Nhớ chạy thêm cái script hỗ trợ mở rộng dữ liệu

**Comment by lqbinh1987** [comment]
Trên form gõ số lẻ thì được rồi, bấm nút Lưu vẫn ok, nhưng trong dữ liệu không lưu được số lẻ, mà nó làm tròn.
Ví dụ nhập 0.5 trở lên thì nó là 1, 0.5 trở xuống thì nó lưu là 0.
