### ISSUE TITLE
Giấy chứng sinh lỗi khi ngày sinh và ngày lập giấy chứng sinh khác tháng-năm kế toán

### ISSUE THREAD

**Issue by nqhoa1005** [dh-hos/dhg.hosptaltreatment#190]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.1: Phiếu ghi nhận lỗi phát sinh DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN LỖI PHÁT SINH</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **NGUYỄN QUỐC HÒA**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **02/01/2024**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `94006`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **BVĐK H.THẠNH TRỊ**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `hoa_dbthanhtri_loics`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`](link_csdl)

###### ![chi_tiet_loi](https://img.shields.io/badge/Chi%20tiết%20lỗi%20phát%20sinh-:-blue?style=for-the-badge&logo=github)

-  ![loi_benh_nhan](https://img.shields.io/badge/Chi%20tiết%20bệnh%20nhân-:-blue?style=plastic&logo=github)
   > _**MaBN**_: `MaBN` - _**MaKB**_: `MaKB` - _**MaBA**_: `2023010238` _**NgayKCB**_: `NgayKCB` - _**MaPhong**_: `MaPhong` - _**MaDV**_: `01` - _**ThangKT**_: `ThangKT` - _**NamKT**_: `NamKT`
-  ![loi_thuoc](https://img.shields.io/badge/Chi%20tiết%20thuốc-:-blue?style=plastic&logo=github)
   > _**KhoChan**_: `KhoChan` - _**KhoLe**_: `KhoLe` - _**MaHH**_: `MaHH` - _**SoHD**_: `SoHD` - _**NgayHD**_: `NgayHD` - _**ThangKT**_: `ThangKT` - _**NamKT**_: `NamKT`
-  ![loi_cls](https://img.shields.io/badge/Chi%20tiết%20CLS-:-blue?style=plastic&logo=github)
   > _**MaCLS**_: `MaCLS` - _**PhieuYC**_: `PhieuYC`
-  ![loi_bo_sung](https://img.shields.io/badge/Chi%20tiết%20bổ%20sung-:-blue?style=plastic&logo=github)
   > _**Khac**_: `Khac`

###### ![mo_ta_loi](https://img.shields.io/badge/Mô%20tả%20thông%20tin%20lỗi-:-blue?style=for-the-badge&logo=github)

Ngày sinh và ngày lập phiếu chứng sinh khác tháng/năm kế toán khi xem phát sinh lỗi.

![image](https://github.com/dh-hos/dhg.hosptaltreatment/assets/130281806/e7ee601e-4217-4857-be7c-cec1639849b6)

**Comment by lequocthong29** [comment]
Cập nhật dll [DH.ThongTinKSK.dll](https://github.com/dh-hos/oLibraries/blob/main/DH.ThongTinKSK.dll)
- đối với trường hợp load thông tin một bệnh nhân, chỉ load theo maba

**Comment by nqhoa1005** [comment]
anh @vuongdh cập nhật dll build lại dùm em

**Comment by vuongdh** [comment]
File cập nhật: [Treat4.2024.01.03v3](https://gofile.me/78TQg/qSKbMI8rP)

**Comment by nqhoa1005** [comment]
dll vẫn còn bản cũ anh @vuongdh , update lại dùm em nhé


![image](https://github.com/dh-hos/dhg.hosptaltreatment/assets/130281806/d11f0f40-3578-4208-8c82-5164d52573f0)
![image](https://github.com/dh-hos/dhg.hosptaltreatment/assets/130281806/cb7e061a-f973-4c38-9fee-75996553e0ad)

**Comment by vuongdh** [comment]
Cập nhật lại bản này: [Treat4.2024.01.04v1](https://gofile.me/78TQg/oiiuC3NKc)
