### ISSUE TITLE
Lỗi - Gửi đơn thuốc điện tử EPR (PK Đông Tây)

### ISSUE THREAD

**Issue by le-an-87** [dh-hos/dhg.hosptaltreatment#191]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.1: Phiếu ghi nhận lỗi phát sinh DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN LỖI PHÁT SINH</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Ân**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **15/01/2024**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `77025`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **PK Đông Tây**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `tra_dongtay_epr_loitrung_full_09012024`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`tra_dongtay_epr_loitrung_full_09012024`](https://gofile.me/78TQg/DYA9tj3mG)

###### ![mo_ta_loi](https://img.shields.io/badge/Mô%20tả%20thông%20tin%20lỗi-:-blue?style=for-the-badge&logo=github)

```
Phòng khám cài module EPR khi thực hiện gửi toa thuốc báo lỗi.
Nhờ anh xem trực tiếp lỗi tại cơ sở giúp.
Do dữ liệu lấy về test không xảy ra lỗi như cài tại đơn vị

```
![image](https://github.com/dh-hos/dhg.hosptaltreatment/assets/96155021/c730a5ed-aa5d-444b-91b7-6f5fe1aac7d0)

**Comment by le-an-87** [comment]
Chổ này anh kiểm tra chưa anh.

**Comment by nghivanbi** [comment]
@vuongdh xem cái này coi bị gì nhé

**Comment by vuongdh** [comment]
@le-an-87 anh test không không có lỗi như hình nhưng nó báo trùng mã đơn thuốc, em nói người dùng gửi file log error để xem lỗi gì

**Comment by vuongdh** [comment]
![image](https://github.com/dh-hos/dhg.hosptaltreatment/assets/32563776/19982926-00b0-48d3-9090-6e35f3ff3eca)

**Comment by vuongdh** [comment]
{"loai_don_thuoc":"c","ma_don_thuoc":"770250000086-c","ten_benh_nhan":"Đào Thị Kim Thịnh","ngay_sinh_benh_nhan":"25/11/1956","ma_dinh_danh_y_te":"","ma_dinh_danh_cong_dan":"","can_nang":0,"gioi_tinh":3,"ma_so_the_bao_hiem_y_te":"GD4777722592306","thong_tin_nguoi_giam_ho":".","dia_chi":"Đạt Thành, Xã Quảng Thành, Huyện Châu Đức, Tỉnh Bà Rịa - Vũng Tàu","chan_doan":[{"ma_chan_doan" : "R51;G43;R42;H81.3", "ten_chan_doan" : "Đau đầu;Migraine;Hoa mắt và chóng mặt;Chóng mặt do nguyên nhân ngoại biên khác", "ket_luan" : "."}],"luu_y":"","hinh_thuc_dieu_tri":2,"dot_dung_thuoc":[{"dot" : 1, "tu_ngay" : "01/01/2024", "den_ngay" : "08/01/2024"}],"thong_tin_don_thuoc":[{"ma_thuoc" : "PR51", "biet_duoc" : "Pracetam 800 (Piracetam) ", "ten_thuoc" : "Pracetam 800", "don_vi_tinh" : "viên", "so_luong" : 20.000, "cach_dung" : " ngày uống 3 lần. lần 1 viên sau ăn"}],"loi_dan":"tái khám khi hết thuốc hoặc bệnh nặng hơn / Đã tư vấn về thuốc và bệnh trên","so_dien_thoai_nguoi_kham_benh":"000","ngay_tai_kham":7,"ngay_gio_ke_don":"2024-01-01 08:21:03","chu_ky_so":""}
{"loai_don_thuoc":"c","ma_don_thuoc":"770250000086-c","ten_benh_nhan":"Đào Thị Kim Thịnh","ngay_sinh_benh_nhan":"25/11/1956","ma_dinh_danh_y_te":"","ma_dinh_danh_cong_dan":"","can_nang":0,"gioi_tinh":3,"ma_so_the_bao_hiem_y_te":"GD4777722592306","thong_tin_nguoi_giam_ho":".","dia_chi":"Đạt Thành, Xã Quảng Thành, Huyện Châu Đức, Tỉnh Bà Rịa - Vũng Tàu","chan_doan":[{"ma_chan_doan" : "R51;G43;R42;H81.3", "ten_chan_doan" : "Đau đầu;Migraine;Hoa mắt và chóng mặt;Chóng mặt do nguyên nhân ngoại biên khác", "ket_luan" : "."}],"luu_y":"","hinh_thuc_dieu_tri":2,"dot_dung_thuoc":[{"dot" : 1, "tu_ngay" : "01/01/2024", "den_ngay" : "08/01/2024"}],"thong_tin_don_thuoc":[{"ma_thuoc" : "PR51", "biet_duoc" : "Pracetam 800 (Piracetam) ", "ten_thuoc" : "Pracetam 800", "don_vi_tinh" : "viên", "so_luong" : 20.000, "cach_dung" : " ngày uống 3 lần. lần 1 viên sau ăn"}],"loi_dan":"tái khám khi hết thuốc hoặc bệnh nặng hơn / Đã tư vấn về thuốc và bệnh trên","so_dien_thoai_nguoi_kham_benh":"000","ngay_tai_kham":7,"ngay_gio_ke_don":"2024-01-01 08:21:03","chu_ky_so":""}

**Comment by le-an-87** [comment]
Lỗi phát sinh vậy sao mà có log mà gửi anh?

**Comment by vuongdh** [comment]
Vậy em kêu cái máy khác xem, giờ test không ra lỗi như em báo rồi
