### ISSUE TITLE
Lỗi - Hiển thị sai năm sinh của BN

### ISSUE THREAD

**Issue by lqbinh1987** [dh-hos/dhg.hosptaltreatment#192]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.1: Phiếu ghi nhận lỗi phát sinh DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN LỖI PHÁT SINH</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Bình**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **16/01/2024**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `92117`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **V Huyết Học**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `binh_dbhuyethoc_full`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`](link_csdl)

###### ![chi_tiet_loi](https://img.shields.io/badge/Chi%20tiết%20lỗi%20phát%20sinh-:-blue?style=for-the-badge&logo=github)

-  ![loi_benh_nhan](https://img.shields.io/badge/Chi%20tiết%20bệnh%20nhân-:-blue?style=plastic&logo=github)
   > _**MaBN**_: `ALL` - _**MaKB**_: `MaKB` - _**MaBA**_: `ALL` _**NgayKCB**_: `NgayKCB` - _**MaPhong**_: `MaPhong` - _**MaDV**_: `20` - _**ThangKT**_: `01` - _**NamKT**_: `2024`
-  ![loi_thuoc](https://img.shields.io/badge/Chi%20tiết%20thuốc-:-blue?style=plastic&logo=github)
   > _**KhoChan**_: `KhoChan` - _**KhoLe**_: `KhoLe` - _**MaHH**_: `MaHH` - _**SoHD**_: `SoHD` - _**NgayHD**_: `NgayHD` - _**ThangKT**_: `ThangKT` - _**NamKT**_: `NamKT`
-  ![loi_cls](https://img.shields.io/badge/Chi%20tiết%20CLS-:-blue?style=plastic&logo=github)
   > _**MaCLS**_: `MaCLS` - _**PhieuYC**_: `PhieuYC`
-  ![loi_bo_sung](https://img.shields.io/badge/Chi%20tiết%20bổ%20sung-:-blue?style=plastic&logo=github)
   > _**Khac**_: `Khac`

###### ![mo_ta_loi](https://img.shields.io/badge/Mô%20tả%20thông%20tin%20lỗi-:-blue?style=for-the-badge&logo=github)
Chức năng in **TK CP ngày theo danh sách**, in lên bảng kê thì năm sinh của BN lúc nào cũng chạy theo năm nhập viện.

![image](https://github.com/dh-hos/dhg.hosptaltreatment/assets/99630883/ecb83a27-192a-48fe-a56e-4e632c93c9cb)
![image](https://github.com/dh-hos/dhg.hosptaltreatment/assets/99630883/cf6a8518-903e-4be4-9c9e-c9087dbd3663)
![image](https://github.com/dh-hos/dhg.hosptaltreatment/assets/99630883/edde0b9c-0115-4308-ae93-d9bb7fc46195)

**Comment by vuongdh** [comment]
@lqbinh1987 mẫu này trước giờ chỉ lấy năm sinh, không lấy ngày sinh. Em hỏi BV xem có hướng dẫn ghi chép cho mẫu này không? đê có cơ sở chỉnh lại theo yêu cầu

**Comment by lqbinh1987** [comment]
Anh @vuongdh. Hiện tại e kiếm thì ko thấy mẫu quy định, nhưng trước mắt anh chỉnh cho hiển thị đúng **ngày tháng năm sinh** của BN lun đi anh. Vì hiện tại đang hiển thị sai.

**Comment by vuongdh** [comment]
@lqbinh1987 vậy em lập yêu cầu đi, để tiện theo dõi

**Comment by vuongdh** [comment]
Cập nhật <b>Treat4.2024.01.16v1 </b>- vào chi tiết để tải bản cập nhật

<div align="left">

[![View](https://img.shields.io/badge/-Xem%20chi%20ti%E1%BA%BFt%20c%E1%BA%ADp%20nh%E1%BA%ADt-informational?logo=github)](https://github.com/dh-hos/dhg.hosptaltreatment/blob/main/README.md)

</div>

**Comment by lqbinh1987** [comment]
Đã xong
