### ISSUE TITLE
Lỗi - Chỉnh thông tin bệnh nhân ghi nhận sai lý do vào viện (BV Phụ Sản)

### ISSUE THREAD

**Issue by le-an-87** [dh-hos/dhg.hosptaltreatment#193]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.1: Phiếu ghi nhận lỗi phát sinh DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN LỖI PHÁT SINH</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Ân**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **16/01/2024**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `Tất cả`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **Tất cả**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `an_phusan_chinh_traituyen_16012024`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`an_phusan_chinh_traituyen_16012024`](https://gofile.me/78TQg/OY7b2lkmr)

###### ![chi_tiet_loi](https://img.shields.io/badge/Chi%20tiết%20lỗi%20phát%20sinh-:-blue?style=for-the-badge&logo=github)

-  ![loi_benh_nhan](https://img.shields.io/badge/Chi%20tiết%20bệnh%20nhân-:-blue?style=plastic&logo=github)
   > _**MaBN**_: `2024003462` - _**MaKB**_: `2401007435` - _**MaBA**_: `000704` _**NgayKCB**_: `16/01/2024` - _**MaPhong**_: `SB` - _**MaDV**_: `11` - _**ThangKT**_: `01` - _**NamKT**_: `2024`

###### ![mo_ta_loi](https://img.shields.io/badge/Mô%20tả%20thông%20tin%20lỗi-:-blue?style=for-the-badge&logo=github)

```
Chức năng chỉnh thông tin bệnh nhân:
1. Không hiển thị đúng thông tin (đúng tuyến/ trái tuyến) khi xem lại.
- Khi hiệu chỉnh phần mềm hiển thị trạng thái trái tuyến
=> thoát chức năng rồi xem lại phần mềm hiển thị cùng tuyến.
2. Không chỉnh được bệnh nhân sang trạng thái trái tuyến được hưởng như cùng tuyến.
- khi chỉnh trương chỉnh vẫn báo bệnh nhân thuộc diện trái tuyến được hưởng như cùng tuyến
=> khi vào xem lại vẫn hiển thị cùng tuyến
==> khi in bảng kê vẫn check vào cùng tuyến

```
![image](https://github.com/dh-hos/dhg.hosptaltreatment/assets/96155021/b2f06918-9884-46fe-be87-4b940ecd0ec5)
![image](https://github.com/dh-hos/dhg.hosptaltreatment/assets/96155021/82414f6d-1c4d-4adb-9881-713f936ca0c7)
[Tải video thao tác](https://gofile.me/78TQg/PvbbImapS)

**Comment by vuongdh** [comment]
Cập nhật <b>Treat4.2024.01.17v1 </b>- vào chi tiết để tải bản cập nhật

<div align="left">

[![View](https://img.shields.io/badge/-Xem%20chi%20ti%E1%BA%BFt%20c%E1%BA%ADp%20nh%E1%BA%ADt-informational?logo=github)](https://github.com/dh-hos/dhg.hosptaltreatment/blob/main/README.md)

</div>

**Comment by le-an-87** [comment]
Đã fix!
![image](https://github.com/dh-hos/dhg.hosptaltreatment/assets/96155021/132941a2-4173-4771-8628-1eb8a3465174)
