### ISSUE TITLE
Lỗi - Phiếu công khai toa tủ trực không hiển thị ghi chú Toa Tủ Trực (BV Thốt Nốt)

### ISSUE THREAD

**Issue by le-an-87** [dh-hos/dhg.hosptaltreatment#196]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.1: Phiếu ghi nhận lỗi phát sinh DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN LỖI PHÁT SINH</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Ân**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **17/01/2023**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `92923`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **BV Thốt Nốt**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `an_thotnot_ghichu_toatutruc_17012024`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [an_thotnot_ghichu_toatutruc_17012024`](https://gofile.me/78TQg/67YJ2sx12)

###### ![chi_tiet_loi](https://img.shields.io/badge/Chi%20tiết%20lỗi%20phát%20sinh-:-blue?style=for-the-badge&logo=github)

-  ![loi_benh_nhan](https://img.shields.io/badge/Chi%20tiết%20bệnh%20nhân-:-blue?style=plastic&logo=github)
   > _**MaBN**_: `2023001443` - _**MaKB**_: `2401006394` - _**MaBA**_: `2024000479` _**NgayKCB**_: `13/01/2024` - _**MaPhong**_: `212B` - _**MaDV**_: `07` - _**ThangKT**_: `01` - _**NamKT**_: `2024`
-  ![loi_thuoc](https://img.shields.io/badge/Chi%20tiết%20thuốc-:-blue?style=plastic&logo=github)
   > _**SoHD**_: `N3.X24.0112.084138` - _**NgayHD**_: `13/01/2024` 

###### ![mo_ta_loi](https://img.shields.io/badge/Mô%20tả%20thông%20tin%20lỗi-:-blue?style=for-the-badge&logo=github)

```
1. Toa tủ trực khi in phiếu công khai không hiển thị ghi chú toa tủ trực
2. Form chỉ định toa thuốc toa tủ trực không check vào toa tủ trực.

```
- 1
>
Phiếu công khai đã in
![image](https://github.com/dh-hos/dhg.hosptaltreatment/assets/96155021/63a740c8-35b5-47df-b5d9-4651d64306b1)
Phiếu in lại Treatment mới
![image](https://github.com/dh-hos/dhg.hosptaltreatment/assets/96155021/025f6f08-a535-4e14-b7a3-f7d89b64e2d5)

- 2
>Form toa thuốc
![image](https://github.com/dh-hos/dhg.hosptaltreatment/assets/96155021/bb4b7865-b4fc-4a6d-afde-18e2305dfa8e)

**Comment by le-an-87** [comment]
Treatment bản 28/11/2023
![image](https://github.com/dh-hos/dhg.hosptaltreatment/assets/96155021/7f36ae8b-7641-4b1d-b73f-8d010198c867)

**Comment by vuongdh** [comment]
em chạy script này và cập nhật bản mới xem còn lỗi mất trạng thái loaitoatt không?
![image](https://github.com/dh-hos/dhg.hosptaltreatment/assets/32563776/bf203fde-b60a-4896-a31e-bad296392bd3)

**Comment by le-an-87** [comment]
anh fix xong hết đi anh!
