### ISSUE TITLE
Lỗi - Trang in phiếu đánh giá dưỡng không hiển thị được chiều cao.

### ISSUE THREAD

**Issue by lqbinh1987** [dh-hos/dhg.hosptaltreatment#197]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.1: Phiếu ghi nhận lỗi phát sinh DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN LỖI PHÁT SINH</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Bình**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **18/01/2024**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `92003`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **BV Nhi Đồng**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `binh_dbnhidong_112023`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`](link_csdl)

###### ![chi_tiet_loi](https://img.shields.io/badge/Chi%20tiết%20lỗi%20phát%20sinh-:-blue?style=for-the-badge&logo=github)

-  ![loi_benh_nhan](https://img.shields.io/badge/Chi%20tiết%20bệnh%20nhân-:-blue?style=plastic&logo=github)
   > _**MaBN**_: `2023174362` - _**MaKB**_: `MaKB` - _**MaBA**_: `2023036383` _**NgayKCB**_: `NgayKCB` - _**MaPhong**_: `MaPhong` - _**MaDV**_: `04` - _**ThangKT**_: `11` - _**NamKT**_: `2023`
-  ![loi_thuoc](https://img.shields.io/badge/Chi%20tiết%20thuốc-:-blue?style=plastic&logo=github)
   > _**KhoChan**_: `KhoChan` - _**KhoLe**_: `KhoLe` - _**MaHH**_: `MaHH` - _**SoHD**_: `SoHD` - _**NgayHD**_: `NgayHD` - _**ThangKT**_: `ThangKT` - _**NamKT**_: `NamKT`
-  ![loi_cls](https://img.shields.io/badge/Chi%20tiết%20CLS-:-blue?style=plastic&logo=github)
   > _**MaCLS**_: `MaCLS` - _**PhieuYC**_: `PhieuYC`
-  ![loi_bo_sung](https://img.shields.io/badge/Chi%20tiết%20bổ%20sung-:-blue?style=plastic&logo=github)
   > _**Khac**_: `Khac`

###### ![mo_ta_loi](https://img.shields.io/badge/Mô%20tả%20thông%20tin%20lỗi-:-blue?style=for-the-badge&logo=github)

Hiện tại khi nhập chiều cao của BN mà nhập từ 1m trở lên thì in ra bị che mất nộ dung do trên trang in quy đổi ra cm.(Hình 1)
Khi mở form đánh giá dinh dưỡng lên thì không mặc định load chỉ số BMI vào form, mà phải lưu nó mới load lên được.(Hình 2)

Hình 1:
![image](https://github.com/dh-hos/dhg.hosptaltreatment/assets/99630883/81044837-add7-4d05-881c-46d502426658)

Hình 2:
![image](https://github.com/dh-hos/dhg.hosptaltreatment/assets/99630883/959d22a3-db71-4534-8c97-38fde36b48f9)

**Comment by vuongdh** [comment]
@lequocthong29 em xem lại chổ này hén

**Comment by lequocthong29** [comment]
UPDATE DLL [DH.TinhTrangDinhDuong.dll](https://github.com/dh-hos/oLibraries/blob/main/DH.TinhTrangDinhDuong.dll).
- Fix 2 lỗi đề cập phía trên

**Comment by lqbinh1987** [comment]
Build lại dùm em cái nhe anh @vuongdh .

**Comment by vuongdh** [comment]
Cập nhật <b>Treat4.2024.01.23v1 </b>- vào chi tiết để tải bản cập nhật

<div align="left">

[![View](https://img.shields.io/badge/-Xem%20chi%20ti%E1%BA%BFt%20c%E1%BA%ADp%20nh%E1%BA%ADt-informational?logo=github)](https://github.com/dh-hos/dhg.hosptaltreatment/blob/main/README.md)

</div>

**Comment by lqbinh1987** [comment]
Đã thể hiện được chiều cao.
![image](https://github.com/dh-hos/dhg.hosptaltreatment/assets/99630883/efb111c1-fa40-4631-b8d6-0674fd6b48c8)
