### ISSUE TITLE
Lỗi - Sai mức hưởng đối với bệnh nội trú có nhập thẻ 2 (BV Tim Mạch AG)

### ISSUE THREAD

**Issue by le-an-87** [dh-hos/dhg.hosptaltreatment#198]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.1: Phiếu ghi nhận lỗi phát sinh DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN LỖI PHÁT SINH</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Ân**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **19/01/2024**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `Tất cả`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **Tất cả**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `an_timmach_ag_muchuongthe2_19012024`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`an_timmach_ag_muchuongthe2_19012024`](https://gofile.me/78TQg/jAF9AwUYq)

###### ![chi_tiet_loi](https://img.shields.io/badge/Chi%20tiết%20lỗi%20phát%20sinh-:-blue?style=for-the-badge&logo=github)

-  ![loi_benh_nhan](https://img.shields.io/badge/Chi%20tiết%20bệnh%20nhân-:-blue?style=plastic&logo=github)
   > _**MaBN**_: `2023031812` - _**MaKB**_: `2401001685` - _**MaBA**_: `2024000254` _**NgayKCB**_: `12/01/2024` - _**MaPhong**_: `18` - _**MaDV**_: `07` - _**ThangKT**_: `01` - _**NamKT**_: `2024`

###### ![mo_ta_loi](https://img.shields.io/badge/Mô%20tả%20thông%20tin%20lỗi-:-blue?style=for-the-badge&logo=github)

```
Bệnh nhân có nhập thẻ 2 GD4898925631610 có mức hưởng 80
phần mềm khi xem tại Form tổng kết 6556 và in bảng kê thể hiện mức hưởng 100%
-> sai mức hưởng thẻ 2

* test phát hiện trường hợp chỉnh trạng thái cấp cứu
```
bảng kê lỗi
![image](https://github.com/dh-hos/dhg.hosptaltreatment/assets/96155021/fb7e52f9-e1d3-46a7-bded-c2396254ae31)

Video test lỗi

https://github.com/dh-hos/dhg.hosptaltreatment/assets/96155021/2410d319-1dc9-41ff-b538-aed3a3467f3d

**Comment by vuongdh** [comment]
Do phần mềm ghi nhận ptthu (thẻ 2) bị sai. Dùng phiên bản Treat4.2024.01.18v1 test: Cập nhật thông tin thẻ 2 --> Lưu lại --> Hiển thị đúng ptthu.

**Comment by le-an-87** [comment]
bản anh nói là fix lỗi em báo rồi phải không anh

**Comment by vuongdh** [comment]
đúng rồi em

**Comment by le-an-87** [comment]
Treatment em test và chụp hình lên là bản Treat4.2024.01.18v1 nhe anh. vẫn còn lỗi nhe anh

**Comment by vuongdh** [comment]
![image](https://github.com/dh-hos/dhg.hosptaltreatment/assets/32563776/63aecd37-a5c7-40ec-a9c7-1ce0621e9881)
Anh chạy nó đúng mà ta, phải cập nhật và lưu lại trên thẻ 2 để ghi nhận đúng thông tin ptthu

**Comment by le-an-87** [comment]
Em báo lỗi ghi nhận sai mức hưởng khi chỉnh trạng thái cấp cứu.
này bắt buộc chỉnh trạng thái là phải chỉnh thông tin thẻ 2 như anh nói sau?

**Comment by le-an-87** [comment]
anh nói em không hiểu.
hiện tại là Treatment có sửa lỗi đó không anh hay phải chỉnh đối tượng chổ thông tin thẻ 2.

**Comment by vuongdh** [comment]
à, hiểu rồi. Em dùng bản cũ: Hiệu chỉnh thông tin thẻ 2, xem có cập nhật đúng ptthu không? nếu đúng thì thôi, khỏi cập nhật lại bản mới. Còn không đúng thì dùng bản mới nhất (cụ thể là bản 2024.01.18v1) hiệu chỉnh thông tin thẻ 2 để cập nhật lại ptthu cho đúng.

**Comment by le-an-87** [comment]
vậy giờ Treatment vẫn chưa sửa lỗi nhé anh!

**Comment by vuongdh** [comment]
Ý em sao ta, anh không hiểu, test lại fix được lỗi, thì sửa gì nữa em

**Comment by le-an-87** [comment]
khi anh chỉnh trạng thái bệnh nhân từ cấp cứu sang bình thường hoặc là ngược lại
thì mức hưởng ghi nhận đúng chưa?
nếu đã đúng thì anh cho em xin bản đó nhe

**Comment by vuongdh** [comment]
Bảng Treat 2024.01.18v1: 
Test:
- Xóa --> nhập mới thẻ BH2
- Chuyển cấp sang bn bình thương
- Chuyển bn bình thường sang cấp cứu

==> Vẫn lưu thông tin ptthu = 20. Em test lại hén

**Comment by le-an-87** [comment]
Lỗi em đã đưa lên kèm theo hình ảnh và video.
Bản nào không bị lỗi thì anh cứ úp lên hoặc gửi link lên để em test lại.

**Comment by vuongdh** [comment]
[Treat4.2024.01.18v1](https://gofile.me/78TQg/nRqiKwvTS)

**Comment by le-an-87** [comment]
bản anh gửi vẫn chưa được nhé!
https://github.com/dh-hos/dhg.hosptaltreatment/assets/96155021/011aa955-d56a-4676-90e9-2bd95b9155ad

**Comment by vuongdh** [comment]
Cập nhật <b>Treat4.2024.01.22v1 </b>- vào chi tiết để tải bản cập nhật

<div align="left">

[![View](https://img.shields.io/badge/-Xem%20chi%20ti%E1%BA%BFt%20c%E1%BA%ADp%20nh%E1%BA%ADt-informational?logo=github)](https://github.com/dh-hos/dhg.hosptaltreatment/blob/main/README.md)

</div>

**Comment by le-an-87** [comment]
Đã fix!
![image](https://github.com/dh-hos/dhg.hosptaltreatment/assets/96155021/291619cd-fc48-4119-b106-0f59b06ca0c3)
![image](https://github.com/dh-hos/dhg.hosptaltreatment/assets/96155021/813a2bb6-4f7c-4e12-a98c-92fc867aef3d)
