### ISSUE TITLE
Lỗi - Chỉnh trạng thái cấp cứu -> Bình thường phần mềm ghi nhận sai lý do vào viện của bệnh nhân (BV phụ sản)

### ISSUE THREAD

**Issue by le-an-87** [dh-hos/dhg.hosptaltreatment#199]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.1: Phiếu ghi nhận lỗi phát sinh DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN LỖI PHÁT SINH</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Ân**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **31/01/2024**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `Tất cả`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **Tất cả**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `an_phusan_tonkho_tutruc_22122023`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`an_phusan_tonkho_tutruc_22122023`](https://gofile.me/78TQg/TAnC9pkUQ)

###### ![chi_tiet_loi](https://img.shields.io/badge/Chi%20tiết%20lỗi%20phát%20sinh-:-blue?style=for-the-badge&logo=github)

-  ![loi_benh_nhan](https://img.shields.io/badge/Chi%20tiết%20bệnh%20nhân-:-blue?style=plastic&logo=github)
   > _**MaBN**_: `2024000011` - _**MaKB**_: `2401000011` - _**MaBA**_: `000009` _**NgayKCB**_: `31/01/2024` - _**MaPhong**_: `39` - _**MaDV**_: `09` - _**ThangKT**_: `01` - _**NamKT**_: `2024`

###### ![mo_ta_loi](https://img.shields.io/badge/Mô%20tả%20thông%20tin%20lỗi-:-blue?style=for-the-badge&logo=github)

```
Test trường hợp bệnh nhập viện ở trạng thái cấp cứu muốn chỉnh sang trạng thái bình thường.
-> Treatment cập nhật sai lý do vào viện của bệnh nhân.

cụ thể test mã bệnh án 000009 sau khi chỉnh cấp cứu về bình thường phần mềm vẫn hiển thị bệnh nhân ở trạng thái đúng tuyến

=> trạng thái đúng: trái tuyến được hưởng như cùng tuyến.

```
Nhập viện trước khi chỉnh
![image](https://github.com/dh-hos/dhg.hosptaltreatment/assets/96155021/9073f684-0096-492d-a8fd-8ec447810a15)

chỉnh cấp cứu -> bình thường
![image](https://github.com/dh-hos/dhg.hosptaltreatment/assets/96155021/d49c0387-7712-4d8e-8362-8a1807f0ee92)

thông tin sau khi chỉnh
![image](https://github.com/dh-hos/dhg.hosptaltreatment/assets/96155021/7265b083-1164-44bc-b863-2a858fde4ab4)
![image](https://github.com/dh-hos/dhg.hosptaltreatment/assets/96155021/91f8b618-dcf3-45fd-86f7-e6af518f784e)

**Comment by vuongdh** [comment]
Cập nhật <b>Treat4.2024.01.31v1 </b>- vào chi tiết để tải bản cập nhật

<div align="left">

[![View](https://img.shields.io/badge/-Xem%20chi%20ti%E1%BA%BFt%20c%E1%BA%ADp%20nh%E1%BA%ADt-informational?logo=github)](https://github.com/dh-hos/dhg.hosptaltreatment/blob/main/README.md)

</div>

**Comment by le-an-87** [comment]
Đã fix!
![image](https://github.com/dh-hos/dhg.hosptaltreatment/assets/96155021/31ca8515-d1c5-47ed-b8be-8c978945a849)
