### ISSUE TITLE
Lỗi - Ra toa nội trú nhà thuốc báo lỗi

### ISSUE THREAD

**Issue by le-an-87** [dh-hos/dhg.hosptaltreatment#20]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.1: Phiếu ghi nhận lỗi phát sinh DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN LỖI PHÁT SINH</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **ÂN**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **14/09/2022**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `92017`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **BV Da liễu CT**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `an_dalieu_toanntnt`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`](link_csdl)

###### ![chi_tiet_loi](https://img.shields.io/badge/Chi%20tiết%20lỗi%20phát%20sinh-:-blue?style=for-the-badge&logo=github)

-  ![loi_benh_nhan](https://img.shields.io/badge/Chi%20tiết%20bệnh%20nhân-:-blue?style=plastic&logo=github)
   > _**MaBN**_: `2022042628` - _**MaKB**_: `2208001236` - _**MaBA**_: `002320` _**NgayKCB**_: `12/09/2022` - _**MaPhong**_: `CSĐB` - _**MaDV**_: `02` - _**ThangKT**_: `09` - _**NamKT**_: `2022`

###### ![mo_ta_loi](https://img.shields.io/badge/Mô%20tả%20thông%20tin%20lỗi-:-blue?style=for-the-badge&logo=github)

```
Khi lưu toa thuốc nội trú nhà thuốc báo lỗi!

```
Khi lưu toa thuốc nội trú nhà thuốc báo lỗi
![image](https://user-images.githubusercontent.com/96155021/190087249-40bc4454-85ec-4df1-9aba-98ada04582e3.png)

**Comment by vuongdh** [comment]
@le-an-87 Lỗi này do độ dài của cột chungtu.kqcdoanp (255), không đủ độ dài. Anh có up script mở rộng độ dài, em nói bệnh viện chạy script là được.
![image](https://user-images.githubusercontent.com/32563776/190299595-f38bc266-7874-4c3b-b2ff-da9338e9196b.png)

**Comment by le-an-87** [comment]
ok anh!
