### ISSUE TITLE
Lỗi - Chỉnh thông tin bệnh nhân nội trú (BV Đặng Thùy Trâm)

### ISSUE THREAD

**Issue by le-an-87** [dh-hos/dhg.hosptaltreatment#201]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.1: Phiếu ghi nhận lỗi phát sinh DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN LỖI PHÁT SINH</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Ân**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **07/02/2024**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `Tất cả`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **Tất cả**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `ten_csdl`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải dangthuytram_chinh_noitru`](https://gofile.me/78TQg/G3PupfKUa)

###### ![chi_tiet_loi](https://img.shields.io/badge/Chi%20tiết%20lỗi%20phát%20sinh-:-blue?style=for-the-badge&logo=github)

-  ![loi_benh_nhan](https://img.shields.io/badge/Chi%20tiết%20bệnh%20nhân-:-blue?style=plastic&logo=github)
   > _**MaBN**_: `2024002106` - _**MaKB**_: `2402001612` - _**MaBA**_: `2024001160` _**NgayKCB**_: `07/02/2024` - _**MaPhong**_: `MaPhong` - _**MaDV**_: `12` - _**ThangKT**_: `02` - _**NamKT**_: `2024`

###### ![mo_ta_loi](https://img.shields.io/badge/Mô%20tả%20thông%20tin%20lỗi-:-blue?style=for-the-badge&logo=github)

```
Chức năng chỉnh thông tin bệnh nhân khi lưu báo lỗi.

```
![image](https://github.com/dh-hos/dhg.hosptaltreatment/assets/96155021/677c02d3-d3ed-48d7-9bdf-7bfb15bf8f68)
![image](https://github.com/dh-hos/dhg.hosptaltreatment/assets/96155021/b46f4a76-5336-4397-8bfe-7322c3355933)

**Comment by vuongdh** [comment]
Cập nhật <b>Treat4.2024.02.08v1 </b>- vào chi tiết để tải bản cập nhật

<div align="left">

[![View](https://img.shields.io/badge/-Xem%20chi%20ti%E1%BA%BFt%20c%E1%BA%ADp%20nh%E1%BA%ADt-informational?logo=github)](https://github.com/dh-hos/dhg.hosptaltreatment/blob/main/README.md)

</div>
