### ISSUE TITLE
Lỗi - QT điều trị không cấn trừ thuốc đã trả

### ISSUE THREAD

**Issue by le-an-87** [dh-hos/dhg.hosptaltreatment#209]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.1: Phiếu ghi nhận lỗi phát sinh DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN LỖI PHÁT SINH</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Ân**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **28/02/2024**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `Tất cả`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **Tất cả**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `an_lapvo_022024_28022024`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`an_lapvo_022024_28022024`](https://gofile.me/78TQg/n3J5n0VkM)

###### ![chi_tiet_loi](https://img.shields.io/badge/Chi%20tiết%20lỗi%20phát%20sinh-:-blue?style=for-the-badge&logo=github)

-  ![loi_benh_nhan](https://img.shields.io/badge/Chi%20tiết%20bệnh%20nhân-:-blue?style=plastic&logo=github)
   > _**MaBN**_: `2024004381` - _**MaKB**_: `2402011749` - _**MaBA**_: `2024002013` _**NgayKCB**_: `28/02/2024` -  _**MaDV**_: `01` - _**ThangKT**_: `02` - _**NamKT**_: `2024`
-  ![loi_thuoc](https://img.shields.io/badge/Chi%20tiết%20thuốc-:-blue?style=plastic&logo=github)
   > _**KhoChan**_: `14` - _**KhoLe**_: `01` - _**MaHH**_: `A.23` - _**SoHD**_: `N08.T24.0228.161617` - _**NgayHD**_: `28/02/2024` 
###### ![mo_ta_loi](https://img.shields.io/badge/Mô%20tả%20thông%20tin%20lỗi-:-blue?style=for-the-badge&logo=github)

```
Thuốc A.23 xuất 4 viên và đã trả 3 viên khi in quá trình điều trị vẫn hiển thị 4 viên
-> không cấn trừ được thuốc trả và không hiển thị thuốc trả

```
Form tổng kết
![image](https://github.com/dh-hos/dhg.hosptaltreatment/assets/96155021/75aa8551-15b1-45e9-bdf3-a10490ff529c)
Tờ điều trị
![image](https://github.com/dh-hos/dhg.hosptaltreatment/assets/96155021/76562526-b806-404b-8e47-686f05ae1ac4)

**Comment by vuongdh** [comment]
Cập nhật <b>Treat4.2024.03.06v3 </b>- vào chi tiết để tải bản cập nhật

<div align="left">

[![View](https://img.shields.io/badge/-Xem%20chi%20ti%E1%BA%BFt%20c%E1%BA%ADp%20nh%E1%BA%ADt-informational?logo=github)](https://github.com/dh-hos/dhg.hosptaltreatment/blob/main/README.md)

</div>

**Comment by le-an-87** [comment]
anh kiểm tra lại chổ này giùm em nhe. bản này không hiển thị được đúng trạng thái - TRÁI TUYẾN CÙNG TUYẾN
![ảnh](https://github.com/dh-hos/dhg.hosptaltreatment/assets/96155021/82667a01-92c9-49e1-8ccc-d0d0061623fd)

**Comment by vuongdh** [comment]
Anh nhìn sơ hình em gửi: BV tuyến huyện thông tuyến toàn quốc --> cùng tuyến
BV tuyến tỉnh:  mới áp dụng --> trái tuyến được hưởng như cùng tuyến
Em kiêm tra xem phải vậy không? Có gì anh xem lại

**Comment by le-an-87** [comment]
> Anh nhìn sơ hình em gửi: BV tuyến huyện thông tuyến toàn quốc --> cùng tuyến BV tuyến tỉnh: mới áp dụng --> trái tuyến được hưởng như cùng tuyến Em kiêm tra xem phải vậy không? Có gì anh xem lại

Bệnh viện áp dụng theo công văn 627 đó anh. anh coi lại giùm em.
thêm vấn đề nữa nếu tuyến huyện không áp dụng được vậy sao Treatment lại ghi nhận trạng thái trái tuyến được hưởng như cùng tuyến như vậy.

**Comment by vuongdh** [comment]
OK

**Comment by le-an-87** [comment]
với anh cho em hỏi chổ sắp xếp thứ tự này với
Hiện tại khi in là sắp xếp theo thứ tự thế nào vậy anh. hiển thị thì theo ngày tháng diễn biến -> khi in thì không theo vậy
khi trả thuốc khác ngày mà trong ngày đó không có toa chỉ định thì bản in mình không in ra luôn hả anh.
![ảnh](https://github.com/dh-hos/dhg.hosptaltreatment/assets/96155021/1bc4679a-acfc-4eef-bcd3-a854c69b2a07)

ngày 6 có trả thuốc nhưng không hiển thị cùng không cấn trừ ngày củ
![ảnh](https://github.com/dh-hos/dhg.hosptaltreatment/assets/96155021/88cdf167-3e81-4f6b-ad1f-4428216176da)

**Comment by vuongdh** [comment]
Cập nhật <b>Treat4.2024.03.07v1 </b>- vào chi tiết để tải bản cập nhật

<div align="left">

[![View](https://img.shields.io/badge/-Xem%20chi%20ti%E1%BA%BFt%20c%E1%BA%ADp%20nh%E1%BA%ADt-informational?logo=github)](https://github.com/dh-hos/dhg.hosptaltreatment/blob/main/README.md)

</div>

**Comment by le-an-87** [comment]
chổ chỉnh thông tin này chưa được nhe anh.
chỉnh bệnh nhân phần mềm hỏi có giấy chuyển viện không.
-> chọn có thì form hiển thị đúng tuyến
=> tắt form hiệu chỉnh mở lại thì trái tuyến, nhật ký hiệu chỉnh cũng ghi trái tuyến nữa.
anh kiểm tra lại giùm em với.
![ảnh](https://github.com/dh-hos/dhg.hosptaltreatment/assets/96155021/c851cf83-8436-41ca-88ac-7bfb8520ae4d)
![ảnh](https://github.com/dh-hos/dhg.hosptaltreatment/assets/96155021/732c779f-d8b1-4e90-b941-a7ae23d8cf33)
![ảnh](https://github.com/dh-hos/dhg.hosptaltreatment/assets/96155021/bdd833e3-b87f-48be-8427-923c902d2767)

**Comment by vuongdh** [comment]
Cập nhật <b>Treat4.2024.03.07v2 </b>- vào chi tiết để tải bản cập nhật

<div align="left">

[![View](https://img.shields.io/badge/-Xem%20chi%20ti%E1%BA%BFt%20c%E1%BA%ADp%20nh%E1%BA%ADt-informational?logo=github)](https://github.com/dh-hos/dhg.hosptaltreatment/blob/main/README.md)

</div>
Em test lại coi được chưa

**Comment by le-an-87** [comment]
Còn vướng trường hợp nhập giấy chuyển viện như anh.
bệnh có thẻ đăng ký ở bv 87004 cùng tỉnh với bv khám
Chỉnh đối tượng nhập mã bv chuyển vào bảng kê vẫn hiển thị lý do vào viện Thông tuyến
![ảnh](https://github.com/dh-hos/dhg.hosptaltreatment/assets/96155021/1001b53a-880f-4103-b2d7-b39695fc1009)
![ảnh](https://github.com/dh-hos/dhg.hosptaltreatment/assets/96155021/1aac31cb-3c55-45d6-9995-da9bf791db8a)

**Comment by vuongdh** [comment]
Còn vướng chổ nào em test hết dùm anh đi, anh chỉnh luôn 1 lần

**Comment by vuongdh** [comment]
Chổ này theo tt40: nó là thông tuyến
Còn theo 627: là thông tuyến hay đúng tuyến. Em check lại dùm anh.
 ![image](https://github.com/dh-hos/dhg.hosptaltreatment/assets/32563776/6745670e-c3fe-4bd6-846b-c926a3f92418)
Trên mẫu 6556 không thấy hướng dẫn để thế nào

**Comment by le-an-87** [comment]
đã fix lỗi qt điều trị.

lỗi chỉnh đối tượng chuyển sang git https://github.com/dh-hos/dhg.hospitalregister/issues/69
