### ISSUE TITLE
Lỗi - Load lại thông tin cân nặng cũ khi lập phiếu đánh giá dinh dưỡng.

### ISSUE THREAD

**Issue by lqbinh1987** [dh-hos/dhg.hosptaltreatment#211]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.1: Phiếu ghi nhận lỗi phát sinh DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN LỖI PHÁT SINH</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Bình**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **06/03/2024**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `92003`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **BV Nhi Đồng**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `binh_dbnhidong_dinhduong`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`](link_csdl)

###### ![chi_tiet_loi](https://img.shields.io/badge/Chi%20tiết%20lỗi%20phát%20sinh-:-blue?style=for-the-badge&logo=github)

-  ![loi_benh_nhan](https://img.shields.io/badge/Chi%20tiết%20bệnh%20nhân-:-blue?style=plastic&logo=github)
   > _**MaBN**_: `2023042227` - _**MaKB**_: `MaKB` - _**MaBA**_: `2024003249` _**NgayKCB**_: `NgayKCB` - _**MaPhong**_: `MaPhong` - _**MaDV**_: `08` - _**ThangKT**_: `02` - _**NamKT**_: `2024`
-  ![loi_thuoc](https://img.shields.io/badge/Chi%20tiết%20thuốc-:-blue?style=plastic&logo=github)
   > _**KhoChan**_: `KhoChan` - _**KhoLe**_: `KhoLe` - _**MaHH**_: `MaHH` - _**SoHD**_: `SoHD` - _**NgayHD**_: `NgayHD` - _**ThangKT**_: `02` - _**NamKT**_: `2024`
-  ![loi_cls](https://img.shields.io/badge/Chi%20tiết%20CLS-:-blue?style=plastic&logo=github)
   > _**MaCLS**_: `MaCLS` - _**PhieuYC**_: `PhieuYC`
-  ![loi_bo_sung](https://img.shields.io/badge/Chi%20tiết%20bổ%20sung-:-blue?style=plastic&logo=github)
   > _**Khac**_: `Khac`

###### ![mo_ta_loi](https://img.shields.io/badge/Mô%20tả%20thông%20tin%20lỗi-:-blue?style=for-the-badge&logo=github)

Khi lập phiếu đánh giá dinh dưỡng thì phần mềm lại load lại thông tin cân nặng và ngày lập của BA nhập viện cũ.
![image](https://github.com/dh-hos/dhg.hosptaltreatment/assets/99630883/173f4fe1-5f26-4705-be7b-88e06926898f)
![image](https://github.com/dh-hos/dhg.hosptaltreatment/assets/99630883/bee2bd2b-db8b-4d1b-b71b-d3266b4db623)

**Comment by vuongdh** [comment]
@lequocthong29 em check lại chổ này hén

**Comment by lequocthong29** [comment]
Update DLL [DH.TinhTrangDinhDuong.dll](https://github.com/dh-hos/oLibraries/blob/main/DH.TinhTrangDinhDuong.dll)
- Fix lỗi load lại thông tin cân nặng cũ khi lập phiếu đánh giá dinh dưỡng.

**Comment by vuongdh** [comment]
Cập nhật <b>Treat4.2024.03.06v2 </b>- vào chi tiết để tải bản cập nhật

<div align="left">

[![View](https://img.shields.io/badge/-Xem%20chi%20ti%E1%BA%BFt%20c%E1%BA%ADp%20nh%E1%BA%ADt-informational?logo=github)](https://github.com/dh-hos/dhg.hosptaltreatment/blob/main/README.md)

</div>

**Comment by lqbinh1987** [comment]
Đã fix
![image](https://github.com/dh-hos/dhg.hosptaltreatment/assets/99630883/d67fadfc-61a1-453a-9817-e458469e973b)
![image](https://github.com/dh-hos/dhg.hosptaltreatment/assets/99630883/0b98ac11-1e57-48f5-a3e7-0d50a71deb83)

**Comment by hvtuan1987** [comment]
test

**Comment by vuongdh** [comment]
@hvtuan1987 này là sao em?

**Comment by lqbinh1987** [comment]
Này e kêu Tuấn nó test thử thông báo bên e thôi anh

> @hvtuan1987 này là sao em?
