### ISSUE TITLE
Lỗi - Phiếu chỉ định xét nghiệm không sắp xếp được cls theo số thứ tự đã cấu hình (BV Ung Bướu)

### ISSUE THREAD

**Issue by le-an-87** [dh-hos/dhg.hosptaltreatment#215]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.1: Phiếu ghi nhận lỗi phát sinh DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN LỖI PHÁT SINH</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Ân**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **25/03/2024**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `Tất cả`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **Tất cả**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `an_ungbuou_phieuchidinh_25032024`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`an_ungbuou_phieuchidinh_25032024`](https://gofile.me/78TQg/zS1e2YiXJ)

###### ![chi_tiet_loi](https://img.shields.io/badge/Chi%20tiết%20lỗi%20phát%20sinh-:-blue?style=for-the-badge&logo=github)

-  ![loi_benh_nhan](https://img.shields.io/badge/Chi%20tiết%20bệnh%20nhân-:-blue?style=plastic&logo=github)
   > _**MaBN**_: `2024012037` - _**MaKB**_: `2403011032` - _**MaBA**_: `005929` _**NgayKCB**_: `25/03/2024` - _**MaDV**_: `01` - _**ThangKT**_: `03` - _**NamKT**_: `2024`

-  ![loi_cls](https://img.shields.io/badge/Chi%20tiết%20CLS-:-blue?style=plastic&logo=github)
   > _**MaCLS**_: `KH24` - _**PhieuYC**_: `Phiếu chỉ định xét nghiệm`

###### ![mo_ta_loi](https://img.shields.io/badge/Mô%20tả%20thông%20tin%20lỗi-:-blue?style=for-the-badge&logo=github)

```
1. Phiếu chỉ định xét nghiệm in theo mẫu chuẩn in không đúng thứ tự đã cấu hình tại danh mục cls.
2. Tiêu đề bệnh viện không hiển thị hết nội dung.
```
Hình ảnh phiếu chỉ định Treatment và phiếu kết quả tại Labor
![ảnh](https://github.com/dh-hos/dhg.hosptaltreatment/assets/96155021/35e9b941-6a03-4768-b607-da6a395edf5a)
dmcls
![ảnh](https://github.com/dh-hos/dhg.hosptaltreatment/assets/96155021/014582c2-33f5-4d91-88cd-57235a662cec)
![ảnh](https://github.com/dh-hos/dhg.hosptaltreatment/assets/96155021/ae765f60-0c79-4ad1-a691-8119ca56aab5)

**Comment by gh-dh-bot-00** [comment]
###### 📣[gh-bot-dh-hos-projects-timelines] - Nhật ký thay đổi công việc hiện tại 📣 [dataUrl](https://o-dh-002-default-rtdb.asia-southeast1.firebasedatabase.app/github-com/dh-hos/webhooks/Issues/dhg-hosptaltreatment/215)

**Comment by vuongdh** [comment]
Cập nhật <b>Treat4.2024.03.26v1 </b>- vào chi tiết để tải bản cập nhật

<div align="left">

[![View](https://img.shields.io/badge/-Xem%20chi%20ti%E1%BA%BFt%20c%E1%BA%ADp%20nh%E1%BA%ADt-informational?logo=github)](https://github.com/dh-hos/dhg.hosptaltreatment/blob/main/README.md)

</div>

**Comment by le-an-87** [comment]
Đã fix phiếu chỉ định.
![ảnh](https://github.com/dh-hos/dhg.hosptaltreatment/assets/96155021/e0110b0d-f7fa-468c-892e-3a98b377c480)

** Phát sinh lỗi chỉnh đối tượng.
Bệnh nhân không chỉnh sang trạng thái Trái tuyến như cùng tuyến được.
- khi chỉnh từ cùng tuyến -> sang trái tuyến được hưởng như cùng tuyến.
=> phần mềm vẫn hiển thị cùng tuyến.

![ảnh](https://github.com/dh-hos/dhg.hosptaltreatment/assets/96155021/b3db2281-6203-4de3-a144-482cdbdb9baa)
![ảnh](https://github.com/dh-hos/dhg.hosptaltreatment/assets/96155021/46cf6d3e-42e4-4793-b67d-20428bf4407e)
![ảnh](https://github.com/dh-hos/dhg.hosptaltreatment/assets/96155021/455e50ef-205a-4610-a3be-ba2f3e57ef0a)

**Comment by vuongdh** [comment]
Cập nhật <b>Treat4.2024.03.26v2 </b>- vào chi tiết để tải bản cập nhật

<div align="left">

[![View](https://img.shields.io/badge/-Xem%20chi%20ti%E1%BA%BFt%20c%E1%BA%ADp%20nh%E1%BA%ADt-informational?logo=github)](https://github.com/dh-hos/dhg.hosptaltreatment/blob/main/README.md)

</div>

**Comment by le-an-87** [comment]
Đã fix!
các chức năng cơ bản sử dụng bình thường.
![ảnh](https://github.com/dh-hos/dhg.hosptaltreatment/assets/96155021/1b050ff3-4b91-47d6-91a8-e55836afa98e)
![ảnh](https://github.com/dh-hos/dhg.hosptaltreatment/assets/96155021/6f710368-fcda-4ca0-8925-4d907ea24064)
![ảnh](https://github.com/dh-hos/dhg.hosptaltreatment/assets/96155021/13ae073e-6e6d-4a00-95ea-287bbc906958)
![ảnh](https://github.com/dh-hos/dhg.hosptaltreatment/assets/96155021/0405f92b-1a6e-44f2-b1fc-b83486104703)
