### ISSUE TITLE
Lỗi - test yêu cầu ra toa Vật tư kèm theo được chọn tủ trực Vật tư

### ISSUE THREAD

**Issue by le-an-87** [dh-hos/dhg.hosptaltreatment#216]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.1: Phiếu ghi nhận lỗi phát sinh DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN LỖI PHÁT SINH</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Ân**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **27/03/2024**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `92010`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **BV Thốt Nốt**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `an_thotnot_toatt_27032024`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`an_thotnot_toatt_27032024`](https://gofile.me/78TQg/o34bsM2J5)

###### ![chi_tiet_loi](https://img.shields.io/badge/Chi%20tiết%20lỗi%20phát%20sinh-:-blue?style=for-the-badge&logo=github)

-  ![loi_benh_nhan](https://img.shields.io/badge/Chi%20tiết%20bệnh%20nhân-:-blue?style=plastic&logo=github)
   > _**MaBN**_: `2024012044` - _**MaKB**_: `2403015712` - _**MaBA**_: `2024000001` _**NgayKCB**_: `27/03/2024` - _**MaPhong**_: `21` - _**MaDV**_: `23` - _**ThangKT**_: `03` - _**NamKT**_: `2024`

###### ![mo_ta_loi](https://img.shields.io/badge/Mô%20tả%20thông%20tin%20lỗi-:-blue?style=for-the-badge&logo=github)
Git yêu cầu
[ Yêu cầu - Mở chức năng ra toa nhiều tủ trực #190](https://github.com/dh-hos/To_Lap_Trinh/issues/190#issue-2021986499)
```
Hiện tại vào chức năng chỉ định cls báo lỗi nên chưa test được chỉ định toa vật tư kèm theo anh ơi.

đã cập nhật hết cấu trúc.
```
![ảnh](https://github.com/dh-hos/dhg.hosptaltreatment/assets/96155021/8a7a9941-406b-4c57-bb83-af54e5610b9e)

**Comment by gh-dh-bot-00** [comment]
###### 📣[gh-bot-dh-hos-projects-timelines] - Nhật ký thay đổi công việc hiện tại 📣 [dataUrl](https://o-dh-002-default-rtdb.asia-southeast1.firebasedatabase.app/github-com/dh-hos/webhooks/Issues/dhg-hosptaltreatment/216)

**Comment by vuongdh** [comment]
@le-an-87 lỗi này do thiếu cột soluong bàng bocls, @lqbinh1987 gửi @le-an-87 script cập nhật hén

**Comment by lqbinh1987** [comment]
> @le-an-87 lỗi này do thiếu cột soluong bàng bocls, @lqbinh1987 gửi @le-an-87 script cập nhật hén

https://github.com/dh-hos/Mo-ta-he-thong/blob/main/20240124%20-%20Chu%20de%20-%20Bo%20can%20lam%20sang.md

**Comment by le-an-87** [comment]
chổ này tụi em chạy cript cho từng bệnh viện hay sao anh @vuongdh ?

**Comment by vuongdh** [comment]
ủa chưa đưa lên admin hả, anh tưởng sau bảng cập nhật trước là @lqbinh1987 đưa lên chung hết chứ

**Comment by vuongdh** [comment]
để anh đưa lên

**Comment by lqbinh1987** [comment]
Có rồi mà
![image](https://github.com/dh-hos/dhg.hosptaltreatment/assets/99630883/39fba778-e565-4358-9d8e-b5ef2812cbe0)

**Comment by lqbinh1987** [comment]
> ủa chưa đưa lên admin hả, anh tưởng sau bảng cập nhật trước là @lqbinh1987 đưa lên chung hết chứ

Cài này e không phụ trách cập nhật script lên nhé anh.

**Comment by vuongdh** [comment]
@lqbinh1987 OK em, nhưng sau này em test chức năng nào ổn thì nói với người phụ trách để đưa script lên hén

**Comment by le-an-87** [comment]
anh không có kiểm tra cái lỗi luôn hả anh.

em cập nhật cript anh mới úp rồi mà vẫn còn lỗi nhe
![ảnh](https://github.com/dh-hos/dhg.hosptaltreatment/assets/96155021/a1a3f345-c56f-4f68-aa2b-dd4175ca1229)

**Comment by vuongdh** [comment]
@le-an-87 dữ liệu nào vậy em?

**Comment by le-an-87** [comment]
ở trên đó anh ơi

**Comment by vuongdh** [comment]
@le-an-87 em xem trên máy em ra bảng mấy vậy? để anh coi up file có lộn không?

**Comment by vuongdh** [comment]
[Treat.2024.03.28v1](https://gofile.me/78TQg/BIU6uTNk0)
Anh mới build lại, em thử lại xem

**Comment by le-an-87** [comment]
Đã bổ sung chức năng chọn tủ trực VTYT khi ra toa vật tư kèm theo!

* Vấn đề phát sinh:
1. Bệnh nhân được chuyển viện nhưng bảng kê vẫn check vào thông tuyến. maba: 2024000002

2. bệnh nhân xuất viện thì không xem được toa vật tư kèm theo đã chỉ định. (chức năng bị ẩn bệnh khi ra viện)
maba: 2024000001
-----
>1.
![ảnh](https://github.com/dh-hos/dhg.hosptaltreatment/assets/96155021/fed5347a-1d1c-46ba-bd9c-8c8a8797fdee)
![ảnh](https://github.com/dh-hos/dhg.hosptaltreatment/assets/96155021/75797f72-f1e1-498f-ac4e-932f013db83b)

>2. 
![ảnh](https://github.com/dh-hos/dhg.hosptaltreatment/assets/96155021/88531d05-d6e1-4434-9e7d-e511fe61c6ad)

> Đã bổ sung chức năng
![ảnh](https://github.com/dh-hos/dhg.hosptaltreatment/assets/96155021/2870c64a-0898-4b8e-a4fc-e7879489f2c3)
![ảnh](https://github.com/dh-hos/dhg.hosptaltreatment/assets/96155021/e85e174c-8240-4f3f-b06f-8cd6d7316f8a)

**Comment by vuongdh** [comment]
1. Em check lại thông tin xem chổ này hiển thị thế nào là đúng qui định (mấy nay lấn cấn chổ này hơi nhiều)
2. Hỗ trợ xem được toa sau khi bệnh nhân đã ra viện

**Comment by vuongdh** [comment]
Cập nhật <b>Treat4.2024.03.28v2 </b>- vào chi tiết để tải bản cập nhật

<div align="left">

[![View](https://img.shields.io/badge/-Xem%20chi%20ti%E1%BA%BFt%20c%E1%BA%ADp%20nh%E1%BA%ADt-informational?logo=github)](https://github.com/dh-hos/dhg.hosptaltreatment/blob/main/README.md)

</div>

Fix: bệnh nhân xuất viện thì không xem được toa vật tư kèm theo đã chỉ định. (chức năng bị ẩn bệnh khi ra viện)
maba: 2024000001

**Comment by le-an-87** [comment]
chổ số 1 bảng kê đó có sửa chưa vậy anh.

**Comment by vuongdh** [comment]
@le-an-87 Bệnh nhân được chuyển viện nhưng bảng kê vẫn check vào thông tuyến. maba: 2024000002
Này là sao em? không hiểu

**Comment by vuongdh** [comment]
Cập nhật <b>Treat4.2024.03.29v1 </b>- vào chi tiết để tải bản cập nhật

<div align="left">

[![View](https://img.shields.io/badge/-Xem%20chi%20ti%E1%BA%BFt%20c%E1%BA%ADp%20nh%E1%BA%ADt-informational?logo=github)](https://github.com/dh-hos/dhg.hosptaltreatment/blob/main/README.md)

</div>

**Comment by le-an-87** [comment]
Bản mới bị lỗi nữa nhe anh!
Bệnh có thẻ đăng ký ở trạm khi tự đi khám bệnh (không có giấy chuyển viện) 
-> Treatment in bảng kê ra đúng tuyến hết.
--> chức năng chỉnh đối tượng cũng không chỉnh về trạng thái thông tuyến được.
![ảnh](https://github.com/dh-hos/dhg.hosptaltreatment/assets/96155021/b42bd32c-15ba-46f1-b6de-badd3715cc84)

![ảnh](https://github.com/dh-hos/dhg.hosptaltreatment/assets/96155021/12e76852-51f4-4afe-b7fd-1d1f688d235d)

**Comment by vuongdh** [comment]
Cập nhật <b>Treat4.2024.04.01v1 </b>- vào chi tiết để tải bản cập nhật

<div align="left">

[![View](https://img.shields.io/badge/-Xem%20chi%20ti%E1%BA%BFt%20c%E1%BA%ADp%20nh%E1%BA%ADt-informational?logo=github)](https://github.com/dh-hos/dhg.hosptaltreatment/blob/main/README.md)

</div>

**Comment by vuongdh** [comment]
Em test lại hén

**Comment by le-an-87** [comment]
vẫn còn lỗi nhé anh
- thẻ đăng ký ở bv huyện ngoài tỉnh -> lại hiển thị thông tuyến
![ảnh](https://github.com/dh-hos/dhg.hosptaltreatment/assets/96155021/a1ebff83-8cfb-46c9-9d34-74404f892bb2)

**Comment by le-an-87** [comment]
![ảnh](https://github.com/dh-hos/dhg.hosptaltreatment/assets/96155021/f862fb5b-5ce9-4dad-9a57-5431c49648fa)
![ảnh](https://github.com/dh-hos/dhg.hosptaltreatment/assets/96155021/9b79fbc6-daad-4cd3-b65c-d9cf536c68ed)

**Comment by vuongdh** [comment]
Trước giờ, Nó còn phụ thuộc vào tham số tt40, em xem tt40 = mấy vậy?

**Comment by vuongdh** [comment]
nếu tt40 không còn phù hợp thì để anh bỏ qua tham số này luôn

**Comment by vuongdh** [comment]
tt40 = 1:
- cùng tỉnh, tuyến bv khám = 3 hoặc 4, tuyến bv đăng ký = 3, 4 ==> thông tuyến
tt40 =2:
- cùng tỉnh, tuyến bv đăng ký = 3, 4 ==> thông tuyến
tt40=3:
- tuyến bv đăng ký = 3, 4 ==> thông tuyến

Hiện tại tt40 đang áp dụng vậy

**Comment by le-an-87** [comment]
> Đã bổ sung chức năng chọn tủ trực VTYT khi ra toa vật tư kèm theo!
> 
>     * Vấn đề phát sinh:

chuyển sang issuse: https://github.com/dh-hos/dhg.hospitalregister/issues/69
