### ISSUE TITLE
Lỗi - Mẫu phiếu trả Thuốc VTYT.. hóa chất... Sai Tiêu đề...

### ISSUE THREAD

**Issue by hvtuan1987** [dh-hos/dhg.hosptaltreatment#219]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.1: Phiếu ghi nhận lỗi phát sinh DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN LỖI PHÁT SINH</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Hà Văn Tuấn**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **14/04/2024**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `79029`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **Bệnh viện Quận 12**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `tuan_dbquan12_phieutra`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`](link_csdl)

###### ![chi_tiet_loi](https://img.shields.io/badge/Chi%20tiết%20lỗi%20phát%20sinh-:-blue?style=for-the-badge&logo=github)

-  ![loi_benh_nhan](https://img.shields.io/badge/Chi%20tiết%20bệnh%20nhân-:-blue?style=plastic&logo=github)
   > _**MaBN**_: `2024024890` - _**MaKB**_: `2404006126` - _**MaBA**_: `2024006575` _**NgayKCB**_: `11/04/2024` - _**MaPhong**_: `MaPhong` - _**MaDV**_: `02` - _**ThangKT**_: `04` - _**NamKT**_: `2024`
-  ![loi_thuoc](https://img.shields.io/badge/Chi%20tiết%20thuốc-:-blue?style=plastic&logo=github)
   > _**KhoChan**_: `14` - _**KhoLe**_: `KhoLe` - _**MaHH**_: `MaHH` - _**SoHD**_: `SoHD` - _**NgayHD**_: `NgayHD` - _**ThangKT**_: `03` - _**NamKT**_: `2024`
-  ![loi_cls](https://img.shields.io/badge/Chi%20tiết%20CLS-:-blue?style=plastic&logo=github)
   > _**MaCLS**_: `MaCLS` - _**PhieuYC**_: `PhieuYC`
-  ![loi_bo_sung](https://img.shields.io/badge/Chi%20tiết%20bổ%20sung-:-blue?style=plastic&logo=github)
   > _**Khac**_: `Khac`

###### ![mo_ta_loi](https://img.shields.io/badge/Mô%20tả%20thông%20tin%20lỗi-:-blue?style=for-the-badge&logo=github)
Lỗi khi bấm vào nút  In ấn
Các phiếu Trả thuốc, VTYT, Hóa chất.. khi tổng hợp tại Treatment in ra sai Mẫu số và nhãn người nhận người trả cụ thể như sau:
Khi bấm Nút IN
Sai phần MS: 01D/BV-01  -> Mẫu đúng  MS: 05D/BV-01
Sai Nhãn NGƯỜI NHẬN->Đúng:  TRƯỞNG PHÒNG TÀI CHÍNH - KẾ TOÁN
Sai Nhãn NGƯỜI TRẢ-> Đúng: NGƯỜI LẬP PHIẾU
Sai và thiếu tên cột theo mẫu
Khi bấm nút IN NB thì các cột đúng theo mẫu nhưng sai các Tiêu đề và Mẫu số
![image](https://github.com/dh-hos/dhg.hosptaltreatment/assets/97272364/c6178b4f-3000-4d73-b1cf-c5ebb5d0f23b)
Hiện tại các mẫu phiếu trả In tại SecondStore thì đúng theo thông tư
![image](https://github.com/dh-hos/dhg.hosptaltreatment/assets/97272364/e83f24b0-cb79-4fc4-928c-839ebd8eebc8)

Mẫu theo Thông tư 
![image](https://github.com/dh-hos/dhg.hosptaltreatment/assets/97272364/ecb2f7d9-2db6-45e3-a525-b70462974566)
Link tham khảo:
https://vbpl.vn/TW/Pages/vbpq-van-ban-goc.aspx?ItemID=26731

```

**Comment by vuongdh** [comment]
@hvtuan1987  Em xem lại tham số này, coi sao hén
![image](https://github.com/dh-hos/dhg.hosptaltreatment/assets/32563776/56c46526-dcbc-4feb-b24c-562ba154373a)

**Comment by hvtuan1987** [comment]
ok rồi á anh !
