### ISSUE TITLE
Lỗi - Test chức năng phiếu chẩn đoán nguyên nhân tử vong thông tư 24/2020 Treatment 

### ISSUE THREAD

**Issue by chauthanhtra** [dh-hos/dhg.hosptaltreatment#22]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.1: Phiếu ghi nhận lỗi phát sinh DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN LỖI PHÁT SINH</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Châu Thanh Trà**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **22/9/2022**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `mabvbh`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **khach_hang**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `tra_moduc_092022_fees_loadsaichiphi`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`](link_csdl)

###### ![chi_tiet_loi](https://img.shields.io/badge/Chi%20tiết%20lỗi%20phát%20sinh-:-blue?style=for-the-badge&logo=github)

-  ![loi_benh_nhan](https://img.shields.io/badge/Chi%20tiết%20bệnh%20nhân-:-blue?style=plastic&logo=github)
   > _**MaBN**_: `2022016857` - _**MaKB**_: `2209002044` - _**MaBA**_: `003963` _**NgayKCB**_: `NgayKCB` - _**MaPhong**_: `MaPhong` - _**MaDV**_: `07` - _**ThangKT**_: `09` - _**NamKT**_: `2022`
-  ![loi_thuoc](https://img.shields.io/badge/Chi%20tiết%20thuốc-:-blue?style=plastic&logo=github)
   > _**KhoChan**_: `KhoChan` - _**KhoLe**_: `KhoLe` - _**MaHH**_: `MaHH` - _**SoHD**_: `SoHD` - _**NgayHD**_: `NgayHD` - _**ThangKT**_: `ThangKT` - _**NamKT**_: `NamKT`
-  ![loi_cls](https://img.shields.io/badge/Chi%20tiết%20CLS-:-blue?style=plastic&logo=github)
   > _**MaCLS**_: `MaCLS` - _**PhieuYC**_: `PhieuYC`
-  ![loi_bo_sung](https://img.shields.io/badge/Chi%20tiết%20bổ%20sung-:-blue?style=plastic&logo=github)
   > _**Khac**_: `Khac`

###### ![mo_ta_loi](https://img.shields.io/badge/Mô%20tả%20thông%20tin%20lỗi-:-blue?style=for-the-badge&logo=github)

1. - Form nhập liệu quá nhỏ 1 số ô bị khuất, khó thấy thông tin, thêm dòng, không thấy chức năng xoá dòng (Nguyên nhân tử vong, Bệnh lý, nguy cơ,....) -> nếu được giản ra tạo thanh cuộn nguyên trang sẽ dể nhìn hơn cho các máy màn hình nhỏ
    - "Cân nặng trẻ<tuổi"-> "Cân nặng trẻ<1 tuổi"  (thiếu số 1)
    - Hình thức điều tra: "Đang điều tra" -> "Chờ điều tra"
![ảnh](https://user-images.githubusercontent.com/97272332/191676930-b540b100-3f2a-4c1f-a94f-539cb241893b.png)

2. - Các ô nhập ICD không enter hay F2 lên danh sách ICD mà phải gõ trước 1 ký tự vào ô trước sau đó enter hoặc click chuột sang ô khác mới hiển thị danh sách ICD. 
    - Khi đã lên danh sách ICD thì không bỏ qua được mà bắt buộc phải chọn trên danh sách mới đóng được form ICD
![ảnh](https://user-images.githubusercontent.com/97272332/191680242-ea025735-1b15-4e21-88ba-91fdae9649f2.png)

4. - Không lưu được số định danh
    - Số thẻ BH, giá trị thẻ, nơi đăng ký ban đầu lấy sai thông tin
    - Thời điểm đủ 5 năm, miễn cùng chi trả chưa lấy được thông tin
    - Thiếu đơn vị tuổi
    - Nghề nghiệp, tôn giáo lấy sai thông tin
    - Chưa có chổ nhập: Địa chỉ thường trú, Nơi ghi nhận ca bệnh
    - "Ngày vào viện/TV" -> "Ngày ra viện/TV"
    - Mục "Tử Vong tại:" -> chưa check được thông tin
    - Các ô kẻ khung table khi in ra bị mất 
    - Mục "Đối với phụ nữ có phải tử vong khi mang thai" -> check sai ô khi in
    - Nơi xảy ra nguyên nhân bên ngoài thiếu ô check Không biết. khi chọn không biết thì lại check Khu thương mại DV
![ảnh](https://user-images.githubusercontent.com/97272332/191691203-aa17521f-043f-4b94-9f3a-833dc6bd7b36.png)

    - Các mục chon trên trang in có ô chọn hình tròn, đánh số dòng bằng ký tự a) b) c),... , dấu mũ 2 trên chữ Thời gian như 
![ảnh](https://user-images.githubusercontent.com/97272332/191691760-ca29bb21-3f94-48af-bb74-7fd786bdbebd.png)
![ảnh](https://user-images.githubusercontent.com/97272332/191691936-74c0fe57-a4f5-4cc9-9144-fc973cd522d7.png)

**Comment by vuongdh** [comment]
@chauthanhtra nếu là tuổi thì để chuỗi rỗng

**Comment by vuongdh** [comment]
@chauthanhtra Test lại nội dung [bản cập nhật](http://www.fsend.vn/download/8wHOBIAbs11hLsh8-CMqmtZNny5pAvsn)
- Hình thức hiển thị (tròn hoặc vuông) để liên hệ lại vì cùng một nội dung mà lúc tròn lúc vuông
- Thao tác show khi gõ mã ICD (cập nhật sau)

**Comment by chauthanhtra** [comment]
Lỗi không tải file được anh ơi

**Comment by vuongdh** [comment]
@chauthanhtra để anh gửi qua zalo

**Comment by chauthanhtra** [comment]
- Chưa lưu được số định danh
- Thời điểm đủ 5 năm chưa có
- Ngày miễn trừ chưa có
- Nghề nghiệp chưa lấy đúng
- Tôn giáo chưa có 
- Địa chỉ thường trú chưa có 
- Nơi ghi nhận ca bệnh chưa có
- 24. Ngày vào viện/TV -> ngày ra viện/TV
- Ngày ra viện/TV lấy sai (nó lấy ngày vào viện)
- Mất kẻ khung khi in
- Số thứ tự bảng 1,2,3 -> a) b) c)
- Trưng cầu Giám định pháp y chọn Không nhưng ô Nếu có vẫn check được 
- Hình thức tử vong chọn không biết thì check 2 ô
- Nơi xảy ra nguyên nhân chọn không biết thì check 2 ô
- 
![ảnh](https://user-images.githubusercontent.com/97272332/191921525-3f38be63-e1d6-481e-b02f-7c888c0c8652.png)

- Đối với phụ nữ có phải tử vong khi mang thai thiếu lựa chọn Không biết
![ảnh](https://user-images.githubusercontent.com/97272332/191923911-a5329894-64ca-45fe-bde4-72aaf92b2838.png)

- Khi vừa lưu ra viện xong thì nút Tử vong bị ẩn phải đóng form mở lại
![ảnh](https://user-images.githubusercontent.com/97272332/191924114-df66857d-ce55-47cb-ae5f-104e3caf4761.png)
