### ISSUE TITLE
Lỗi - LỖI KHÔNG TRẢ VỀ THANH BHYT KHI CHỈ ĐỊNH CLS CHECK THU PHÍ CHỈNH LẠI BỎ CHECK THU PHÍ

### ISSUE THREAD

**Issue by nqhoa1005** [dh-hos/dhg.hosptaltreatment#221]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.1: Phiếu ghi nhận lỗi phát sinh DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN LỖI PHÁT SINH</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **NGUYỄN QUỐC HÒA**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **15/04/2024**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `94006`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **BVĐK H.THẠNH TRỊ**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `binh_thanhtri_full_t12`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`](link_csdl)

###### ![chi_tiet_loi](https://img.shields.io/badge/Chi%20tiết%20lỗi%20phát%20sinh-:-blue?style=for-the-badge&logo=github)

-  ![loi_benh_nhan](https://img.shields.io/badge/Chi%20tiết%20bệnh%20nhân-:-blue?style=plastic&logo=github)
   > _**MaBN**_: `MaBN` - _**MaKB**_: `MaKB` - _**MaBA**_: `2023010038` _**NgayKCB**_: `NgayKCB` - _**MaPhong**_: `MaPhong` - _**MaDV**_: `MaDV` - _**ThangKT**_: `04` - _**NamKT**_: `2024`
-  ![loi_thuoc](https://img.shields.io/badge/Chi%20tiết%20thuốc-:-blue?style=plastic&logo=github)
   > _**KhoChan**_: `KhoChan` - _**KhoLe**_: `KhoLe` - _**MaHH**_: `MaHH` - _**SoHD**_: `SoHD` - _**NgayHD**_: `NgayHD` - _**ThangKT**_: `ThangKT` - _**NamKT**_: `NamKT`
-  ![loi_cls](https://img.shields.io/badge/Chi%20tiết%20CLS-:-blue?style=plastic&logo=github)
   > _**MaCLS**_: `MaCLS` - _**PhieuYC**_: `PhieuYC`
-  ![loi_bo_sung](https://img.shields.io/badge/Chi%20tiết%20bổ%20sung-:-blue?style=plastic&logo=github)
   > _**Khac**_: `Khac`

###### ![mo_ta_loi](https://img.shields.io/badge/Mô%20tả%20thông%20tin%20lỗi-:-blue?style=for-the-badge&logo=github)

Trường hợp người dùng chỉ định CLS check vào TP để BN đóng tiền sau đó điều chỉnh lại bỏ Check TP ra để BN được hưởng BH (đối với CLS có check thanh BHYT trong danh mục) thì ghi nhận dữ liệu không đánh dấu lại chidinhcls.bhyt = 1, người dùng lầm tưởng khi bỏ check thì sẽ được hưởng BH.
em kiểm tra test thử thì nếu check TP thì lấy giá đúng nhưng đánh dấu lại dữ liệu thì chưa đúng.

khi check TP thì bhyt=0 và thuphi=1
![image](https://github.com/dh-hos/dhg.hosptaltreatment/assets/130281806/9a2b875c-1d02-4d5e-9970-49bbbd9c569d)
![image](https://github.com/dh-hos/dhg.hosptaltreatment/assets/130281806/4a0b8018-ef26-49f3-afff-f1774775767e)

Khi chỉnh lại và bỏ check để BN được hưởng BHYT thì dòng cũ đánh dấu xóa sau đó insert 1 dòng mới cột thuphi set lại 0 nhưng cột bhyt vẫn = 0 
![image](https://github.com/dh-hos/dhg.hosptaltreatment/assets/130281806/af6db9b1-998e-41ab-a847-7cf8f0d440dc)
![image](https://github.com/dh-hos/dhg.hosptaltreatment/assets/130281806/56508901-34c6-4e69-9157-aa8b4a1ed119)

sau cùng sẽ thể hiện CLS được chỉ định theo giá BHYT nhưng không thanh
![image](https://github.com/dh-hos/dhg.hosptaltreatment/assets/130281806/9ca9e7a0-3471-46a7-9b71-13a6a705b4e6)

**Comment by gh-dh-bot-01** [comment]
###### 📣[gh-bot-dh-hos-projects-timelines] - Nhật ký thay đổi công việc hiện tại 📣 [dataUrl](https://o-dh-002-default-rtdb.asia-southeast1.firebasedatabase.app/github-com/dh-hos/webhooks/Issues/dhg-hosptaltreatment/221)

**Comment by vuongdh** [comment]
Cập nhật <b>Treat4.2024.04.17v1 </b>- vào chi tiết để tải bản cập nhật

<div align="left">

[![View](https://img.shields.io/badge/-Xem%20chi%20ti%E1%BA%BFt%20c%E1%BA%ADp%20nh%E1%BA%ADt-informational?logo=github)](https://github.com/dh-hos/dhg.hosptaltreatment/blob/main/README.md)

</div>

**Comment by nqhoa1005** [comment]
đã fix khi bỏ check TP sẽ set bhyt=1 và thuphi=0
![image](https://github.com/dh-hos/dhg.hosptaltreatment/assets/130281806/03c7ed54-e559-4335-8c22-65a0f639a29f)
![image](https://github.com/dh-hos/dhg.hosptaltreatment/assets/130281806/5b2710e1-0e59-4933-aa61-3326e8230404)
