### ISSUE TITLE
Lỗi - Hiển thị giờ trong Quá trình điều trị 

### ISSUE THREAD

**Issue by hvtuan1987** [dh-hos/dhg.hosptaltreatment#222]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.1: Phiếu ghi nhận lỗi phát sinh DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN LỖI PHÁT SINH</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Hà Văn Tuấn**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **19/04/2024**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) ``
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **Tất cả khách hàng**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `binh_dbtpct_chungnhanmien`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`](link_csdl)

###### ![chi_tiet_loi](https://img.shields.io/badge/Chi%20tiết%20lỗi%20phát%20sinh-:-blue?style=for-the-badge&logo=github)

-  ![loi_benh_nhan](https://img.shields.io/badge/Chi%20tiết%20bệnh%20nhân-:-blue?style=plastic&logo=github)
   > _**MaBN**_: `2023079967` - _**MaKB**_: `2312020054` - _**MaBA**_: `039462` _**NgayKCB**_: `19/04/2024` - _**MaPhong**_: `MaPhong` - _**MaDV**_: `43` - _**ThangKT**_: `01` - _**NamKT**_: `2024`

Khi bấm vào QT Điều trị như hình dưới
![image](https://github.com/dh-hos/dhg.hosptaltreatment/assets/97272364/d7e5aa7f-370f-403d-bc77-48abe49f0f53)
Cột ngày giờ [chổ phút bị dính ký tự i] tất cả ngày giờ y lệnh
![image](https://github.com/dh-hos/dhg.hosptaltreatment/assets/97272364/d5b90b19-c24d-4ff8-b7a2-851c89cfe4fc)

```

**Comment by gh-dh-bot-01** [comment]
###### 📣[gh-bot-dh-hos-projects-timelines] - Nhật ký thay đổi công việc hiện tại 📣 [dataUrl](https://o-dh-002-default-rtdb.asia-southeast1.firebasedatabase.app/github-com/dh-hos/webhooks/Issues/dhg-hosptaltreatment/222)
<details> <summary>   ℹ️<code>2024-19-04 08:55:58</code> <code>@hvtuan1987</code><code>projects_v2_item.created</code>   <code><code>[<a href='https://o-dh-003-default-rtdb.asia-southeast1.firebasedatabase.app/github-com/dh-hos/webhooks/Issues/-Nvo3K3PzDNP2WVroAa6'>-Nvo3K3PzDNP2WVroAa6</a>]</code></code><code>AZ</code> </summary> <code>[bot]</code><code>1.24.0321.1600@az-o-adv-more-alien-weekly-ubuntu-latest-definitionId28-1713491517853</code><code>[<a href='https://dev.azure.com/o-adv/more-alien-weekly-ubuntu-latest/_build/results?buildId=8701&view=logs'>webhook-logs</a>]</code></details>

**Comment by vuongdh** [comment]
Cập nhật <b>Treat4.2024.04.19v1 </b>- vào chi tiết để tải bản cập nhật

<div align="left">

[![View](https://img.shields.io/badge/-Xem%20chi%20ti%E1%BA%BFt%20c%E1%BA%ADp%20nh%E1%BA%ADt-informational?logo=github)](https://github.com/dh-hos/dhg.hosptaltreatment/blob/main/README.md)

</div>

**Comment by hvtuan1987** [comment]
ok rồi á anh !
![image](https://github.com/dh-hos/dhg.hosptaltreatment/assets/97272364/8dab602e-dfdd-416d-b732-1113a8a7b997)
