### ISSUE TITLE
Lỗi - Hiển thị trên phiếu 01KCB không đúng cột [Khác] khi cận lâm sàng check lấy bộ và có Check miễn phí không thanh BHYT

### ISSUE THREAD

**Issue by hvtuan1987** [dh-hos/dhg.hosptaltreatment#223]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.1: Phiếu ghi nhận lỗi phát sinh DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN LỖI PHÁT SINH</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Hà Văn Tuấn**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **26/04/2024**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `94029`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **Bệnh viện chuyên khoa Sản nhi Sowsc Trăng**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `tuan_dbsannhist_mienphi`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`](link_csdl)

###### ![chi_tiet_loi](https://img.shields.io/badge/Chi%20tiết%20lỗi%20phát%20sinh-:-blue?style=for-the-badge&logo=github)

-  ![loi_benh_nhan](https://img.shields.io/badge/Chi%20tiết%20bệnh%20nhân-:-blue?style=plastic&logo=github)
   > _**MaBN**_: `2023052340` - _**MaKB**_: `2403003256` - _**MaBA**_: `2024005044` _**NgayKCB**_: `26/04/2024` - _**MaPhong**_: `P.B - 05` - _**MaDV**_: `KD005` - _**ThangKT**_: `04` - _**NamKT**_: `2024`
-  ![loi_thuoc](https://img.shields.io/badge/Chi%20tiết%20thuốc-:-blue?style=plastic&logo=github)
   > _**KhoChan**_: `KhoChan` - _**KhoLe**_: `KhoLe` - _**MaHH**_: `MaHH` - _**SoHD**_: `SoHD` - _**NgayHD**_: `NgayHD` - _**ThangKT**_: `ThangKT` - _**NamKT**_: `NamKT`
-  ![loi_cls](https://img.shields.io/badge/Chi%20tiết%20CLS-:-blue?style=plastic&logo=github)
   > _**MaCLS**_: `HA04` - _**PhieuYC**_: `PhieuYC`
-  ![loi_bo_sung](https://img.shields.io/badge/Chi%20tiết%20bổ%20sung-:-blue?style=plastic&logo=github)
   > _**Khac**_: `Khac`

###### ![mo_ta_loi](https://img.shields.io/badge/Mô%20tả%20thông%20tin%20lỗi-:-blue?style=for-the-badge&logo=github)
Đối với những cận lâm sàng trên danh mục check miễn phí và không thanh BHYT như hình dưới thì trên bảng kê 01KCB hiển thị đúng chổ cột nguồn khác.
![image](https://github.com/dh-hos/dhg.hosptaltreatment/assets/97272364/b7b0df44-9a99-4d5c-8123-3d3a5694215f)
![image](https://github.com/dh-hos/dhg.hosptaltreatment/assets/97272364/ea569729-8e4a-4e43-b203-32a6a4d96ea6)

Đối với những cận lâm sàng trên danh mục check miễn phí và không thanh BHYT nhưng có check Lấy bộ và có cận lâm sàng con như hình dưới thì trên bảng kê 01KCB hiển thị ngay cột Người bệnh tự trả (Nên sai).
![image](https://github.com/dh-hos/dhg.hosptaltreatment/assets/97272364/958567e3-b492-4abd-986b-36be0ec4f276)
![image](https://github.com/dh-hos/dhg.hosptaltreatment/assets/97272364/df2332e6-5a10-4a28-84fd-c421ac85643c)

Bệnh viện yêu cầu những cận lâm sàng có check miễn phí, không thanh BHYT và có có check lấy bộ thì hiển thị ngay cột nguồn khác trên bảng kê 01KCB

**Comment by gh-dh-bot-00** [comment]
###### 📣[gh-bot-dh-hos-projects-timelines] - Nhật ký thay đổi công việc hiện tại 📣 [dataUrl](https://o-dh-002-default-rtdb.asia-southeast1.firebasedatabase.app/github-com/dh-hos/webhooks/Issues/dhg-hosptaltreatment/223)
<details> <summary>   ℹ️<code>2024-26-04 11:18:46</code> <code>@hvtuan1987</code><code>projects_v2_item.created</code>   <code><code>[<a href='https://o-dh-003-default-rtdb.asia-southeast1.firebasedatabase.app/github-com/dh-hos/webhooks/Issues/-NwNc8EWnvOQN06-H765'>-NwNc8EWnvOQN06-H765</a>]</code></code><code>GH</code> </summary> <code>[bot]</code><code>1.24.0321.1600@gh-dh-hos-more-alien-weekly-ubuntu-latest-gh-svr-listen-yml-1714104494189</code><code>[<a href='https://github.com/dh-hos/more-alien-weekly-ubuntu-latest/actions/runs/8842953586'>webhook-logs</a>]</code></details>

**Comment by vuongdh** [comment]
Này là yêu cầu hay lỗi vậy @hvtuan1987

**Comment by hvtuan1987** [comment]
@vuongdh Lỗi á anh Vương !

**Comment by hvtuan1987** [comment]
Vì cùng là cận lâm sàng đều là check miễn phí hết nhưng chỉ khác chổ Lấy bộ nhưng hiển thị hong đúng á

**Comment by vuongdh** [comment]
OK, anh thấy trong nội dung có để yêu cầu

**Comment by vuongdh** [comment]
@hvtuan1987 em backup dữ liệu thể hiện được như vậy gửi anh hén
![image](https://github.com/dh-hos/dhg.hosptaltreatment/assets/32563776/52bb8ed2-fd0d-4620-8e0c-b4a529f2e500)

**Comment by vuongdh** [comment]
Cập nhật <b>Treat4.2024.04.30v1 </b>- vào chi tiết để tải bản cập nhật

<div align="left">

[![View](https://img.shields.io/badge/-Xem%20chi%20ti%E1%BA%BFt%20c%E1%BA%ADp%20nh%E1%BA%ADt-informational?logo=github)](https://github.com/dh-hos/dhg.hosptaltreatment/blob/main/README.md)

</div>
@hvtuan1987 Em test lại hén

**Comment by hvtuan1987** [comment]
@vuongdh Vẫn chưa được anh Vương ơi !

**Comment by vuongdh** [comment]
Chỉ định mới, mới được nha em, chỉ định cũ ghi nhận sai dữ liệu rồi

**Comment by hvtuan1987** [comment]
Em chỉ định mới luôn á

**Comment by hvtuan1987** [comment]
@vuongdh Dạ dữ liệu trên githib này á

**Comment by vuongdh** [comment]
CLS nào luôn hén, để anh test lại thử

**Comment by hvtuan1987** [comment]
Mã cls HA04 á anh @vuongdh

**Comment by vuongdh** [comment]
Chờ fix wifi nha em, vô wifi khác (wifi tổ lập trình) thì không vô được dữ liệu máy chủ 
![image](https://github.com/dh-hos/dhg.hosptaltreatment/assets/32563776/ecc8ee63-df55-43a4-97f9-b8a11656e7b5)

**Comment by hvtuan1987** [comment]
@vuongdh dạ !

**Comment by vuongdh** [comment]
Cập nhật <b>Treat4.2024.05.02v1 </b>- vào chi tiết để tải bản cập nhật

<div align="left">

[![View](https://img.shields.io/badge/-Xem%20chi%20ti%E1%BA%BFt%20c%E1%BA%ADp%20nh%E1%BA%ADt-informational?logo=github)](https://github.com/dh-hos/dhg.hosptaltreatment/blob/main/README.md)

</div>
@hvtuan1987  test lại bảng này hén

**Comment by hvtuan1987** [comment]
ok rồi á anh @vuongdh
