### ISSUE TITLE
Lỗi - Không xem được kết quả xét nghiệm sinh hóa máu (BV Thanh Bình)

### ISSUE THREAD

**Issue by le-an-87** [dh-hos/dhg.hosptaltreatment#224]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.1: Phiếu ghi nhận lỗi phát sinh DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN LỖI PHÁT SINH</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Ân**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **07/05/2024**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `Tất cẩ`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **Tất cả**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `an_thanhbinh_kqsh_06052024`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`an_thanhbinh_kqsh_06052024`](https://gofile.me/78TQg/VzJDB7UC4)

###### ![chi_tiet_loi](https://img.shields.io/badge/Chi%20tiết%20lỗi%20phát%20sinh-:-blue?style=for-the-badge&logo=github)

-  ![loi_benh_nhan](https://img.shields.io/badge/Chi%20tiết%20bệnh%20nhân-:-blue?style=plastic&logo=github)
   > _**MaBN**_: `2024008166` - _**MaKB**_: `2405000120` - _**MaBA**_: `2024003374` _**NgayKCB**_: `30/04/2024` - _**MaDV**_: `09` - _**ThangKT**_: `05` - _**NamKT**_: `2024`
-  ![loi_cls](https://img.shields.io/badge/Chi%20tiết%20CLS-:-blue?style=plastic&logo=github)
   > _**MaCLS**_: `DI312`

###### ![mo_ta_loi](https://img.shields.io/badge/Mô%20tả%20thông%20tin%20lỗi-:-blue?style=for-the-badge&logo=github)

```
Treatment xem kết quả cls DI312 đã thực hiện rồi không được.
phần mềm hiện thì form lên rồi tự động tắt như video sau

```
![ảnh](https://github.com/dh-hos/dhg.hosptaltreatment/assets/96155021/6df47936-e721-4cba-a085-823dda8cedc8)

https://github.com/dh-hos/dhg.hosptaltreatment/assets/96155021/bc6273f7-735c-44f5-a2d3-21a6e507a2c9

**Comment by gh-dh-bot-00** [comment]
###### 📣[gh-bot-dh-hos-projects-timelines] - Nhật ký thay đổi công việc hiện tại 📣 [dataUrl](https://o-dh-002-default-rtdb.asia-southeast1.firebasedatabase.app/github-com/dh-hos/webhooks/Issues/dhg-hosptaltreatment/224)
<details> <summary>   ℹ️<code>2024-07-05 16:17:31</code> <code>@le-an-87</code><code>projects_v2_item.created</code>   <code><code>[<a href='https://o-dh-003-default-rtdb.asia-southeast1.firebasedatabase.app/github-com/dh-hos/webhooks/Issues/-NxHL-toZ7aaGpolM_x8'>-NxHL-toZ7aaGpolM_x8</a>]</code></code><code>GH</code> </summary> <code>[bot]</code><code>1.24.0321.1600@gh-dh-hos-more-alien-weekly-ubuntu-latest-gh-svr-listen-yml-1715072843371</code><code>[<a href='https://github.com/dh-hos/more-alien-weekly-ubuntu-latest/actions/runs/8982685937'>webhook-logs</a>]</code></details>

**Comment by vuongdh** [comment]
@vinh-dh xem lại chổ này dùm

**Comment by vuongdh** [comment]
![image](https://github.com/dh-hos/dhg.hosptaltreatment/assets/32563776/b64f814d-e7de-4da0-8cb7-a2d424ee5de8)

**Comment by vinh-dh** [comment]
Cập nhật lại DLL mới [tại đây](https://github.com/dh-hos/oLibraries/commit/5ca65b7cca40a899b043981cfaad3a76b9a16482) nhé!

**Comment by vuongdh** [comment]
Cập nhật <b>Treat4.2024.05.08v1 </b>- vào chi tiết để tải bản cập nhật

<div align="left">

[![View](https://img.shields.io/badge/-Xem%20chi%20ti%E1%BA%BFt%20c%E1%BA%ADp%20nh%E1%BA%ADt-informational?logo=github)](https://github.com/dh-hos/dhg.hosptaltreatment/blob/main/README.md)

</div>

**Comment by vuongdh** [comment]
@le-an-87 Em test lại hén

**Comment by le-an-87** [comment]
Đã fix!
các chức năng cơ bản khác như: thêm diễn biến, ra toa thuốc, chỉ định cls, kết thúc điều trị. hoạt động bình thường.
![ảnh](https://github.com/dh-hos/dhg.hosptaltreatment/assets/96155021/acabf418-bc94-4b6a-9be5-f2658830d6b3)
![ảnh](https://github.com/dh-hos/dhg.hosptaltreatment/assets/96155021/386b332d-d891-4ca4-804b-474858702317)
