### ISSUE TITLE
Lỗi - Bệnh có nhập CN Miễn nhưng vẫn phát sinh thu 20% (BV Ung Bướu)

### ISSUE THREAD

**Issue by le-an-87** [dh-hos/dhg.hosptaltreatment#226]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.1: Phiếu ghi nhận lỗi phát sinh DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN LỖI PHÁT SINH</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Ân**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **17/06/2024**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `Tất cả`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **Tất cả**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `an_ungbuou_cnmien_17052024`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`an_ungbuou_cnmien_17052024`](link_csdl)

###### ![chi_tiet_loi](https://img.shields.io/badge/Chi%20tiết%20lỗi%20phát%20sinh-:-blue?style=for-the-badge&logo=github)

-  ![loi_benh_nhan](https://img.shields.io/badge/Chi%20tiết%20bệnh%20nhân-:-blue?style=plastic&logo=github)
   > _**MaBN**_: `2023048308` - _**MaKB**_: `2405005459` - _**MaBA**_: `009307` _**NgayKCB**_: `17/05/2024` - _**MaPhong**_: `DV06` - _**MaDV**_: `22` - _**ThangKT**_: `05` - _**NamKT**_: `2024`

###### ![mo_ta_loi](https://img.shields.io/badge/Mô%20tả%20thông%20tin%20lỗi-:-blue?style=for-the-badge&logo=github)

```
Bệnh có nhập giấy chứng nhận miễn nhưng bảng kê 6556 vẫn hiển thị thu tiền cùng chi trả.

```
![ảnh](https://github.com/dh-hos/dhg.hosptaltreatment/assets/96155021/50fd651f-bd7f-4ae1-912b-9843058f5edc)

![ảnh](https://github.com/dh-hos/dhg.hosptaltreatment/assets/96155021/575ec04e-f685-4f9b-822a-17d731cb47d5)

**Comment by gh-dh-bot-01** [comment]
###### 📣[gh-bot-dh-hos-projects-timelines] - Nhật ký thay đổi công việc hiện tại 📣 [dataUrl](https://o-dh-002-default-rtdb.asia-southeast1.firebasedatabase.app/github-com/dh-hos/webhooks/Issues/dhg-hosptaltreatment/226)

**Comment by gh-dh-bot-01** [comment]
### 📣📣📣 Treatment.exe v.4.24.0517.0 [⬇️OneDrive](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FTreatmentexe%2F42405170-OneDrive.json) [⬇️GoogleStorage](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FTreatmentexe%2F42405170-GoogleStorage.json) [⬇️NasDHSolutions](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FTreatmentexe%2F42405170-NasDHSolutions.json)

## Nội dung thay đổi

- ✨: Yêu cầu - BV Phụ Sản CT: 1. Mẫu tự thiết kế Biên bản hội chẩn và Trích Biên bản hội chẩn trên Prescription và Treatment

Bật tham số: nt.tuthietke = 3

- ☑:https://github.com/dh-hos/To_Lap_Trinh/issues/346

- 🐛: Lỗi - Bệnh có nhập CN Miễn nhưng vẫn phát sinh thu 20% (BV Ung Bướu) #226

- ☑:https://github.com/dh-hos/dhg.hosptaltreatment/issues/226

<div align="right">

[![View](https://img.shields.io/badge/-Xem%20l%E1%BB%8Bch%20s%E1%BB%AD%20phi%C3%AAn%20b%E1%BA%A3n-informational?logo=github)](https://github.com/dh-hos-code/Treatment.exe?tab=readme-ov-file#readme) [![View](https://img.shields.io/badge/-Th%E1%BB%B1c%20hi%E1%BB%87n%20b%E1%BB%9Fi%3A%20%40vuongdh-informational?logo=github)](https://github.com/vuongdh) [![View](https://img.shields.io/badge/Nh%E1%BA%ADn%20th%C3%B4ng%20b%C3%A1o%20tr%C3%AAn%20Telegram-2CA5E0?style=flat-squeare&logo=telegram&logoColor=white)](https://t.me/dhhoscodemsifiles)
</div>

**Comment by le-an-87** [comment]
Đã fix! các thao tác cơ bản hoạt động bình thường.
![ảnh](https://github.com/dh-hos/dhg.hosptaltreatment/assets/96155021/95c5dcc5-d9bf-4772-b57e-7eef79e46f59)
![ảnh](https://github.com/dh-hos/dhg.hosptaltreatment/assets/96155021/29015dc0-4320-4db6-ae70-406daf619bd9)
![ảnh](https://github.com/dh-hos/dhg.hosptaltreatment/assets/96155021/89bf51de-ab77-4465-8b76-021a64732340)
![ảnh](https://github.com/dh-hos/dhg.hosptaltreatment/assets/96155021/8b88f931-fef5-4ccd-9dee-fc435a27bff5)

**Comment by vuongdh** [comment]
Nội dung thay đổi
✨: Yêu cầu - BV Phụ Sản CT: 1. Mẫu tự thiết kế Biên bản hội chẩn và Trích Biên bản hội chẩn trên Prescription và Treatment
Bật tham số: nt.inbienbanhc = 3 (thông tin ở trên gõ sai)
