### ISSUE TITLE
Lỗi - Toa Xuất viện thuốc Nghiện - HT không hiển thị số ngày uống

### ISSUE THREAD

**Issue by minhduc2it** [dh-hos/dhg.hosptaltreatment#227]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.1: Phiếu ghi nhận lỗi phát sinh DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN LỖI PHÁT SINH</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **ĐỨC**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **20/05/2024**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `60015`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **BV Nam Bình Thuận**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `duc_nambinhthuan_toaht`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`] https://gofile.me/78TQg/40AemqZ88

###### ![chi_tiet_loi](https://img.shields.io/badge/Chi%20tiết%20lỗi%20phát%20sinh-:-blue?style=for-the-badge&logo=github)

-  ![loi_benh_nhan](https://img.shields.io/badge/Chi%20tiết%20bệnh%20nhân-:-blue?style=plastic&logo=github)
   > _**MaBN**_: `2019001814` - _**MaKB**_: `2405005458` - _**MaBA**_: `2024006725` _**NgayKCB**_: `10/05/2024` - _ - _**MaDV**_: `22` - _**ThangKT**_: `05` - _**NamKT**_: `2024`

###### ![mo_ta_loi](https://img.shields.io/badge/Mô%20tả%20thông%20tin%20lỗi-:-blue?style=for-the-badge&logo=github)

Toa Xuất viện thuốc Nghiện - HT không hiển thị số ngày uống 
Chứng từ: N75.X24.0517.092744   Ngày lập 17/05/2024

![image](https://github.com/dh-hos/dhg.hosptaltreatment/assets/98437757/4d4b0ec2-6da8-4179-9c04-b22a7434902d)

Toa Đơn thuốc có hiển thị số ngày uống
![image](https://github.com/dh-hos/dhg.hosptaltreatment/assets/98437757/949aa67c-4935-4f10-a551-c9e8765e998d)

**Comment by gh-dh-bot-01** [comment]
###### 📣[gh-bot-dh-hos-projects-timelines] - Nhật ký thay đổi công việc hiện tại 📣 [dataUrl](https://o-dh-002-default-rtdb.asia-southeast1.firebasedatabase.app/github-com/dh-hos/webhooks/Issues/dhg-hosptaltreatment/227)

**Comment by vuongdh** [comment]
![image](https://github.com/dh-hos/dhg.hosptaltreatment/assets/32563776/961b2fe6-4e97-44f2-ac8c-b6e5dd9a8b2e)
@nghivanbi xem lại chổ này dùm hén, có truyền vô nhưng toa thuốc H không thể hiện

**Comment by ongtrieuhau-dh** [comment]
Anh @vuongdh pull mới về, cập nhật chỗ này nhé 
![image](https://github.com/dh-hos/dhg.hosptaltreatment/assets/155862740/86a45670-6f4d-41e9-a38f-fb3e9340faac)

**Comment by gh-dh-bot-01** [comment]
### 📣📣📣 Treatment.exe v.4.24.0605.2 [⬇️OneDrive](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FTreatmentexe%2F42406052-OneDrive.json) [⬇️GoogleStorage](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FTreatmentexe%2F42406052-GoogleStorage.json) [⬇️NasDHSolutions](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FTreatmentexe%2F42406052-NasDHSolutions.json)

## Nội dung thay đổi

- 🐛: Lỗi - Toa Xuất viện thuốc Nghiện - HT không hiển thị số ngày uống #227

- ☑: https://github.com/dh-hos/dhg.hosptaltreatment/issues/227

<div align="right">

 [![](https://img.shields.io/badge/-Th%E1%BB%B1c%20hi%E1%BB%87n%20b%E1%BB%9Fi%3A%20%40vuongdh-informational?logo=github)](https://github.com/vuongdh) [![](https://img.shields.io/badge/-Xem%20l%E1%BB%8Bch%20s%E1%BB%AD%20phi%C3%AAn%20b%E1%BA%A3n-informational?logo=github)](https://github.com/dh-hos-code/Treatment.exe?tab=readme-ov-file#readme) [![](https://img.shields.io/badge/Nh%E1%BA%ADn%20th%C3%B4ng%20b%C3%A1o%20tr%C3%AAn%20Telegram-2CA5E0?style=flat-squeare&logo=telegram&logoColor=white)](https://t.me/dhhoscodemsifiles)
</div>

**Comment by minhduc2it** [comment]
Đã test ok Toa Xuất viện thuốc Nghiện - HT có hiển thị số ngày uống
![image](https://github.com/dh-hos/dhg.hosptaltreatment/assets/98437757/1d983008-5a0e-4547-b749-93c57ef5a2e4)

Test các chức năng: diễn biến, chỉ định cls, cấp toa, toa xuất viện hoạt động bình thường

![image](https://github.com/dh-hos/dhg.hosptaltreatment/assets/98437757/1682e39f-455d-4e4e-b4c1-3ffa4b128142)

![image](https://github.com/dh-hos/dhg.hosptaltreatment/assets/98437757/a5a2e82a-ce5c-47a2-bb31-d51ca23c5a6d)

![image](https://github.com/dh-hos/dhg.hosptaltreatment/assets/98437757/7d93adc9-40bb-49ba-85ec-beeab1b35c53)
