### ISSUE TITLE
Lỗi - Form Khám điều trị bệnh double tên bệnh nhân khi vừa có Thông tin thẻ thứ 2 và có thêm Thông tin con

### ISSUE THREAD

**Issue by hvtuan1987** [dh-hos/dhg.hosptaltreatment#228]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.1: Phiếu ghi nhận lỗi phát sinh DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN LỖI PHÁT SINH</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Hà Văn Tuấn**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **24/05/2024**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `87044`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **Bệnh viện Quân Dân Y Đồng Tháp**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `tuan_dbquandanydt_nxt`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`](link_csdl)

###### ![chi_tiet_loi](https://img.shields.io/badge/Chi%20tiết%20lỗi%20phát%20sinh-:-blue?style=for-the-badge&logo=github)

-  ![loi_benh_nhan](https://img.shields.io/badge/Chi%20tiết%20bệnh%20nhân-:-blue?style=plastic&logo=github)
   > _**MaBN**_: `2024011109` - _**MaKB**_: `2404012902` - _**MaBA**_: `2024011109` _**NgayKCB**_: `24/05/2024` - _**MaPhong**_: `MaPhong` - _**MaDV**_: `05` - _**ThangKT**_: `05` - _**NamKT**_: `2024`
-  ![loi_thuoc](https://img.shields.io/badge/Chi%20tiết%20thuốc-:-blue?style=plastic&logo=github)

-  ![loi_bo_sung](https://img.shields.io/badge/Chi%20tiết%20bổ%20sung-:-blue?style=plastic&logo=github)
   > _**Khac**_: `Khac`

###### ![mo_ta_loi](https://img.shields.io/badge/Mô%20tả%20thông%20tin%20lỗi-:-blue?style=for-the-badge&logo=github)

Bệnh nhân có thông tin thẻ BHYT số 2 và có thêm thông tin con thì Form Khám và điều trị bệnh hiển thị tên bệnh nhân Double 
Mô tả các bước:
Bước 1: Chọn bệnh nhân  đang điều trị vào Nút  BHYT SỐ 2 lúc này nhập thông tin thẻ BH số 2 và lưu lại 
![image](https://github.com/dh-hos/dhg.hosptaltreatment/assets/97272364/b42bc978-8684-4bbb-bc20-3bc1c387a7f4)

Bước 2: Vào nút Thông tin con-> Nhập thông tin con và lưu lại lúc này Form Khám và điều trị bệnh double như hình dưới

Ghi chú (Nhập thông tin con trước hoặc Thông tin thẻ BHYT SỐ 2 trước đều bị Double như nhau nếu vùa có Thông tin con và thẻ BHYT SỐ 2 )
![image](https://github.com/dh-hos/dhg.hosptaltreatment/assets/97272364/8eb2d0fb-7687-48cc-8fbd-ed5e2f3d8ee9)

![image](https://github.com/dh-hos/dhg.hosptaltreatment/assets/97272364/b1281fc9-c8c6-401a-ae6b-708854da9234)

**Comment by gh-dh-bot-01** [comment]
###### 📣[gh-bot-dh-hos-projects-timelines] - Nhật ký thay đổi công việc hiện tại 📣 [dataUrl](https://o-dh-002-default-rtdb.asia-southeast1.firebasedatabase.app/github-com/dh-hos/webhooks/Issues/dhg-hosptaltreatment/228)

**Comment by gh-dh-bot-01** [comment]
### 📣📣📣 Treatment.exe v.4.24.0527.0 [⬇️OneDrive](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FTreatmentexe%2F42405270-OneDrive.json) [⬇️GoogleStorage](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FTreatmentexe%2F42405270-GoogleStorage.json) [⬇️NasDHSolutions](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FTreatmentexe%2F42405270-NasDHSolutions.json)

## Nội dung thay đổi

- 🐛: Lỗi - Form Khám điều trị bệnh double tên bệnh nhân khi vừa có Thông tin thẻ thứ 2 và có thêm Thông tin con #228

- ☑: https://github.com/dh-hos/dhg.hosptaltreatment/issues/228

<div align="right">

 [![](https://img.shields.io/badge/-Th%E1%BB%B1c%20hi%E1%BB%87n%20b%E1%BB%9Fi%3A%20%40vuongdh-informational?logo=github)](https://github.com/vuongdh) [![](https://img.shields.io/badge/-Xem%20l%E1%BB%8Bch%20s%E1%BB%AD%20phi%C3%AAn%20b%E1%BA%A3n-informational?logo=github)](https://github.com/dh-hos-code/Treatment.exe?tab=readme-ov-file#readme) [![](https://img.shields.io/badge/Nh%E1%BA%ADn%20th%C3%B4ng%20b%C3%A1o%20tr%C3%AAn%20Telegram-2CA5E0?style=flat-squeare&logo=telegram&logoColor=white)](https://t.me/dhhoscodemsifiles)
</div>

**Comment by hvtuan1987** [comment]
@vuongdh Vẫn còn lỗi á ! Bệnh nhân màu vàng em mới test thêm vẫn còn lỗi như cũ
![image](https://github.com/dh-hos/dhg.hosptaltreatment/assets/97272364/0b6aacf1-ab93-4718-84e6-c5af32fa6581)

**Comment by hvtuan1987** [comment]
@vuongdh Vẫn còn lỗi á ! Em mới thử thêm bệnh nhân có diễn biến màu vàng vẫn Double như cũ !
![image](https://github.com/dh-hos/dhg.hosptaltreatment/assets/97272364/2f344827-0310-49a4-8c64-6aeb8464fdea)

**Comment by vuongdh** [comment]
![image](https://github.com/dh-hos/dhg.hosptaltreatment/assets/32563776/c1553575-a197-4cd4-8e6a-04a6c0ccd6fc)
Anh xem không lỗi ta :(

**Comment by gh-dh-bot-01** [comment]
### 📣📣📣 Treatment.exe v.4.24.0527.1 [⬇️OneDrive](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FTreatmentexe%2F42405271-OneDrive.json) [⬇️GoogleStorage](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FTreatmentexe%2F42405271-GoogleStorage.json) [⬇️NasDHSolutions](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FTreatmentexe%2F42405271-NasDHSolutions.json)

## Nội dung thay đổi

- 🐛: Lỗi - Form Khám điều trị bệnh double tên bệnh nhân khi vừa có Thông tin thẻ thứ 2 và có thêm Thông tin con

- ☑: https://github.com/dh-hos/dhg.hosptaltreatment/issues/228

- ✨: Yêu cầu - BV Phụ Sản CT: 1. Mẫu tự thiết kế Biên bản hội chẩn và Trích Biên bản hội chẩn trên Prescription và Treatment

- Đổi chở chữ và margin

- ☑: https://github.com/dh-hos/To_Lap_Trinh/issues/346

<div align="right">

 [![](https://img.shields.io/badge/-Th%E1%BB%B1c%20hi%E1%BB%87n%20b%E1%BB%9Fi%3A%20%40vuongdh-informational?logo=github)](https://github.com/vuongdh) [![](https://img.shields.io/badge/-Xem%20l%E1%BB%8Bch%20s%E1%BB%AD%20phi%C3%AAn%20b%E1%BA%A3n-informational?logo=github)](https://github.com/dh-hos-code/Treatment.exe?tab=readme-ov-file#readme) [![](https://img.shields.io/badge/Nh%E1%BA%ADn%20th%C3%B4ng%20b%C3%A1o%20tr%C3%AAn%20Telegram-2CA5E0?style=flat-squeare&logo=telegram&logoColor=white)](https://t.me/dhhoscodemsifiles)
</div>

**Comment by hvtuan1987** [comment]
Lỗi Double bệnh nhân đã ok rồi á ! 
![image](https://github.com/dh-hos/dhg.hosptaltreatment/assets/97272364/06423244-c8de-4087-9443-1cc5300c78a9)
