### ISSUE TITLE
Lỗi - BBHC và trích BBHC bị mất chữ

### ISSUE THREAD

**Issue by le-an-87** [dh-hos/dhg.hosptaltreatment#23]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.1: Phiếu ghi nhận lỗi phát sinh DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN LỖI PHÁT SINH</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **ÂN**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **23/09/2023**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `92118`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **BV Phụ Sản CT**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `an_phusan_ct_bbhc_matchu`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`](link_csdl)

###### ![chi_tiet_loi](https://img.shields.io/badge/Chi%20tiết%20lỗi%20phát%20sinh-:-blue?style=for-the-badge&logo=github)

-  ![loi_benh_nhan](https://img.shields.io/badge/Chi%20tiết%20bệnh%20nhân-:-blue?style=plastic&logo=github)
   > _**MaBN**_: `2022057292` - _**MaKB**_: `2207000388` - _**MaBA**_: `008027` _**NgayKCB**_: `08/07/2022`  - _**MaDV**_: `16` - _**ThangKT**_: `07` - _**NamKT**_: `2022`

###### ![mo_ta_loi](https://img.shields.io/badge/Mô%20tả%20thông%20tin%20lỗi-:-blue?style=for-the-badge&logo=github)

```
Biên bản hội chẩn và trích biên bản hội chẩn bị mất chữ!

```
BBHC
![image](https://user-images.githubusercontent.com/96155021/191873740-1578eef3-66c8-4de6-94d5-447664d1fe09.png)

Trích BBHC
![image](https://user-images.githubusercontent.com/96155021/191874031-0a9f16cd-0a63-4776-8205-3383941bea3c.png)

**Comment by vuongdh** [comment]
@le-an-87 Bản fix lỗi [ver2022.09.23.v1](http://www.fsend.vn/download/YTuwGhHXcxS5YiBGAOpAKR2mSdhY_9Nt)

**Comment by le-an-87** [comment]
mẫu BBHC chưa được anh ơi!
![image](https://user-images.githubusercontent.com/96155021/191887241-4a075ea4-7a0c-4e2b-a3ad-d671507ffba6.png)

**Comment by vuongdh** [comment]
@le-an-87 Bản cập nhật [2022.09.23.v2](http://www.fsend.vn/download/ilxgL9fwTcfOVJPOOXqvdGIa4s50zAHv)

**Comment by le-an-87** [comment]
đã chỉnh!
