### ISSUE TITLE
Lỗi - PHIẾU THỰC HIỆN KỸ THUẬT PHỤC HỒI CHỨC NĂNG không lấy được Phòng (BV YHCT CT)

### ISSUE THREAD

**Issue by le-an-87** [dh-hos/dhg.hosptaltreatment#230]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.1: Phiếu ghi nhận lỗi phát sinh DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN LỖI PHÁT SINH</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Ân**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **05/06/2024**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `92013`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **BV YHCT TPCT**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `an_yhct_phieu_phcn_05062024`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`an_yhct_phieu_phcn_05062024`](https://gofile.me/78TQg/yqZOA5X4Y)

###### ![chi_tiet_loi](https://img.shields.io/badge/Chi%20tiết%20lỗi%20phát%20sinh-:-blue?style=for-the-badge&logo=github)

-  ![loi_benh_nhan](https://img.shields.io/badge/Chi%20tiết%20bệnh%20nhân-:-blue?style=plastic&logo=github)
   > _**MaBN**_: `2024002972` - _**MaKB**_: `2405002427` - _**MaBA**_: `2024001793` _**NgayKCB**_: `05/06/2024` - _**MaPhong**_: `A8` - _**MaDV**_: `01` - _**ThangKT**_: `06` - _**NamKT**_: `2024`

###### ![mo_ta_loi](https://img.shields.io/badge/Mô%20tả%20thông%20tin%20lỗi-:-blue?style=for-the-badge&logo=github)

```
PHIẾU THỰC HIỆN KỸ THUẬT PHỤC HỒI CHỨC NĂNG khi in không load được phòng.
- với anh cho em hỏi trường hợp bệnh chuyển nhiều khoa thì chổ đơn vị và phòng là lấy như thế nào vậy?

* Đề xuất cập nhật phiếu theo mẫu thông tư 32
* Chuyển qua mẫu tự thiết kế để tiện cho đơn vị thiết kế lại mẫu


```
![ảnh](https://github.com/dh-hos/dhg.hosptaltreatment/assets/96155021/9f810366-0712-4ba4-a07e-89c6e6f46683)
![ảnh](https://github.com/dh-hos/dhg.hosptaltreatment/assets/96155021/9ef7fe65-3ca2-42c3-a638-44f67a157c8f)

**Comment by vuongdh** [comment]
Hạn: 12/06/2024

- Hiện tại mẫu đã tự thiết kế
- Chỉ có thể lấy khoa hiện tại

**Comment by gh-dh-bot-01** [comment]
### 📣📣📣 Treatment.exe v.4.24.0611.0 [⬇️OneDrive](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FTreatmentexe%2F42406110-OneDrive.json) [⬇️GoogleStorage](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FTreatmentexe%2F42406110-GoogleStorage.json) [⬇️NasDHSolutions](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FTreatmentexe%2F42406110-NasDHSolutions.json)

## Nội dung thay đổi

✨: Yêu cầu thực hiện 4750 - Thực hiện tích hợp DLL gửi checkIn, hồ sơ #380

☑: https://github.com/dh-hos/To_Lap_Trinh/issues/380

✨: Yêu cầu - Hỗ trợ test XML của quyết định 130 #57

☑: https://github.com/dh-hos/To_Trien_Khai/issues/57

✨: Yêu cầu - Hỗ trợ test XML của quyết định 130 #20

☑: https://github.com/dh-hos/To_Ho_Tro/issues/20

🐛: Lỗi - PHIẾU THỰC HIỆN KỸ THUẬT PHỤC HỒI CHỨC NĂNG không lấy được Phòng (BV YHCT CT) #230

☑: https://github.com/dh-hos/dhg.hosptaltreatment/issues/230

<div align="right">

 [![](https://img.shields.io/badge/-Th%E1%BB%B1c%20hi%E1%BB%87n%20b%E1%BB%9Fi%3A%20%40vuongdh-informational?logo=github)](https://github.com/vuongdh) [![](https://img.shields.io/badge/-Xem%20l%E1%BB%8Bch%20s%E1%BB%AD%20phi%C3%AAn%20b%E1%BA%A3n-informational?logo=github)](https://github.com/dh-hos-code/Treatment.exe?tab=readme-ov-file#readme) [![](https://img.shields.io/badge/Nh%E1%BA%ADn%20th%C3%B4ng%20b%C3%A1o%20tr%C3%AAn%20Telegram-2CA5E0?style=flat-squeare&logo=telegram&logoColor=white)](https://t.me/dhhoscodemsifiles)
</div>

**Comment by le-an-87** [comment]
Đã load được mã phòng.
em kiểm tra không thấy para nào hiển thị tên phòng anh bổ sung thêm para tên phòng cho đơn vị tự cấu hình nhe anh @vuongdh 
![ảnh](https://github.com/dh-hos/dhg.hosptaltreatment/assets/96155021/3e873dbb-a1e3-4b70-b15d-e0de593f8594)
![ảnh](https://github.com/dh-hos/dhg.hosptaltreatment/assets/96155021/46d8d632-cef6-4578-b365-c192efcf7c2d)

**Comment by gh-dh-bot-01** [comment]
### 📣📣📣 Treatment.exe v.4.24.0611.2 [⬇️OneDrive](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FTreatmentexe%2F42406112-OneDrive.json) [⬇️GoogleStorage](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FTreatmentexe%2F42406112-GoogleStorage.json) [⬇️NasDHSolutions](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FTreatmentexe%2F42406112-NasDHSolutions.json)

## Nội dung thay đổi

🐛: Lỗi - PHIẾU THỰC HIỆN KỸ THUẬT PHỤC HỒI CHỨC NĂNG không lấy được Phòng (BV YHCT CT) #230

- Bổ sung para: tenphong

☑: https://github.com/dh-hos/dhg.hosptaltreatment/issues/230

<div align="right">

 [![](https://img.shields.io/badge/-Th%E1%BB%B1c%20hi%E1%BB%87n%20b%E1%BB%9Fi%3A%20%40vuongdh-informational?logo=github)](https://github.com/vuongdh) [![](https://img.shields.io/badge/-Xem%20l%E1%BB%8Bch%20s%E1%BB%AD%20phi%C3%AAn%20b%E1%BA%A3n-informational?logo=github)](https://github.com/dh-hos-code/Treatment.exe?tab=readme-ov-file#readme) [![](https://img.shields.io/badge/Nh%E1%BA%ADn%20th%C3%B4ng%20b%C3%A1o%20tr%C3%AAn%20Telegram-2CA5E0?style=flat-squeare&logo=telegram&logoColor=white)](https://t.me/dhhoscodemsifiles)
</div>

**Comment by le-an-87** [comment]
Đã bổ sung para phong và tenphong!
![ảnh](https://github.com/dh-hos/dhg.hosptaltreatment/assets/96155021/893142ba-2a58-4448-ab96-f019c4c74b0c)
