### ISSUE TITLE
Lỗi - Cách tính số tiền BH thanh toán và BNCCT khi bệnh nhân có miễn cùng chi trả (toa thuốc trước ngày miễn, toa trả sau ngày miễn)

### ISSUE THREAD

**Issue by chauthanhtra** [dh-hos/dhg.hosptaltreatment#231]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.1: Phiếu ghi nhận lỗi phát sinh DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN LỖI PHÁT SINH</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Châu Thanh Trà**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **2/6/2023**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `92001`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **BV Tim Mạch CT**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `tra_timmach_lechbncct_02_tongket_fees`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`](https://gofile.me/78TQg/OgjJsDqcB)

###### ![chi_tiet_loi](https://img.shields.io/badge/Chi%20tiết%20lỗi%20phát%20sinh-:-blue?style=for-the-badge&logo=github)

-  ![loi_benh_nhan](https://img.shields.io/badge/Chi%20tiết%20bệnh%20nhân-:-blue?style=plastic&logo=github)
   > _**MaBN**_: `18025645` - _**MaKB**_: `2305020097` - _**MaBA**_: `23002110` _**NgayKCB**_: `02/06/2023` - _**MaPhong**_: `MaPhong` - _**MaDV**_: `18` - _**ThangKT**_: `06` - _**NamKT**_: `2023`
-  ![loi_thuoc](https://img.shields.io/badge/Chi%20tiết%20thuốc-:-blue?style=plastic&logo=github)
   > _**KhoChan**_: `KhoChan` - _**KhoLe**_: `KhoLe` - _**MaHH**_: `G3.01.1358.22` - _**SoHD**_: `SoHD` - _**NgayHD**_: `NgayHD` - _**ThangKT**_: `ThangKT` - _**NamKT**_: `NamKT`
-  ![loi_cls](https://img.shields.io/badge/Chi%20tiết%20CLS-:-blue?style=plastic&logo=github)
   > _**MaCLS**_: `MaCLS` - _**PhieuYC**_: `PhieuYC`
-  ![loi_bo_sung](https://img.shields.io/badge/Chi%20tiết%20bổ%20sung-:-blue?style=plastic&logo=github)
   > _**Khac**_: `Khac`

###### ![mo_ta_loi](https://img.shields.io/badge/Mô%20tả%20thông%20tin%20lỗi-:-blue?style=for-the-badge&logo=github)

*Issue này ghi nhận lại tách ra từ issue: https://github.com/dh-hos/dhg.hospitalfees/issues/131
  - Issue khác Fees: https://github.com/dh-hos/dhg.hospitalfees/issues/163

Cách tính chi phí thuốc+VTYT khi bệnh nhân bệnh nhân có toa thuốc trước ngày miễn cùng chi trả nhưng có toa trả sau ngày miễn cùng chi trả
-> Treatment thống nhất cách tính chi phí trong trường hợp này với Fees, Admin, và Reports (Fees, Admin, và Reports cấn trừ số lượng trước rồi tính chi phí)

Mô tả Mo.ta.ghi.nhan.muc.huong.100.khi.ap.ngay.mien.chi.tra.-.27-02-2020 không ghi rõ trường hợp này.

- Ngày miễn chi trả: 31/05/2023

- Toa xuất : CC2.X23.0529.041946 ngày 29/05/2023 thuốc G3.01.1358.22
![ảnh](https://github.com/dh-hos/dhg.hosptaltreatment/assets/97272332/1f2ca184-2e50-4e86-96fc-c4ea8e6d6aeb)

- Toa trả : CC2.T23.0601.085729 ngày 01/06/2023 thuốc G3.01.1358.22
![ảnh](https://github.com/dh-hos/dhg.hosptaltreatment/assets/97272332/9e3bce39-1823-4217-bef5-40e846375b8f)

- Treatment tính sai số tiền BH thanh toán và bệnh nhân CCT

![ảnh](https://github.com/dh-hos/dhg.hosptaltreatment/assets/97272332/3688f1e1-c452-46b5-90b7-3ef4c65fd3e3)
![ảnh](https://github.com/dh-hos/dhg.hosptaltreatment/assets/97272332/90797eda-e79d-4abe-b5c1-669d27828e75)

**Comment by le-an-87** [comment]
alo anh @ongtrieuhau anh @vuongdh ơi coi chổ này giùm để đồng nhất giữa các module nhe mấy anh.

* hiện tại bảng kê 6556 lệch tiền so với FEES và XML

chổ này báo qua mấy git rồi mà không thống nhất được anh ơi
https://github.com/dh-hos/dhg.hospitalfees/issues/131
https://github.com/dh-hos/dhg.hospitalfees/issues/163

**Comment by ongtrieuhau-dh** [comment]
Cái này sẽ mô tả để thuốc trả cấn trừ đúng với thuốc đánh nhé

**Comment by nghivanbi** [comment]
Đã chốt thực hiện theo mô tả.

**Comment by chauthanhtra** [comment]
### **✔️KẾT QUẢ TEST**
***
https://github.com/dh-hos/To_Ho_Tro/issues/42#issuecomment-2291738187

- Fees 13/08/2024 đã tính chi phí cấn trừ thuốc trả theo mô tả Mô tả [Quy trình trả thuốc-VTYT bệnh án nội trú.md](https://github.com/dh-hos/Mo-ta-he-thong/blob/main/M%C3%B4%20t%E1%BA%A3%20Quy%20tr%C3%ACnh%20tr%E1%BA%A3%20thu%E1%BB%91c-VTYT%20b%E1%BB%87nh%20%C3%A1n%20n%E1%BB%99i%20tr%C3%BA.md#user-content-fnref-2024-06-13-968dfdfe98ce4b4fae15fb8f59abc84c)

![ảnh](https://github.com/user-attachments/assets/d97e0521-09dd-4d6b-add8-7472b3bbccee)
![ảnh](https://github.com/user-attachments/assets/031f4790-a733-4e63-84cd-7e02c8cc5604)
![ảnh](https://github.com/user-attachments/assets/ff3d097b-3fff-4d8a-bd54-14397ca692e9)
![ảnh](https://github.com/user-attachments/assets/f8ca3a90-baa7-4a06-a4f7-10ca1ebd126f)


- Admin 14/08/2024 đã tính chi phí cấn trừ thuốc trả theo mô tả Mô tả [Quy trình trả thuốc-VTYT bệnh án nội trú.md](https://github.com/dh-hos/Mo-ta-he-thong/blob/main/M%C3%B4%20t%E1%BA%A3%20Quy%20tr%C3%ACnh%20tr%E1%BA%A3%20thu%E1%BB%91c-VTYT%20b%E1%BB%87nh%20%C3%A1n%20n%E1%BB%99i%20tr%C3%BA.md#user-content-fnref-2024-06-13-968dfdfe98ce4b4fae15fb8f59abc84c)

![ảnh](https://github.com/user-attachments/assets/d44b9160-a63a-451a-8e42-50e324541037)
![ảnh](https://github.com/user-attachments/assets/68030da8-9b93-4984-aea3-3d56f8c621a0)


> Trường hợp không đủ thông tin kiểm tra hoặc còn lỗi ghi nhận phản hồi cho CO.


- Diễn giải lỗi: Reports và Treatment chưa thể hiện được chi phí thuốc cấn trừ theo số hóa đơn xuất theo Mô tả [Quy trình trả thuốc-VTYT bệnh án nội trú.md](https://github.com/dh-hos/Mo-ta-he-thong/blob/main/M%C3%B4%20t%E1%BA%A3%20Quy%20tr%C3%ACnh%20tr%E1%BA%A3%20thu%E1%BB%91c-VTYT%20b%E1%BB%87nh%20%C3%A1n%20n%E1%BB%99i%20tr%C3%BA.md#user-content-fnref-2024-06-13-968dfdfe98ce4b4fae15fb8f59abc84c)

  - Chi phí thuốc chưa tính đúng khi bệnh nhân có chứng nhận miễn
  - Thuốc CE214 Cefotaxime 1000 sau khi trả vẫn còn số lượng sau ngày miễn giảm (2 lọ) được hưởng 100% nhưng phần mềm chưa tính được 
- Data: tra_phusan_saithangquyettoan_xml4750_07_082024
- Port: 5434
- Mã BN: 2024063305
- Mã KB: 
- Mã BA: 013036
- Khoa: 11
- Phòng: 
- Ngày KCB: 
- Ngày RV: 15/08/2024
- Tháng KT: 08/2024
- Nas: https://gofile.me/78TQg/nsh4pG2OL

- Hình ảnh lỗi:

![ảnh](https://github.com/user-attachments/assets/e1b3d63d-db18-47eb-8720-b04e60f99595)
![ảnh](https://github.com/user-attachments/assets/ab9ccc03-c94e-445b-8597-473c4ace224b)
 
 - Treatment 
  
![ảnh](https://github.com/user-attachments/assets/ea0b9f95-e6fc-483b-bf0f-4d3b7533d6f1)
![ảnh](https://github.com/user-attachments/assets/2a18d472-88da-457b-a378-9d6f59519566)

  - Reports 

![ảnh](https://github.com/user-attachments/assets/e76586ef-cfe6-4c8c-a007-96d3136bf055)



> Hình ảnh Phiếu 01, 02, xuất XML.

> Nhập thuốc -> xuất thuốc -> tổng hợp.

> Hình ảnh chứng mình cho việc kiểm tra này.

> Mô tả, hướng dẫn sử dụng chức năng cập nhật (nếu có).
***
##### Phát sinh lỗi chức năng hiện tại -> Ghi nhận lỗi và ngưng test các vấn đề còn lại.

**Comment by ongtrieuhau-dh** [comment]
## HD.09 [^HD09]
-  ✔️ **Phê duyệt YC theo HD.08** 
-  👉 **Assign**: @vuongdh , @vinh-dh 
-  👉 **Thực hiện các yêu cầu theo luồng công việc này**
-  📣 **Lưu ý khi tiếp nhận**: Xem lại các thông tin lỗi hoặc xác nhận lại với nhóm HT

1. _Ghi nhận thời gian hoàn thành dự kiến, theo định dạng yyyy-MM-dd, và thời gian hoàn thành không được lớn hơn thời gian dự kiến ở HD.05_ 
2. _Trường hợp không tiếp nhận hoặc thời gian không đúng với thời gian dự kiến ở HD.05 phải nêu rõ lý do._
3. _Theo dõi vi phạm HD.04 của luồng công việc này theo_ **HD.04** [^HD04]
4. _Cập  nhật sản phẩm để giải quyết luồng công việc này, diễn giải đầy đủ chức năng mới, chỉnh sửa lỗi theo mẫu READMECODING.md khi push code, có kèm hình ảnh hoặc tài liệu xác định đã có các chức năng mới, chỉnh lỗi xong._


[^HD09]: Thời gian phải tiếp nhận ( Bình thường: 120 phút. Gấp: 60 phút), Trách nhiệm: theo dõi đến khi Close Issue
[^HD04]: Nghĩa vụ: ghi nhận đầy đủ thông tin

**Comment by vinh-dh** [comment]
Lỗi này @chauthanhtra đã báo lỗi bên [Yêu cầu thực hiện Theo mô tả - MÔ TẢ QUY TRÌNH TRẢ THUỐC/VTYT NGƯỜI BỆNH ĐIỀU TRỊ NỘI TRÚ #43](https://github.com/dh-hos/To_Ho_Tro/issues/43), anh tiếp nhận bên đó rồi.

**Comment by gh-dh-bot-01** [comment]
### 📣📣📣 Reports.exe v.3.24.0816.0 [⬇️OneDrive](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FReportsexe%2F32408160-OneDrive.json) [⬇️GoogleStorage](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FReportsexe%2F32408160-GoogleStorage.json) [⬇️NasDHSolutions](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FReportsexe%2F32408160-NasDHSolutions.json)

## Nội dung thay đổi

- 🐛: Sửa lỗi ghi nhận sai chi phí đối với thuốc nội trú có toa trả.

- ☑: https://github.com/dh-hos/To_Ho_Tro/issues/43

- ☑: https://github.com/dh-hos/dhg.hosptaltreatment/issues/231

<div align="right">

 [![](https://img.shields.io/badge/-Th%E1%BB%B1c%20hi%E1%BB%87n%20b%E1%BB%9Fi%3A%20%40vinh--dh-informational?logo=github)](https://github.com/vinh-dh) [![](https://img.shields.io/badge/-Xem%20l%E1%BB%8Bch%20s%E1%BB%AD%20phi%C3%AAn%20b%E1%BA%A3n-informational?logo=github)](https://github.com/dh-hos-code/Reports.exe?tab=readme-ov-file#readme) [![](https://img.shields.io/badge/Nh%E1%BA%ADn%20th%C3%B4ng%20b%C3%A1o%20tr%C3%AAn%20Telegram-2CA5E0?style=flat-squeare&logo=telegram&logoColor=white)](https://t.me/dhhoscodemsifiles)
</div>

**Comment by chauthanhtra** [comment]
- ✔️ Đã tiếp nhận
- ⌛ Thời gian dự kiến hoàn thành kiểm tra: '22/08/2024'.
***
- Kiểm tra chức năng BLYC theo:
o Mô tả, hướng dẫn sử dụng chức năng cập nhật (nếu có).
- Kiểm tra chức năng cơ bản của phân hệ trong qui trình khám chữa bệnh hoặc qui trình kho. Chứng minh bằng hình ảnh:
o Phiếu 01, 02, xuất XML.
o Nhập thuốc -> xuất thuốc -> tổng hợp.
o Có hình ảnh chứng mình cho việc kiểm tra này.
- File: copy sản phẩm đã kiểm thử thành công lên NAS: NAS\DuLieuCongTy\Modules -> Close Issue.
- Trường hợp không đủ thông tin kiểm tra hoặc còn lỗi ghi nhận phản hồi cho CO.

**Comment by chauthanhtra** [comment]
### **✔️KẾT QUẢ TEST**
***
Phần mềm Reports 3.24.08.22.0
***
>Lỗi, yêu cầu đã hoàn thành 
- Nội dung: Đã fix lỗi ghi nhận sai chi phí đối với thuốc nội trú có toa trả trường hợp bệnh nhân có chứng nhận miễn


- Hình ảnh: 

![ảnh](https://github.com/user-attachments/assets/c4611db6-f76c-4563-b87f-91d76338e9a5)
![ảnh](https://github.com/user-attachments/assets/e72d1eb0-7fcf-46b9-a485-85d70b055c1c)


***
> Trường hợp không đủ thông tin kiểm tra hoặc còn lỗi ghi nhận phản hồi cho CO.

>- Diễn giải lỗi:


>- Hình ảnh lỗi:



> Hình ảnh Phiếu 01, 02, xuất XML.

> Nhập thuốc -> xuất thuốc -> tổng hợp.

> Hình ảnh chứng mình cho việc kiểm tra này.

> Mô tả, hướng dẫn sử dụng chức năng cập nhật (nếu có).
***
##### Phát sinh lỗi chức năng hiện tại -> Ghi nhận lỗi và ngưng test các vấn đề còn lại.
