### ISSUE TITLE
Lỗi - Chức năng chỉnh thông tin bệnh nhân tình trạng cấp cứu (Bảng kê không hiển thị mã lý do vào viện theo mô tả mới)

### ISSUE THREAD

**Issue by le-an-87** [dh-hos/dhg.hosptaltreatment#232]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.1: Phiếu ghi nhận lỗi phát sinh DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN LỖI PHÁT SINH</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Ân**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **1706/2024**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `Tất cả`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **Tất cả**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `an_130_tohotro_issues_20`
-  [`CÁCH GHI NHẬN GIÁ TRỊ CỘT XML1.MA_LYDO_VVIEN (cột 16, bảng 1 - XML4210)`](https://github.com/dh-hos/Mo-ta-he-thong/blob/main/XML4210/Vinh%20-%20Mo%20ta%20XML4210%20-%20XML1.MA_LYDO_VVIEN.md)

###### ![chi_tiet_loi](https://img.shields.io/badge/Chi%20tiết%20lỗi%20phát%20sinh-:-blue?style=for-the-badge&logo=github)

-  ![loi_benh_nhan](https://img.shields.io/badge/Chi%20tiết%20bệnh%20nhân-:-blue?style=plastic&logo=github)
   > **NgayKCB**_: `17/06/2024` - _**MaDV**_: `15` - _**ThangKT**_: `06` - _**NamKT**_: `2024`

###### ![mo_ta_loi](https://img.shields.io/badge/Mô%20tả%20thông%20tin%20lỗi-:-blue?style=for-the-badge&logo=github)

```
Khi chỉnh trạng thái bệnh nhân cấp cứu -> Bình thường
=> Bảng kê 6556 xác định lý do vào viện không đúng theo qui định.
```
>1. Bệnh nhân trái tuyến (được hưởng như cùng tuyến) -> chỉnh cấp cứu sau đó chỉnh lại bình thường => bảng kê 6556 hiển thị sai lý do vào viện.
Trước khi chỉnh
![ảnh](https://github.com/dh-hos/dhg.hosptaltreatment/assets/96155021/61a7fdca-3e7c-480f-ab13-a617774e070a)
sau khi chỉnh
![ảnh](https://github.com/dh-hos/dhg.hosptaltreatment/assets/96155021/b50b3ac5-b2d9-413f-aa29-f5f9a5c20ef0)

>2. Bệnh nhân trạng thái cấp cứu -> Bình thường => bảng kê 6556 hiển thị sai lý do vào viện. (không xác định đúng lý do vào viện theo 627)
(bệnh nhân có mã bv đăng ký tuyến tỉnh 92004 khám tại bv tuyến huyện 87010 lý do vào viện thông tuyến)
Trước khi chỉnh
![ảnh](https://github.com/dh-hos/dhg.hosptaltreatment/assets/96155021/7a4e0ebd-b87b-49f2-bdf5-2668c4b62622)
Sau khi chỉnh
![ảnh](https://github.com/dh-hos/dhg.hosptaltreatment/assets/96155021/dfbbf0d7-7e6b-459a-9110-3226140a5682)

**Comment by vuongdh** [comment]
**Test trên bệnh nhân:** 
mabn = '2024010721'     
maba = '2024003927'     
makb = '2405008176' 

**Dữ liệu ban đầu: BN trái tuyến được hưởng như cùng tuyến, có xác nhân cư trú: psdangky.giayxacnhancutru = 1**

![image](https://github.com/dh-hos/dhg.hosptaltreatment/assets/32563776/17360bc8-6088-41ad-a6a3-c4bbd32269fa)
**--> Chỉnh xác nhận cư trú = 0**
![image](https://github.com/dh-hos/dhg.hosptaltreatment/assets/32563776/24504cf2-efa2-467e-96dd-21e4b46563f0)

**Chỉnh trạng chỉnh trạng thái sang cấp cứu:**
![image](https://github.com/dh-hos/dhg.hosptaltreatment/assets/32563776/947a839b-10ba-410f-96b4-d5d8849a6da5)

**Chỉnh trạng thái cấp cứu về bình thường:**
![image](https://github.com/dh-hos/dhg.hosptaltreatment/assets/32563776/705ebdc5-8c8e-4a6e-9386-65857de07a89)

P/s:  Xác định lý do vào viện chỉ còn áp dụng theo mô tả này: https://github.com/dh-hos/Mo-ta-he-thong/blob/main/XML4210/Vinh%20-%20Mo%20ta%20XML4210%20-%20XML1.MA_LYDO_VVIEN.md
 
Các mô tả khác không còn sử dụng.

**Comment by vuongdh** [comment]
P/s: do không chỉnh trạng thái bệnh nhân (nhóm test cung cấp) về trạng thái trái tuyến được hưởng như cùng tuyến nên test trên bn mới)

**Comment by le-an-87** [comment]
các trường hợp nội trú khi em chỉnh trạng thái cấp cứu về trạng thái bình thường.
-> bảng kê 6556 không check đúng lý do vào viện theo qui định.
em có nêu ví dụ 2 trường hợp cụ thể ở trên. anh kiểm tra giải quyết giùm em.

Trường hợp em báo không đúng anh xác nhận giùm em báo sai gì đó để em còn close git này lại.

**Comment by vuongdh** [comment]
@le-an-87 em test một trường hợp khác, và trả lại trạng thái ban đầu trước khi test dùm anh hén. 
Vì anh trả về trạng thái: Bệnh nhân trái tuyến (được hưởng như cùng tuyến) để test thì không được. nên anh phải test BN khác tương tự (Bệnh nhân trái tuyến (được hưởng như cùng tuyến) ), theo các bước em test thì không lỗi.

P/s: bn anh test anh cập nhật chứng nhận nơi cư trú bằng SQL. Các thao tác khác anh làm trên phần mềm hết

**Comment by nghivanbi** [comment]
@le-an-87, @vuongdh, @ongtrieuhau nếu các lỗi phát sinh đều thực hiện trên form trên cương vị người sử dụng không gây ra bởi các phân hệ khác --> thì thực hiện test đúng mô tả. Không hoàn thành không pass qua.

**Comment by ongtrieuhau-dh** [comment]
![image](https://i.imgur.com/DL1NeUz.png)

Anh @vuongdh lưu ý, chỗ các mô tả khác không còn sử dụng là khi áp dụng khi  **Xác định lý do vào viện trên bảng kê** thôi nhé anh, còn **các thao tác để lưu dữ liệu vẫn bình thường**. (vd, lưu thông các thông tin tuyến vẫn còn theo mô tả của 627,.....)

@le-an-87 xác định giúp 2 việc:

1. Lưu dữ liệu đúng chưa (như trước giờ không quan tâm tới mô tả này)
2. Với dữ liệu đang lưu thì lấy **Xác định lý do vào viện trên bảng kê** có đúng với mô tả chưa

**Comment by le-an-87** [comment]
> 1. Lưu dữ liệu đúng chưa (như trước giờ không quan tâm tới mô tả này)
=> chổ này không xác định được anh do này không có qui định cụ thể

> 2. Với dữ liệu đang lưu thì lấy Xác định lý do vào viện trên bảng kê có đúng với mô tả chưa
=> Hiện tại Bảng kê đã làm đúng theo mô tả mới.

**Comment by le-an-87** [comment]
Đã thống nhất lỗi dữ liệu liệu khi nhận bệnh tuyenxml = 0.
