### ISSUE TITLE
Lỗi - Khuất nội dung khi lập phiếu TT/PT

### ISSUE THREAD

**Issue by lqbinh1987** [dh-hos/dhg.hosptaltreatment#234]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.1: Phiếu ghi nhận lỗi phát sinh DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN LỖI PHÁT SINH</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Bình**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **08/07/2024**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `ALL`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **ALL**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `binh_dbthanhtri_052024042024`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`](https://gofile.me/78TQg/uMPZZgusC)

###### ![chi_tiet_loi](https://img.shields.io/badge/Chi%20tiết%20lỗi%20phát%20sinh-:-blue?style=for-the-badge&logo=github)

-  ![loi_benh_nhan](https://img.shields.io/badge/Chi%20tiết%20bệnh%20nhân-:-blue?style=plastic&logo=github)
   > _**MaBN**_: `2020007868` - _**MaKB**_: `MaKB` - _**MaBA**_: `2024003729` _**NgayKCB**_: `08/07/2024` - _**MaPhong**_: `MaPhong` - _**MaDV**_: `18` - _**ThangKT**_: `06` - _**NamKT**_: `2024`
-  ![loi_thuoc](https://img.shields.io/badge/Chi%20tiết%20thuốc-:-blue?style=plastic&logo=github)
   > _**KhoChan**_: `KhoChan` - _**KhoLe**_: `KhoLe` - _**MaHH**_: `MaHH` - _**SoHD**_: `SoHD` - _**NgayHD**_: `NgayHD` - _**ThangKT**_: `ThangKT` - _**NamKT**_: `NamKT`
-  ![loi_cls](https://img.shields.io/badge/Chi%20tiết%20CLS-:-blue?style=plastic&logo=github)
   > _**MaCLS**_: `MaCLS` - _**PhieuYC**_: `PhieuYC`
-  ![loi_bo_sung](https://img.shields.io/badge/Chi%20tiết%20bổ%20sung-:-blue?style=plastic&logo=github)
   > _**Khac**_: `Khac`

###### ![mo_ta_loi](https://img.shields.io/badge/Mô%20tả%20thông%20tin%20lỗi-:-blue?style=for-the-badge&logo=github)

Hiện tại đa số màn hình ở BV có độ phân giải chiều cao tối đa **768**, trong form lập phiếu TT/PT bị khuất nội dung chô Thêm ekip, BV không lập ekipt được => không lưu được phiếu TT/PT.
![image](https://github.com/dh-hos/dhg.hosptaltreatment/assets/99630883/67b1d65f-5f65-4072-9570-dd4339818c23)

**Comment by vuongdh** [comment]
Thông tin cần hiển thị nhiều, không thể hiển thị đủ với độ phần giải 800x600 
==> độ phân giải tối thiểu 1152 x  863
==> Đề xuất tạm thời: hide thanh taskbar

**Comment by ongtrieuhau-dh** [comment]
anh @vuongdh xem gom gọn lại, theo qui chuẩn của mình là **768** nhé a

**Comment by vuongdh** [comment]
![image](https://github.com/dh-hos/dhg.hosptaltreatment/assets/32563776/e15bc4f9-0643-4d01-849d-2ceb590ba6c1)
theo chẩn (1024x768) vẫn không đủ hiển thị

**Comment by ongtrieuhau-dh** [comment]
Gom mấy control vô chung hàng đi anh, mấy cái nào ít thì gom lại, cho đúng vào chuẩn 768

**Comment by vuongdh** [comment]
![image](https://github.com/dh-hos/dhg.hosptaltreatment/assets/32563776/919f0c6f-0c03-4f5a-be7a-078069b18561)
Đã chỉnh về chuẩn 1024 x 768 
==> Hạn 08/7/2024

**Comment by gh-dh-bot-01** [comment]
### 📣📣📣 Treatment.exe v.4.24.0708.0 [⬇️OneDrive](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FTreatmentexe%2F42407080-OneDrive.json) [⬇️GoogleStorage](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FTreatmentexe%2F42407080-GoogleStorage.json) [⬇️NasDHSolutions](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FTreatmentexe%2F42407080-NasDHSolutions.json)

## Nội dung thay đổi

- 🐛: Fix lỗi: Form chỉnh thông tin chổ nút [...] enter lên danh sách thì load theo 4750 đã ok, nhưng khi gõ viết tắt thì giá trị gõ vào ko có trong 4750 nhưng phần mềm vẫn cho enter chọn và vẫn cho lưu

- ☑: https://github.com/dh-hos/To_Lap_Trinh/issues/449

- 🐛: Fix lỗi: Lỗi - Khuất nội dung khi lập phiếu TT/PT #234

- Setup form về chuẩn: 1024x768

- ☑: https://github.com/dh-hos/dhg.hosptaltreatment/issues/234

<div align="right">

 [![](https://img.shields.io/badge/-Th%E1%BB%B1c%20hi%E1%BB%87n%20b%E1%BB%9Fi%3A%20%40vuongdh-informational?logo=github)](https://github.com/vuongdh) [![](https://img.shields.io/badge/-Xem%20l%E1%BB%8Bch%20s%E1%BB%AD%20phi%C3%AAn%20b%E1%BA%A3n-informational?logo=github)](https://github.com/dh-hos-code/Treatment.exe?tab=readme-ov-file#readme) [![](https://img.shields.io/badge/Nh%E1%BA%ADn%20th%C3%B4ng%20b%C3%A1o%20tr%C3%AAn%20Telegram-2CA5E0?style=flat-squeare&logo=telegram&logoColor=white)](https://t.me/dhhoscodemsifiles)
</div>

**Comment by lqbinh1987** [comment]
Đã fix
![image](https://github.com/dh-hos/dhg.hosptaltreatment/assets/99630883/8e1f06fe-02f8-4a09-a307-a4ad251bdf3f)
