### ISSUE TITLE
Lỗi - BN CÓ MÃ ĐKBĐ ĐĂNG KÝ ĐÚNG NƠI ĐKBĐ PHIẾU 01 CHECK SAI THÔNG TUYẾN

### ISSUE THREAD

**Issue by minhduc2it** [dh-hos/dhg.hosptaltreatment#235]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.1: Phiếu ghi nhận lỗi phát sinh DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN LỖI PHÁT SINH</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **ĐỨC**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **09/07/2024**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `92009`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **Thới Lai**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `duc_thoilai_thongtuyen`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`] https://gofile.me/78TQg/ocJMKgDhM

###### ![chi_tiet_loi](https://img.shields.io/badge/Chi%20tiết%20lỗi%20phát%20sinh-:-blue?style=for-the-badge&logo=github)

-  ![loi_benh_nhan](https://img.shields.io/badge/Chi%20tiết%20bệnh%20nhân-:-blue?style=plastic&logo=github)
   > _**MaBN**_: `2021027771` - _**MaKB**_: `2407001232` - _**MaBA**_: `2024002408` _**NgayKCB**_: `03/07/2024` - _**MaDV**_: `02` - _**ThangKT**_: `07` - _**NamKT**_: `2024`

###### ![mo_ta_loi](https://img.shields.io/badge/Mô%20tả%20thông%20tin%20lỗi-:-blue?style=for-the-badge&logo=github)

BN điều trị nội trú đúng nơi ĐKBĐ
Phiếu 01 in check Thông tuyến > Check Đúng tuyến

![image](https://github.com/dh-hos/dhg.hosptaltreatment/assets/98437757/579c2778-95c0-4f39-be91-c72a6599fa8f)

**Comment by le-an-87** [comment]
Em kiểm tra lại Treatment bảng mấy
bảng kê in có đúng theo mô tả không nhé https://github.com/dh-hos/Mo-ta-he-thong/blob/main/XML4210/Vinh%20-%20Mo%20ta%20XML4210%20-%20XML1.MA_LYDO_VVIEN.md

**Comment by minhduc2it** [comment]
Treatment bảng 4.24.0708.0
bnnoitru.tuyen = 0 và bnnoitru.mabvdk: 92009 = bnnoitru.mabvkb: 92009

![image](https://github.com/dh-hos/dhg.hosptaltreatment/assets/98437757/9a3db679-4e2b-4ba9-aed5-0f7853de74fe)

**Comment by vuongdh** [comment]
✔️ Đã tiếp nhận
⌛ Thời gian hoàn thành dự kiến: 2024-07-09

**Comment by gh-dh-bot-01** [comment]
### 📣📣📣 Treatment.exe v.4.24.0709.1 [⬇️OneDrive](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FTreatmentexe%2F42407091-OneDrive.json) [⬇️GoogleStorage](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FTreatmentexe%2F42407091-GoogleStorage.json) [⬇️NasDHSolutions](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FTreatmentexe%2F42407091-NasDHSolutions.json)

## Nội dung thay đổi

- 🐛: Fix Lỗi - BN CÓ MÃ ĐKBĐ ĐĂNG KÝ ĐÚNG NƠI ĐKBĐ PHIẾU 01 CHECK SAI THÔNG TUYẾN #235

![image](https://github.com/dh-hos/dhg.hosptaltreatment/assets/32563776/d0d0c674-5d7a-4a91-8ac2-4618b0b93966)

- ☑: https://github.com/dh-hos/dhg.hosptaltreatment/issues/235

<div align="right">

 [![](https://img.shields.io/badge/-Th%E1%BB%B1c%20hi%E1%BB%87n%20b%E1%BB%9Fi%3A%20%40vuongdh-informational?logo=github)](https://github.com/vuongdh) [![](https://img.shields.io/badge/-Xem%20l%E1%BB%8Bch%20s%E1%BB%AD%20phi%C3%AAn%20b%E1%BA%A3n-informational?logo=github)](https://github.com/dh-hos-code/Treatment.exe?tab=readme-ov-file#readme) [![](https://img.shields.io/badge/Nh%E1%BA%ADn%20th%C3%B4ng%20b%C3%A1o%20tr%C3%AAn%20Telegram-2CA5E0?style=flat-squeare&logo=telegram&logoColor=white)](https://t.me/dhhoscodemsifiles)
</div>

**Comment by minhduc2it** [comment]
Đã kiểm tra in phiếu 01 thành công
![image](https://github.com/dh-hos/dhg.hosptaltreatment/assets/98437757/900f4db5-e0c0-4e40-97d0-3932e899700b)

Các chức năng cơ bản khác: cấp toa, ra viện, in phiếu 01 chưa ghi nhận bất thường
![image](https://github.com/dh-hos/dhg.hosptaltreatment/assets/98437757/9e84c041-1473-4d81-a5ca-fad0e1ae9466)
