### ISSUE TITLE
Lỗi - Form khám và điều trị không hiển thị hết thông tin sinh hiêu (BV Thốt Nốt)

### ISSUE THREAD

**Issue by le-an-87** [dh-hos/dhg.hosptaltreatment#238]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.1: Phiếu ghi nhận lỗi phát sinh DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN LỖI PHÁT SINH</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Ân**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **09/07/2024**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `tất cả`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **Tất cả**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `an_130_tohotro_issues_20`

###### ![mo_ta_loi](https://img.shields.io/badge/Mô%20tả%20thông%20tin%20lỗi-:-blue?style=for-the-badge&logo=github)

```
From khám và điều trị không hiển thị hết sinh hiệu.

```
![ảnh](https://github.com/dh-hos/dhg.hosptaltreatment/assets/96155021/d2d0426a-210a-49ba-baa4-821fa50eef95)
![ảnh](https://github.com/dh-hos/dhg.hosptaltreatment/assets/96155021/0b8973dc-5625-430b-90d1-281426738b42)

**Comment by vuongdh** [comment]
Hiện tại đã thiết kế form dưỡi chẩn qui định 1024x768
![image](https://github.com/dh-hos/dhg.hosptaltreatment/assets/32563776/8e5cc348-ec55-4b36-b05a-57282ee43bc6)
Nhỏ hơn nữa thể hiện hết

**Comment by ongtrieuhau** [comment]
Anh phải trừ hao taskbar, tiêu đề form và status bar của form chính nữa a @vuongdh

**Comment by vuongdh** [comment]
✔️ Đã tiếp nhận
⌛ Thời gian hoàn thành dự kiến: 2024-07-11

**Comment by le-an-87** [comment]
Đã fix!
![ảnh](https://github.com/user-attachments/assets/27d1609f-409a-412c-bcff-132760b58b65)
