### ISSUE TITLE
Lỗi - Treatment chỉnh thông tin bệnh nhân trường Phường xã không lấy theo địa chỉ 4750

### ISSUE THREAD

**Issue by hvtuan1987** [dh-hos/dhg.hosptaltreatment#239]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.1: Phiếu ghi nhận lỗi phát sinh DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN LỖI PHÁT SINH</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Hà Văn Tuấn**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **10/07/2024**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `All`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **Tất cả**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `tuan_dbdalieuct_diachi`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`](https://gofile.me/78TQg/hjZHtUwdx)

###### ![chi_tiet_loi](https://img.shields.io/badge/Chi%20tiết%20lỗi%20phát%20sinh-:-blue?style=for-the-badge&logo=github)

-  ![loi_benh_nhan](https://img.shields.io/badge/Chi%20tiết%20bệnh%20nhân-:-blue?style=plastic&logo=github)
   > _**MaBN**_: `2024034785` - _**MaKB**_: `2406013101` - _**MaBA**_: `001909` _**NgayKCB**_: `NgayKCB` - _**MaPhong**_: `B5` - _**MaDV**_: `02` - _**ThangKT**_: `07` - _**NamKT**_: `2024`

- [x] 1. Form khám điều trị bệnh chọn bệnh nhân  và bấm vào dấu ... Chỉnh và chọn lại địa chỉ không lấy được địa chỉ mới 4750 và thông báo Phường xã không tồn tại như hình dưới

![image](https://github.com/dh-hos/dhg.hosptaltreatment/assets/97272364/cf5abb18-ce48-47c8-b752-a9154e0d33ef)

- [x] 2.  Form Tiện ích-> Chỉnh thông tin bệnh nhân (Chỉnh và cũng báo như hình phía trên). Treatment nên thống nhất cách hiển thị Phường xã như hình (Lấy theo chữ viết tắt hoặc theo mã xã, đề xuất lấy theo chữa viết tắt)

![image](https://github.com/dh-hos/dhg.hosptaltreatment/assets/97272364/247eea76-e701-4952-8d20-f8ad5ff67bde)

**Comment by vuongdh** [comment]
✔️ Đã tiếp nhận
⌛ Thời gian hoàn thành dự kiến: 2024-07-10

**Comment by gh-dh-bot-01** [comment]
### 📣📣📣 Treatment.exe v.4.24.0710.1 [⬇️OneDrive](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FTreatmentexe%2F42407101-OneDrive.json) [⬇️GoogleStorage](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FTreatmentexe%2F42407101-GoogleStorage.json) [⬇️NasDHSolutions](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FTreatmentexe%2F42407101-NasDHSolutions.json)

## Nội dung thay đổi

- 🐛: Fix Lỗi - Không lưu được thông tin phường xã 4750 #240

- ☑: https://github.com/dh-hos/dhg.hosptaltreatment/issues/240

- 🐛: Fix Lỗi - Treatment chỉnh thông tin bệnh nhân trường Phường xã không lấy theo địa chỉ 4750 #239

--> Đồng bộ 2 form sẽ cập nhật sau, đáp ứng chỉnh thông tin của bệnh viện trước

- ☑: https://github.com/dh-hos/dhg.hosptaltreatment/issues/239

<div align="right">

 [![](https://img.shields.io/badge/-Th%E1%BB%B1c%20hi%E1%BB%87n%20b%E1%BB%9Fi%3A%20%40vuongdh-informational?logo=github)](https://github.com/vuongdh) [![](https://img.shields.io/badge/-Xem%20l%E1%BB%8Bch%20s%E1%BB%AD%20phi%C3%AAn%20b%E1%BA%A3n-informational?logo=github)](https://github.com/dh-hos-code/Treatment.exe?tab=readme-ov-file#readme) [![](https://img.shields.io/badge/Nh%E1%BA%ADn%20th%C3%B4ng%20b%C3%A1o%20tr%C3%AAn%20Telegram-2CA5E0?style=flat-squeare&logo=telegram&logoColor=white)](https://t.me/dhhoscodemsifiles)
</div>

**Comment by hvtuan1987** [comment]
@vuongdh Hiện tại chổ yêu cầu chỉnh địa chỉ cho đồng bộ 2 form theo viết tắt khi nhập địa chỉ như hình dưới--> 
![image](https://github.com/user-attachments/assets/6a611639-be15-4494-a02d-477cf7fb31b3)
 Có gì anh bổ sung để em đóng github luôn á !

**Comment by vuongdh** [comment]
@hvtuan1987 thống nhất 2 form thì em tạo git yêu cầu nha em

**Comment by vuongdh** [comment]
Cái này ít khi sử dụng, vả lại form đã đáp ứng nhu cầu sử dụng của người dùng theo từ form. Có cần phải form này có thì form kia phải có không?

**Comment by hvtuan1987** [comment]
@vuongdh Dạ tạm thời cũng đã đáp ứng yêu cầu khi nào các đơn vị khác cần hỗ trợ em lập github !
