### ISSUE TITLE
Yêu cầu - Bổ sung chức năng lập nhanh phiếu phẫu thuật (copy nội dung phiếu đã có)

### ISSUE THREAD

**Issue by nghivanbi** [dh-hos/dhg.hosptaltreatment#24]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.2: Phiếu ghi nhận Yêu cầu mới DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN YÊU CẦU CHỨC NĂNG MỚI</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Nghị Văn Bi**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **23/09/2022**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `Tất cả`

###### ![chi_tiet_yeu_cau](https://img.shields.io/badge/Chi%20tiết%20yêu%20cầu%20-:-blue?style=for-the-badge&logo=github)

```

Gợi ý  thực hiện:
B1: chọn cls chưa lập phiếu --> Nhấn thêm.
B2: chọn phiếu phẫu thuật đã có.
B3: nhấn [Lấy lại thông tin] --> để copy nội dung cho phiếu phẫu thuật đang thêm.

```

**Comment by vuongdh** [comment]
Cập nhật chức năng lấy lại phiếu phẫu thuật thủ thuật [Treat4.221012v2](http://www.fsend.vn/download/bzU7qLxihA_PJyo4IY0rEeyKRNceXRqt)
@hvtuan1987 em test và viết hướng dẫn sử dụng luôn hén
