### ISSUE TITLE
Lỗi - Bệnh nhân chỉ có năm sinh khi in cấp lại giấy chứng sinh thì có ngày tháng sinh

### ISSUE THREAD

**Issue by chauthanhtra** [dh-hos/dhg.hosptaltreatment#243]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.1: Phiếu ghi nhận lỗi phát sinh DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN LỖI PHÁT SINH</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Châu Thanh Trà **
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **22/07/2024**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `84006`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **BV Trà Cú**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `tra_phusan_130`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`](https://gofile.me/78TQg/svNwdjUdn)

###### ![chi_tiet_loi](https://img.shields.io/badge/Chi%20tiết%20lỗi%20phát%20sinh-:-blue?style=for-the-badge&logo=github)

-  ![loi_benh_nhan](https://img.shields.io/badge/Chi%20tiết%20bệnh%20nhân-:-blue?style=plastic&logo=github)
   > _**MaBN**_: `2024034998` - _**MaKB**_: `2404019397` - _**MaBA**_: `006923` _**NgayVV**_: `28/04/2024` - _**MaPhong**_: `MaPhong` - _**MaDV**_: `11` - _**ThangKT**_: `04` - _**NamKT**_: `2024`
-  ![loi_thuoc](https://img.shields.io/badge/Chi%20tiết%20thuốc-:-blue?style=plastic&logo=github)
   > _**KhoChan**_: `KhoChan` - _**KhoLe**_: `KhoLe` - _**MaHH**_: `MaHH` - _**SoHD**_: `SoHD` - _**NgayHD**_: `NgayHD` - _**ThangKT**_: `ThangKT` - _**NamKT**_: `NamKT`
-  ![loi_cls](https://img.shields.io/badge/Chi%20tiết%20CLS-:-blue?style=plastic&logo=github)
   > _**MaCLS**_: `MaCLS` - _**PhieuYC**_: `PhieuYC`
-  ![loi_bo_sung](https://img.shields.io/badge/Chi%20tiết%20bổ%20sung-:-blue?style=plastic&logo=github)
   > _**Khac**_: `Khac`

###### ![mo_ta_loi](https://img.shields.io/badge/Mô%20tả%20thông%20tin%20lỗi-:-blue?style=for-the-badge&logo=github)

Bệnh nhân chỉ có năm sinh khi in cấp lại giấy chứng sinh thì phần mềm hiển thị có ngày tháng năm sinh (in giấy chứng sinh thì chỉ có năm sinh)

![ảnh](https://github.com/user-attachments/assets/bc786e2b-4171-4a8d-bb93-4c0af02e11cc)
![ảnh](https://github.com/user-attachments/assets/fd0c93ca-c4ea-446a-ba98-eaf48a88c261)
![ảnh](https://github.com/user-attachments/assets/055d0d8a-d166-4f0d-8e28-2d696425f669)

**Comment by vuongdh** [comment]
✔️ Đã tiếp nhận
⌛ Thời gian hoàn thành dự kiến: 2024-07-23

**Comment by gh-dh-bot-01** [comment]
### 📣📣📣 Treatment.exe v.4.24.0723.0 [⬇️OneDrive](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FTreatmentexe%2F42407230-OneDrive.json) [⬇️GoogleStorage](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FTreatmentexe%2F42407230-GoogleStorage.json) [⬇️NasDHSolutions](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FTreatmentexe%2F42407230-NasDHSolutions.json)

## Nội dung thay đổi

- 🐛: FIx lỗi - Bệnh nhân chỉ có năm sinh khi in cấp lại giấy chứng sinh thì có ngày tháng sinh #243

- ☑: https://github.com/dh-hos/dhg.hosptaltreatment/issues/243

- 🐛: FIx lỗi - IN PHIẾU CHỈ ĐỊNH CLS BÁO LỖI #244

- ☑: https://github.com/dh-hos/dhg.hosptaltreatment/issues/244

<div align="right">

 [![](https://img.shields.io/badge/-Th%E1%BB%B1c%20hi%E1%BB%87n%20b%E1%BB%9Fi%3A%20%40vuongdh-informational?logo=github)](https://github.com/vuongdh) [![](https://img.shields.io/badge/-Xem%20l%E1%BB%8Bch%20s%E1%BB%AD%20phi%C3%AAn%20b%E1%BA%A3n-informational?logo=github)](https://github.com/dh-hos-code/Treatment.exe?tab=readme-ov-file#readme) [![](https://img.shields.io/badge/Nh%E1%BA%ADn%20th%C3%B4ng%20b%C3%A1o%20tr%C3%AAn%20Telegram-2CA5E0?style=flat-squeare&logo=telegram&logoColor=white)](https://t.me/dhhoscodemsifiles)
</div>

**Comment by chauthanhtra** [comment]
> ### 📣📣📣 Treatment.exe v.4.24.0723.0 [⬇️OneDrive](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FTreatmentexe%2F42407230-OneDrive.json) [⬇️GoogleStorage](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FTreatmentexe%2F42407230-GoogleStorage.json) [⬇️NasDHSolutions](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FTreatmentexe%2F42407230-NasDHSolutions.json)
> ## Nội dung thay đổi
> 
>     * 🐛: FIx lỗi - Bệnh nhân chỉ có năm sinh khi in cấp lại giấy chứng sinh thì có ngày tháng sinh [Lỗi - Bệnh nhân chỉ có năm sinh khi in cấp lại giấy chứng sinh thì có ngày tháng sinh #243](https://github.com/dh-hos/dhg.hosptaltreatment/issues/243)
> 
>     * ☑: [Lỗi - Bệnh nhân chỉ có năm sinh khi in cấp lại giấy chứng sinh thì có ngày tháng sinh #243](https://github.com/dh-hos/dhg.hosptaltreatment/issues/243)
> 
>     * 🐛: FIx lỗi - IN PHIẾU CHỈ ĐỊNH CLS BÁO LỖI [Lỗi - IN PHIẾU CHỈ ĐỊNH CLS BÁO LỖI #244](https://github.com/dh-hos/dhg.hosptaltreatment/issues/244)
> 
>     * ☑: [Lỗi - IN PHIẾU CHỈ ĐỊNH CLS BÁO LỖI #244](https://github.com/dh-hos/dhg.hosptaltreatment/issues/244)
> 
> 
> [![](https://camo.githubusercontent.com/2d0cd3db12b7028249cdcce7eead9942abcaded16a72b6e181710651d9d326e3/68747470733a2f2f696d672e736869656c64732e696f2f62616467652f2d54682545312542422542316325323068692545312542422538376e253230622545312542422539466925334125323025343076756f6e6764682d696e666f726d6174696f6e616c3f6c6f676f3d676974687562)](https://github.com/vuongdh) [![](https://camo.githubusercontent.com/8375d1042897ab92159f8fc4de5d61a4a3b7586baa3d15442c948f68a357f76c/68747470733a2f2f696d672e736869656c64732e696f2f62616467652f2d58656d2532306c2545312542422538426368253230732545312542422541442532307068692543332541416e253230622545312542412541336e2d696e666f726d6174696f6e616c3f6c6f676f3d676974687562)](https://github.com/dh-hos-code/Treatment.exe?tab=readme-ov-file#readme) [![](https://camo.githubusercontent.com/d21df0e2392d69e70bbbda45fa7304196e57abd1cfa17878b66b0b728a485153/68747470733a2f2f696d672e736869656c64732e696f2f62616467652f4e682545312542412541446e25323074682543332542346e67253230622543332541316f25323074722543332541416e25323054656c656772616d2d3243413545303f7374796c653d666c61742d73717565617265266c6f676f3d74656c656772616d266c6f676f436f6c6f723d7768697465)](https://t.me/dhhoscodemsifiles)

Treatment mới đã fix lỗi in lại giấy chứng sinh bệnh nhân chỉ có năm sinh hiển thị ngày tháng sinh

![ảnh](https://github.com/user-attachments/assets/92df0e65-25b2-446e-becd-2c7335e385c8)
