### ISSUE TITLE
Lỗi - IN PHIẾU CHỈ ĐỊNH CLS BÁO LỖI

### ISSUE THREAD

**Issue by minhduc2it** [dh-hos/dhg.hosptaltreatment#244]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.1: Phiếu ghi nhận lỗi phát sinh DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN LỖI PHÁT SINH</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **ĐỨC**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **23/07/2024**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `92006`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **TTYT Cái Răng**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `duc_cairang_treat`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`] https://gofile.me/78TQg/lq9kMz1Ns

###### ![chi_tiet_loi](https://img.shields.io/badge/Chi%20tiết%20lỗi%20phát%20sinh-:-blue?style=for-the-badge&logo=github)

-  ![loi_benh_nhan](https://img.shields.io/badge/Chi%20tiết%20bệnh%20nhân-:-blue?style=plastic&logo=github)
   > _**MaBN**_: `2024000166` - _**MaKB**_: `2407007311` - _**MaBA**_: `2024001029` _**NgayKCB**_: `22/07/2024` - _**MaDV**_: `06` - _**ThangKT**_: `07` - _**NamKT**_: `2024`

###### ![mo_ta_loi](https://img.shields.io/badge/Mô%20tả%20thông%20tin%20lỗi-:-blue?style=for-the-badge&logo=github)

**In phiếu chỉ định CLS báo lỗi như sau:**

Phiên bản :2024.07.23.111531AM
System.Data.SyntaxErrorException: Syntax error: Missing operand after 'In' operator.
   at System.Data.ExpressionParser.Parse()
   at System.Data.DataExpression..ctor(DataTable table, String expression, Type type)
   at System.Data.DataView.set_RowFilter(String value)
   at HospitalTreatment.Forms.FrmCanLamSang.btnClick(Object sender, EventArgs e)

![image](https://github.com/user-attachments/assets/97eb290d-3000-4124-bb36-4b17baf7902f)

**Comment by vuongdh** [comment]
✔️ Đã tiếp nhận
⌛ Thời gian hoàn thành dự kiến: 2024-07-24

**Comment by gh-dh-bot-01** [comment]
### 📣📣📣 Treatment.exe v.4.24.0723.0 [⬇️OneDrive](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FTreatmentexe%2F42407230-OneDrive.json) [⬇️GoogleStorage](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FTreatmentexe%2F42407230-GoogleStorage.json) [⬇️NasDHSolutions](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FTreatmentexe%2F42407230-NasDHSolutions.json)

## Nội dung thay đổi

- 🐛: FIx lỗi - Bệnh nhân chỉ có năm sinh khi in cấp lại giấy chứng sinh thì có ngày tháng sinh #243

- ☑: https://github.com/dh-hos/dhg.hosptaltreatment/issues/243

- 🐛: FIx lỗi - IN PHIẾU CHỈ ĐỊNH CLS BÁO LỖI #244

- ☑: https://github.com/dh-hos/dhg.hosptaltreatment/issues/244

<div align="right">

 [![](https://img.shields.io/badge/-Th%E1%BB%B1c%20hi%E1%BB%87n%20b%E1%BB%9Fi%3A%20%40vuongdh-informational?logo=github)](https://github.com/vuongdh) [![](https://img.shields.io/badge/-Xem%20l%E1%BB%8Bch%20s%E1%BB%AD%20phi%C3%AAn%20b%E1%BA%A3n-informational?logo=github)](https://github.com/dh-hos-code/Treatment.exe?tab=readme-ov-file#readme) [![](https://img.shields.io/badge/Nh%E1%BA%ADn%20th%C3%B4ng%20b%C3%A1o%20tr%C3%AAn%20Telegram-2CA5E0?style=flat-squeare&logo=telegram&logoColor=white)](https://t.me/dhhoscodemsifiles)
</div>

**Comment by minhduc2it** [comment]
Đã kiểm tra In phiếu chỉ định CLS hoàn thành
![image](https://github.com/user-attachments/assets/85dc451b-372a-4607-8df3-4978b28cec94)

Các chức năng cơ bản khác: Chỉ đinh cls, Ra viện, In 01 chưa ghi nhận bất thường
![image](https://github.com/user-attachments/assets/fd656d97-4857-4abd-b307-157e724c4f0a)

![image](https://github.com/user-attachments/assets/9022e95c-a9db-42f1-85e7-00622cc80e49)

![image](https://github.com/user-attachments/assets/8163b3fa-c90a-4289-8898-0a5ddb5944f8)
