### ISSUE TITLE
Lỗi -  Treatment ghi nhận sai cột tuyen trong bảng bnnoitru khi chỉnh đối tượng

### ISSUE THREAD

**Issue by hvtuan1987** [dh-hos/dhg.hosptaltreatment#245]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.1: Phiếu ghi nhận lỗi phát sinh DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN LỖI PHÁT SINH</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Hà Văn Tuấn**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **23/07/2024**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `Tất cả`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **Tất cả**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `tuan_dbdalieuct_diachi`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`](https://gofile.me/78TQg/hjZHtUwdx)

###### ![chi_tiet_loi](https://img.shields.io/badge/Chi%20tiết%20lỗi%20phát%20sinh-:-blue?style=for-the-badge&logo=github)

-  ![loi_benh_nhan](https://img.shields.io/badge/Chi%20tiết%20bệnh%20nhân-:-blue?style=plastic&logo=github)
   > _**MaBN**_: `2024035303` - _**MaKB**_: `2407000010` - _**MaBA**_: `000003` _**NgayKCB**_: `23/07/2024` - _**MaPhong**_: `` - _**MaDV**_: `02` - _**ThangKT**_: `07` - _**NamKT**_: `2024`

Bệnh nhân ban đầu là nhập đối tượng Thu phí sau khi khám xong bác sĩ xử trí nhập viện. Bệnh nhân vào điều trị nội trú và xuất trình BHYT. Thẻ BHYT của bệnh nhân lúc này đăng ký tại tuyến xã và nhập viện tại Bệnh viện tuyến tỉnh. Khi chỉnh Đối tượng tại Treatment từ THU PHÍ sang BHYT Có hỏi bệnh nhân có giấy chuyển tuyến hoặc Cấp cứu Không. Chọn không và Treatment ghi nhận cột tuyen=0 trong bảng bnnoitru nên sai so với mô tả.
(Ghi chú: Đúng thì cột tuyen=1 tại bảng bnnoitru. )
![image](https://github.com/user-attachments/assets/ffe0acbc-09cf-4f8a-8aeb-95d38c099af0)
Hình sau khi chỉnh đối tượng
![image](https://github.com/user-attachments/assets/0ca262f0-4903-4064-a984-6e3f4fb9c1c5)

Hình ghi nhận cột tuyen trong dữ liệu
![image](https://github.com/user-attachments/assets/3db1cab9-b142-402e-a09b-ba888d83722a)

**Comment by vuongdh** [comment]
✔️ Đã tiếp nhận
⌛ Thời gian hoàn thành dự kiến: 2024-07-24

**Comment by vuongdh** [comment]
@hvtuan1987 bệnh nhân này anh thấy bình thường mà
 bệnh nhận trái tuyến được hưởng như cùng tuyến ==> tuyen = 0 và xét thêm cột tuyenxml.
![image](https://github.com/user-attachments/assets/0b204383-52b3-4c67-8a21-e5e1bc6c6b7d)

![image](https://github.com/user-attachments/assets/ea8c85e6-0d4c-4f71-9ef8-9ff406d94bb0)
Em dẫn giải 3.2 trên mô tả nào vậy? gửi lại anh chổ mô tả đó hén

**Comment by hvtuan1987** [comment]
@vuongdh Theo mô tả của trường hợp này thì cột tuyến trong bnnoitru=1 á
[https://github.com/dh-hos/Mo-ta-he-thong/blob/main/XML130/QD4570/Table%20xml130.bang00checkin%20-%20%5BPh%E1%BB%A5%20l%E1%BB%A5c%20-%20M%C3%B4%20t%E1%BA%A3%20XML130%20-%20B%E1%BB%95%20sung%20Q%C4%90%204750%5D.md](url)
Hình theo mô tả 
![image](https://github.com/user-attachments/assets/7fce6bd3-2be3-48e2-9b51-3bc667cf6440)

**Comment by vuongdh** [comment]
@hvtuan1987 có 2 vấn đề cần làm rõ:
1. Trái tuyến được hưởng như cùng tuyến: ghi nhận tuyen=0 và tuyenxml = 1 vậy đúng hay sai?
2. 3.2 là kết quả của bnnoitru.tuyen = 1 và giá trị tham số tuyenbv = 3. Chứ không phải 3.2 thì suy luận ngược lại bnnoitru.tuyen = 1
==> lên phòng code thảo luận chút nhé

**Comment by hvtuan1987** [comment]
Qua trao đổi thì xác định nguyên nhân sai do mô tả.
