### ISSUE TITLE
Lỗi - Treatment không hiển thị được nút Chuyển viện Lao khi Xử trí Không phải Chuyển viện (Đặc thù BV Phổi Đồng Tháp)

### ISSUE THREAD

**Issue by hvtuan1987** [dh-hos/dhg.hosptaltreatment#246]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.1: Phiếu ghi nhận lỗi phát sinh DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN LỖI PHÁT SINH</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Hà Văn Tuấn**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **24/07/2024**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `87114`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **Bệnh viện phổi Đồng Tháp**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `tuan_dbphoidt_khonginduoc01kcb`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`](https://gofile.me/78TQg/0b5xGa3Of)

###### ![chi_tiet_loi](https://img.shields.io/badge/Chi%20tiết%20lỗi%20phát%20sinh-:-blue?style=for-the-badge&logo=github)

-  ![loi_benh_nhan](https://img.shields.io/badge/Chi%20tiết%20bệnh%20nhân-:-blue?style=plastic&logo=github)
   > _**MaBN**_: `2024002365` - _**MaKB**_: `2407001917` - _**MaBA**_: `2024000001` _**NgayKCB**_: `24/07/2024` - _**MaPhong**_: `MaPhong` - _**MaDV**_: `03` - _**ThangKT**_: `07` - _**NamKT**_: `2024`

###### ![mo_ta_loi](https://img.shields.io/badge/Mô%20tả%20thông%20tin%20lỗi-:-blue?style=for-the-badge&logo=github)

Do đặc thù của Bệnh viện Lao Phổi Đồng Tháp khi xử trí Xuất viện và lập phiếu Chuyển viện Lao về tuyến dưới điều trị không quan tâm đến kết quả xử trí. Hiện tại Treatment phiên bản 23.07.1 đang bị ẩn nút Chuyển viện lao nếu Xử trí không phải là chuyển viện (như hình dưới)
![image](https://github.com/user-attachments/assets/a292921e-a437-4c6f-8366-f26368203c44)

Lúc trước Treament đã hỗ trợ Bệnh viện phiếu Chuyển viện Lao theo gith này

https://github.com/dh-hos/To_Lap_Trinh/issues/205
![image](https://github.com/user-attachments/assets/580cd947-1818-48fa-b375-51c8935dfc5b)

**Comment by vuongdh** [comment]
✔️ Đã tiếp nhận
⌛ Thời gian hoàn thành dự kiến: 2024-07-25

**Comment by gh-dh-bot-01** [comment]
### 📣📣📣 Treatment.exe v.4.24.0725.0 [⬇️OneDrive](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FTreatmentexe%2F42407250-OneDrive.json) [⬇️GoogleStorage](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FTreatmentexe%2F42407250-GoogleStorage.json) [⬇️NasDHSolutions](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FTreatmentexe%2F42407250-NasDHSolutions.json)

## Nội dung thay đổi

- 🐛: Fix lỗi - Treatment không hiển thị được nút Chuyển viện Lao khi Xử trí Không phải Chuyển viện (Đặc thù BV Phổi Đồng Tháp) #246

- Cập nhật: nút chuyển viện lao không phụ thuộc xử trí

- ☑: https://github.com/dh-hos/dhg.hosptaltreatment/issues/246

<div align="right">

 [![](https://img.shields.io/badge/-Th%E1%BB%B1c%20hi%E1%BB%87n%20b%E1%BB%9Fi%3A%20%40vuongdh-informational?logo=github)](https://github.com/vuongdh) [![](https://img.shields.io/badge/-Xem%20l%E1%BB%8Bch%20s%E1%BB%AD%20phi%C3%AAn%20b%E1%BA%A3n-informational?logo=github)](https://github.com/dh-hos-code/Treatment.exe?tab=readme-ov-file#readme) [![](https://img.shields.io/badge/Nh%E1%BA%ADn%20th%C3%B4ng%20b%C3%A1o%20tr%C3%AAn%20Telegram-2CA5E0?style=flat-squeare&logo=telegram&logoColor=white)](https://t.me/dhhoscodemsifiles)
</div>

**Comment by hvtuan1987** [comment]
Đã ok 
![image](https://github.com/user-attachments/assets/a4d5ac51-6dc3-4bb6-90ba-f5c499598e0b)

![image](https://github.com/user-attachments/assets/7a42a022-af49-4194-84ad-5f484b0ebcb1)
