### ISSUE TITLE
Lỗi -  Hiển thị sai giờ bắt đầu và giờ kết thúc các phiếu TT/PT đã lập

### ISSUE THREAD

**Issue by hvtuan1987** [dh-hos/dhg.hosptaltreatment#248]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.1: Phiếu ghi nhận lỗi phát sinh DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN LỖI PHÁT SINH</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Hà Văn Tuấn**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **25/07/2024**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `Tất cả`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **Tất cả**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `tuan_dbphoidt_ngaygiophauthuat`
-  ![port_csdl](https://img.shields.io/badge/Port%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `5434`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`](https://gofile.me/78TQg/71XZpWbn9)

###### ![chi_tiet_loi](https://img.shields.io/badge/Chi%20tiết%20lỗi%20phát%20sinh-:-blue?style=for-the-badge&logo=github)

-  ![loi_benh_nhan](https://img.shields.io/badge/Chi%20tiết%20bệnh%20nhân-:-blue?style=plastic&logo=github)
   > _**MaBN**_: `2024003942` - _**MaKB**_: `2406000020` - _**MaBA**_: `2024001499` _**NgayKCB**_: `NgayKCB` - _**MaPhong**_: `MaPhong` - _**MaDV**_: `05` - _**ThangKT**_: `07` - _**NamKT**_: `2024`

-  ![loi_cls](https://img.shields.io/badge/Chi%20tiết%20CLS-:-blue?style=plastic&logo=github)
   > _**MaCLS**_: `MaCLS` - _**PhieuYC**_: `PhieuYC`

###### ![mo_ta_loi](https://img.shields.io/badge/Mô%20tả%20thông%20tin%20lỗi-:-blue?style=for-the-badge&logo=github)

Tất cả các phiếu TT/PT đã lập khi vào xem lại đều hiển thị sai ngày giờ bắt đầu và ngày giờ kết thúc TT/PT
Hình em chụp trong Lập phiếu và trong dữ liệu
![image](https://github.com/user-attachments/assets/1b5a7628-8590-41da-b094-6ef4c9da5a3b)

**Comment by vuongdh** [comment]
✔️ Đã tiếp nhận
⌛ Thời gian hoàn thành dự kiến: 2024-07-29

**Comment by vuongdh** [comment]
@hvtuan1987 em xem lại mô tả lỗi gấp, anh thấy lỗi nào em cũng để gấp :D

**Comment by hvtuan1987** [comment]
@vuongdh ! Vì người dùng rà soát lại trước khi cho ra viện, thấy hiển thị sai nên không dám cho xuất viện  áh !

**Comment by vuongdh** [comment]
![image](https://github.com/user-attachments/assets/4d2b45b6-90ae-4942-aab3-18f6a5e24cea)
@hvtuan1987 em xem lại dữ liệu, anh kết nối không được

**Comment by hvtuan1987** [comment]
Em có ghi port phiá trên á
![image](https://github.com/user-attachments/assets/30adac40-f625-4ea0-88a7-05e79e9465a7)

**Comment by gh-dh-bot-01** [comment]
### 📣📣📣 Treatment.exe v.4.24.0726.0 [⬇️OneDrive](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FTreatmentexe%2F42407260-OneDrive.json) [⬇️GoogleStorage](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FTreatmentexe%2F42407260-GoogleStorage.json) [⬇️NasDHSolutions](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FTreatmentexe%2F42407260-NasDHSolutions.json)

## Nội dung thay đổi

- 🐛: Fix lỗi thể hiện, và thêm yêu cầu ghi nhận nhật ký thay đổi lại ⌛Dự kiến: 2024-07-26 #534

- Cập nhật lỗi:

![image](https://github.com/user-attachments/assets/f65b1ea5-f789-429e-84c1-492df65e18d2)

- Ghi nhật ký:

![image](https://github.com/user-attachments/assets/352573f1-7324-4efb-86b5-9f2721a3c2ea)

- ☑: https://github.com/dh-hos/To_Lap_Trinh/issues/534

- 🐛: Fix Lỗi - Hiển thị sai giờ bắt đầu và giờ kết thúc các phiếu TT/PT đã lập #248

- ☑: https://github.com/dh-hos/dhg.hosptaltreatment/issues/248

<div align="right">

 [![](https://img.shields.io/badge/-Th%E1%BB%B1c%20hi%E1%BB%87n%20b%E1%BB%9Fi%3A%20%40vuongdh-informational?logo=github)](https://github.com/vuongdh) [![](https://img.shields.io/badge/-Xem%20l%E1%BB%8Bch%20s%E1%BB%AD%20phi%C3%AAn%20b%E1%BA%A3n-informational?logo=github)](https://github.com/dh-hos-code/Treatment.exe?tab=readme-ov-file#readme) [![](https://img.shields.io/badge/Nh%E1%BA%ADn%20th%C3%B4ng%20b%C3%A1o%20tr%C3%AAn%20Telegram-2CA5E0?style=flat-squeare&logo=telegram&logoColor=white)](https://t.me/dhhoscodemsifiles)
</div>

**Comment by hvtuan1987** [comment]
Đã hiển thị đúng 
![image](https://github.com/user-attachments/assets/a9002fd2-f575-4c58-b197-884eedb15ee9)
