### ISSUE TITLE
Lỗi - Khi bấm vào nút Phẫu Thuật

### ISSUE THREAD

**Issue by hvtuan1987** [dh-hos/dhg.hosptaltreatment#250]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.1: Phiếu ghi nhận lỗi phát sinh DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN LỖI PHÁT SINH</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Hà Văn Tuấn**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **31/07/2024**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `92007`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **Bệnh viện Quận Ô Môn**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `tuan_dbomon_phauthuat`
-  ![port_csdl](https://img.shields.io/badge/Port%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `5434`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`](https://gofile.me/78TQg/J3nAH3wRP)

###### ![chi_tiet_loi](https://img.shields.io/badge/Chi%20tiết%20lỗi%20phát%20sinh-:-blue?style=for-the-badge&logo=github)

-  ![loi_benh_nhan](https://img.shields.io/badge/Chi%20tiết%20bệnh%20nhân-:-blue?style=plastic&logo=github)
   > _**MaBN**_: `2024024020` - _**MaKB**_: `2407029572` - _**MaBA**_: `2024009790` _**NgayKCB**_: `31/07/2024` - _**MaPhong**_: `21` - _**MaDV**_: `04` - _**ThangKT**_: `07` - _**NamKT**_: `2024`
   > _**MaCLS**_: `MaCLS` - _**PhieuYC**_: `PhieuYC`

Khi bấm vào nút PHẪU THUẬT xuất hiện lỗi như hình dưới 
Ghi chú: (Các bệnh nhân khác thì vào bình thường)
![image](https://github.com/user-attachments/assets/f39d8070-e403-457e-9af8-605efe161f81)

![image](https://github.com/user-attachments/assets/7ce00860-dcab-4b11-b684-18a8b759a617)

Chi tiết lỗi
See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values.
Parameter name: The MaxDate must be greater or equal than the MinDate
   at Janus.Windows.CalendarCombo.Calendar.h(DateTime )
   at Janus.Windows.CalendarCombo.CalendarCombo.set_MaxDate(DateTime value)
   at HospitalTreatment.Forms.FrmTinhHinhPhauThuat.setMaxMinDate(Int32 i)
   at HospitalTreatment.Forms.FrmTinhHinhPhauThuat.load_thongtin()
   at HospitalTreatment.Forms.FrmTinhHinhPhauThuat.FrmTinhHinhPhauThuat_Load(Object sender, EventArgs e)
   at System.Windows.Forms.Form.OnLoad(EventArgs e)
   at System.Windows.Forms.Form.OnCreateControl()
   at System.Windows.Forms.Control.CreateControl(Boolean fIgnoreVisible)
   at System.Windows.Forms.Control.CreateControl()
   at System.Windows.Forms.Control.WmShowWindow(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.Form.WmShowWindow(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

************** Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9256.0 built by: NET481REL1LAST_B
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework64/v4.0.30319/mscorlib.dll
----------------------------------------
Treatment
    Assembly Version: 4.24.730.1
    Win32 Version: 4.24.0730.1
    CodeBase: file:///C:/Program%20Files%20(x86)/DHG%20Pharma/DHG.Hospital%20Treatment/Treatment.exe
----------------------------------------
System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9251.0 built by: NET481REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
DH.HospitalLib
    Assembly Version: 1.24.503.1
    Win32 Version: 1.24.0503.1
    CodeBase: file:///C:/Program%20Files%20(x86)/DHG%20Pharma/DHG.Hospital%20Treatment/DH.HospitalLib.DLL
----------------------------------------
System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9251.0 built by: NET481REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9037.0 built by: NET481REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
HosReg.Code
    Assembly Version: 3.24.726.0
    Win32 Version: 3.24.0726.0
    CodeBase: file:///C:/Program%20Files%20(x86)/DHG%20Pharma/DHG.Hospital%20Treatment/HosReg.Code.DLL
----------------------------------------
Janus.Windows.Common.v3
    Assembly Version: 3.5.0.0
    Win32 Version: 3.5.0.22
    CodeBase: file:///C:/Program%20Files%20(x86)/DHG%20Pharma/DHG.Hospital%20Treatment/Janus.Windows.Common.v3.DLL
----------------------------------------
System.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9241.0 built by: NET481REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
Treatment.DataAccess
    Assembly Version: 4.24.729.1
    Win32 Version: 4.24.0729.1
    CodeBase: file:///C:/Program%20Files%20(x86)/DHG%20Pharma/DHG.Hospital%20Treatment/Treatment.DataAccess.DLL
----------------------------------------
DH.Common
    Assembly Version: 4.24.513.1
    Win32 Version: 4.24.0513.1
    CodeBase: file:///C:/Program%20Files%20(x86)/DHG%20Pharma/DHG.Hospital%20Treatment/DH.Common.DLL
----------------------------------------
System.Data
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9214.0 built by: NET481REL1LAST_B
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_64/System.Data/v4.0_4.0.0.0__b77a5c561934e089/System.Data.dll
----------------------------------------
System.Xml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9037.0 built by: NET481REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
Treatment.BusinessLogic
    Assembly Version: 4.24.729.1
    Win32 Version: 4.24.0729.1
    CodeBase: file:///C:/Program%20Files%20(x86)/DHG%20Pharma/DHG.Hospital%20Treatment/Treatment.BusinessLogic.DLL
----------------------------------------
LibraryApp
    Assembly Version: 4.24.715.0
    Win32 Version: 4.24.0715.0
    CodeBase: file:///C:/Program%20Files%20(x86)/DHG%20Pharma/DHG.Hospital%20Treatment/LibraryApp.DLL
----------------------------------------
Clas.Emr.Ipc
    Assembly Version: 1.1.0.0
    Win32 Version: 1.1.0.0
    CodeBase: file:///C:/Program%20Files%20(x86)/DHG%20Pharma/DHG.Hospital%20Treatment/Clas.Emr.Ipc.DLL
----------------------------------------
Npgsql
    Assembly Version: 2.2.3.0
    Win32 Version: 2.2.3
    CodeBase: file:///C:/Program%20Files%20(x86)/DHG%20Pharma/DHG.Hospital%20Treatment/Npgsql.DLL
----------------------------------------
System.Transactions
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9037.0 built by: NET481REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_64/System.Transactions/v4.0_4.0.0.0__b77a5c561934e089/System.Transactions.dll
----------------------------------------
DevExpress.Utils.v17.1
    Assembly Version: 17.1.3.0
    Win32 Version: 17.1.3.0
    CodeBase: file:///C:/Program%20Files%20(x86)/DHG%20Pharma/DHG.Hospital%20Treatment/DevExpress.Utils.v17.1.DLL
----------------------------------------

**Comment by vuongdh** [comment]
✔️ Đã tiếp nhận
⌛ Thời gian hoàn thành dự kiến: 2024-08-01

**Comment by gh-dh-bot-01** [comment]
### 📣📣📣 Treatment.exe v.4.24.0731.0 [⬇️OneDrive](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FTreatmentexe%2F42407310-OneDrive.json) [⬇️GoogleStorage](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FTreatmentexe%2F42407310-GoogleStorage.json) [⬇️NasDHSolutions](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FTreatmentexe%2F42407310-NasDHSolutions.json)

## Nội dung thay đổi

- 🐛: Fix Lỗi - Khi bấm vào nút Phẫu Thuật #250

- ☑: https://github.com/dh-hos/dhg.hosptaltreatment/issues/250

<div align="right">

 [![](https://img.shields.io/badge/-Th%E1%BB%B1c%20hi%E1%BB%87n%20b%E1%BB%9Fi%3A%20%40vuongdh-informational?logo=github)](https://github.com/vuongdh) [![](https://img.shields.io/badge/-Xem%20l%E1%BB%8Bch%20s%E1%BB%AD%20phi%C3%AAn%20b%E1%BA%A3n-informational?logo=github)](https://github.com/dh-hos-code/Treatment.exe?tab=readme-ov-file#readme) [![](https://img.shields.io/badge/Nh%E1%BA%ADn%20th%C3%B4ng%20b%C3%A1o%20tr%C3%AAn%20Telegram-2CA5E0?style=flat-squeare&logo=telegram&logoColor=white)](https://t.me/dhhoscodemsifiles)
</div>

**Comment by lqbinh1987** [comment]
Lưu ý chổ này là BN có chỉ định cls là TT/PT nhưng chưa lập phiếu thì vào form xuất hiện lỗi.
Còn BN không có chỉ định TT/PT, hoặc có định và thời có lập phiếu lun thì ko bị

**Comment by hvtuan1987** [comment]
Đã ok rồi á !
