### ISSUE TITLE
Lỗi - TRÙNG MÃ GIƯỜNG & MÃ GIƯỜNG KHÔNG CẢNH BÁO TRÙNG

### ISSUE THREAD

**Issue by minhduc2it** [dh-hos/dhg.hosptaltreatment#252]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.1: Phiếu ghi nhận lỗi phát sinh DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN LỖI PHÁT SINH</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **ĐỨC**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **05/08/2024**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `92006`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **TTYT Cái Răng**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `duc_cairang_t8`
-  ![port_csdl](https://img.shields.io/badge/Port%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `5434`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`] https://gofile.me/78TQg/7q3H7Vvvg

###### ![chi_tiet_loi](https://img.shields.io/badge/Chi%20tiết%20lỗi%20phát%20sinh-:-blue?style=for-the-badge&logo=github)

-  ![loi_benh_nhan](https://img.shields.io/badge/Chi%20tiết%20bệnh%20nhân-:-blue?style=plastic&logo=github)
   > _**MaBN**_: `2024009624` - _**MaKB**_: `2408001109` - _**MaBA**_: `2024001130` _**MaDV**_: `05` - _**ThangKT**_: `08` - _**NamKT**_: `2024`

_**MaBN**_: `2018000193` - _**MaKB**_: `2408000889` - _**MaBA**_: `2024001125` _**MaDV**_: `05` - _**ThangKT**_: `08` - _**NamKT**_: `2024`

###### ![mo_ta_loi](https://img.shields.io/badge/Mô%20tả%20thông%20tin%20lỗi-:-blue?style=for-the-badge&logo=github)

BN tên Thai chỉ định mã giường H001
BN tên Có vẫn chỉ định được mã Giường H001 
1. Phần mềm không cảnh báo trùng mà vẫn cho Lưu diễn biến
2. Bảng chỉ định mã giường không Loại trừ mã giường đã chỉ định

![image](https://github.com/user-attachments/assets/72bd1b1a-6834-4e24-b985-8757beec1d55)

 Đang sử dụng tham số nt.magiuong= 2. Khi chỉ định trùng mã giường PM không cảnh báo trùng

![image](https://github.com/user-attachments/assets/51b442f8-16dc-488c-841b-db690fc0e215)

**Comment by vuongdh** [comment]
✔️ Đã tiếp nhận
⌛ Thời gian hoàn thành dự kiến: 2024-08-06

**Comment by vuongdh** [comment]
@minhduc2it Nguyên nhân không kiểm tra giường bệnh: đơn vị đã tắt tham số congdulieuBHXH.cv4210

**Comment by vuongdh** [comment]
Để đáp ứng nhu cầu, phần mềm sẽ không kiểm tra theo tham số này nữa

**Comment by gh-dh-bot-01** [comment]
### 📣📣📣 Treatment.exe v.4.24.0806.0 [⬇️OneDrive](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FTreatmentexe%2F42408060-OneDrive.json) [⬇️GoogleStorage](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FTreatmentexe%2F42408060-GoogleStorage.json) [⬇️NasDHSolutions](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FTreatmentexe%2F42408060-NasDHSolutions.json)

## Nội dung thay đổi

- 🐛: Fix Lỗi - TRÙNG MÃ GIƯỜNG & MÃ GIƯỜNG KHÔNG CẢNH BÁO TRÙNG #252

- Cập nhật: cảnh báo/ chặn theo tham số: nt.magiuong

- ☑: https://github.com/dh-hos/dhg.hosptaltreatment/issues/252

<div align="right">

 [![](https://img.shields.io/badge/-Th%E1%BB%B1c%20hi%E1%BB%87n%20b%E1%BB%9Fi%3A%20%40vuongdh-informational?logo=github)](https://github.com/vuongdh) [![](https://img.shields.io/badge/-Xem%20l%E1%BB%8Bch%20s%E1%BB%AD%20phi%C3%AAn%20b%E1%BA%A3n-informational?logo=github)](https://github.com/dh-hos-code/Treatment.exe?tab=readme-ov-file#readme) [![](https://img.shields.io/badge/Nh%E1%BA%ADn%20th%C3%B4ng%20b%C3%A1o%20tr%C3%AAn%20Telegram-2CA5E0?style=flat-squeare&logo=telegram&logoColor=white)](https://t.me/dhhoscodemsifiles)
</div>

**Comment by minhduc2it** [comment]
Đã kiểm tra thành công

![Image](https://github.com/user-attachments/assets/1fa3f85a-12de-49e3-86ae-0b87f51b234e)

Các chức năng khác: Chỉ định CLS, thuốc, ra viện, in 01 chưa ghi nhận bất thường

![Image](https://github.com/user-attachments/assets/7d1576a8-f2f1-48c3-ae8e-4e4a34273948)

![Image](https://github.com/user-attachments/assets/96581833-6a2f-4a8c-b180-76273b0cc251)
