### ISSUE TITLE
Lỗi - Chức năng 6556 không xem được đối với BN có 2 thẻ.

### ISSUE THREAD

**Issue by lqbinh1987** [dh-hos/dhg.hosptaltreatment#255]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.1: Phiếu ghi nhận lỗi phát sinh DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN LỖI PHÁT SINH</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Bình**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **08/08/2024**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `92117`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **BV Huyết Học cần thơ**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `binh_huyethoc`
-  ![port_csdl](https://img.shields.io/badge/Port%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `5434`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`](https://gofile.me/78TQg/0T8OweKLu)

###### ![chi_tiet_loi](https://img.shields.io/badge/Chi%20tiết%20lỗi%20phát%20sinh-:-blue?style=for-the-badge&logo=github)

-  ![loi_benh_nhan](https://img.shields.io/badge/Chi%20tiết%20bệnh%20nhân-:-blue?style=plastic&logo=github)
   > _**MaBN**_: `2024004179` - _**MaKB**_: `MaKB` - _**MaBA**_: `003290` _**NgayKCB**_: `ALL` - _**MaPhong**_: `MaPhong` - _**MaDV**_: `20` - _**ThangKT**_: `08` - _**NamKT**_: `2024`
-  ![loi_thuoc](https://img.shields.io/badge/Chi%20tiết%20thuốc-:-blue?style=plastic&logo=github)
   > _**KhoChan**_: `KhoChan` - _**KhoLe**_: `KhoLe` - _**MaHH**_: `MaHH` - _**SoHD**_: `SoHD` - _**NgayHD**_: `NgayHD` - _**ThangKT**_: `ThangKT` - _**NamKT**_: `NamKT`
-  ![loi_cls](https://img.shields.io/badge/Chi%20tiết%20CLS-:-blue?style=plastic&logo=github)
   > _**MaCLS**_: `MaCLS` - _**PhieuYC**_: `PhieuYC`
-  ![loi_bo_sung](https://img.shields.io/badge/Chi%20tiết%20bổ%20sung-:-blue?style=plastic&logo=github)
   > _**Khac**_: `Khac`

###### ![mo_ta_loi](https://img.shields.io/badge/Mô%20tả%20thông%20tin%20lỗi-:-blue?style=for-the-badge&logo=github)

BN mà có thông tin thẻ BHYT thứ 2 thì khi bấm Tỏng kết theo 6556 bị lỗi như hình dưới.
Đóng lỗi thì vào được form nhưng không  load được chi phí bấm in cũng lỗi

**Chỉnh gấp dùm em vì BN đang đợi ra viện, trả về bản cũ cũng lỗi, trả về bản quá cũ thì không có các chức năng liên quan đến 4750**

![image](https://github.com/user-attachments/assets/52031008-7290-47db-a744-0c4aac774086)
![image](https://github.com/user-attachments/assets/e4b18b03-4128-47ca-b5e4-58cc178c453c)

**Comment by vuongdh** [comment]
✔️ Đã tiếp nhận
⌛ Thời gian hoàn thành dự kiến: 2024-08-08

**Comment by vuongdh** [comment]
@lqbinh1987 Hỗ trợ nhập bnnoitru.ngaytachthe vô nha em. BN có thẻ 2 mà ngày tách thẻ bị null --> Lỗi. Test dùm anh xem sao bỏ trống được ngày này luôn hén.

**Comment by vuongdh** [comment]
@lqbinh1987 Hướng dẫn người dùng nhập ngày tách thẻ trên Bảo Hiểm 2 là được

**Comment by lqbinh1987** [comment]
Tạm thời đã giải quyết đc, để e test lại xem lý do tại sao nó lại mất ngày tách thẻ.
![image](https://github.com/user-attachments/assets/78df5fbf-dd09-4e89-bdb3-3b433dc0a5d4)
