### ISSUE TITLE
Lỗi - Bảng kê 6556 in sai lý do vào viện đối với bệnh nhân có nhập khu vực sinh sống K2 (BV QDY ST)

### ISSUE THREAD

**Issue by le-an-87** [dh-hos/dhg.hosptaltreatment#256]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.1: Phiếu ghi nhận lỗi phát sinh DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN LỖI PHÁT SINH</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Ân**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **09/08/2024**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `Tất cả`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **Tất cả**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `an_qdyst_k2_09082024`
-  ![port_csdl](https://img.shields.io/badge/Port%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `5434`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`an_qdyst_k2_09082024`](https://gofile.me/78TQg/GlZbVRlyl)

###### ![chi_tiet_loi](https://img.shields.io/badge/Chi%20tiết%20lỗi%20phát%20sinh-:-blue?style=for-the-badge&logo=github)

-  ![loi_benh_nhan](https://img.shields.io/badge/Chi%20tiết%20bệnh%20nhân-:-blue?style=plastic&logo=github)
   > _**MaBN**_: `2024035016` - _**MaKB**_: `2407024488` - _**MaBA**_: `2024005118` _**NgayKCB**_: `09/08/2024` - _**MaPhong**_: `0402` - _**MaDV**_: `04` - _**ThangKT**_: `08` - _**NamKT**_: `2024`

###### ![mo_ta_loi](https://img.shields.io/badge/Mô%20tả%20thông%20tin%20lỗi-:-blue?style=for-the-badge&logo=github)

```
Bệnh nhân có nhập thông tin khu vực sinh sống K2
-> lý do vào viện bảng kê 6556 in check vào bệnh nhân trái tuyến
```
![ảnh](https://github.com/user-attachments/assets/b67bb4d9-9168-4e85-928d-73a48b0aa21f)
![ảnh](https://github.com/user-attachments/assets/3d2015bf-c60f-42e6-b617-5be7e80f8e5c)

**Comment by vuongdh** [comment]
✔️ Đã tiếp nhận
⌛ Thời gian hoàn thành dự kiến: 2024-08-12

**Comment by vuongdh** [comment]
Sau khi kiểm tra dữ liệu ==> Số liệu ngoại trú đưa vào không đúng.

**Comment by vuongdh** [comment]
![image](https://github.com/user-attachments/assets/e83a5c96-87cc-4fd7-8c8b-89302486cdca)
Số liệu từ ngoài trú chuyển vào nội trú

**Comment by vuongdh** [comment]
![image](https://github.com/user-attachments/assets/ed285d2a-4d42-410c-8480-632561a5cb9d)
Dữ liệu sau khi chỉnh đối tượng

**Comment by le-an-87** [comment]
anh làm đúng theo mô tả nhe.

**Comment by vuongdh** [comment]
Theo số liệu ngoại trú chuyển vào --> phiếu 6556 check trái tuyến là đúng theo mô tả
![image](https://github.com/user-attachments/assets/54c5e848-ea12-4426-97b9-64b1f1c085eb)

**Comment by le-an-87** [comment]
> Theo số liệu ngoại trú chuyển vào --> phiếu 6556 check trái tuyến là đúng theo mô tả ![image](https://private-user-images.githubusercontent.com/32563776/356522848-54c5e848-ea12-4426-97b9-64b1f1c085eb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMxOTIzODIsIm5iZiI6MTcyMzE5MjA4MiwicGF0aCI6Ii8zMjU2Mzc3Ni8zNTY1MjI4NDgtNTRjNWU4NDgtZWExMi00NDI2LTk3YjktNjRiMWYxYzA4NWViLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODA5VDA4MjgwMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJlYzk0Y2YyOGVmYjJiZWRhZjQyY2ZjMThlNWI4MDcxNTczMWFjODk3YmIxMDc2YWZmZDlkYmJiZTEzOWJlMGUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.nm19DrxFWdDzOOM2b1tc6Gt1bo_1EpEBYpel9fGA21o)

mô tả không có trường hợp này. anh @ongtrieuhau  giải quyết chổ này giùm em nhe!

**Comment by ongtrieuhau-dh** [comment]
## HD.09 [^HD09]
-  ✔️ **Phê duyệt YC theo HD.08** 
-  👉 **Assign**: @vuongdh , @lequocthong29 
-  👉 **Thực hiện các yêu cầu theo luồng công việc này**
-  📣 **Lưu ý khi tiếp nhận**: Anh Vương hỗ trợ Thống tìm nguyên nhân và chỉnh lỗi này luôn

1. _Ghi nhận thời gian hoàn thành dự kiến, theo định dạng yyyy-MM-dd, và thời gian hoàn thành không được lớn hơn thời gian dự kiến ở HD.05_ 
2. _Trường hợp không tiếp nhận hoặc thời gian không đúng với thời gian dự kiến ở HD.05 phải nêu rõ lý do._
3. _Theo dõi vi phạm HD.04 của luồng công việc này theo_ **HD.04** [^HD04]
4. _Cập  nhật sản phẩm để giải quyết luồng công việc này, diễn giải đầy đủ chức năng mới, chỉnh sửa lỗi theo mẫu READMECODING.md khi push code, có kèm hình ảnh hoặc tài liệu xác định đã có các chức năng mới, chỉnh lỗi xong._


[^HD09]: Thời gian phải tiếp nhận ( Bình thường: 120 phút. Gấp: 60 phút), Trách nhiệm: theo dõi đến khi Close Issue
[^HD04]: Nghĩa vụ: ghi nhận đầy đủ thông tin

**Comment by vuongdh** [comment]
✔️ Đã tiếp nhận
👉 Thực hiện: Thực hiện các yêu cầu theo luồng công việc này.
📆 Thời gian hoàn thành : 2024-08-14

**Comment by lequocthong29** [comment]
Đã check lại trên phiên bản Prescription v.3.24.0812.2 - số liệu ngoại trú đưa vào là đúng.
![image](https://github.com/user-attachments/assets/68833bd7-47e6-4f57-97fd-c3703b7e4357)

**Comment by le-an-87** [comment]
### **Đề nghị cung cấp thêm thông tin xử lý**
- Yêu cầu cung cấp thông tin: Bảng kê 6556 Treatment khi dữ liệu xảy ra trường hợp này thì sẽ in lý do vào viện thế nào?

**Comment by ongtrieuhau-dh** [comment]
### ✅ TỔ LẬP TRÌNH - HOÀN THÀNH ✅
-  📣 **Nhờ kiểm tra sản phẩm**: @le-an-87 
- 📢👉 Nhờ hướng dẫn khách hàng chỉnh đối tượng bệnh nhân này lại để fix lỗi cụ thể trường hợp này. ![](https://i.imgur.com/wUdzxg0.png)
---
### 💼  TỔ LẬP TRÌNH - NHỜ KIỂM THỬ THÊM CHỨC NĂNG, LỖI 💼 
- 📣 Bản mới tổ CODE đã kiểm thử không bị tình trạng này. Nhờ @le-an-87  kiểm thử xem bản mới lại có bị giống tình trạng này hông. ![](https://i.imgur.com/JTxUK2s.png)

**Comment by ongtrieuhau-dh** [comment]
### ✅ TỔ LẬP TRÌNH - HOÀN THÀNH ✅
-  📣 **Nhờ kiểm tra sản phẩm**: @le-an-87 @nghivanbi

**Comment by le-an-87** [comment]
### **HoànThành**
✔️ isssude không có sẳn phẩm để kiểm tra.
✔️Đã hỗ trợ chỉnh cho khách hàng
***
