### ISSUE TITLE
Lỗi - Không lập được phiếu thủ thuật cho Thông tin con (BV Phụ Sản)

### ISSUE THREAD

**Issue by le-an-87** [dh-hos/dhg.hosptaltreatment#258]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.1: Phiếu ghi nhận lỗi phát sinh DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN LỖI PHÁT SINH</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Ân**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **14/08/2024**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `Tất cả`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **tất cả**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `an_phusan_laptt_14082024`
-  ![port_csdl](https://img.shields.io/badge/Port%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `5434`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`an_phusan_laptt_14082024`](https://gofile.me/78TQg/VRyyDZNIC)

###### ![chi_tiet_loi](https://img.shields.io/badge/Chi%20tiết%20lỗi%20phát%20sinh-:-blue?style=for-the-badge&logo=github)

-  ![loi_benh_nhan](https://img.shields.io/badge/Chi%20tiết%20bệnh%20nhân-:-blue?style=plastic&logo=github)
   > _**MaBN**_: `2024064929` - _**MaKB**_: `2408006547` - _**MaBA**_: `013380` _**NgayKCB**_: `10/08/2024 5:40:00 CH` - _**MaPhong**_: `MaPhong` - _**MaDV**_: `25` - _**ThangKT**_: `08` - _**NamKT**_: `2024`

-  ![loi_cls](https://img.shields.io/badge/Chi%20tiết%20CLS-:-blue?style=plastic&logo=github)
   > _**MaCLS**_: `CH282` - _**PhieuYC**_: `Phiếu thủ thuật`
-  ![loi_bo_sung](https://img.shields.io/badge/Chi%20tiết%20bổ%20sung-:-blue?style=plastic&logo=github)
   > _**Khac**_: `Khac`

###### ![mo_ta_loi](https://img.shields.io/badge/Mô%20tả%20thông%20tin%20lỗi-:-blue?style=for-the-badge&logo=github)

```
Thông tin con có chỉ định cls thủ thuật CH282
-> vào phẫu thuật không load được cls để lập phiếu

```
![ảnh](https://github.com/user-attachments/assets/d46fbfa5-181e-41dc-b068-a647440dd313)

![ảnh](https://github.com/user-attachments/assets/d4e66d25-4dda-40fe-9c0f-801b4a3d42fe)
![ảnh](https://github.com/user-attachments/assets/8312c56f-90e6-44ea-ae29-94f8981f463f)

**Comment by vuongdh** [comment]
✔️ Đã tiếp nhận
⌛ Thời gian hoàn thành dự kiến: 2024-08-19

**Comment by gh-dh-bot-01** [comment]
### 📣📣📣 Treatment.exe v.4.24.0814.0 [⬇️OneDrive](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FTreatmentexe%2F42408140-OneDrive.json) [⬇️GoogleStorage](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FTreatmentexe%2F42408140-GoogleStorage.json) [⬇️NasDHSolutions](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FTreatmentexe%2F42408140-NasDHSolutions.json)

## Nội dung thay đổi

- ✨: Yêu cầu - EKIP PT/TT CHỈ LOAD NHÂN VIÊN CÓ CHỨNG CHỈ HÀNH NGHỀ #583

- ✨: Thực hiện theo mô tả bổ sung tham số để thêm tùy chọn áp dụng #597

- Bổ sung tham số: ekip.pttt

Ê kíp phẫu thuật thủ thuật chỉ hiển thị nhân viên có chứng chỉ hành nghề

Giá trị:

- 0 (hoặc null): Không áp dụng (hiển thị tất cả)

- 1: Áp dụng (chỉ hiển thị nhân viên có chứng chỉ hành nghề)

- Test với 2 nhân viên: 1 có CCHN và 1 không có (database: tra_phusan_saidiachi_12082024)

![image](https://github.com/user-attachments/assets/ef354fe7-e1cd-40ac-ba2d-6b1ae538c092)

- Khi ekip.pttt = 0:

![image](https://github.com/user-attachments/assets/b45107cb-fe8d-4238-a1cd-83d2ee058fbf)

![image](https://github.com/user-attachments/assets/c0fe2430-eba3-4f16-8d5c-de8313e21d94)

- Khi ekip.pttt = 1:

![image](https://github.com/user-attachments/assets/351cbe7e-1ccd-4980-8632-b6ce7dd6eb9f)

- ☑: https://github.com/dh-hos/To_Lap_Trinh/issues/583

- ☑: https://github.com/dh-hos/To_Lap_Trinh/issues/597

- 🐛: Fix lỗi - Không lập được phiếu thủ thuật cho Thông tin con (BV Phụ Sản) #258

![image](https://github.com/user-attachments/assets/3629a837-929e-45c1-bcfb-308e97333568)

- ☑: https://github.com/dh-hos/dhg.hosptaltreatment/issues/258

<div align="right">

 [![](https://img.shields.io/badge/-Th%E1%BB%B1c%20hi%E1%BB%87n%20b%E1%BB%9Fi%3A%20%40vuongdh-informational?logo=github)](https://github.com/vuongdh) [![](https://img.shields.io/badge/-Xem%20l%E1%BB%8Bch%20s%E1%BB%AD%20phi%C3%AAn%20b%E1%BA%A3n-informational?logo=github)](https://github.com/dh-hos-code/Treatment.exe?tab=readme-ov-file#readme) [![](https://img.shields.io/badge/Nh%E1%BA%ADn%20th%C3%B4ng%20b%C3%A1o%20tr%C3%AAn%20Telegram-2CA5E0?style=flat-squeare&logo=telegram&logoColor=white)](https://t.me/dhhoscodemsifiles)
</div>

**Comment by le-an-87** [comment]
### **✔️KẾT QUẢ TEST**
***
> Hình ảnh Phiếu 01, 02, xuất XML.
![ảnh](https://github.com/user-attachments/assets/df25d3ae-e8c5-4570-9d40-6810425cec38)

> Nhập thuốc -> xuất thuốc -> tổng hợp.

> Hình ảnh chứng mình cho việc kiểm tra này.
![ảnh](https://github.com/user-attachments/assets/9bf1a471-57bd-48f7-bc75-a0da3213e755)
![ảnh](https://github.com/user-attachments/assets/3c79c8ae-5acb-44e0-9204-5788abe6a34f)

> Mô tả, hướng dẫn sử dụng chức năng cập nhật (nếu có).
***
##### Phát sinh lỗi chức năng hiện tại -> Ghi nhận lỗi và ngưng test các vấn đề còn lại.

**Comment by le-an-87** [comment]
### **HoànThành**
✔️Hoàn thành kiểm tra
✔️Kết quả kiểm tra đạt yêu cầu
***
- Tiến hành hỗ trợ khách hàng.
