### ISSUE TITLE
Lỗi - CHƯA RÀNG BUỘC NGÀY KẾT QUẢ CỦA GIƯỜNG BỆNH PHẢI LỚN HƠN NGÀY CHỈ ĐỊNH

### ISSUE THREAD

**Issue by nqhoa1005** [dh-hos/dhg.hosptaltreatment#259]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.1: Phiếu ghi nhận lỗi phát sinh DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN LỖI PHÁT SINH</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **NGUYỄN QUỐC HOÀ**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **20/08/2024**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `94006`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **BVĐK H.THẠNH TRỊ**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `hoa_thanhtri_full`
-  ![port_csdl](https://img.shields.io/badge/Port%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `5434`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`](https://gofile.me/78TQg/yfpljkdQ4)

###### ![chi_tiet_loi](https://img.shields.io/badge/Chi%20tiết%20lỗi%20phát%20sinh-:-blue?style=for-the-badge&logo=github)

-  ![loi_benh_nhan](https://img.shields.io/badge/Chi%20tiết%20bệnh%20nhân-:-blue?style=plastic&logo=github)
   > _**MaBN**_: `MaBN` - _**MaKB**_: `MaKB` - _**MaBA**_: `MaBA` _**NgayKCB**_: `NgayKCB` - _**MaPhong**_: `MaPhong` - _**MaDV**_: `MaDV` - _**ThangKT**_: `ThangKT` - _**NamKT**_: `NamKT`
-  ![loi_thuoc](https://img.shields.io/badge/Chi%20tiết%20thuốc-:-blue?style=plastic&logo=github)
   > _**KhoChan**_: `KhoChan` - _**KhoLe**_: `KhoLe` - _**MaHH**_: `MaHH` - _**SoHD**_: `SoHD` - _**NgayHD**_: `NgayHD` - _**ThangKT**_: `ThangKT` - _**NamKT**_: `NamKT`
-  ![loi_cls](https://img.shields.io/badge/Chi%20tiết%20CLS-:-blue?style=plastic&logo=github)
   > _**MaCLS**_: `MaCLS` - _**PhieuYC**_: `PhieuYC`
-  ![loi_bo_sung](https://img.shields.io/badge/Chi%20tiết%20bổ%20sung-:-blue?style=plastic&logo=github)
   > _**Khac**_: `Khac`

###### ![mo_ta_loi](https://img.shields.io/badge/Mô%20tả%20thông%20tin%20lỗi-:-blue?style=for-the-badge&logo=github)

Hiện tại người dùng có thể set ngày kết quả cho giường bệnh có thể nhỏ hơn ngày chỉ định phát sinh lỗi khi gửi giám định 
>> Ràng buộc chặn không cho cập nhật nếu ngày kết quả nhỏ hơn ngày chỉ định (xét ràng buộc luôn trường hợp sử dụng tham số tự động gán ngày kết quả khi chuyển khoa "nt.capnhat_ngaykq")
![image](https://github.com/user-attachments/assets/671833c9-0945-49c7-9a43-0c6df71843f3)

![image](https://github.com/user-attachments/assets/a58c586a-ecc9-404c-a188-951925368030)

**Comment by vuongdh** [comment]
✔️ Đã tiếp nhận
⌛ Thời gian hoàn thành dự kiến: 2024-08-26

**Comment by gh-dh-bot-01** [comment]
### 📣📣📣 Treatment.exe v.4.24.0823.1 [⬇️OneDrive](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FTreatmentexe%2F42408231-OneDrive.json) [⬇️GoogleStorage](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FTreatmentexe%2F42408231-GoogleStorage.json) [⬇️NasDHSolutions](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FTreatmentexe%2F42408231-NasDHSolutions.json)

## Nội dung thay đổi

- 🐛: Fix Lỗi - Lỗi tổng kết chi phí thông tin con #261

![image](https://github.com/user-attachments/assets/4db50377-7615-4724-be78-b7816dc3521a)

- ☑: https://github.com/dh-hos/dhg.hosptaltreatment/issues/261

- 🐛: Fix Lỗi - CHƯA RÀNG BUỘC NGÀY KẾT QUẢ CỦA GIƯỜNG BỆNH PHẢI LỚN HƠN NGÀY CHỈ ĐỊNH #259

![image](https://github.com/user-attachments/assets/cd2686df-5175-4f68-acb2-304d2936f7fe)

- ☑: https://github.com/dh-hos/dhg.hosptaltreatment/issues/259

<div align="right">

 [![](https://img.shields.io/badge/-Th%E1%BB%B1c%20hi%E1%BB%87n%20b%E1%BB%9Fi%3A%20%40vuongdh-informational?logo=github)](https://github.com/vuongdh) [![](https://img.shields.io/badge/-Xem%20l%E1%BB%8Bch%20s%E1%BB%AD%20phi%C3%AAn%20b%E1%BA%A3n-informational?logo=github)](https://github.com/dh-hos-code/Treatment.exe?tab=readme-ov-file#readme) [![](https://img.shields.io/badge/Nh%E1%BA%ADn%20th%C3%B4ng%20b%C3%A1o%20tr%C3%AAn%20Telegram-2CA5E0?style=flat-squeare&logo=telegram&logoColor=white)](https://t.me/dhhoscodemsifiles)
</div>

**Comment by nqhoa1005** [comment]
✅ Đã ràng buộc
![image](https://github.com/user-attachments/assets/36d612a6-16cc-4e22-a5df-26e0642ab62a)

❌ Do cổng bắt thêm ngày chỉ định mà ngày kết quả không được trùng nhau nên chỉnh thêm dùm em chổ này ràng buộc phải lớn hơn ngày chỉ định (tối thiểu tính bằng phút)
Em test thử thì chọn ngày kết quả = ngày chỉ định vẫn được
![image](https://github.com/user-attachments/assets/0049eb78-073f-4095-8adb-b8eb3ebc435a)

**Comment by vuongdh** [comment]
[Cập nhật thực hiện trả kết quả ngày giường tương tự như mô tả này](https://github.com/dh-hos/Mo-ta-he-thong/blob/main/Mô%20tả%20Kiểm%20tra%20thời%20gian%20kết%20quả%20HA-CN-TT-PT.md)

@ongtrieuhau Ý kiến thực hiện

**Comment by ongtrieuhau-dh** [comment]
## HD.05 [^HD05]
-  ❌ **Từ chối tiếp nhận** 
- 📣 **Nguyên nhân**: _Đã thực hiện đúng chỉnh lỗi theo luồng báo lỗi này. Chức năng mới chưa có thì phải lập yêu cầu mới, thông qua sếp duyệt._


[^HD05]: Thời gian phải tiếp nhận ( Bình thường: 120 phút. Gấp: 60 phút) [Đối với các BL “Gấp” thời gian xử lý 4h, trường hợp không kịp bắc buộc phải đề ra các khắc phục tạm thời (Sql, lùi bản cũ…); Mức độ ưu tiên các lỗi “Gấp”: GĐ, tổ trưởng CO, tổ trưởng HT, tổ trưởng TK, nhân viên HT, nhân viên TK.] Nghĩa vụ: ghi nhận vi phạm nếu có tại HD.04, phản hồi
đủ thông tin

**Comment by nqhoa1005** [comment]
-  ✔️ **Đã tiếp nhận thông tin** 
-  👉 +Nội dung thực hiện : **Đóng Git để lập yêu cầu mới**
