### ISSUE TITLE
Yêu cầu - Hỗ trợ Thông tư 36/2021/TT-BYT

### ISSUE THREAD

**Issue by le-an-87** [dh-hos/dhg.hosptaltreatment#26]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.2: Phiếu ghi nhận Yêu cầu mới DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN YÊU CẦU CHỨC NĂNG MỚI</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **ÂN**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **28/9/2022**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `Tất cả`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **Tất cả**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `an_lapvo_kqcls`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`](link_csdl)

###### ![chi_tiet_yeu_cau](https://img.shields.io/badge/Chi%20tiết%20yêu%20cầu%20-:-blue?style=for-the-badge&logo=github)

```
1. Đề xuất thêm chức năng cho điều chỉnh từ bệnh bình thường sang bệnh Lao và ngược lại.

2. Thêm dấu hiệu nhận biết bệnh nhân Lao giống như bệnh nhân cấp cứu.

3. Khi in giấy Xác nhận điều trị Lao. hiện tại Tất cả bệnh nhân điều in được phiếu này
-> Đề xuất: chỉ những bệnh nhân có check Bệnh nhân Lao mới cấp được phiếu chứng nhận Lao và ghi nhận ngày giờ cấp để dễ quản lý.

```

**Comment by vuongdh** [comment]
@le-an-87 Bệnh nhân đang điều trị tại BV A (không điều trị bệnh lao), cần giấy xác nhận qua BV B để lãnh thuốc để điều trị bệnh lao
