### ISSUE TITLE
Lỗi - Bảng kê chi phí 6556 thiếu thông tin thẻ 2, sai mức hưởng thẻ 2

### ISSUE THREAD

**Issue by chauthanhtra** [dh-hos/dhg.hosptaltreatment#264]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.1: Phiếu ghi nhận lỗi phát sinh DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN LỖI PHÁT SINH</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Châu Thanh Trà**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **29/08/2024**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `92118`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **BV Phụ Sản**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `tra_phusan_thongtinthe2_6556_29082024`
-  ![port_csdl](https://img.shields.io/badge/Port%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `5434`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`](https://gofile.me/78TQg/AUj8ggi0Y)

###### ![chi_tiet_loi](https://img.shields.io/badge/Chi%20tiết%20lỗi%20phát%20sinh-:-blue?style=for-the-badge&logo=github)

-  ![loi_benh_nhan](https://img.shields.io/badge/Chi%20tiết%20bệnh%20nhân-:-blue?style=plastic&logo=github)
   > _**MaBN**_: `2024067321` - _**MaKB**_: `2408012483` - _**MaBA**_: `013982` _**NgayVV**_: `19/08/2024` - _**MaPhong**_: `MaPhong` - _**MaDV**_: `22` - _**ThangKT**_: `08` - _**NamKT**_: `2024`
-  ![loi_thuoc](https://img.shields.io/badge/Chi%20tiết%20thuốc-:-blue?style=plastic&logo=github)
   > _**KhoChan**_: `KhoChan` - _**KhoLe**_: `KhoLe` - _**MaHH**_: `MaHH` - _**SoHD**_: `SoHD` - _**NgayHD**_: `NgayHD` - _**ThangKT**_: `ThangKT` - _**NamKT**_: `NamKT`
-  ![loi_cls](https://img.shields.io/badge/Chi%20tiết%20CLS-:-blue?style=plastic&logo=github)
   > _**MaCLS**_: `MaCLS` - _**PhieuYC**_: `PhieuYC`
-  ![loi_bo_sung](https://img.shields.io/badge/Chi%20tiết%20bổ%20sung-:-blue?style=plastic&logo=github)
   > _**Khac**_: `Khac`

###### ![mo_ta_loi](https://img.shields.io/badge/Mô%20tả%20thông%20tin%20lỗi-:-blue?style=for-the-badge&logo=github)

Bệnh nhân có 2 thẻ BHYT
- Bảng kê 6556 và form tổng kết chi phí không hiển thị thông tin thẻ 2
- Phần chi phí thẻ 2 bị sai mức hưởng 

![ảnh](https://github.com/user-attachments/assets/4bde4599-d459-4680-9620-86ae4237a296)
![ảnh](https://github.com/user-attachments/assets/d6809466-b6c7-4188-9366-e71f9036d41a)
![ảnh](https://github.com/user-attachments/assets/6b42dd11-3290-4989-9bc3-dcaf1a77fc94)

**Comment by le-an-87** [comment]
Tranh thủ giúp em để gửi bệnh viện cho bệnh nhân ra viện nhe anh @vuongdh

**Comment by gh-dh-bot-01** [comment]
### 📣📣📣 Treatment.exe v.4.24.0829.1 [⬇️OneDrive](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FTreatmentexe%2F42408291-OneDrive.json) [⬇️GoogleStorage](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FTreatmentexe%2F42408291-GoogleStorage.json) [⬇️NasDHSolutions](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FTreatmentexe%2F42408291-NasDHSolutions.json)

## Nội dung thay đổi

- 🐛: Fix lỗi - Bảng kê chi phí 6556 thiếu thông tin thẻ 2, sai mức hưởng thẻ 2 #264

![image](https://github.com/user-attachments/assets/4af6d42f-0c93-4160-82c5-9317c865b99f)

- ☑: https://github.com/dh-hos/dhg.hosptaltreatment/issues/264

<div align="right">

 [![](https://img.shields.io/badge/-Th%E1%BB%B1c%20hi%E1%BB%87n%20b%E1%BB%9Fi%3A%20%40vuongdh-informational?logo=github)](https://github.com/vuongdh) [![](https://img.shields.io/badge/-Xem%20l%E1%BB%8Bch%20s%E1%BB%AD%20phi%C3%AAn%20b%E1%BA%A3n-informational?logo=github)](https://github.com/dh-hos-code/Treatment.exe?tab=readme-ov-file#readme) [![](https://img.shields.io/badge/Nh%E1%BA%ADn%20th%C3%B4ng%20b%C3%A1o%20tr%C3%AAn%20Telegram-2CA5E0?style=flat-squeare&logo=telegram&logoColor=white)](https://t.me/dhhoscodemsifiles)
</div>

**Comment by chauthanhtra** [comment]
### **✔️KẾT QUẢ TEST**
***
Phần mềm Treatment.exe v.4.24.0829.1
***
>Lỗi, yêu cầu đã hoàn thành 
- Nội dung: Form tổng kết chi phí đã lấy được thông tin thẻ 2 và bảng kê chi phí đã lấy được thông tin thẻ 2 và mức hưởng theo qui đinh


- Hình ảnh: 
![ảnh](https://github.com/user-attachments/assets/2cb3880f-3d9d-4f88-9f65-ffcab01afc58)

![ảnh](https://github.com/user-attachments/assets/085a1e9e-2239-4ca1-aaa3-26b77042d5e9)


***
> Trường hợp không đủ thông tin kiểm tra hoặc còn lỗi ghi nhận phản hồi cho CO.

- Diễn giải lỗi: Sai tổng kết chi phí thông tin con và bảng kê chi phí thông tin con lấy mã thẻ 2


- Hình ảnh lỗi:

![ảnh](https://github.com/user-attachments/assets/506b5357-b31e-44d7-8f29-0a45fe49ae09)
![ảnh](https://github.com/user-attachments/assets/eabbf1e7-bd45-40ca-8cbd-2c1b0035e341)
![ảnh](https://github.com/user-attachments/assets/4f205619-c781-4c02-93cc-8047f4826b45)



> Hình ảnh Phiếu 01, 02, xuất XML.

> Nhập thuốc -> xuất thuốc -> tổng hợp.

> Hình ảnh chứng mình cho việc kiểm tra này.

> Mô tả, hướng dẫn sử dụng chức năng cập nhật (nếu có).
***
##### Phát sinh lỗi chức năng hiện tại -> Ghi nhận lỗi và ngưng test các vấn đề còn lại.

**Comment by chauthanhtra** [comment]
### **Chưa hoàn thành**
- Hoàn thành kiểm tra
- Phần mềm chưa đáp ứng đúng yêu cầu.
- Yêu cầu Tổ coder kiểm tra lại trường hợp bệnh nhân vửa có thẻ 2 vừa có thông tin con

**Comment by gh-dh-bot-01** [comment]
### 📣📣📣 Treatment.exe v.4.24.0830.3 [⬇️OneDrive](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FTreatmentexe%2F42408303-OneDrive.json) [⬇️GoogleStorage](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FTreatmentexe%2F42408303-GoogleStorage.json) [⬇️NasDHSolutions](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FTreatmentexe%2F42408303-NasDHSolutions.json)

## Nội dung thay đổi

- 🐛: Fix Lỗi - Bảng kê chi phí 6556 thiếu thông tin thẻ 2, sai mức hưởng thẻ 2 #264

- Tổng kết bệnh nhân có 2 thẻ:

![image](https://github.com/user-attachments/assets/bdbb22b3-c508-4e3f-b347-864ff86e3b0b)

- Tổng kết chi phí (thông tin con):

![image](https://github.com/user-attachments/assets/6db703fa-9fb0-4352-9a24-abeca133487a)

- ☑: https://github.com/dh-hos/dhg.hosptaltreatment/issues/264

<div align="right">

 [![](https://img.shields.io/badge/-Th%E1%BB%B1c%20hi%E1%BB%87n%20b%E1%BB%9Fi%3A%20%40vuongdh-informational?logo=github)](https://github.com/vuongdh) [![](https://img.shields.io/badge/-Xem%20l%E1%BB%8Bch%20s%E1%BB%AD%20phi%C3%AAn%20b%E1%BA%A3n-informational?logo=github)](https://github.com/dh-hos-code/Treatment.exe?tab=readme-ov-file#readme) [![](https://img.shields.io/badge/Nh%E1%BA%ADn%20th%C3%B4ng%20b%C3%A1o%20tr%C3%AAn%20Telegram-2CA5E0?style=flat-squeare&logo=telegram&logoColor=white)](https://t.me/dhhoscodemsifiles)
</div>

**Comment by le-an-87** [comment]
### **✔️KẾT QUẢ KIỂM TRA SẢN PHẨM**
***
> Hình ảnh chứng mình cho việc kiểm tra này.
Tổng kết thông tin con
![ảnh](https://github.com/user-attachments/assets/309c8cef-dacf-4880-a8cd-b9d5f724e98d)
Kết thúc và in tổng kết
![ảnh](https://github.com/user-attachments/assets/af233ff4-dc25-45e2-8590-cfa017adc9f2)
![ảnh](https://github.com/user-attachments/assets/6e57ae6d-8f59-4b89-91d5-318c28dbf3d5)

> Mô tả, hướng dẫn sử dụng chức năng cập nhật (nếu có).
***
##### Phát sinh lỗi chức năng hiện tại -> Ghi nhận lỗi và ngưng test các vấn đề còn lại.

**Comment by le-an-87** [comment]
### **HoànThành**
✔️Hoàn thành kiểm tra
✔️Kết quả kiểm tra đạt yêu cầu
***
- Tiến hành hỗ trợ khách hàng.
