### ISSUE TITLE
Lỗi - BV Phụ Sản: Treatment cấn trừ sai số lượng thuốc khi trả thuốc

### ISSUE THREAD

**Issue by chauthanhtra** [dh-hos/dhg.hosptaltreatment#265]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.1: Phiếu ghi nhận lỗi phát sinh DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN LỖI PHÁT SINH</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Châu Thanh Trà**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **02/09/2024**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `92118`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **BV Phụ Sản**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `(Chưa restore dữ liệu lên máy chủ hỗ trợ)`
-  ![port_csdl](https://img.shields.io/badge/Port%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `port_csdl`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`](https://gofile.me/78TQg/YH0INJBFP)

###### ![chi_tiet_loi](https://img.shields.io/badge/Chi%20tiết%20lỗi%20phát%20sinh-:-blue?style=for-the-badge&logo=github)

-  ![loi_benh_nhan](https://img.shields.io/badge/Chi%20tiết%20bệnh%20nhân-:-blue?style=plastic&logo=github)
   > _**MaBN**_: `2024001997` - _**MaKB**_: `2408018877` - _**MaBA**_: `014535` _**NgayKCB**_: `31/08/2024` - _**MaPhong**_: `MaPhong` - _**MaDV**_: `30` - _**ThangKT**_: `08` - _**NamKT**_: `2024`
-  ![loi_thuoc](https://img.shields.io/badge/Chi%20tiết%20thuốc-:-blue?style=plastic&logo=github)
   > _**KhoChan**_: `14` - _**KhoLe**_: `KhoLe` - _**MaHH**_: `AM118` - _**SoHD**_: `SoHD` - _**NgayHD**_: `NgayHD` - _**ThangKT**_: `08` - _**NamKT**_: `2024`
-  ![loi_cls](https://img.shields.io/badge/Chi%20tiết%20CLS-:-blue?style=plastic&logo=github)
   > _**MaCLS**_: `MaCLS` - _**PhieuYC**_: `PhieuYC`
-  ![loi_bo_sung](https://img.shields.io/badge/Chi%20tiết%20bổ%20sung-:-blue?style=plastic&logo=github)
   > _**Khac**_: `Khac`

###### ![mo_ta_loi](https://img.shields.io/badge/Mô%20tả%20thông%20tin%20lỗi-:-blue?style=for-the-badge&logo=github)

(Chưa restore dữ liệu lên máy chủ hỗ trợ, tải dữ liệu từ link NAS)

Tổng kết chi phí 6556 và bảng kê chi phí 6556 tính sai số lượng thuốc AM118

Tổng số thuốc còn lại của bệnh nhân sau khi trả là 14 nhưng Treatment tính số lượng còn 5

- Đúng

![ảnh](https://github.com/user-attachments/assets/59a728b6-d6bd-4b3f-a968-a8b1eb3700a0)
![ảnh](https://github.com/user-attachments/assets/a4a587ea-4155-401b-bcf8-268756918263)
![ảnh](https://github.com/user-attachments/assets/8e2b285a-8b8e-4f3e-8656-ddc35a62a6b8)

- Sai 

![ảnh](https://github.com/user-attachments/assets/5da20dc6-801f-4739-8e6d-10a4688651f5)
![ảnh](https://github.com/user-attachments/assets/292efbcf-ffc8-47ab-9517-5756d25f9da0)

**Comment by le-an-87** [comment]
### **Trả lời vướng mắc**
- Retore dữ liệu và chep dữ liệu bổ sung nhe @chauthanhtra 
***

**Comment by vuongdh** [comment]
✔️ Đã tiếp nhận
⌛ Thời gian hoàn thành dự kiến: chờ dữ liệu bổ sung

**Comment by chauthanhtra** [comment]
> ### **Trả lời vướng mắc**
> 
>     * Retore dữ liệu bổ sung nhe @chauthanhtra

Đã restore data lên máy chủ
- Data: tra_phusan_lech_thuoc_02092024
- Port: 5434

**Comment by vuongdh** [comment]
Thời gian hoàn thành dự kiến: 2024-09-06

**Comment by gh-dh-bot-01** [comment]
### 📣📣📣 Treatment.exe v.4.24.0906.0 [⬇️OneDrive](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FTreatmentexe%2F42409060-OneDrive.json) [⬇️GoogleStorage](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FTreatmentexe%2F42409060-GoogleStorage.json) [⬇️NasDHSolutions](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FTreatmentexe%2F42409060-NasDHSolutions.json)

## Nội dung thay đổi

- 🐛: Fix lỗi - BV Phụ Sản: Treatment cấn trừ sai số lượng thuốc khi trả thuốc #265

- Phiếu 6556:

![image](https://github.com/user-attachments/assets/ae239e54-3193-4d0c-8caa-e62fe7e81ecc)

![image](https://github.com/user-attachments/assets/b1669c8f-bba1-4695-b096-c0b9c6e571db)

- Phiếu công khai thuốc:

![image](https://github.com/user-attachments/assets/f267eb30-57bb-4350-ad60-1e9f6879555d)

- Fix lỗi: Chức năng lấy lại toa thiếu liều dùng (BV Nhi Đồng Cần Thơ)

![image](https://github.com/user-attachments/assets/a1327e09-cc41-4506-b336-39c1cd96e199)

- ☑: https://github.com/dh-hos/dhg.hosptaltreatment/issues/265

<div align="right">

 [![](https://img.shields.io/badge/-Th%E1%BB%B1c%20hi%E1%BB%87n%20b%E1%BB%9Fi%3A%20%40vuongdh-informational?logo=github)](https://github.com/vuongdh) [![](https://img.shields.io/badge/-Xem%20l%E1%BB%8Bch%20s%E1%BB%AD%20phi%C3%AAn%20b%E1%BA%A3n-informational?logo=github)](https://github.com/dh-hos-code/Treatment.exe?tab=readme-ov-file#readme) [![](https://img.shields.io/badge/Nh%E1%BA%ADn%20th%C3%B4ng%20b%C3%A1o%20tr%C3%AAn%20Telegram-2CA5E0?style=flat-squeare&logo=telegram&logoColor=white)](https://t.me/dhhoscodemsifiles)
</div>

**Comment by chauthanhtra** [comment]
- ✔️ Đã tiếp nhận
- ⌛ Thời gian dự kiến hoàn thành kiểm tra: '  13/9/2024  '.
***
- Kiểm tra chức năng BLYC theo:
o Mô tả, hướng dẫn sử dụng chức năng cập nhật (nếu có).
- Kiểm tra chức năng cơ bản của phân hệ trong qui trình khám chữa bệnh hoặc qui trình kho. Chứng minh bằng hình ảnh:
o Phiếu 01, 02, xuất XML.
o Nhập thuốc -> xuất thuốc -> tổng hợp.
o Có hình ảnh chứng mình cho việc kiểm tra này.
- File: copy sản phẩm đã kiểm thử thành công lên NAS: NAS\DuLieuCongTy\Modules -> Close Issue.
- Trường hợp không đủ thông tin kiểm tra hoặc còn lỗi ghi nhận phản hồi cho CO.

**Comment by chauthanhtra** [comment]
### **✔️KẾT QUẢ TEST**
***
Phần mềm Treatment.exe v.4.24.0907.0
***
>Lỗi, yêu cầu đã hoàn thành 
- Nội dung: 
  - Đã fix lỗi cấn trừ sai số lượng thuốc khi bệnh nhân trả thuốc, cấp toa, chỉ định CLS, ra viện , in bảng kê, thu phí, xuất XML bình thường
  - Kiểm tra dữ liệu bệnh nhân khác đã cấn trừ đúng chi phí bệnh nhân

- Hình ảnh: 

![ảnh](https://github.com/user-attachments/assets/e677c7c9-897f-4819-99cd-e7bd424211e9)
![ảnh](https://github.com/user-attachments/assets/0000dc7f-8c09-4662-b7df-73e3f9bd441b)
![ảnh](https://github.com/user-attachments/assets/f6f4579b-7a40-4457-9c18-8b65a45e14f2)
![ảnh](https://github.com/user-attachments/assets/9f1231b6-a01b-4023-8259-4c293922a618)
![ảnh](https://github.com/user-attachments/assets/c624d99a-4cd5-4ab4-9f6e-fdff1eaccdc8)
![ảnh](https://github.com/user-attachments/assets/572adf19-c19c-46f2-9db1-89d785227584)
![ảnh](https://github.com/user-attachments/assets/20f0c79c-81c2-4a5c-8a40-8d5160cc5967)


  - Ảnh kiểm tra dữ liệu bệnh nhân bị lệch chi phí khác -> đã lấy đúng chi phí

![ảnh](https://github.com/user-attachments/assets/9d4e4d9a-58c7-4f1f-82fc-cab578137dc0)
![ảnh](https://github.com/user-attachments/assets/88544121-f211-4c55-a9a5-4bf1165800f0)


***
> Trường hợp không đủ thông tin kiểm tra hoặc còn lỗi ghi nhận phản hồi cho CO.

>- Diễn giải lỗi:


>- Hình ảnh lỗi:



> Hình ảnh Phiếu 01, 02, xuất XML.

> Nhập thuốc -> xuất thuốc -> tổng hợp.

> Hình ảnh chứng mình cho việc kiểm tra này.

> Mô tả, hướng dẫn sử dụng chức năng cập nhật (nếu có).
***
##### 
>Phát sinh lỗi chức năng hiện tại -> Ghi nhận lỗi và ngưng test các vấn đề còn lại.

**Comment by chauthanhtra** [comment]
### **Hoàn Thành**
✔️Hoàn thành kiểm tra
✔️Kết quả kiểm tra đạt yêu cầu
***
- Tiến hành hỗ trợ khách hàng.
