### ISSUE TITLE
Lỗi - Treatment lấy liều dùng tự động Sai của Toa Xuất viện

### ISSUE THREAD

**Issue by hvtuan1987** [dh-hos/dhg.hosptaltreatment#268]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.1: Phiếu ghi nhận lỗi phát sinh DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN LỖI PHÁT SINH</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Hà Văn Tuấn**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **02/09/2024**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `94006`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **Trung tâm y tế huyện Thạnh Trị**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `tuan_dbthanhtri_loinhapvien`
-  ![port_csdl](https://img.shields.io/badge/Port%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `5434`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`](https://gofile.me/78TQg/TeBCuf3oO)

###### ![chi_tiet_loi](https://img.shields.io/badge/Chi%20tiết%20lỗi%20phát%20sinh-:-blue?style=for-the-badge&logo=github)

-  ![loi_benh_nhan](https://img.shields.io/badge/Chi%20tiết%20bệnh%20nhân-:-blue?style=plastic&logo=github)
   > _**MaBN**_: `2011002829` - _**MaKB**_: `2409000141` - _**MaBA**_: `MaBA` _**NgayKCB**_: `11/09/2024` - _**MaPhong**_: `` - _**MaDV**_: `02` - _**ThangKT**_: `09` - _**NamKT**_: `2024`

Bệnh nhân BHYT khi lập Toa Xuất viện liều dùng lấy tự động Sai so với quy định 4210 
Ví dụ: Thuốc có mã hàng hóa A.26 cho số lượng 7, Sáng 1 thì liêu dùng lấy tự động là Sáng: 1 Viên [7 Viên/ngày]

Đúng thì Liều dùng phải để:  1 Viên/lần * 1 lần/ngày * 7 ngày [1 Viên/ngày]
Quy định theo Quyết định 4750
![image](https://github.com/user-attachments/assets/7bacf51c-2ba7-4a2f-9155-27a6937eb6ec)

Toa xuất viện tại Treatment hiện tại
![image](https://github.com/user-attachments/assets/23a6e74a-1ced-4210-9609-e94e4c0548c0)
![image](https://github.com/user-attachments/assets/4844ac10-f9a3-49e0-8bb1-3d1361db22f8)

**Comment by vuongdh** [comment]
✔️ Đã tiếp nhận
⌛ Thời gian hoàn thành dự kiến: 2024-09-13

**Comment by gh-dh-bot-01** [comment]
### 📣📣📣 Treatment.exe v.4.24.0913.2 [⬇️OneDrive](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FTreatmentexe%2F42409132-OneDrive.json) [⬇️GoogleStorage](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FTreatmentexe%2F42409132-GoogleStorage.json) [⬇️NasDHSolutions](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FTreatmentexe%2F42409132-NasDHSolutions.json)

## Nội dung thay đổi

- 🐛: Fix lỗi - Treatment lấy liều dùng tự động Sai của Toa Xuất viện #268

![image](https://github.com/user-attachments/assets/509ea297-767b-48bc-b20e-f35160e61573)

- ☑: https://github.com/dh-hos/dhg.hosptaltreatment/issues/268

<div align="right">

 [![](https://img.shields.io/badge/-Th%E1%BB%B1c%20hi%E1%BB%87n%20b%E1%BB%9Fi%3A%20%40vuongdh-informational?logo=github)](https://github.com/vuongdh) [![](https://img.shields.io/badge/-Xem%20l%E1%BB%8Bch%20s%E1%BB%AD%20phi%C3%AAn%20b%E1%BA%A3n-informational?logo=github)](https://github.com/dh-hos-code/Treatment.exe?tab=readme-ov-file#readme) [![](https://img.shields.io/badge/Nh%E1%BA%ADn%20th%C3%B4ng%20b%C3%A1o%20tr%C3%AAn%20Telegram-2CA5E0?style=flat-squeare&logo=telegram&logoColor=white)](https://t.me/dhhoscodemsifiles)
</div>

**Comment by hvtuan1987** [comment]
@vuongdh Chức năng lấy liều dùng tự động đã lấy đúng theo lỗi trên. Sẵn theo luồng này em báo thêm như sau:
Khi chỉnh lại số lượng thuốc của toa thuốc Xuất viện trên bấm enter liều dùng chưa lấy lại tự động sẵn anh coi dùm em luôn á !
Hình phía dưới: mã thuốc A.26 lúc đầu em cho SL 1 lấy liều dùng đúng. Sua đó em bấm chỉnh lại thành SL  7 và nhấn Enter qua các cột Sáng/Trưa /Chiều/Tối thì liều dùng chưa lấy lại tự động mà người dùng phải bấm chỉnh thủ công tại cột liều dùng
![image](https://github.com/user-attachments/assets/c3b0388e-4789-4917-a9cd-f2f04e6ee113)

**Comment by vuongdh** [comment]
@hvtuan1987 sửa số lượng xong, enter qua ô chỉ định, enter cái nữa thì mới cập nhật lại, khi mới chỉnh sửa số lượng thì pm chưa biết kết thúc cho số chưa nên không cập nhật lại. Đã fix được lỗi thì close git nha. Nếu có yêu cầu gì thêm thì tạo git mới để tiện theo hén.

**Comment by hvtuan1987** [comment]
@vuongdh Em có thử rồi á ! Enter qua các cột cũng hong lấy lại liều dùng mới theo số lượng vừa cho !

**Comment by gh-dh-bot-01** [comment]
### 📣📣📣 Treatment.exe v.4.24.0916.0 [⬇️OneDrive](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FTreatmentexe%2F42409160-OneDrive.json) [⬇️GoogleStorage](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FTreatmentexe%2F42409160-GoogleStorage.json) [⬇️NasDHSolutions](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FTreatmentexe%2F42409160-NasDHSolutions.json)

## Nội dung thay đổi

- 🐛: Fix lỗi - Treatment lấy liều dùng tự động Sai của Toa Xuất viện #268

- Toa nội trú, toa xuất viện nội trú

- Toa xuất viện ngoại trú

--> Thay đổi số lượng, sáng, trưa, chiều, tối: cập nhật lại liều dùng

- ☑: https://github.com/dh-hos/dhg.hosptaltreatment/issues/268

<div align="right">

 [![](https://img.shields.io/badge/-Th%E1%BB%B1c%20hi%E1%BB%87n%20b%E1%BB%9Fi%3A%20%40vuongdh-informational?logo=github)](https://github.com/vuongdh) [![](https://img.shields.io/badge/-Xem%20l%E1%BB%8Bch%20s%E1%BB%AD%20phi%C3%AAn%20b%E1%BA%A3n-informational?logo=github)](https://github.com/dh-hos-code/Treatment.exe?tab=readme-ov-file#readme) [![](https://img.shields.io/badge/Nh%E1%BA%ADn%20th%C3%B4ng%20b%C3%A1o%20tr%C3%AAn%20Telegram-2CA5E0?style=flat-squeare&logo=telegram&logoColor=white)](https://t.me/dhhoscodemsifiles)
</div>

**Comment by hvtuan1987** [comment]
## 📣 @vuongdh 
Xác nhận đã cập nhật theo lỗi trên! 
![image](https://github.com/user-attachments/assets/e0feb701-1215-4316-b507-b3c424f4df3d)
