### ISSUE TITLE
Lỗi - SAI TUYẾN KHI CHỈNH ĐT HỒ SƠ NỘI TRÚ > MA_DOITUONG_KCB = 9

### ISSUE THREAD

**Issue by nqhoa1005** [dh-hos/dhg.hosptaltreatment#269]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.1: Phiếu ghi nhận lỗi phát sinh DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN LỖI PHÁT SINH</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **NGUYỄN QUỐC HOÀ**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **16/09/2024**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `94006`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **BVĐK H.THẠNH TRỊ**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `hoa_thanhtri_dtkcb9`
-  ![port_csdl](https://img.shields.io/badge/Port%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `5434`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`](https://gofile.me/78TQg/WsGG0APLQ)

###### ![chi_tiet_loi](https://img.shields.io/badge/Chi%20tiết%20lỗi%20phát%20sinh-:-blue?style=for-the-badge&logo=github)

-  ![loi_benh_nhan](https://img.shields.io/badge/Chi%20tiết%20bệnh%20nhân-:-blue?style=plastic&logo=github)
   > _**MaBN**_: `2024010690` - _**MaKB**_: `MaKB` - _**MaBA**_: `2024007208` _**NgayKCB**_: `NgayKCB` - _**MaPhong**_: `MaPhong` - _**MaDV**_: `02` - _**ThangKT**_: `ThangKT` - _**NamKT**_: `NamKT`
-  ![loi_thuoc](https://img.shields.io/badge/Chi%20tiết%20thuốc-:-blue?style=plastic&logo=github)
   > _**KhoChan**_: `KhoChan` - _**KhoLe**_: `KhoLe` - _**MaHH**_: `MaHH` - _**SoHD**_: `SoHD` - _**NgayHD**_: `NgayHD` - _**ThangKT**_: `ThangKT` - _**NamKT**_: `NamKT`
-  ![loi_cls](https://img.shields.io/badge/Chi%20tiết%20CLS-:-blue?style=plastic&logo=github)
   > _**MaCLS**_: `MaCLS` - _**PhieuYC**_: `PhieuYC`
-  ![loi_bo_sung](https://img.shields.io/badge/Chi%20tiết%20bổ%20sung-:-blue?style=plastic&logo=github)
   > _**Khac**_: `Khac`

###### ![mo_ta_loi](https://img.shields.io/badge/Mô%20tả%20thông%20tin%20lỗi-:-blue?style=for-the-badge&logo=github)

Trường hợp khi tiếp nhận là đối tượng thu phí khi nhập viện chỉnh lại đối tượng thêm thẻ BHYT thì không chỉnh được trái tuyến cũng không hiện bảng thông báo giấy chuyển để người dùng xác nhận trái tuyến.

![image](https://github.com/user-attachments/assets/6d1907ff-0218-44e0-b5de-fe0122c89284)

các trường hợp này đúng ma_doituong_kcb = 3.3 nhưng không chỉnh trái tuyến được nên XML khi lấy lên sai điều kiện bnnoitru.tuyenxml = 0 > ma_doituong_kcb = 9 
![image](https://github.com/user-attachments/assets/c81f7710-f1a3-41d7-abb7-2f5ca7848dc6)

tất cả trường hợp này cổng đang trả về lỗi sai lý do vào viện mặc dù lý do vào viện khi kiểm tra thực tế có nhập và lên XML đầy đủ
![image](https://github.com/user-attachments/assets/1f80266c-0d9a-4307-9dc2-bff184db6d92)

**Comment by vuongdh** [comment]
✔️ Đã tiếp nhận
👉 Thực hiện: Thực hiện các yêu cầu theo luồng công việc này.
📆 Thời gian hoàn thành : 2024-09-19

**Comment by nqhoa1005** [comment]
❗❗ **TRAO ĐỔI** ❗❗
-----------------------------
✳️anh @vuongdh anh @nghivanbi chổ này nhiều đơn vị bị hồ sơ cũ quá, cho em xin phương pháp cập nhật lại các hồ sơ cũ rơi vào trường hợp này hay phải trả về điều trị để cập nhật lại, em ghi nhận riêng Thạnh Trị đã có hơn 100 hồ sơ tháng 8

**Comment by gh-dh-bot-01** [comment]
### 📣📣📣 Treatment.exe v.4.24.0919.0 [⬇️OneDrive](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FTreatmentexe%2F42409190-OneDrive.json) [⬇️GoogleStorage](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FTreatmentexe%2F42409190-GoogleStorage.json) [⬇️NasDHSolutions](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FTreatmentexe%2F42409190-NasDHSolutions.json)

## Nội dung thay đổi

- 🐛: Fix lỗi - SAI TUYẾN KHI CHỈNH ĐT HỒ SƠ NỘI TRÚ > MA_DOITUONG_KCB = 9

- Cập nhật fix lỗi sai tuyến khi chỉnh đối tượng

![image](https://github.com/user-attachments/assets/3c606151-0219-48e6-a2d0-42d759e8703e)

![image](https://github.com/user-attachments/assets/2eb6414d-250b-45ca-8b7f-b053c4d3870f)

- ☑: https://github.com/dh-hos/dhg.hosptaltreatment/issues/269

<div align="right">

 [![](https://img.shields.io/badge/-Th%E1%BB%B1c%20hi%E1%BB%87n%20b%E1%BB%9Fi%3A%20%40vuongdh-informational?logo=github)](https://github.com/vuongdh) [![](https://img.shields.io/badge/-Xem%20l%E1%BB%8Bch%20s%E1%BB%AD%20phi%C3%AAn%20b%E1%BA%A3n-informational?logo=github)](https://github.com/dh-hos-code/Treatment.exe?tab=readme-ov-file#readme) [![](https://img.shields.io/badge/Nh%E1%BA%ADn%20th%C3%B4ng%20b%C3%A1o%20tr%C3%AAn%20Telegram-2CA5E0?style=flat-squeare&logo=telegram&logoColor=white)](https://t.me/dhhoscodemsifiles)
</div>

**Comment by nqhoa1005** [comment]
❌ Chưa fix được
- Ví dụ BV Thạnh Trị đang là tuyến huyện, khi em nhập thử mã ĐKBD của tuyến tỉnh cùng tỉnh cũng không hiện thông báo và cũng set là cùng tuyến. Anh check lại giúp em.
![image](https://github.com/user-attachments/assets/76836733-9d5d-469a-bf7d-4b28d0349d40)

**Comment by vuongdh** [comment]
Bệnh viên Thạnh Trị cùng tuyến là do tham số: thetrongtinh và tt40, em coi lại mô tả này dùm anh hén. Có gì anh giải thích sau

**Comment by vuongdh** [comment]
[BI - Mo ta thong tu 40_hieu chinh.docx](https://github.com/user-attachments/files/17056088/BI.-.Mo.ta.thong.tu.40_hieu.chinh.docx)

**Comment by nqhoa1005** [comment]
OK anh để em check lại

**Comment by nqhoa1005** [comment]
✅ Đã fix
Áp dụng thetrongtinh = 1 và tt40 = 1 sẽ thông báo xác nhận giấy chuyển tuyến để chọn được trái tuyến
![image](https://github.com/user-attachments/assets/2514a3af-d209-4073-9e5d-748a5a25a66a)
