### ISSUE TITLE
Lỗi - Không chuyển được chi phí thuốc qua thẻ BHYT 2

### ISSUE THREAD

**Issue by chauthanhtra** [dh-hos/dhg.hosptaltreatment#271]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.1: Phiếu ghi nhận lỗi phát sinh DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN LỖI PHÁT SINH</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Châu Thanh Trà**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **23/09/2024**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `92086`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **BV Ung Bướu**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `tra_ungbuou_kchuyendcchiphithuocquathe2_23092024`
-  ![port_csdl](https://img.shields.io/badge/Port%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `5434`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`](https://gofile.me/78TQg/kwQQSCrNF)

###### ![chi_tiet_loi](https://img.shields.io/badge/Chi%20tiết%20lỗi%20phát%20sinh-:-blue?style=for-the-badge&logo=github)

-  ![loi_benh_nhan](https://img.shields.io/badge/Chi%20tiết%20bệnh%20nhân-:-blue?style=plastic&logo=github)
   > _**MaBN**_: `2022053859` - _**MaKB**_: `2408003383` - _**MaBA**_: `016152` _**NgayKCB**_: `23/09/2024` - _**MaPhong**_: `MaPhong` - _**MaDV**_: `01` - _**ThangKT**_: `09` - _**NamKT**_: `2024`
-  ![loi_thuoc](https://img.shields.io/badge/Chi%20tiết%20thuốc-:-blue?style=plastic&logo=github)
   > _**KhoChan**_: `KhoChan` - _**KhoLe**_: `KhoLe` - _**MaHH**_: `MaHH` - _**SoHD**_: `SoHD` - _**NgayHD**_: `NgayHD` - _**ThangKT**_: `ThangKT` - _**NamKT**_: `NamKT`
-  ![loi_cls](https://img.shields.io/badge/Chi%20tiết%20CLS-:-blue?style=plastic&logo=github)
   > _**MaCLS**_: `MaCLS` - _**PhieuYC**_: `PhieuYC`
-  ![loi_bo_sung](https://img.shields.io/badge/Chi%20tiết%20bổ%20sung-:-blue?style=plastic&logo=github)
   > _**Khac**_: `Khac`

###### ![mo_ta_loi](https://img.shields.io/badge/Mô%20tả%20thông%20tin%20lỗi-:-blue?style=for-the-badge&logo=github)

Bệnh nhân có thẻ BHYT số 2 nhưng không chuyển được chi phí thuốc từ thẻ 1 sang thẻ 2 mà chỉ chuyển được CLS sang thẻ 2

![](https://i.imgur.com/DDdQP9S.png)
![](https://i.imgur.com/LnwwWkA.png)

**Comment by vuongdh** [comment]
✔️ Đã tiếp nhận
👉 Thực hiện: Thực hiện các yêu cầu theo luồng công việc này.
📆 Thời gian hoàn thành : 2024-09-26

**Comment by vuongdh** [comment]
Do bệnh viện bật tham số chức năng sử dụng nhiều kho thuốc: khi bật tham số này, khi chuyển chi phí thuốc sẽ chọn được.
![image](https://github.com/user-attachments/assets/0e87e31f-a42b-4907-beb7-6f3e33d208de)
chỉnh tham số nt.nkho = 0 và hỗ trợ script cập nhật (nếu cần)

**Comment by vuongdh** [comment]
Hướng dẫn cập nhật:
1. Chỉnh tham số nt.nkho = 0
2. Chỉnh đối tượng và lưu lại

**Comment by chauthanhtra** [comment]
### **✔️KẾT QUẢ TEST**
***
Phần mềm Treatment 
***
>Lỗi, yêu cầu đã hoàn thành 

- Nội dung: 

  - Đã chuyển được chi phí KCB qua thẻ BHYT số 2 theo hướng dẫn của coder

- Hình ảnh: 

![](https://i.imgur.com/W3b0gpJ.png)
![](https://i.imgur.com/xPtsW08.png)
![](https://i.imgur.com/7MZlPg9.png)

***
> Trường hợp không đủ thông tin kiểm tra hoặc còn lỗi ghi nhận phản hồi cho CO.

> - Diễn giải lỗi:
>   - 
> 
> - Hình ảnh lỗi:
> 


> Hình ảnh Phiếu 01, 02, xuất XML.

> Nhập thuốc -> xuất thuốc -> tổng hợp.

> Hình ảnh chứng mình cho việc kiểm tra này.

> Mô tả, hướng dẫn sử dụng chức năng cập nhật (nếu có).
***
##### 
>Phát sinh lỗi chức năng hiện tại -> Ghi nhận lỗi và ngưng test các vấn đề còn lại.
