### ISSUE TITLE
Lỗi - Treatment Chưa lấy [Chỉ định ] theo tài khoản đăng nhập trong form Thêm Toa thuốc BV Nhi Đồng

### ISSUE THREAD

**Issue by hvtuan1987** [dh-hos/dhg.hosptaltreatment#272]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.1: Phiếu ghi nhận lỗi phát sinh DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN LỖI PHÁT SINH</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Hà Văn Tuấn**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **24/09/2024**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `92003`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **Bệnh viện Nhi Đồng**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `tuan_dbnhidong_xml7_ko`
-  ![port_csdl](https://img.shields.io/badge/Port%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `5434`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`](https://gofile.me/78TQg/cPdZhsYK0)

###### ![chi_tiet_loi](https://img.shields.io/badge/Chi%20tiết%20lỗi%20phát%20sinh-:-blue?style=for-the-badge&logo=github)

-  ![loi_benh_nhan](https://img.shields.io/badge/Chi%20tiết%20bệnh%20nhân-:-blue?style=plastic&logo=github)
   > _**MaBN**_: `2024074139` - _**MaKB**_: `2408028485` - _**MaBA**_: `2024024396` _**NgayKCB**_: `24/09/2024` - _**MaPhong**_: `MaPhong` - _**MaDV**_: `19` - _**ThangKT**_: `09` - _**NamKT**_: `2024`
-  ![loi_thuoc](https://img.shields.io/badge/Chi%20tiết%20thuốc-:-blue?style=plastic&logo=github)

###### ![mo_ta_loi](https://img.shields.io/badge/Mô%20tả%20thông%20tin%20lỗi-:-blue?style=for-the-badge&logo=github)

Theo đặc thù của Bệnh viện Nhi Đồng lúc trước khi đăng nhập cho toa nội trú cột **Chỉ định** load chỉ định theo tài khoản đăng nhập vào module Treatment. Nhưng module Treatment phiên bản 4.24.0916.0 khi bấm Enter hoặc phím F2 cột chỉ định thì Load theo tài khoản bác sĩ ra toa.
Bệnh viện yêu cầu hỗ trợ load cột chỉ định theo tài khoản đăng nhập lại như ban đầu
Hình ra toa tại Treatment hiện tại
![image](https://github.com/user-attachments/assets/05eccee0-9d74-4d38-949f-a1ee990caec0)

Hình cột chỉ định theo tài khoản đăng nhập hiện tại
![image](https://github.com/user-attachments/assets/a0af2cb4-5aba-4c38-8566-695e97011b3e)

**Comment by vuongdh** [comment]
✔️ Đã tiếp nhận
👉 Thực hiện: Thực hiện các yêu cầu theo luồng công việc này.
📆 Thời gian hoàn thành : 2024-09-26

**Comment by vuongdh** [comment]
@hvtuan1987 Trước giờ nội trú lấy chỉnh định theo mã số bs ra toa,  nói module cũ lấy theo tài khoản đăng nhập là không chính xác, tài khoản điều dưỡng đâu có lập chỉ định uống, nội trú điều dưỡng nhập phiếu (có thể bv nhầm lẫn với một chức nào nào đó)

![image](https://github.com/user-attachments/assets/15801248-853c-4830-8a7f-c81282032ed4)

![image](https://github.com/user-attachments/assets/87657eae-883e-4d1a-a284-d4b5781dcd9c)
 P/s: Em xem lại và nếu bệnh viện vẫn muốn load chỉnh định uống theo tài khoản đăng nhập thì em lập yêu cầu thực hiện nha.

**Comment by hvtuan1987** [comment]
@vuongdh Dạ! Xác nhận phản hồi ý anh trên là đúng!
Em đóng gibth này á !
