### ISSUE TITLE
Lỗi - Treatment Bệnh nhân có thẻ BHYT 2 trả thuốc bên thẻ 2 lỗi

### ISSUE THREAD

**Issue by hvtuan1987** [dh-hos/dhg.hosptaltreatment#274]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.1: Phiếu ghi nhận lỗi phát sinh DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN LỖI PHÁT SINH</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Hà Văn Tuấn**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **02/10/2024**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `92003`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **Bệnh viện Nhi Đồng**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `tuan_dbnhidong_trathuoc_the2`
-  ![port_csdl](https://img.shields.io/badge/Port%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `5434`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`](https://gofile.me/78TQg/tBKPWHOs9)

###### ![chi_tiet_loi](https://img.shields.io/badge/Chi%20tiết%20lỗi%20phát%20sinh-:-blue?style=for-the-badge&logo=github)

-  ![loi_benh_nhan](https://img.shields.io/badge/Chi%20tiết%20bệnh%20nhân-:-blue?style=plastic&logo=github)
   > _**MaBN**_: `2023164912` - _**MaKB**_: `2409034772` - _**MaBA**_: `2024028979` _**NgayKCB**_: `02/10/2024` - _**MaPhong**_: `MaPhong` - _**MaDV**_: `08` - _**ThangKT**_: `09` - _**NamKT**_: `2024`
-  ![loi_thuoc](https://img.shields.io/badge/Chi%20tiết%20thuốc-:-blue?style=plastic&logo=github)

###### ![mo_ta_loi](https://img.shields.io/badge/Mô%20tả%20thông%20tin%20lỗi-:-blue?style=for-the-badge&logo=github)

Bệnh nhân có Thông tin thẻ BHYT 2: Thuốc bệnh nhân đã lĩnh bên thẻ 2 khi chọn thuốc cần trả lại gõ số lượng cần trả và bấm Enter hoặc nút thêm thì thuốc cần trả không hiển thị được trên lưới. Khi bấm lưu Treatment báo không có dữ liệu và xuất hiện hộp thội  như hình dưới.
Chọn BHYT SỐ 2 và bấm vào Trả thuốc như hình dưới (Trả tất cả các loại thuốc đều bị lỗi như nhau)
![image](https://github.com/user-attachments/assets/36a5e1e9-8bd3-4a77-8afc-5cb88c40bd9d)
Hình chọn thuốc cần trả
![image](https://github.com/user-attachments/assets/05eda4ba-031f-47cb-bc89-b83d01f2d578)
Hình sau khi bấm nút Thêm hoặc Enter
![image](https://github.com/user-attachments/assets/f880b816-a316-43dc-a6dd-849bb8db309d)

HÌnh bấm nút Lưu để kiểm tra thử 
![image](https://github.com/user-attachments/assets/dc5501bf-fbe5-4ae2-a5ee-7681ab82998b)

**Comment by vuongdh** [comment]
✔️ Đã tiếp nhận
👉 Thực hiện: Thực hiện các yêu cầu theo luồng công việc này.
📆 Thời gian hoàn thành : 2024-10-08.

**Comment by gh-dh-bot-01** [comment]
### 📣📣📣 Treatment.exe v.4.24.1004.0 [⬇️OneDrive](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FTreatmentexe%2F42410040-OneDrive.json) [⬇️GoogleStorage](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FTreatmentexe%2F42410040-GoogleStorage.json) [⬇️NasDHSolutions](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FTreatmentexe%2F42410040-NasDHSolutions.json)

## Nội dung thay đổi

- 🐛: Fix lỗi - Treatment Bệnh nhân có thẻ BHYT 2 trả thuốc bên thẻ 2 lỗi #274

![image](https://github.com/user-attachments/assets/8d181f7f-574d-4879-8d7f-bbd7e67a9919)

![image](https://github.com/user-attachments/assets/7d71480c-856b-400e-be9c-2a8a810953c8)

![image](https://github.com/user-attachments/assets/4e437c74-b4bd-4570-aaf7-a3b8f9028672)

- ☑: https://github.com/dh-hos/dhg.hosptaltreatment/issues/274

<div align="right">

 [![](https://img.shields.io/badge/-Th%E1%BB%B1c%20hi%E1%BB%87n%20b%E1%BB%9Fi%3A%20%40vuongdh-informational?logo=github)](https://github.com/vuongdh) [![](https://img.shields.io/badge/-Xem%20l%E1%BB%8Bch%20s%E1%BB%AD%20phi%C3%AAn%20b%E1%BA%A3n-informational?logo=github)](https://github.com/dh-hos-code/Treatment.exe?tab=readme-ov-file#readme) [![](https://img.shields.io/badge/Nh%E1%BA%ADn%20th%C3%B4ng%20b%C3%A1o%20tr%C3%AAn%20Telegram-2CA5E0?style=flat-squeare&logo=telegram&logoColor=white)](https://t.me/dhhoscodemsifiles)
</div>
