### ISSUE TITLE
Lỗi - GHI NHẬN SAI THÁNG QUYẾT TOÁN KHI KẾT THÚC HỒ SƠ THÁNG CŨ

### ISSUE THREAD

**Issue by nqhoa1005** [dh-hos/dhg.hosptaltreatment#275]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.1: Phiếu ghi nhận lỗi phát sinh DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN LỖI PHÁT SINH</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **NGUYỄN QUỐC HOÀ**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **07/10/2024**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `94006`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **BVĐK H.THẠNH TRỊ**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `hoa_thanhtri_full_24092024`
-  ![port_csdl](https://img.shields.io/badge/Port%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `5434`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`](https://gofile.me/78TQg/Oi8YIgvrM)

###### ![chi_tiet_loi](https://img.shields.io/badge/Chi%20tiết%20lỗi%20phát%20sinh-:-blue?style=for-the-badge&logo=github)

-  ![loi_benh_nhan](https://img.shields.io/badge/Chi%20tiết%20bệnh%20nhân-:-blue?style=plastic&logo=github)
   > _**MaBN**_: `2024011171` - _**MaKB**_: `MaKB` - _**MaBA**_: `2024007626` _**NgayKCB**_: `NgayKCB` - _**MaPhong**_: `MaPhong` - _**MaDV**_: `01` - _**ThangKT**_: `ThangKT` - _**NamKT**_: `NamKT`
-  ![loi_thuoc](https://img.shields.io/badge/Chi%20tiết%20thuốc-:-blue?style=plastic&logo=github)
   > _**KhoChan**_: `KhoChan` - _**KhoLe**_: `KhoLe` - _**MaHH**_: `MaHH` - _**SoHD**_: `SoHD` - _**NgayHD**_: `NgayHD` - _**ThangKT**_: `ThangKT` - _**NamKT**_: `NamKT`
-  ![loi_cls](https://img.shields.io/badge/Chi%20tiết%20CLS-:-blue?style=plastic&logo=github)
   > _**MaCLS**_: `MaCLS` - _**PhieuYC**_: `PhieuYC`
-  ![loi_bo_sung](https://img.shields.io/badge/Chi%20tiết%20bổ%20sung-:-blue?style=plastic&logo=github)
   > _**Khac**_: `Khac`

###### ![mo_ta_loi](https://img.shields.io/badge/Mô%20tả%20thông%20tin%20lỗi-:-blue?style=for-the-badge&logo=github)

khi sử dụng với tham số nt.raviendungngay = 1
Trường hợp khi đã qua tháng mới nhưng người dùng kết thúc hồ sơ có ngày ra viện thuộc tháng cũ thì phải kết thúc ngày hiện tại trước 
- Trường hợp này thời điểm sinh ra XML sẽ ghi nhận tháng ra viện và tháng quyết toán là tháng hiện tại.
![image](https://github.com/user-attachments/assets/b494f250-10ac-497a-8a6c-c31d3a9ed525)

Sau đó mới sử dụng chức năng Chỉnh thông tin bệnh nhân nội trú để chỉnh ngày ra viện và cập nhật lại tháng ra viện tại admin
![image](https://github.com/user-attachments/assets/5e217be2-e1bd-4295-9b80-3dea3cb713de)
![image](https://github.com/user-attachments/assets/e1afbbb2-3d57-43d6-b5b8-03592d93566f)

Tuy nhiên khi đăng nhập về tháng cũ để chỉnh lại ngày ra viện thuộc tháng cũ thì phần mềm không cập nhật lại tháng quyết toán cho XML đồng thời giữ nguyên malk có thông tin tháng quyết toán là tháng mới nên xuất 4750 từ admin sẽ không thấy hồ sơ đó để gửi cổng gây thiếu hồ sơ.  

![image](https://github.com/user-attachments/assets/b6534125-4edf-4ea2-b432-c7bfe77a829f)
![image](https://github.com/user-attachments/assets/31fb20cc-a4a6-40bf-a64f-8ad774ab6045)

--

Tại chức năng Chỉnh thông tin bệnh nhân nội trú hiện tại cũng chưa ràng buộc ngày ra viện phải lớn hơn ngày kết quả GB 
![image](https://github.com/user-attachments/assets/9cbf7096-784b-4dbe-a56a-dba653631da1)
![image](https://github.com/user-attachments/assets/eac48faa-8a2e-4f02-b493-90791256820e)

✴️ Đề nghị :
- Fix Kiểm tra xử lý lại thông tin XML sau khi đã phát sinh nếu người dùng cập nhật lại ngày ra viện cho đúng tháng quyết toán, tháng ra viện.

❗❗❗ Lưu ý : trường hợp nếu ngày ra viện là ngày giao thoa giữa 2 tháng kế toán thì chức năng Kiểm tra tháng ra viện nội trú trên Admin cũng không thấy để cập nhật lại nên khi chỉnh ngày ra viện em đề xuất auto xoá và xuất lại XML nếu chỉnh ngày ra viện về tháng cũ (thoã điều kiện để có hồ sơ xuất 4750 trên Admin để người dùng không gửi sót).

- Ràng buộc ngày ra viện phải lớn hơn ngày kết quả CLS và giường bệnh.

**Comment by ongtrieuhau-dh** [comment]
## HD.05 [^HD05]
-  ✔️ **Đã tiếp nhận** 
- ⌛ Thời gian hoàn thành dự kiến: **2024-10-14**


[^HD05]: Thời gian phải tiếp nhận ( Bình thường: 120 phút. Gấp: 60 phút) [Đối với các BL “Gấp” thời gian xử lý 4h, trường hợp không kịp bắc buộc phải đề ra các khắc phục tạm thời (Sql, lùi bản cũ…); Mức độ ưu tiên các lỗi “Gấp”: GĐ, tổ trưởng CO, tổ trưởng HT, tổ trưởng TK, nhân viên HT, nhân viên TK.]

**Comment by vuongdh** [comment]
✔️ Đã tiếp nhận
⌛ Thời gian hoàn thành dự kiến: 2024-10-14

**Comment by ongtrieuhau-dh** [comment]
### ✅ TỔ LẬP TRÌNH - HOÀN THÀNH ✅
-  📣 **Nhờ kiểm tra sản phẩm**: @nqhoa1005 @lqbinh1987 liên quan tới XML4750
- Đã thực hiện theo luồng công việc này: [Lỗi - BA TRẢ VỀ ĐIỀU TRỊ KẾT THÚC TẠI THÁNG MỚI GHI NHẬN SAI THÔNG TIN TRÊN 4750](https://github.com/dh-hos/dhg.hosptaltreatment/issues/276)

**Comment by ongtrieuhau-dh** [comment]
## HD.05 [^HD05]
-  ❌ **Từ chối tiếp nhận** 
- 📣 **Nguyên nhân**: ***Không tiếp nhận lỗi chưa bắt ngày giờ. Lý do tách riêng công việc theo qui định của công ty. Tiêu đề để là Lỗi - GHI NHẬN SAI THÁNG QUYẾT TOÁN KHI KẾT THÚC HỒ SƠ THÁNG CŨ***


[^HD05]: Thời gian phải tiếp nhận ( Bình thường: 120 phút. Gấp: 60 phút) [Đối với các BL “Gấp” thời gian xử lý 4h, trường hợp không kịp bắc buộc phải đề ra các khắc phục tạm thời (Sql, lùi bản cũ…); Mức độ ưu tiên các lỗi “Gấp”: GĐ, tổ trưởng CO, tổ trưởng HT, tổ trưởng TK, nhân viên HT, nhân viên TK.] Nghĩa vụ: ghi nhận vi phạm nếu có tại HD.04, phản hồi
đủ thông tin

**Comment by nqhoa1005** [comment]
✅ HOÀN THÀNH
👉 Đã kiểm soát khi chỉnh ngày ra và cập nhật tháng ra viện theo https://github.com/dh-hos/dhg.hosptaltreatment/issues/276
