### ISSUE TITLE
Lỗi - CHỈNH DIỄN BIẾN MẤT CHẨN ĐOÁN PHỤ TOA THUỐC TRÊN FORM, TRANG IN

### ISSUE THREAD

**Issue by nqhoa1005** [dh-hos/dhg.hosptaltreatment#277]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.1: Phiếu ghi nhận lỗi phát sinh DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN LỖI PHÁT SINH</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **NGUYỄN QUỐC HOÀ**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **14/10/2024**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `92004`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **BV ĐKTP CẦN THƠ**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `hoa_dktpct_102024092024`
-  ![port_csdl](https://img.shields.io/badge/Port%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `5434`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`](https://gofile.me/78TQg/4VVaBufOZ)

###### ![chi_tiet_loi](https://img.shields.io/badge/Chi%20tiết%20lỗi%20phát%20sinh-:-blue?style=for-the-badge&logo=github)

-  ![loi_benh_nhan](https://img.shields.io/badge/Chi%20tiết%20bệnh%20nhân-:-blue?style=plastic&logo=github)
   > _**MaBN**_: `2024068118` - _**MaKB**_: `MaKB` - _**MaBA**_: `033564` _**NgayKCB**_: `NgayKCB` - _**MaPhong**_: `MaPhong` - _**MaDV**_: `06` - _**ThangKT**_: `10` - _**NamKT**_: `2024`
-  ![loi_thuoc](https://img.shields.io/badge/Chi%20tiết%20thuốc-:-blue?style=plastic&logo=github)
   > _**KhoChan**_: `KhoChan` - _**KhoLe**_: `KhoLe` - _**MaHH**_: `MaHH` - _**SoHD**_: `SoHD` - _**NgayHD**_: `NgayHD` - _**ThangKT**_: `ThangKT` - _**NamKT**_: `NamKT`
-  ![loi_cls](https://img.shields.io/badge/Chi%20tiết%20CLS-:-blue?style=plastic&logo=github)
   > _**MaCLS**_: `MaCLS` - _**PhieuYC**_: `PhieuYC`
-  ![loi_bo_sung](https://img.shields.io/badge/Chi%20tiết%20bổ%20sung-:-blue?style=plastic&logo=github)
   > _**Khac**_: `Khac`

###### ![mo_ta_loi](https://img.shields.io/badge/Mô%20tả%20thông%20tin%20lỗi-:-blue?style=for-the-badge&logo=github)

Sau khi đổi diễn biến và cho toa thuốc ra ngoài chỉnh diễn biến thì vào lại toa thuốc mất tên chẩn đoán phụ trên form và trên phiếu công khai thuốc.

> Dữ liệu em thấy toa thuốc vẫn cập nhật theo chẩn đoán của qtdieutri khi chỉnh diễn biến nhưng trên form thì lại thiếu.

Clip test 
https://github.com/user-attachments/assets/c78d3928-f94c-4891-b29a-c9fa4634e012
![image](https://github.com/user-attachments/assets/c6e6d38e-270d-4837-b6fd-d8fea3214790)

**Comment by vuongdh** [comment]
✔️ Đã tiếp nhận
⌛ Thời gian hoàn thành dự kiến: 2024-10-15

**Comment by gh-dh-bot-01** [comment]
### 📣📣📣 Treatment.exe v.4.24.1015.0 [⬇️OneDrive](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FTreatmentexe%2F42410150-OneDrive.json) [⬇️GoogleStorage](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FTreatmentexe%2F42410150-GoogleStorage.json) [⬇️NasDHSolutions](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FTreatmentexe%2F42410150-NasDHSolutions.json)

## Nội dung thay đổi

- 🐛: Fix lỗi - CHỈNH DIỄN BIẾN MẤT CHẨN ĐOÁN PHỤ TOA THUỐC TRÊN FORM, TRANG IN #277

- Cập nhật: chọn diễn biến có toa bị lỗi --> cập nhật --> lưu

![image](https://github.com/user-attachments/assets/e537a769-4160-4d75-bdff-07729dd65846)

- ☑: https://github.com/dh-hos/dhg.hosptaltreatment/issues/277

<div align="right">

 [![](https://img.shields.io/badge/-Th%E1%BB%B1c%20hi%E1%BB%87n%20b%E1%BB%9Fi%3A%20%40vuongdh-informational?logo=github)](https://github.com/vuongdh) [![](https://img.shields.io/badge/-Xem%20l%E1%BB%8Bch%20s%E1%BB%AD%20phi%C3%AAn%20b%E1%BA%A3n-informational?logo=github)](https://github.com/dh-hos-code/Treatment.exe?tab=readme-ov-file#readme) [![](https://img.shields.io/badge/Nh%E1%BA%ADn%20th%C3%B4ng%20b%C3%A1o%20tr%C3%AAn%20Telegram-2CA5E0?style=flat-squeare&logo=telegram&logoColor=white)](https://t.me/dhhoscodemsifiles)
</div>

**Comment by nqhoa1005** [comment]
❌ **CHƯA ĐẠT YÊU CẦU** ❌ 
- ❗❗ Phát sinh lỗi trong quá trình test
![image](https://github.com/user-attachments/assets/2ed72f19-edbc-4b8d-90db-f46a29607e4b)
Em đã kiểm tra cấu trúc thì không có thiếu cấu trúc
![image](https://github.com/user-attachments/assets/6409386e-c326-4756-acf0-b9af3e2eb83a)

Check lại dùm em
---
- ✳️ Lần test : 1
- ❗❗ Dừng test các chức năng liên quan.

**Comment by vuongdh** [comment]
Dữ liệu test:
![image](https://github.com/user-attachments/assets/47bfcef6-3391-4093-89c6-6da66825a64a)
Kết quả thêm  toa thuốc:
![image](https://github.com/user-attachments/assets/58f3028c-9235-4abf-a80e-734c0f215b3e)

**Comment by vuongdh** [comment]
Cùng 1 phiên bản mà ta, để anh build lai xem
![image](https://github.com/user-attachments/assets/7c2bc352-2f7c-434d-ba00-d5850e904cea)

**Comment by nqhoa1005** [comment]
em thêm toa mới hay lấy lại toa cũ miễn bấm lưu là ra lỗi à

**Comment by gh-dh-bot-01** [comment]
### 📣📣📣 Treatment.exe v.4.24.1015.1 [⬇️OneDrive](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FTreatmentexe%2F42410151-OneDrive.json) [⬇️GoogleStorage](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FTreatmentexe%2F42410151-GoogleStorage.json) [⬇️NasDHSolutions](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FTreatmentexe%2F42410151-NasDHSolutions.json)

## Nội dung thay đổi

- 🐛: Fix lỗi - CHỈNH DIỄN BIẾN MẤT CHẨN ĐOÁN PHỤ TOA THUỐC TRÊN FORM, TRANG IN #277

- Cập nhật: chọn diễn biến có toa bị lỗi --> cập nhật --> lưu

![image](https://github.com/user-attachments/assets/e537a769-4160-4d75-bdff-07729dd65846)

- ☑: https://github.com/dh-hos/dhg.hosptaltreatment/issues/277

<div align="right">

 [![](https://img.shields.io/badge/-Th%E1%BB%B1c%20hi%E1%BB%87n%20b%E1%BB%9Fi%3A%20%40vuongdh-informational?logo=github)](https://github.com/vuongdh) [![](https://img.shields.io/badge/-Xem%20l%E1%BB%8Bch%20s%E1%BB%AD%20phi%C3%AAn%20b%E1%BA%A3n-informational?logo=github)](https://github.com/dh-hos-code/Treatment.exe?tab=readme-ov-file#readme) [![](https://img.shields.io/badge/Nh%E1%BA%ADn%20th%C3%B4ng%20b%C3%A1o%20tr%C3%AAn%20Telegram-2CA5E0?style=flat-squeare&logo=telegram&logoColor=white)](https://t.me/dhhoscodemsifiles)
</div>

**Comment by gh-dh-bot-01** [comment]
### 📣📣📣 Treatment.exe v.4.24.1015.2 [⬇️OneDrive](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FTreatmentexe%2F42410152-OneDrive.json) [⬇️GoogleStorage](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FTreatmentexe%2F42410152-GoogleStorage.json) [⬇️NasDHSolutions](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FTreatmentexe%2F42410152-NasDHSolutions.json)

## Nội dung thay đổi

- 🐛: Fix lỗi - CHỈNH DIỄN BIẾN MẤT CHẨN ĐOÁN PHỤ TOA THUỐC TRÊN FORM, TRANG IN #277

- Cập nhật: chọn diễn biến có toa bị lỗi --> cập nhật --> lưu

![image](https://github.com/user-attachments/assets/e537a769-4160-4d75-bdff-07729dd65846)

- ☑: https://github.com/dh-hos/dhg.hosptaltreatment/issues/277

<div align="right">

 [![](https://img.shields.io/badge/-Th%E1%BB%B1c%20hi%E1%BB%87n%20b%E1%BB%9Fi%3A%20%40vuongdh-informational?logo=github)](https://github.com/vuongdh) [![](https://img.shields.io/badge/-Xem%20l%E1%BB%8Bch%20s%E1%BB%AD%20phi%C3%AAn%20b%E1%BA%A3n-informational?logo=github)](https://github.com/dh-hos-code/Treatment.exe?tab=readme-ov-file#readme) [![](https://img.shields.io/badge/Nh%E1%BA%ADn%20th%C3%B4ng%20b%C3%A1o%20tr%C3%AAn%20Telegram-2CA5E0?style=flat-squeare&logo=telegram&logoColor=white)](https://t.me/dhhoscodemsifiles)
</div>
