### ISSUE TITLE
Lỗi - Treatment Phiếu tai nạn hiển thị sai giờ xảy ra tai nạn

### ISSUE THREAD

**Issue by hvtuan1987** [dh-hos/dhg.hosptaltreatment#280]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.1: Phiếu ghi nhận lỗi phát sinh DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN LỖI PHÁT SINH</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Hà Văn Tuấn**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **18/10/2024**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `Tất cả`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **Tất cả**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `tuan_dbdalieuct_qtdieutri`
-  ![port_csdl](https://img.shields.io/badge/Port%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `5434`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`](https://gofile.me/78TQg/SwdEmoYT9)

###### ![chi_tiet_loi](https://img.shields.io/badge/Chi%20tiết%20lỗi%20phát%20sinh-:-blue?style=for-the-badge&logo=github)

-  ![loi_benh_nhan](https://img.shields.io/badge/Chi%20tiết%20bệnh%20nhân-:-blue?style=plastic&logo=github)
   > _**MaBN**_: `2024059261` - _**MaKB**_: `2410004531` - _**MaBA**_: `003105` _**NgayKCB**_: `18/10/2024` - _**MaPhong**_: `B15` - _**MaDV**_: `02` - _**ThangKT**_: `10` - _**NamKT**_: `2024`

Bệnh nhân điều trị nội trú khi vào Chăm sóc-> Tai nạn ->Cột Ngày giờ xảy ra:  Người dùng cập nhật ngày giờ nhưng khi vào xem lại thì chổ giờ phút giây lại hiển thị 00:00:00  như hình dưới
![image](https://github.com/user-attachments/assets/42bb4ee1-ad6d-4166-a8f5-99bc31f9dedb)
Người dùng bấm cập nhật và nhập ngày giờ xảy ra
![image](https://github.com/user-attachments/assets/9134ca32-d2d1-417b-9f7b-2156d962380e)
Hình khi Đóng form và vào lại
![image](https://github.com/user-attachments/assets/c7feefa7-ff84-49d7-9f90-05990f861ddd)

**Comment by vuongdh** [comment]
✔️ Đã tiếp nhận
👉 Thực hiện: Thực hiện các yêu cầu theo luồng công việc này.
📆 Thời gian hoàn thành : 2024-11-01

**Comment by gh-dh-bot-01** [comment]
### 📣📣📣 Treatment.exe v.4.24.1022.2 [⬇️OneDrive](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FTreatmentexe%2F42410222-OneDrive.json) [⬇️GoogleStorage](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FTreatmentexe%2F42410222-GoogleStorage.json) [⬇️NasDHSolutions](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FTreatmentexe%2F42410222-NasDHSolutions.json)

## Nội dung thay đổi

- 🐛: Lỗi - Treatment Phiếu tai nạn hiển thị sai giờ xảy ra tai nạn #280

- Cập nhật:

- Bổ sung cấu trúc

![image](https://github.com/user-attachments/assets/9f068d8c-2693-4f9b-960c-cee6139c8191)

- Cập nhật phần mềm:

![image](https://github.com/user-attachments/assets/864aba46-5b71-4aff-a665-0e22be390199)

![image](https://github.com/user-attachments/assets/3fb0cb72-3c97-4025-8ff5-2917572bf18f)

- ☑: https://github.com/dh-hos/dhg.hosptaltreatment/issues/280

<div align="right">

 [![](https://img.shields.io/badge/-Th%E1%BB%B1c%20hi%E1%BB%87n%20b%E1%BB%9Fi%3A%20%40vuongdh-informational?logo=github)](https://github.com/vuongdh) [![](https://img.shields.io/badge/-Xem%20l%E1%BB%8Bch%20s%E1%BB%AD%20phi%C3%AAn%20b%E1%BA%A3n-informational?logo=github)](https://github.com/dh-hos-code/Treatment.exe?tab=readme-ov-file#readme) [![](https://img.shields.io/badge/Nh%E1%BA%ADn%20th%C3%B4ng%20b%C3%A1o%20tr%C3%AAn%20Telegram-2CA5E0?style=flat-squeare&logo=telegram&logoColor=white)](https://t.me/dhhoscodemsifiles)
</div>

**Comment by hvtuan1987** [comment]
-  ✔️ **Xác nhận Treatment đã lấy đúng theo yêu cầu trên**
![image](https://github.com/user-attachments/assets/167b641c-d2cb-4fed-bbaf-5a450f3e7c64)
