### ISSUE TITLE
Lỗi - CẬP NHẬT TRÁI TUYẾN KHI CHỈNH ĐỐI TƯỢNG => XUẤT XML1.MA_DOITUONG_KCB = 9

### ISSUE THREAD

**Issue by nqhoa1005** [dh-hos/dhg.hosptaltreatment#281]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.1: Phiếu ghi nhận lỗi phát sinh DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN LỖI PHÁT SINH</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **NGUYỄN QUỐC HOÀ**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **21/10/2024**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `94006`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **BVĐK H.THẠNH TRỊ**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `hoa_dbthanhtri_102024`
-  ![port_csdl](https://img.shields.io/badge/Port%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `5434`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`](https://gofile.me/78TQg/BY0O0jHXm)

###### ![chi_tiet_loi](https://img.shields.io/badge/Chi%20tiết%20lỗi%20phát%20sinh-:-blue?style=for-the-badge&logo=github)

-  ![loi_benh_nhan](https://img.shields.io/badge/Chi%20tiết%20bệnh%20nhân-:-blue?style=plastic&logo=github)
   > _**MaBN**_: `2024012015` - _**MaKB**_: `2410006145` - _**MaBA**_: `2024008337` _**NgayKCB**_: `NgayKCB` - _**MaPhong**_: `MaPhong` - _**MaDV**_: `18` - _**ThangKT**_: `10` - _**NamKT**_: `2024`
-  ![loi_thuoc](https://img.shields.io/badge/Chi%20tiết%20thuốc-:-blue?style=plastic&logo=github)
   > _**KhoChan**_: `KhoChan` - _**KhoLe**_: `KhoLe` - _**MaHH**_: `MaHH` - _**SoHD**_: `SoHD` - _**NgayHD**_: `NgayHD` - _**ThangKT**_: `ThangKT` - _**NamKT**_: `NamKT`
-  ![loi_cls](https://img.shields.io/badge/Chi%20tiết%20CLS-:-blue?style=plastic&logo=github)
   > _**MaCLS**_: `MaCLS` - _**PhieuYC**_: `PhieuYC`
-  ![loi_bo_sung](https://img.shields.io/badge/Chi%20tiết%20bổ%20sung-:-blue?style=plastic&logo=github)
   > _**Khac**_: `Khac`

###### ![mo_ta_loi](https://img.shields.io/badge/Mô%20tả%20thông%20tin%20lỗi-:-blue?style=for-the-badge&logo=github)

❌ Khi chỉnh đối tượng => chọn Không trên bảng thông báo "Có giấy chuyển tuyến không?" thì phần mềm cập nhật lại trạng thái "Trái tuyến" 
👉 Kiểm tra qua thì thấy chỉ update lại bnnoitru.tuyen = 1 nhưng bnnoitru.tuyenxml vẫn = 0 nên khi xuất XML thì XML1.MA_DOITUONG_KCB = 9 => Cổng trả về lỗi sai lý do vào viện.
![image](https://github.com/user-attachments/assets/1b2eb806-6f79-4c56-9f8d-66c807f81c88)
![image](https://github.com/user-attachments/assets/9c1620ff-4b7d-4af8-b902-07fbe5bfa944)

- Khi ở trạng thái này thì chạy cập nhật chi phí trên 4210 và Đối soát trên 130 cũng không cập nhật lại đúng được XML1.MA_DOITUONG_KCB
![image](https://github.com/user-attachments/assets/9e31baf6-7e23-4650-af88-3fd5d15c3175)
![image](https://github.com/user-attachments/assets/e3df596e-1c36-48c3-8d1d-d6b1e0ddbe0f)
❌ Kết quả sau khi đã chạy cập nhật
![image](https://github.com/user-attachments/assets/64a835aa-cc25-4d4d-af96-b966e64b03e0)
![image](https://github.com/user-attachments/assets/8c1a187b-a731-4458-9b43-0b889409b1fb)

👉 Các trường hợp này phải hỗ trợ chỉnh trực tiếp vào dữ liệu bnnoitru.tuyen = 0 và bnnoitru.tuyenxml = 1 chạy cập nhật chi phí trên 4210 thì mới update XML lại đúng thông tin.

- ✔️ VD Trường hợp đúng :
 Bệnh nhân trái tuyến thì bnnoitru.tuyen = 0 và bnnoitru.tuyenxml = 1 sẽ hiển thị **Trái tuyến (Đ.cùng tuyến)** sẽ ra đúng XML1.MA_DOITUONG_KCB = 3.3
![image](https://github.com/user-attachments/assets/809c93fd-a041-4782-a5e1-ca7ea264903d)
![image](https://github.com/user-attachments/assets/19e68e49-8b26-45fa-b51e-5bfe68ffeb17)

✴️ Fix lại thao tác người dùng để xác định đúng tuyến/trái tuyến đồng bộ bnnoitru.tuyen và bnnoitru.tuyenxml để lấy đúng thông tin lên XML.
- 👉 Hiện đã có [Mô tả bổ sung](https://github.com/dh-hos/Mo-ta-he-thong/blob/main/XML130/QD4570/M%C3%B4%20t%E1%BA%A3%20XML130%20-%20B%E1%BB%95%20sung%20Q%C4%90%204750.md) để xác định tuyến đúng không hiển thị thông báo giấy chuyển tuyến nữa để tránh sai sót người dùng.

**Comment by vuongdh** [comment]
✔️ Đã tiếp nhận
👉 Thực hiện: Thực hiện các yêu cầu theo luồng công việc này.
📆 Thời gian hoàn thành : 2024-11-04

**Comment by nqhoa1005** [comment]
Đóng Git này mô tả rõ ràng lại theo https://github.com/dh-hos/dhg.hosptaltreatment/issues/282 để fix đúng chổ đang bị thao tác sai
