### ISSUE TITLE
Lỗi - Treament Form Lập phiếu TT/PT hiển thị mất thông tin khi độ phân giải màn hình 1024x768

### ISSUE THREAD

**Issue by hvtuan1987** [dh-hos/dhg.hosptaltreatment#285]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.1: Phiếu ghi nhận lỗi phát sinh DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN LỖI PHÁT SINH</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Hà Văn Tuấn**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **07/11/2024**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `87044`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **Bệnh viện Quân Dân Y Đồng Tháp**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `tuan_dbquandanydt_102024`
-  ![port_csdl](https://img.shields.io/badge/Port%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `5434`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`](https://gofile.me/78TQg/q5BqwD2mz)

###### ![chi_tiet_loi](https://img.shields.io/badge/Chi%20tiết%20lỗi%20phát%20sinh-:-blue?style=for-the-badge&logo=github)

-  ![loi_benh_nhan](https://img.shields.io/badge/Chi%20tiết%20bệnh%20nhân-:-blue?style=plastic&logo=github)
   > _**MaBN**_: `2024007636` - _**MaKB**_: `2410011300` - _**MaBA**_: `2024007636` _**NgayKCB**_: `07/11/2024` - _**MaPhong**_: `MaPhong` - _**MaDV**_: `03` - _**ThangKT**_: `10` - _**NamKT**_: `2024`

Do hiện tại các màn hình máy tính tại nhiều bệnh viện có độ phân giải thấp nên vào Treatment lập phiếu TTPT bị ẩn một số thông tin. Yêu cầu Treatment chỉnh lại Form này độ phân giải tối thiểu 1024 x 768 để hiển thị đầy đủ thông tin hoặc có phương án thiết kế phù hợp hỗ trợ đơn vị !
Form Lập phiếu Thủ thuật, Phẫu thuật bị ẩn các nút Thêm ekipt khi độ phân giải màn hình 1024 x 768
![image](https://github.com/user-attachments/assets/ba4186c5-61e0-4445-b28f-2d6e9cc3f501)

Form Lập phiếu Thủ thuật, Phẫu thuật bình thường với màn hình có độ phân giải lớn hơn 1024 x 768
![image](https://github.com/user-attachments/assets/d5ea820f-7f46-440d-b269-0d3a834c1df8)

**Comment by vuongdh** [comment]
✔️ Đã tiếp nhận
⌛ Thời gian hoàn thành dự kiến: 2024-11-08

**Comment by onghaup** [comment]
### 📣📣📣 Treatment.exe v.4.24.1108.0 <sub><sup><sup>[⬇️OneDrive](https://tolaptrinh.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2FdirectTo%2FTreatmentexe%2F42411080-OneDrive.json) [⬇️GoogleStorage](https://tolaptrinh.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2FdirectTo%2FTreatmentexe%2F42411080-GoogleStorage.json) [⬇️NasDHSolutions](https://tolaptrinh.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2FdirectTo%2FTreatmentexe%2F42411080-NasDHSolutions.json)</sup></sup></sub>

## Nội dung thay đổi


- 🐛: Lỗi - Treament Form Lập phiếu TT/PT hiển thị mất thông tin khi độ phân giải màn hình 1024x768 #285

- Cập nhật:

![image](https://github.com/user-attachments/assets/1adcb893-2825-4b0c-bc49-57d32942621a)

- ☑: https://github.com/dh-hos/dhg.hosptaltreatment/issues/285
<div align="right">

 [![](https://img.shields.io/badge/-Th%E1%BB%B1c%20hi%E1%BB%87n%20b%E1%BB%9Fi%3A%20%40vuongdh-informational?logo=github)](https://github.com/vuongdh) [![](https://img.shields.io/badge/-Xem%20l%E1%BB%8Bch%20s%E1%BB%AD%20phi%C3%AAn%20b%E1%BA%A3n-informational?logo=github)](https://github.com/tolaptrinh/Treatment.exe?tab=readme-ov-file#readme) [![](https://img.shields.io/badge/Nh%E1%BA%ADn%20th%C3%B4ng%20b%C3%A1o%20tr%C3%AAn%20Telegram-2CA5E0?style=flat-squeare&logo=telegram&logoColor=white)](https://t.me/dhhoscodemsifiles)
</div>

**Comment by hvtuan1987** [comment]
- ✔️ **Xác nhận Treatment đã Fix xong lỗi này** 
![image](https://github.com/user-attachments/assets/0a2db191-dcdd-423c-8b76-34ccef78e58e)
