### ISSUE TITLE
Lỗi - BV Ô Môn: Chẩn đoán kèm theo bảng kê 6556 ghép dư chẩn đoán YHCT

### ISSUE THREAD

**Issue by chauthanhtra** [dh-hos/dhg.hosptaltreatment#31]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.1: Phiếu ghi nhận lỗi phát sinh DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN LỖI PHÁT SINH</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Châu Thanh Trà**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **05/10/2022**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `92007`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **BV Ô Môn**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `tra_omon_chandoan`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`](link_csdl)

###### ![chi_tiet_loi](https://img.shields.io/badge/Chi%20tiết%20lỗi%20phát%20sinh-:-blue?style=for-the-badge&logo=github)

-  ![loi_benh_nhan](https://img.shields.io/badge/Chi%20tiết%20bệnh%20nhân-:-blue?style=plastic&logo=github)
   > _**MaBN**_: `2019015628` - _**MaKB**_: `2209021267` - _**MaBA**_: `2022012271` _**NgayKCB**_: `NgayKCB` - _**MaPhong**_: `MaPhong` - _**MaDV**_: `11` - _**ThangKT**_: `10` - _**NamKT**_: `2022`
-  ![loi_thuoc](https://img.shields.io/badge/Chi%20tiết%20thuốc-:-blue?style=plastic&logo=github)
   > _**KhoChan**_: `KhoChan` - _**KhoLe**_: `KhoLe` - _**MaHH**_: `MaHH` - _**SoHD**_: `SoHD` - _**NgayHD**_: `NgayHD` - _**ThangKT**_: `ThangKT` - _**NamKT**_: `NamKT`
-  ![loi_cls](https://img.shields.io/badge/Chi%20tiết%20CLS-:-blue?style=plastic&logo=github)
   > _**MaCLS**_: `MaCLS` - _**PhieuYC**_: `PhieuYC`
-  ![loi_bo_sung](https://img.shields.io/badge/Chi%20tiết%20bổ%20sung-:-blue?style=plastic&logo=github)
   > _**Khac**_: `Khac`

###### ![mo_ta_loi](https://img.shields.io/badge/Mô%20tả%20thông%20tin%20lỗi-:-blue?style=for-the-badge&logo=github)

- Khi toa thuốc có ghép mã YHCT thì trên bảng kê 6556 chẩn đoán kèm theo ghép dư tên chẩn đoán [YHCT] + tên ICD 10 khác

![ảnh](https://user-images.githubusercontent.com/97272332/193955881-d5dbe4cd-56d4-4abe-b823-b600476f37f5.png)
![ảnh](https://user-images.githubusercontent.com/97272332/193955922-63d65e01-a2d3-47ac-9b6b-839aae4642fa.png)
![ảnh](https://user-images.githubusercontent.com/97272332/193956091-7bf3324f-6a06-4579-94d0-72e6246bad60.png)
![ảnh](https://user-images.githubusercontent.com/97272332/193955975-6bf5e96e-53cd-4bfd-b5f1-0f3af082d75b.png)

**Comment by vuongdh** [comment]
@chauthanhtra Em test lại hén, cho ngoài cấu hình ICD là không được
![image](https://user-images.githubusercontent.com/32563776/193970002-7e9ddf27-4c2e-4e68-bf1a-0b5d60d7294d.png)

**Comment by chauthanhtra** [comment]
1. Phần mềm Treatment mới kết thúc điều trị cập nhật XML báo lỗi

Error [0]Message: Lỗi code [OTH.Adapter.HosBHXH.AGiamDinh.loadData].


Error [0]HResult: -2146233088
Error [0]Source: OTH.Adapter
Error [0]StackTrace:    at OTH.Adapter.HosBHXH.AGiamDinh.loadData()
   at OTH.Adapter.HosBHXH.XML917.XML917Local(String pMaBN, String pMaKB, String pMaBA, String pMaBATTConBH2, v_LoaiHoSoKCB pLoaiHSKCB, v_LoadBenhNhan vLoadBenhNhan, v_LoadDataFor vLoadDataFor)
   at HospitalTreatment.Forms.FrmXuatVien.ButtonRaVienClick(Object sender, EventArgs e)
Error [0]TargetSite: Void loadData()

Error [1]=== INNER EXCEPTION ===
Error [1]Message: Method not found: 'System.Nullable`1<System.Decimal> OTH.Entity.HosBHXH.EGiamDinh.TONG_HOP.get_psdangky_benhnhan_lao()'.
Error [1]HResult: -2146233069
Error [1]Source: OTH.Adapter
Error [1]StackTrace:    at OTH.Adapter.HosBHXH.AGiamDinh.IsBenhnhanLao_TTBYT362021()
   at OTH.Adapter.HosBHXH.AGiamDinh.loadData()
Error [1]TargetSite: Boolean IsBenhnhanLao_TTBYT362021()
![ảnh](https://user-images.githubusercontent.com/97272332/193980145-a732e6b2-a337-41f3-a346-ff9152f39f20.png)

2. kqchandoanxml bị trùng
![ảnh](https://user-images.githubusercontent.com/97272332/193980253-e3cf8da7-6ea4-46f9-8197-6c4ae8e5d9ed.png)

3. Chẩn đoán chính và chẩn đoán phụ trên bảng kê bị trùng
![ảnh](https://user-images.githubusercontent.com/97272332/193980366-65500933-0cde-4b3a-a12b-27fc758fd024.png)

**Comment by vuongdh** [comment]
@chauthanhtra hình dữ liệu bỏ 2 ô màu đỏ, để coi nó là gì: Chứng tý [Thoái hóa cột sống thắt lưng] và Chứng tý [Thoái hóa cột sống] thắt lưng là không loại trừ được

**Comment by chauthanhtra** [comment]
![ảnh](https://user-images.githubusercontent.com/97272332/194000984-603aaacc-9e0f-4ad2-b68e-ca14e8df7c57.png)
cách nhau dấu ;

**Comment by chauthanhtra** [comment]
ở đây có dấu cách rồi mới ;
![ảnh](https://user-images.githubusercontent.com/97272332/194001922-aec25db9-fa65-4177-9bbc-70b5f783e444.png)

**Comment by vuongdh** [comment]
@chauthanhtra Cập nhật lỗi khi xuất viện và lỗi khi xem phiếu 6556 [Bản cập nhật 4.22.1006v1](http://www.fsend.vn/download/GrkWX5h2mSfisfzFQXtsD7qsGUi-GsCl)

**Comment by vuongdh** [comment]
@chauthanhtra Lỗi xem phiếu 6556: phải trả về về điều trị và cho ra viện lại

**Comment by chauthanhtra** [comment]
- Kết quả chẩn đoán XML này gửi XML BV không chịu đâu anh (Chứng tý [Chứng tý [thoái hóa cột sống]] ;)
Chứng tý [Chứng tý [thoái hóa cột sống]] ;Bệnh trào ngược dạ dày - thực quản;Viêm đại tràng không xác định;thoái hóa cột sống;thắt lưng
![ảnh](https://user-images.githubusercontent.com/97272332/194214176-c7bd5547-a94a-4cea-85f6-a65db600808c.png)


- Có ''thoái hoá cột sống'' ở chẩn đoán chính rồi anh bỏ ở chẩn đoán phụ luôn được không?
![ảnh](https://user-images.githubusercontent.com/97272332/194213840-04912ef8-d384-4252-bffa-abec14da9851.png)

**Comment by chauthanhtra** [comment]
- Trường hợp bệnh nhân có chẩn đoán có dư khoảng cách ở cuối ICD A09.0 ở 1 số vị trí, 1 số thì không nên không lọc trùng được 
- Data: tra_omon_chandoancokhoangcach
- Khoa: 07
- Tháng kt: 10/2022
- Mabn: 2018083148    Lê Thị Trắng
![ảnh](https://user-images.githubusercontent.com/97272332/194786408-49e46dbc-c763-4d7f-a870-7509e7c65db7.png)
![ảnh](https://user-images.githubusercontent.com/97272332/194786504-cc598574-4d27-452e-86b8-5d072b791213.png)
![ảnh](https://user-images.githubusercontent.com/97272332/194786811-6a846caf-e4eb-4ced-90af-1694a9e0eaab.png)
