### ISSUE TITLE
Lỗi - BV Sa Đéc: Treatment tổng hợp toa nội trú làm tròn lượng thuốc 

### ISSUE THREAD

**Issue by chauthanhtra** [dh-hos/dhg.hosptaltreatment#32]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.1: Phiếu ghi nhận lỗi phát sinh DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN LỖI PHÁT SINH</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Châu Thanh Trà **
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **07/10/2022**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `87014`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **Bệnh viện đa khoa Sa Đéc**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `tra_sadec_lechtien_rep`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`](link_csdl)

###### ![chi_tiet_loi](https://img.shields.io/badge/Chi%20tiết%20lỗi%20phát%20sinh-:-blue?style=for-the-badge&logo=github)

-  ![loi_benh_nhan](https://img.shields.io/badge/Chi%20tiết%20bệnh%20nhân-:-blue?style=plastic&logo=github)
   > _**MaBN**_: `2022000001` - _**MaKB**_: `MaKB` - _**MaBA**_: `MaBA` _**NgayKCB**_: `NgayKCB` - _**MaPhong**_: `MaPhong` - _**MaDV**_: `NTM` - _**ThangKT**_: `10` - _**NamKT**_: `2022`
-  ![loi_thuoc](https://img.shields.io/badge/Chi%20tiết%20thuốc-:-blue?style=plastic&logo=github)
   > _**KhoChan**_: `KhoChan` - _**KhoLe**_: `KhoLe` - _**MaHH**_: `MaHH` - _**SoHD**_: `SoHD` - _**NgayHD**_: `NgayHD` - _**ThangKT**_: `ThangKT` - _**NamKT**_: `NamKT`
-  ![loi_cls](https://img.shields.io/badge/Chi%20tiết%20CLS-:-blue?style=plastic&logo=github)
   > _**MaCLS**_: `MaCLS` - _**PhieuYC**_: `PhieuYC`
-  ![loi_bo_sung](https://img.shields.io/badge/Chi%20tiết%20bổ%20sung-:-blue?style=plastic&logo=github)
   > _**Khac**_: `Khac`

###### ![mo_ta_loi](https://img.shields.io/badge/Mô%20tả%20thông%20tin%20lỗi-:-blue?style=for-the-badge&logo=github)

- Khi cấp toa thuốc thuốc có số lượng là số lẻ -> tổng hợp toa nội trú sẽ làm tròn số lượng thuốc lên
ví dụ: thuốc có số lượng 0.5 sau khi tổng hợp thì số lượng thuốc đó cập nhật thành 1 sau khi tổng hợp

![ảnh](https://user-images.githubusercontent.com/97272332/194485070-9dad7f51-05be-4532-9632-fc8d6d4d85a1.png)
![ảnh](https://user-images.githubusercontent.com/97272332/194485097-edc4a9a4-3ad7-4d09-ab74-29ac9743fa6c.png)
![ảnh](https://user-images.githubusercontent.com/97272332/194485133-e51df234-4791-44b1-a23b-bc84047ab941.png)
![ảnh](https://user-images.githubusercontent.com/97272332/194485157-89a2242f-3f40-4b61-9b6f-64ac1c543db7.png)

**Comment by vuongdh** [comment]
@chauthanhtra qui trình của Sa Đéc là vậy đó
