### ISSUE TITLE
Lỗi -  Bệnh án đã kết thúc (xử trí chuyển viện) nhưng vẫn cho xóa phiếu chuyển viện được

### ISSUE THREAD

**Issue by le-an-87** [dh-hos/dhg.hosptaltreatment#33]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.1: Phiếu ghi nhận lỗi phát sinh DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN LỖI PHÁT SINH</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Ân**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **13/10/2022**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `Tất cả`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **Tất cả**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `an_tamnong_bangke_mabvchuyen`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`](link_csdl)

###### ![chi_tiet_loi](https://img.shields.io/badge/Chi%20tiết%20lỗi%20phát%20sinh-:-blue?style=for-the-badge&logo=github)

-  ![loi_benh_nhan](https://img.shields.io/badge/Chi%20tiết%20bệnh%20nhân-:-blue?style=plastic&logo=github)
   > _**MaBN**_: `2020014388` - _**MaKB**_: `2210003250` - _**MaBA**_: `2022005186` _**NgayKCB**_: `10/10/2022` - _**MaDV**_: `21` - _**ThangKT**_: `10` - _**NamKT**_: `2022`

###### ![mo_ta_loi](https://img.shields.io/badge/Mô%20tả%20thông%20tin%20lỗi-:-blue?style=for-the-badge&logo=github)

```
Bệnh án đã kết thúc ra viện (xử trí chuyển viện và lập phiếu chuyển viện rồi) nhưng vẫn cho xóa phiếu chuyển viện.

```
![image](https://user-images.githubusercontent.com/96155021/195556479-c7530699-ab71-4f7e-8188-9cddf37c384e.png)

**Comment by vuongdh** [comment]
@le-an-87 cho xóa phiếu chuyển viện, nhưng nếu xử trí là chuyển viện bắt buột phải vô lập phiếu chuyển viện lại

**Comment by vuongdh** [comment]
@le-an-87 vì nếu không cho xóa, mà đơn vị muốn xử trí khác chuyển là không làm được

**Comment by le-an-87** [comment]
này Treatment phải trả về điều trị thì mới cho xóa giấy chuyển viện chứ anh chưa trả về điều trị mà cho xóa vậy thì hồ sơ đó bị lỗi rồi cũng không lập lại được giấy chuyển viện nữa

**Comment by vuongdh** [comment]
@le-an-87 để tránh phiền hà cho người người, mới vừa lưu xong thì phải làm thao tác trả về điều trị, em thử test xóa phiếu chuyển viện và lưu với xử trí là chuyển viện xem được không?

**Comment by le-an-87** [comment]
như trường hợp này thì làm sao mới lập lại được giấy chuyển viện anh và biết bệnh đó đã chuyển viện ở bệnh viện nào để làm lại như cũ

**Comment by vuongdh** [comment]
@le-an-87 Bản cập nhật [Treat4.20221018v1](http://www.fsend.vn/download/oKW0EEuNSLHBOyMT2e0bGFaclKML7Nzv)
