### ISSUE TITLE
Lỗi - BV Ô Môn: Chứng từ thuốc và CLS nội trú không ghi nhận mã ICD phụ -> không có ICD phụ trên XML 2, 3

### ISSUE THREAD

**Issue by chauthanhtra** [dh-hos/dhg.hosptaltreatment#34]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.1: Phiếu ghi nhận lỗi phát sinh DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN LỖI PHÁT SINH</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Châu Thanh Trà **
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **14/10/2022**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `92007`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **BV Ô Môn**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `tra_omon_chandoan`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`](link_csdl)

###### ![chi_tiet_loi](https://img.shields.io/badge/Chi%20tiết%20lỗi%20phát%20sinh-:-blue?style=for-the-badge&logo=github)

-  ![loi_benh_nhan](https://img.shields.io/badge/Chi%20tiết%20bệnh%20nhân-:-blue?style=plastic&logo=github)
   > _**MaBN**_: `2019015628` - _**MaKB**_: `2209021267` - _**MaBA**_: `2022012271` _**NgayKCB**_: `NgayKCB` - _**MaPhong**_: `MaPhong` - _**MaDV**_: `11` - _**ThangKT**_: `10` - _**NamKT**_: `2022`
-  ![loi_thuoc](https://img.shields.io/badge/Chi%20tiết%20thuốc-:-blue?style=plastic&logo=github)
   > _**KhoChan**_: `KhoChan` - _**KhoLe**_: `KhoLe` - _**MaHH**_: `MaHH` - _**SoHD**_: `SoHD` - _**NgayHD**_: `NgayHD` - _**ThangKT**_: `ThangKT` - _**NamKT**_: `NamKT`
-  ![loi_cls](https://img.shields.io/badge/Chi%20tiết%20CLS-:-blue?style=plastic&logo=github)
   > _**MaCLS**_: `MaCLS` - _**PhieuYC**_: `PhieuYC`
-  ![loi_bo_sung](https://img.shields.io/badge/Chi%20tiết%20bổ%20sung-:-blue?style=plastic&logo=github)
   > _**Khac**_: `Khac`

###### ![mo_ta_loi](https://img.shields.io/badge/Mô%20tả%20thông%20tin%20lỗi-:-blue?style=for-the-badge&logo=github)

- Chứng từ thuốc không ghi nhận mã ICD phụ
![ảnh](https://user-images.githubusercontent.com/97272332/195749252-87b3df34-b5e3-4f3a-956c-c66d7e2c2841.png)
![ảnh](https://user-images.githubusercontent.com/97272332/195749299-66dfb83f-ecba-444d-8810-da3e96bf7cff.png)

- Chỉ định CLS không ghi nhận mã ICD phụ khi vừa đổi, chỉnh diễn biến mà phải load lại thông tin bệnh nhân, làm tươi danh sách hoặc chọn bệnh nhân khác rồi chọn lại bệnh nhân rồi vào chỉ định CLS mới có mã ICD phụ
   + Đổi, chỉnh diễn biến rồi vào chỉ định CLS
![ảnh](https://user-images.githubusercontent.com/97272332/195750875-6dad89c5-981f-4eb5-b0ad-75dd33d09599.png)
![ảnh](https://user-images.githubusercontent.com/97272332/195750927-45aef16e-cf9a-4f3a-88a2-48d626dd3789.png)

   + Đổi, chỉnh diễn biến load lại thông tin bệnh nhân rồi chỉ định CLS
![ảnh](https://user-images.githubusercontent.com/97272332/195751183-c03ecb47-0e73-4fbe-bc47-a7bed1ae9ab8.png)
![ảnh](https://user-images.githubusercontent.com/97272332/195751279-8eb4d34a-7e24-4a10-8e3e-ff5f3da030d9.png)

-> Khi ô CĐ phụ ở form Danh sách bệnh nhân điều trị không hiển thì ICD thì vào chỉ định CLS sẽ thiếu ICD phụ
![ảnh](https://user-images.githubusercontent.com/97272332/195751581-223e5ae0-426f-4973-ae99-6afad45117fe.png)

**Comment by vuongdh** [comment]
@chauthanhtra Test lại hén [Treat4.20221014v1](http://www.fsend.vn/download/LVKhv1UaLFtZwT0J8lELwVr4dFw_xzoz)

**Comment by chauthanhtra** [comment]
Vẫn chưa được anh ơi
- chứng từ vẫn chưa ghi nhận ICD phụ
- chỉ định CLS vẫn còn lỗi như cũ
