### ISSUE TITLE
Yều cầu - Bổ sung tham số để thực hiện thiết kế phiếu chỉ định CLS nội trú

### ISSUE THREAD

**Issue by nghivanbi** [dh-hos/dhg.hosptaltreatment#35]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.2: Phiếu ghi nhận Yêu cầu mới DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN YÊU CẦU CHỨC NĂNG MỚI</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Nghị Văn Bi**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **14/10/2022**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `Tất cả`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **Tất cả**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `ten_csdl`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`](link_csdl)

###### ![chi_tiet_yeu_cau](https://img.shields.io/badge/Chi%20tiết%20yêu%20cầu%20-:-blue?style=for-the-badge&logo=github)

```
Lý do: trong qua trình thưc hiện sử dụng chung tham số phieuycchuan  các bệnh viện vướng phải nhiều bất cập.
Yều cầu: thêm tham số mới để thực hiện thiết kế hay sử dụng mẫu chỉ định chuẩn trong Nội trú.

```

**Comment by vuongdh** [comment]
@hvtuan1987 chạy cập nhật tham số và test lại với [Treat4.20221014v1](http://www.fsend.vn/download/4FhxnvuNFJeVi5_UStJMNvWc1tKP8XSd)

**Comment by hvtuan1987** [comment]
Đã ok rồi á !
