### ISSUE TITLE
Yêu cầu - Toa nhà thuốc BN đang điều trị

### ISSUE THREAD

**Issue by lqbinh1987** [dh-hos/dhg.hosptaltreatment#37]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.2: Phiếu ghi nhận Yêu cầu mới DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN YÊU CẦU CHỨC NĂNG MỚI</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Tuấn**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **07/10/2022**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `87190`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **BV Da Liễu ĐT**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `binh_dalieudt`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`](https://drive.google.com/file/d/1Pmq9tbQganHio_AE4BrTI9apiN82XH_e/view?usp=sharing)

###### ![chi_tiet_yeu_cau](https://img.shields.io/badge/Chi%20tiết%20yêu%20cầu%20-:-blue?style=for-the-badge&logo=github)

Yêu cầu hỗ trợ Toa mua ngoài đối với bệnh nhân đang điều trị (Lấy thuốc theo cấu hình của đối tượng không BHYT ngoại trú).
**_Làm giống BV NHi Đồng CT_**

![image](https://user-images.githubusercontent.com/99630883/199186934-c9403271-3211-4ed6-8997-38cd4dbff4b7.png)

**Comment by lqbinh1987** [comment]
anh @nghivanbi , anh @vuongdh xem dùm em nhe.

**Comment by vuongdh** [comment]
@lqbinh1987 Bản cập nhật [Treat4.20221118v3](http://www.fsend.vn/download/TerofK3Pe6yx9__XcQNtDTitCwMFy440)
