### ISSUE TITLE
Yêu cầu - Yêu cầu hỗ trợ phiếu Thỏa thuận sử dụng Thủ thuật và Thỏa thuận sử dụng thuốc ngoài BHYT.

### ISSUE THREAD

**Issue by lqbinh1987** [dh-hos/dhg.hosptaltreatment#38]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.2: Phiếu ghi nhận Yêu cầu mới DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN YÊU CẦU CHỨC NĂNG MỚI</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Tuấn**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **07/10/2022**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `87190`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **BV Da Liễu ĐT**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `binh_dalieudt`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`](https://drive.google.com/file/d/1Pmq9tbQganHio_AE4BrTI9apiN82XH_e/view?usp=sharing)

###### ![chi_tiet_yeu_cau](https://img.shields.io/badge/Chi%20tiết%20yêu%20cầu%20-:-blue?style=for-the-badge&logo=github)

Yêu cầu hỗ trợ phiếu Thỏa thuận sử dụng Thủ thuật ngoài danh mục BHYT giống ngoại trú.
**_Ngoại trú đã hỗ trợ._** như mẫu:

Mẫu phiếu thỏa thuận sử dụng TT/PT
![image](https://user-images.githubusercontent.com/99630883/199185696-f607b4cb-2b31-4209-b7ea-b6d2f3939a85.png).

Mẫu phiếu thỏa thuận sử dụng thuốc.
![image](https://user-images.githubusercontent.com/99630883/199187493-7a3cad10-f8f9-4bb5-9152-e6a3ab82cbbf.png)

**Comment by lqbinh1987** [comment]
anh @nghivanbi , anh @vuongdh xem giúp em nhé

**Comment by vuongdh** [comment]
@lqbinh1987 @hvtuan1987  Bản cập nhật [Treat4.20221104v1](http://www.fsend.vn/download/Vh2RapQ1kymLgYX92XGr4GInLx5PQCKj)
![image](https://user-images.githubusercontent.com/32563776/199901740-00667e53-a86d-4143-a825-82a1e95cc1f0.png)

**Comment by vuongdh** [comment]
Bản fix lỗi [Treat4.20221104v2](http://www.fsend.vn/download/nbfy5pFkgQWVXZeknU0Z7-nUWMAgZZAV)

**Comment by hvtuan1987** [comment]
Hiện tại trường Địa chỉ của 2 phiếu Thỏa Thuận anh chưa lấy được á ! Các trường khác đều ok !
![image](https://user-images.githubusercontent.com/97272364/200209622-482da425-915d-47dd-a9b8-55d000ce91c6.png)

**Comment by vuongdh** [comment]
@hvtuan1987 Bản cập nhật [Treat4.20221107v1](http://www.fsend.vn/download/-dJYMOXOTsfMKSkSSv0Ii-lQcRWD2n4R)

**Comment by hvtuan1987** [comment]
Đã ok rồi á anh Vương !
