### ISSUE TITLE
BV Quận 12 yêu cầu hỗ trợ Chỉ định dùng thuốc và Tổng hợp phiếu lĩnh tại Treatment

### ISSUE THREAD

**Issue by hvtuan1987** [dh-hos/dhg.hosptaltreatment#4]
YÊU CẦU BỆNH VIỆN QUẬN 12

1.	Treatment: phần tổng hợp phiếu lĩnh cho phép chọn tất cả chứng từ để tổng hợp phiếu lĩnh cho nhanh. Hiện tại chỉ nhấn phím Enter để chọn từng dòng chứng từ.
2.	Treatment: phần chỉ định dùng thuốc hỗ trợ lấy cách lấy chỉ định uống theo khoa nội trú tạo. Hiện tại lấy theo tài khoản BS thì mỗi tài khoản BS mỗi khác nên người dùng các khoa nội trú khi cho thuốc rất lâu.

**Comment by vuongdh** [comment]
1. Treatment: phần tổng hợp phiếu lĩnh cho phép chọn tất cả chứng từ để tổng hợp phiếu lĩnh cho nhanh. Hiện tại chỉ nhấn phím Enter để chọn từng dòng chứng từ. --> Hiện tại cho chọn số bắt đầu, số kết thúc để lấy hết
2. Treatment: phần chỉ định dùng thuốc hỗ trợ lấy cách lấy chỉ định uống theo khoa nội trú tạo. Hiện tại lấy theo tài khoản BS thì mỗi tài khoản BS mỗi khác nên người dùng các khoa nội trú khi cho thuốc rất lâu. --> trước giờ chỉ tạo chỉ định theo bs, chưa chỉ định theo khoa, nếu thực hiện phải xem dữ liệu và mô tả thực hiện

**Comment by hvtuan1987** [comment]
ok anh !
