### ISSUE TITLE
Yêu cầu - Hỗ trợ chức năng xuất khác tại tủ trực

### ISSUE THREAD

**Issue by nghivanbi** [dh-hos/dhg.hosptaltreatment#40]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.2: Phiếu ghi nhận Yêu cầu mới DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN YÊU CẦU CHỨC NĂNG MỚI</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Nghị Văn Bi**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **26/10/2022**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `87115`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **BỆNH VIỆN PHỔI ĐỒNG THÁP**

![image](https://user-images.githubusercontent.com/91751241/197912405-4aa1584d-767c-4d09-b099-0074a271e243.png)

**Comment by vuongdh** [comment]
Phiên bản cập nhật [Treat4.20221026v1](http://www.fsend.vn/download/23JJLlaLrTrWN1GbB6CBZc4m_hXjDW6i)
Các bệnh viện hỗ trợ:
"87014": BV Sa Đéc - Đồng Tháp
"87003": BV Cao Lãnh- Đồng Tháp
"87005": BV Lấp vò - Đồng Tháp
"87115": BV Phổi - Đồng Tháp

**Comment by nghivanbi** [comment]
@hvtuan1987 kiểm tra chỗ này cho Phổi, ok thì close dùm anh.

**Comment by hvtuan1987** [comment]
Chổ xuất khác tủ trực mở khóa ở đâu á anh Vương ?

**Comment by vuongdh** [comment]
@hvtuan1987 nội trú là không có khái niệm mở khóa em ơi

**Comment by hvtuan1987** [comment]
@vuongdh ,@nghivanbi Nếu xuất khác tủ trực này hong có chổ mở khóa sẽ khó cho người dùng á anh Bi !
