### ISSUE TITLE
Yêu cầu - Thực hiện ghi nhật ký các trường hợp cho ra việc thực hiện khác ngày ra viện

### ISSUE THREAD

**Issue by nghivanbi** [dh-hos/dhg.hosptaltreatment#41]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.2: Phiếu ghi nhận Yêu cầu mới DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN YÊU CẦU CHỨC NĂNG MỚI</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Nghị Văn Bi**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **09/11/2022**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `Tất cả`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **Tất cả**

###### ![chi_tiet_yeu_cau](https://img.shields.io/badge/Chi%20tiết%20yêu%20cầu%20-:-blue?style=for-the-badge&logo=github)

```
- Ghi nhật ký cụ thể các trường hợp thực hiện cho ra việc khác ngày ra viện.
- Người dùng dễ tìm thấy các bệnh nhân này tại nhật ký theo dõi.

```

**Comment by vuongdh** [comment]
@le-an-87 
![image](https://user-images.githubusercontent.com/32563776/200787496-233c3866-260f-4973-b520-3dfeb099741c.png)

Nội dung tác vụ:
Ra viện đúng ngày: "Kết thúc điều trị"
Ra viện lùi ngày (ngày ra viện < ngày hệ thống): "Lùi ngày xuất viện"
Ra viện trước ngày (ngày ra viện > ngày hệ thống): "Ra viện trước ngày"
Trong phần nội dung: có bổ sung ngày giờ xuất viện và ngày giờ lập phiếu

**Comment by nghivanbi** [comment]
@lqbinh1987 Test lại cái này ok thì Close nha.
