### ISSUE TITLE
Yêu cầu: Hỗ trợ mặc định và bỏ qua 1 số ràng buộc khi lập phiếu phẫu thuật theo yêu cầu đặc thù của bệnh viện

### ISSUE THREAD

**Issue by nghivanbi** [dh-hos/dhg.hosptaltreatment#48]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.2: Phiếu ghi nhận Yêu cầu mới DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN YÊU CẦU CHỨC NĂNG MỚI</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Nghị Văn Bi**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **28/11/2022**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `87164`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **Bệnh viện Phục hồi chức năng Đồng Tháp**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `bi_phcn_2022002702`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`](link_csdl)

###### ![chi_tiet_yeu_cau](https://img.shields.io/badge/Chi%20tiết%20yêu%20cầu%20-:-blue?style=for-the-badge&logo=github)

```
//khi thêm mới lấy mặc định
if (FrmMain.strMaBVBH == "87164")
{
    this.txtMaST.Text = "01";//Lành tính

    this.txtMaICDT.Text = //mã icd  hiện tại;
    this.txtKQCDoanT.Text = //bệnh hiện tại;

    this.txtMaICDSPT.Text = //mã icd  hiện tại;
    this.txtKQCDoanSPT.Text = t //bệnh hiện tại;

    this.mcboTinhHinhPT.Value = 1;//Chủ động
}
//khi lưu không bắt buộc chọn phương pháp vô cảm --> cho phép để trống (vì BV chỉ làm điện châm)

```

**Comment by vuongdh** [comment]
@nghivanbi Bản cập nhật hỗ trợ lấy mặc định [Treat4.20221129v1](http://www.fsend.vn/download/ryszst2tPBrW4C_5MNTJlV9Jkjxj6Im8)
