### ISSUE TITLE
Lỗi - Trích BBHC của bệnh nhân có 2 trang, trang 2 chỉ có chữ ký không có nội dung

### ISSUE THREAD

**Issue by le-an-87** [dh-hos/dhg.hosptaltreatment#5]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.1: Phiếu ghi nhận lỗi phát sinh DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN LỖI PHÁT SINH</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Ân**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **26/7/2022**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `Tất cả`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **Tất cả**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `an_phusan_chukytrang2`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`](link_csdl)

###### ![chi_tiet_loi](https://img.shields.io/badge/Chi%20tiết%20lỗi%20phát%20sinh-:-blue?style=for-the-badge&logo=github)

-  ![loi_benh_nhan](https://img.shields.io/badge/Chi%20tiết%20bệnh%20nhân-:-blue?style=plastic&logo=github)
   > _**MaBN**_: `2022050226` - _**MaKB**_: `2206011515` - _**MaBA**_: `007643` _**NgayKCB**_: `01/07/2022` - _**MaPhong**_: `34` - _**MaDV**_: `07` - _**ThangKT**_: `07` - _**NamKT**_: `2022`

###### ![mo_ta_loi](https://img.shields.io/badge/Mô%20tả%20thông%20tin%20lỗi-:-blue?style=for-the-badge&logo=github)

```
Trích BBHC: Trích BBHC của bệnh nhân có 2 trang, trang 2 chỉ có chữ ký không có nội dung
 -> Đề nghị chỉnh sửa khi Trích BBHC có nhiều trang thì trang cuối phải có nội dung và chữ ký.
```
Trang 2 Trích BBHC
![image](https://user-images.githubusercontent.com/96155021/180943604-f4d081be-19b4-4cf2-bb2f-a265f55d8f0c.png)

@vuongdh

**Comment by vuongdh** [comment]
Để anh xem @le-an-87

**Comment by le-an-87** [comment]
đã fix!
