### ISSUE TITLE
Yêu Cầu - Chức năng hỗ trợ tiền ăn cho BN>

### ISSUE THREAD

**Issue by lqbinh1987** [dh-hos/dhg.hosptaltreatment#55]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.2: Phiếu ghi nhận Yêu cầu mới DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN YÊU CẦU CHỨC NĂNG MỚI</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Bình**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **15/12/2022**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `51214`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **TT Nội Tiết QNI**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `binh_noitiet`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`](link_csdl)

###### ![chi_tiet_yeu_cau](https://img.shields.io/badge/Chi%20tiết%20yêu%20cầu%20-:-blue?style=for-the-badge&logo=github)

Yêu cầu bổ sung chức năng hỗ trợ tiền ăn cho BN, chức năng giống BV Gò Vấp đã làm.

![image](https://user-images.githubusercontent.com/99630883/208016203-41100f6a-d3e6-4af1-981d-cad324d44d69.png)

**Comment by lqbinh1987** [comment]
Này xem hỗ trợ hoặc có phản hồi gì cho BV dùm em, để BV đợi lâu quá BV phản ánh mấy anh ơi.

**Comment by vuongdh** [comment]
@lqbinh1987 không còn dữ liệu, cái này cấu hình trong danh mục đối tượng như Vò Gấp là được

**Comment by lqbinh1987** [comment]
Chắc năng đã ok, nhưng hiện tại phần mềm đang tính làm tròn số tiền, tham số cấu hình 44,700, nhưng khi tính tiền lại làm tròn lên 45,000.
Yêu cầu lấy đúng theo số tiền được cấu hình trong tham số.
![image](https://user-images.githubusercontent.com/99630883/221789060-2fe74e29-a542-48aa-9591-f801645892b4.png)
![image](https://user-images.githubusercontent.com/99630883/221789437-0c9fcbf0-4d95-49a6-a4e8-c5f4c563a66c.png)

**Comment by vuongdh** [comment]
TEST TEST mã số là gì vậy?
