### ISSUE TITLE
Yêu cầu - Mở chức năng kiểm tra chỉ đinh - chống chỉ định theo ICD

### ISSUE THREAD

**Issue by nghivanbi** [dh-hos/dhg.hosptaltreatment#56]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.2: Phiếu ghi nhận Yêu cầu mới DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN YÊU CẦU CHỨC NĂNG MỚI</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Nghị Văn Bi**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **22/12/2022**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `95005`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **TRUNG TÂM Y TẾ HUYỆN HỒNG DÂN**

**Comment by vuongdh** [comment]
@nghivanbi Mở chức năng kiểm tra chỉ định, chống chỉ định cho TTYT Huyện Hồng Dân [Treat4.20221221v1](http://www.fsend.vn/download/7dFY6dF13zQRD_X5B8XJSQTkTpdVwaxC)
