### ISSUE TITLE
Lỗi - in Phần chung hs bệnh án YHCT báo lỗi

### ISSUE THREAD

**Issue by le-an-87** [dh-hos/dhg.hosptaltreatment#59]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.1: Phiếu ghi nhận lỗi phát sinh DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN LỖI PHÁT SINH</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Ân**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **22/12/2022**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `92013`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **BV YHCT TPCT**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `an_yhct_bsyhct`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`](link_csdl)

###### ![chi_tiet_loi](https://img.shields.io/badge/Chi%20tiết%20lỗi%20phát%20sinh-:-blue?style=for-the-badge&logo=github)

-  ![loi_benh_nhan](https://img.shields.io/badge/Chi%20tiết%20bệnh%20nhân-:-blue?style=plastic&logo=github)
   > _**MaBN**_: `2022022500` - _**MaKB**_: `2212000658` - _**MaBA**_: `2022004946` _**NgayKCB**_: `22/12/2022` - _**MaPhong**_: `N9` - _**MaDV**_: `04` - _**ThangKT**_: `12` - _**NamKT**_: `2022`

###### ![mo_ta_loi](https://img.shields.io/badge/Mô%20tả%20thông%20tin%20lỗi-:-blue?style=for-the-badge&logo=github)

```
in hs bệnh án YHCT
-> phần chung báo lỗi!
```
![image](https://user-images.githubusercontent.com/96155021/209075267-0d8c081d-21b1-4c1f-ba56-fb21ffec7a3d.png)

**Comment by vuongdh** [comment]
@le-an-87 bản cập nhật [Treat4.20221223v3](http://www.fsend.vn/download/8wd5O1eTinCsQr6ZJr_hIgrbRCy7crFR)

**Comment by le-an-87** [comment]
đã fix!
