### ISSUE TITLE
Lỗi - Sử dụng quyển chứng sinh

### ISSUE THREAD

**Issue by lqbinh1987** [dh-hos/dhg.hosptaltreatment#61]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.1: Phiếu ghi nhận lỗi phát sinh DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN LỖI PHÁT SINH</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Bình**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **03/01/2022**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `94006`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **TTYT Thạnh Trị**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `an_thanhtri_st_2023_02_10`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`](link_csdl)

###### ![chi_tiet_loi](https://img.shields.io/badge/Chi%20tiết%20lỗi%20phát%20sinh-:-blue?style=for-the-badge&logo=github)

-  ![loi_benh_nhan](https://img.shields.io/badge/Chi%20tiết%20bệnh%20nhân-:-blue?style=plastic&logo=github)
   > _**MaBN**_: `MaBN` - _**MaKB**_: `MaKB` - _**MaBA**_: `2022008794` _**NgayKCB**_: `NgayKCB` - _**MaPhong**_: `MaPhong` - _**MaDV**_: `18` - _**ThangKT**_: `01` - _**NamKT**_: `2023`
-  ![loi_thuoc](https://img.shields.io/badge/Chi%20tiết%20thuốc-:-blue?style=plastic&logo=github)
   > _**KhoChan**_: `KhoChan` - _**KhoLe**_: `KhoLe` - _**MaHH**_: `MaHH` - _**SoHD**_: `SoHD` - _**NgayHD**_: `NgayHD` - _**ThangKT**_: `ThangKT` - _**NamKT**_: `NamKT`
-  ![loi_cls](https://img.shields.io/badge/Chi%20tiết%20CLS-:-blue?style=plastic&logo=github)
   > _**MaCLS**_: `MaCLS` - _**PhieuYC**_: `PhieuYC`
-  ![loi_bo_sung](https://img.shields.io/badge/Chi%20tiết%20bổ%20sung-:-blue?style=plastic&logo=github)
   > _**Khac**_: `Khac`

###### ![mo_ta_loi](https://img.shields.io/badge/Mô%20tả%20thông%20tin%20lỗi-:-blue?style=for-the-badge&logo=github)

Cấu hình đến số 1000 nhưng chỉ mới cấp đến 999, thì lúc cấp thêm nó không còn thấy để cấp cuối cùng nữa.

![image](https://user-images.githubusercontent.com/99630883/210293224-afcc8dc7-c777-4ef0-9eef-4c8fb7731c96.png)
![image](https://user-images.githubusercontent.com/99630883/234744770-a4bd5216-60c7-4556-8c27-bdeb1a63fdfd.png)
![image](https://user-images.githubusercontent.com/99630883/210293258-a2a77448-41bd-4c08-847e-95360e360bfc.png)

**Comment by vuongdh** [comment]
@lqbinh1987 em coi trong quyển đó cấp tới số mấy rồi nếu 1000 thì sẽ ko hiển thị cho chọn thêm nữa

**Comment by lqbinh1987** [comment]
Mới cấp tới số 999 thôi anh
![image](https://user-images.githubusercontent.com/99630883/234744825-87698851-a64a-4eee-8ee2-7c9dd6b5fd23.png)

**Comment by vuongdh** [comment]
Bảng fix  lỗi [Treatment](http://www.fsend.vn/download/NgzUVoXyuq4sGXIgJSRxf7d-yLTmLygA)

**Comment by lqbinh1987** [comment]
Chưa được nhe anh @vuongdh , em tạo thử quyển mới, bao nhiêu số không cần biết, chỉ cần chọn nó cấp 1 số là nó tự động set dmquyencs.sudung=0 lun à.
Như quyển này mới tạo, cấp được số 01 rồi, là nó tự set cột sudung=0 lun à, và cột sohientai cũng không tăng lên luôn.
![image](https://user-images.githubusercontent.com/99630883/234782569-d8e27f0c-2b1c-4246-86d7-22f341a88bc8.png)
![image](https://user-images.githubusercontent.com/99630883/234782282-e2398f84-24d8-4010-937e-56f03f0960fa.png)

**Comment by vuongdh** [comment]
@lqbinh1987 Test lại bảng này hén [Cập nhật](http://www.fsend.vn/download/Areoa-H6MY6IQ1u1PNo-3ECsZgohWl69)
