### ISSUE TITLE
Lỗi - BV DKTPCT: Bệnh nhân có giấy chứng nhận miễn thẻ 1, bảng kê 6556 không tính % cùng chi trả thẻ 2, Fees tính sai chi phí bệnh nhân, XML Admin tính sai chi phí bệnh nhân 

### ISSUE THREAD

**Issue by chauthanhtra** [dh-hos/dhg.hosptaltreatment#65]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.1: Phiếu ghi nhận lỗi phát sinh DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN LỖI PHÁT SINH</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Châu Thanh Trà **
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **06/01/2023**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `92004`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **BV ĐKTPCT**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `tra_dktp_cnmien`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`](link_csdl)

###### ![chi_tiet_loi](https://img.shields.io/badge/Chi%20tiết%20lỗi%20phát%20sinh-:-blue?style=for-the-badge&logo=github)

-  ![loi_benh_nhan](https://img.shields.io/badge/Chi%20tiết%20bệnh%20nhân-:-blue?style=plastic&logo=github)
   > _**MaBN**_: `2022099460` - _**MaKB**_: `MaKB` - _**MaBA**_: `037705` _**NgayKCB**_: `NgayKCB` - _**MaPhong**_: `MaPhong` - _**MaDV**_: `22` - _**ThangKT**_: `01` - _**NamKT**_: `2023`
-  ![loi_thuoc](https://img.shields.io/badge/Chi%20tiết%20thuốc-:-blue?style=plastic&logo=github)
   > _**KhoChan**_: `KhoChan` - _**KhoLe**_: `KhoLe` - _**MaHH**_: `MaHH` - _**SoHD**_: `SoHD` - _**NgayHD**_: `NgayHD` - _**ThangKT**_: `ThangKT` - _**NamKT**_: `NamKT`
-  ![loi_cls](https://img.shields.io/badge/Chi%20tiết%20CLS-:-blue?style=plastic&logo=github)
   > _**MaCLS**_: `MaCLS` - _**PhieuYC**_: `PhieuYC`
-  ![loi_bo_sung](https://img.shields.io/badge/Chi%20tiết%20bổ%20sung-:-blue?style=plastic&logo=github)
   > _**Khac**_: `Khac`

###### ![mo_ta_loi](https://img.shields.io/badge/Mô%20tả%20thông%20tin%20lỗi-:-blue?style=for-the-badge&logo=github)

Bệnh nhân có chứng nhận miễn ở thẻ 1 được hưởng 100 chi phí, thẻ 2 hưởng 80%
bảng kê 6556 chi phí thẻ 2 không tính tiền cùng chi trả của bệnh nhân 

![ảnh](https://user-images.githubusercontent.com/97272332/210935181-8ab32c8e-90fd-4d6f-aabf-690cc591c6d3.png)
![ảnh](https://user-images.githubusercontent.com/97272332/210935214-4ade958b-4647-4fb4-8bf0-e8b61b35a68e.png)
![ảnh](https://user-images.githubusercontent.com/97272332/210935240-e24427e6-c197-453b-ac42-e71c55465a16.png)
![ảnh](https://user-images.githubusercontent.com/97272332/210935260-ec27a576-8bef-4afd-a2c3-637cdbfd94a7.png)

**Comment by chauthanhtra** [comment]
Bệnh nhân có chứng nhận miễn ở thẻ 1 được hưởng 100 chi phí, thẻ 2 hưởng 80% chi phí.
![ảnh](https://user-images.githubusercontent.com/97272332/211445299-832fc2ff-53aa-4ef8-9e6c-6119c9255531.png)

- Fees tính sai chi phí bệnh nhân 
![ảnh](https://user-images.githubusercontent.com/97272332/211443359-abfd650b-79ab-4f28-b5f4-dd90e2cda9d5.png)
- Admin xuất XML1 sai số tiền BNCTT, BHTT, XML2 sai % hưởng
![ảnh](https://user-images.githubusercontent.com/97272332/211443793-f04ec44e-51c9-47d5-9c29-29eb981241d5.png)
ví dụ: thẻ BHYT 2 thuốc VE74 xuất 3 trả 2 còn 1 , hưởng 80%. xml lấy sai số lượng thẻ 1 thẻ 2
![ảnh](https://user-images.githubusercontent.com/97272332/211444266-e79a9ddb-95fa-4b99-955e-7c84e29c5ba5.png)

**Comment by ongtrieuhau** [comment]
Cập nhật Fees [3.23.0412.1](https://github.com/dh-hos/dhg.hospitalfees/commit/3426e44f28310dfe8540aeff0f9fb4e07580d047)
