### ISSUE TITLE
Lỗi - Tóm tắt bệnh án bị mất nội dung tiêu đề bv và Hướng điều trị tiếp theo

### ISSUE THREAD

**Issue by le-an-87** [dh-hos/dhg.hosptaltreatment#69]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.1: Phiếu ghi nhận lỗi phát sinh DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN LỖI PHÁT SINH</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Ân**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **13/01/2023**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `Tất cả`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **Tất cả**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `an_timmach_ag_tomtatba`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`](link_csdl)

###### ![chi_tiet_loi](https://img.shields.io/badge/Chi%20tiết%20lỗi%20phát%20sinh-:-blue?style=for-the-badge&logo=github)

-  ![loi_benh_nhan](https://img.shields.io/badge/Chi%20tiết%20bệnh%20nhân-:-blue?style=plastic&logo=github)
   > _**MaBN**_: `2023000984` - _**MaKB**_: `2301007494` - _**MaBA**_: `2023000537` _**NgayKCB**_: `13/01/2023` - _**MaPhong**_: `305` - _**MaDV**_: `04` - _**ThangKT**_: `01` - _**NamKT**_: `2023`

###### ![mo_ta_loi](https://img.shields.io/badge/Mô%20tả%20thông%20tin%20lỗi-:-blue?style=for-the-badge&logo=github)

```
In phiếu tóm tắt bệnh án bị mất nội dung:
1. Tiêu đề bệnh viện
2. Hướng điều trị tiếp theo

```
Phiếu tóm tắt bệnh án
![image](https://user-images.githubusercontent.com/96155021/212279872-a5fd419f-3536-482c-b550-e2b1e821d5d9.png)

**Comment by vuongdh** [comment]
@le-an-87 bảng fix lỗi [v1.2023.01.16](http://www.fsend.vn/download/znJXsUxED0KcXjgSuPceSjpyTKk6INsC)

**Comment by le-an-87** [comment]
đã fix!
