### ISSUE TITLE
Lỗi - cấp toa cho bệnh nhân không lấy được thuốc có hạn dùng gần nhất (tham số xuattheohandung)

### ISSUE THREAD

**Issue by le-an-87** [dh-hos/dhg.hosptaltreatment#71]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.1: Phiếu ghi nhận lỗi phát sinh DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN LỖI PHÁT SINH</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **ÂN**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **31/01/2023**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `87164`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **BV PHCN ĐT**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `an_phcn_dt_handung`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`](link_csdl)

###### ![chi_tiet_loi](https://img.shields.io/badge/Chi%20tiết%20lỗi%20phát%20sinh-:-blue?style=for-the-badge&logo=github)

-  ![loi_benh_nhan](https://img.shields.io/badge/Chi%20tiết%20bệnh%20nhân-:-blue?style=plastic&logo=github)
   > _**MaBN**_: `2023000320` - _**MaKB**_: `2301001602` - _**MaBA**_: `2023000069` _**NgayKCB**_: `31/01/2023` - _**MaPhong**_: `11` - _**MaDV**_: `YH` - _**ThangKT**_: `01` - _**NamKT**_: `2023`
-  ![loi_thuoc](https://img.shields.io/badge/Chi%20tiết%20thuốc-:-blue?style=plastic&logo=github)
   > _**KhoChan**_: `14` - _**KhoLe**_: `14` - _**MaHH**_: `AC23` 

###### ![mo_ta_loi](https://img.shields.io/badge/Mô%20tả%20thông%20tin%20lỗi-:-blue?style=for-the-badge&logo=github)

```
Thuốc AC23 trong kho có 2 lô
-> khi xuất phần mềm lấy thuốc có hạn dùng dài hơn
không áp dụng được theo tham số xuattheohandung = 1

```
2 lô AC23
![image](https://user-images.githubusercontent.com/96155021/215719869-bb7f91db-36e1-4906-9990-86526538f877.png)

ra toa lấy hạn dùng 10/2025
![image](https://user-images.githubusercontent.com/96155021/215719607-dec86a91-2420-4b84-bedf-b3b0d64f2724.png)

Tham số sử dụng
![image](https://user-images.githubusercontent.com/96155021/215719918-97c68c72-a0df-4717-9008-38e87d07c3e5.png)

**Comment by vuongdh** [comment]
Bảng cập nhật [v1.2023.02.02](http://www.fsend.vn/download/LYFqDtXm2LSLrgo9XsW5n0JcNCf0vdtG)

**Comment by le-an-87** [comment]
đã fix!
