### ISSUE TITLE
Yêu cầu - Thực hiện mô tả cập nhật mã toa thuốc

### ISSUE THREAD

**Issue by nghivanbi** [dh-hos/dhg.hosptaltreatment#72]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.2: Phiếu ghi nhận Yêu cầu mới DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN YÊU CẦU CHỨC NĂNG MỚI</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Nghị Văn Bi**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `Tất cả`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **Tất cả**

https://github.com/dh-hos/Mo-ta-he-thong/blob/main/Bi%20-%20Mo%20ta%20bo%20sung%20sinh%20ma%20toa%20thuoc%20theo%20quyet%20dinh%2004_20230203v2.pdf

**Comment by vuongdh** [comment]
Bản cập nhật [Treatment 2023.02.07v1](http://www.fsend.vn/download/7tlqXnsFrn3jt925K95jd7BWvj-F-PP3)

**Comment by le-an-87** [comment]
1. Treatment khi cấp số cuối cùng không tạo quyển mã đơn thuốc mới anh ơi.
2. khi tạo quyển mới thì không set lại trường ngungsd =1.
![image](https://user-images.githubusercontent.com/96155021/217173332-14ba5784-856c-43f2-9f72-a05e351a57b9.png)
Mô tả
![image](https://user-images.githubusercontent.com/96155021/217173677-b9e18358-60de-4781-b303-350ab9f59260.png)

**Comment by vuongdh** [comment]
Ok để hiệu chỉnh lại:
- Hiện tại số cuối là 999999 thì không set ngungsd = 1
- Cấp số mới khi kiểm tra không còn số để cấp

**Comment by vuongdh** [comment]
Bảng cập nhật [Treat.2023.02.08v1](http://www.fsend.vn/download/drMh_rH__Mr9IyfwL9GiUlWZNeXcryQb)

**Comment by le-an-87** [comment]
Đã cập nhật đúng theo mô tả!
