### ISSUE TITLE
Lỗi - BV Cái Răng: Phiếu công khai thuốc không cấn trừ thuốc trả toa mổ TMO

### ISSUE THREAD

**Issue by chauthanhtra** [dh-hos/dhg.hosptaltreatment#76]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.1: Phiếu ghi nhận lỗi phát sinh DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN LỖI PHÁT SINH</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Châu Thanh Trà **
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **10/2/2023**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `92006`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **BV Cái Răng**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `tra_cairang_congkhaithuoc`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`](link_csdl)

###### ![chi_tiet_loi](https://img.shields.io/badge/Chi%20tiết%20lỗi%20phát%20sinh-:-blue?style=for-the-badge&logo=github)

-  ![loi_benh_nhan](https://img.shields.io/badge/Chi%20tiết%20bệnh%20nhân-:-blue?style=plastic&logo=github)
   > _**MaBN**_: `2018006577` - _**MaKB**_: `MaKB` - _**MaBA**_: `0000000084` _**NgayKCB**_: `NgayKCB` - _**MaPhong**_: `MaPhong` - _**MaDV**_: `06` - _**ThangKT**_: `02` - _**NamKT**_: `2023`
-  ![loi_thuoc](https://img.shields.io/badge/Chi%20tiết%20thuốc-:-blue?style=plastic&logo=github)
   > _**KhoChan**_: `KhoChan` - _**KhoLe**_: `KhoLe` - _**MaHH**_: `MaHH` - _**SoHD**_: `YH2.TM23.0207.075327` - _**NgayHD**_: `9/2/2023` - _**ThangKT**_: `02` - _**NamKT**_: `2023`
-  ![loi_cls](https://img.shields.io/badge/Chi%20tiết%20CLS-:-blue?style=plastic&logo=github)
   > _**MaCLS**_: `MaCLS` - _**PhieuYC**_: `PhieuYC`
-  ![loi_bo_sung](https://img.shields.io/badge/Chi%20tiết%20bổ%20sung-:-blue?style=plastic&logo=github)
   > _**Khac**_: `Khac`

###### ![mo_ta_loi](https://img.shields.io/badge/Mô%20tả%20thông%20tin%20lỗi-:-blue?style=for-the-badge&logo=github)

- Khi trả thuốc toa TMO thì tất cả các mẫu phiếu công khai thuốc không cấn trừ thuốc trả toa TMO

![ảnh](https://user-images.githubusercontent.com/97272332/217995312-847156f7-bac3-496d-a803-bebfb3479978.png)
![ảnh](https://user-images.githubusercontent.com/97272332/217995618-30c339fc-9cca-4339-90b3-9295749752d9.png)
![ảnh](https://user-images.githubusercontent.com/97272332/217995665-89244ff7-fe89-43b6-b63d-24d0f01cdde0.png)
![ảnh](https://user-images.githubusercontent.com/97272332/217995732-a390c1ad-298a-40dc-bcac-162a6aa034a5.png)
![ảnh](https://user-images.githubusercontent.com/97272332/217995775-ba4dee64-68a8-4bcf-91b6-b2736bbf7725.png)

- Lỗi xem Tổng kết tại khoa và Tổng kết TMO
![ảnh](https://user-images.githubusercontent.com/97272332/217996180-c28f1920-d0cb-4f52-a174-10a80df7bf94.png)
![ảnh](https://user-images.githubusercontent.com/97272332/217996259-47f245fd-3558-4799-86b8-fca9eb4e4cee.png)
![ảnh](https://user-images.githubusercontent.com/97272332/217996286-e0ba23d2-b4e9-4077-893b-a6c5f2a49224.png)

**Comment by vuongdh** [comment]
Bảng cập nhật [Treat.2023.02.10v1](http://www.fsend.vn/download/1pVHfo9P-GrvTmM4BqVsLm70Qc9Plx70)
