### ISSUE TITLE
Lỗi - Đơn thuốc điệntử không gửi được.

### ISSUE THREAD

**Issue by lqbinh1987** [dh-hos/dhg.hosptaltreatment#77]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.1: Phiếu ghi nhận lỗi phát sinh DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN LỖI PHÁT SINH</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Bình**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **10/02/2023**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `94006`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **TTYT Thạnh Trị**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `binh_thanhtri_full`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`](link_csdl)

###### ![chi_tiet_loi](https://img.shields.io/badge/Chi%20tiết%20lỗi%20phát%20sinh-:-blue?style=for-the-badge&logo=github)

-  ![loi_benh_nhan](https://img.shields.io/badge/Chi%20tiết%20bệnh%20nhân-:-blue?style=plastic&logo=github)
   > _**MaBN**_: `2021014296` - _**MaKB**_: `2302003938` - _**MaBA**_: `MaBA` _**NgayKCB**_: `10/02/2023` - _**MaPhong**_: `MaPhong` - _**MaDV**_: `MaDV` - _**ThangKT**_: `02` - _**NamKT**_: `2023`
-  ![loi_thuoc](https://img.shields.io/badge/Chi%20tiết%20thuốc-:-blue?style=plastic&logo=github)
   > _**KhoChan**_: `KhoChan` - _**KhoLe**_: `KhoLe` - _**MaHH**_: `MaHH` - _**SoHD**_: `SoHD` - _**NgayHD**_: `NgayHD` - _**ThangKT**_: `ThangKT` - _**NamKT**_: `NamKT`
-  ![loi_cls](https://img.shields.io/badge/Chi%20tiết%20CLS-:-blue?style=plastic&logo=github)
   > _**MaCLS**_: `MaCLS` - _**PhieuYC**_: `PhieuYC`
-  ![loi_bo_sung](https://img.shields.io/badge/Chi%20tiết%20bổ%20sung-:-blue?style=plastic&logo=github)
   > _**Khac**_: `Khac`

###### ![mo_ta_loi](https://img.shields.io/badge/Mô%20tả%20thông%20tin%20lỗi-:-blue?style=for-the-badge&logo=github)

Hiện chạy bản EPR AUTO bản mới rồi, nhưng những toa thuốc có mã đơn thuốc theo mô tả mới vẫn chưa gửi tự động được, tài khoản BS đã được duyệt trên hệ thống [donthuocdientu.vn](https://donthuocquocgia.vn/)
Nhật ký vẫn không có, file lỗi hay file thành công đều không có.
![image](https://user-images.githubusercontent.com/99630883/218023363-af135930-9f14-438e-82fb-92dc7aea2320.png)
![image](https://user-images.githubusercontent.com/99630883/218023378-6a085b58-241d-496e-8d25-718d8a914d32.png)

**Comment by vuongdh** [comment]
![image](https://user-images.githubusercontent.com/32563776/218361615-64befb40-c8c3-4cdb-b82b-7547691aedf6.png)
Cập nhật Pre mới gửi toa thuốc đc nè, không ghi log được có thể do thiếu quyền, đang xem lại

**Comment by vuongdh** [comment]
Dữ liệu đc gửi ngày 13/2

**Comment by vuongdh** [comment]
Cập nhật [Hiệu chỉnh ghi log theo ngày](http://www.fsend.vn/download/tgg7PyW5NUphW3l8lzCu2z5CNE7tos1x)
