### ISSUE TITLE
Yêu cầu - Bổ sung mã bvđk vào mã thẻ bhyt khi in toa thuốc

### ISSUE THREAD

**Issue by le-an-87** [dh-hos/dhg.hosptaltreatment#79]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.1: Phiếu ghi nhận lỗi phát sinh DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN LỖI PHÁT SINH</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Ân**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **13/02/2023**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `Tất cả`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **Tất cả**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `an_hongngu_toathuoc_madk`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`](link_csdl)

###### ![chi_tiet_loi](https://img.shields.io/badge/Chi%20tiết%20lỗi%20phát%20sinh-:-blue?style=for-the-badge&logo=github)

-  ![loi_benh_nhan](https://img.shields.io/badge/Chi%20tiết%20bệnh%20nhân-:-blue?style=plastic&logo=github)
   > _**MaBN**_: `2023005046` - _**MaKB**_: `2302006595` - _**MaBA**_: `2023002325` _**NgayKCB**_: `13/02/2023` - _**MaDV**_: `06` - _**ThangKT**_: `02` - _**NamKT**_: `2023`
-  ![loi_thuoc](https://img.shields.io/badge/Chi%20tiết%20thuốc-:-blue?style=plastic&logo=github)
   > **SoHD**_: `N65.X23.0213.100518` - _**NgayHD**_: `13/02/2023` - _**ThangKT**_: `02` - _**NamKT**_: `2023`

###### ![mo_ta_loi](https://img.shields.io/badge/Mô%20tả%20thông%20tin%20lỗi-:-blue?style=for-the-badge&logo=github)

```
In toa chỉ định không ghép mã bv đăng ký vào mã thẻ!

```
Treatment
![image](https://user-images.githubusercontent.com/96155021/218408864-fd222221-df2b-4c01-8f4a-640fa134aa23.png)
toa thuốc tại Prescription
![image](https://user-images.githubusercontent.com/96155021/218408946-5b7d07e8-d0ad-471b-8bc3-5fe5e292ccf5.png)

**Comment by vuongdh** [comment]
![image](https://user-images.githubusercontent.com/32563776/218672355-1396721b-ef9e-445b-ad5b-313c2cac0e9b.png)
Này chỉ việc kéo mabvdk vào là được
