### ISSUE TITLE
Hỗ trợ giấy ra viện BANT theo đợt ghép mã ICD YHCT su tên bệnh YHCT

### ISSUE THREAD

**Issue by hvtuan1987** [dh-hos/dhg.hosptaltreatment#8]
Hỗ trợ giấy ra viện BANT theo đợt ghép mã ICD YHCT su tên bệnh YHCT

<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.2: Phiếu ghi nhận Yêu cầu mới DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>Hỗ trợ giấy ra viện BANT theo đợt ghép mã ICD YHCT sử dụng tên bệnh YHCT </h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Hà Văn Tuấn**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **28/07/2022**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `87044`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **Bệnh viện Quân dân y Đồng Tháp**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `dbquandanydt`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`](link_csdl)

###### ![chi_tiet_yeu_cau](https://img.shields.io/badge/Chi%20tiết%20yêu%20cầu%20-:-blue?style=for-the-badge&logo=github)

```
Bệnh nhân BANT theo đợt giấy ra viện chưa lấy đc mã bệnh YHCT sau tên bệnh !
 Bệnh viện yêu cầu hỗ trợ ghép thêm Mã ICD YHCT 
```

**Comment by nghivanbi** [comment]
Yêu cầu ghép cụ thể thế nào @hvtuan1987 ?
