### ISSUE TITLE
Lỗi - toa vtyt kèm theo - toa tủ trực

### ISSUE THREAD

**Issue by le-an-87** [dh-hos/dhg.hosptaltreatment#82]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.1: Phiếu ghi nhận lỗi phát sinh DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN LỖI PHÁT SINH</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Ân**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **21/02/2023**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `92004`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **BV ĐKTP Cần Thơ**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `an_dktp_toavtyt_tutruc`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`](link_csdl)

###### ![chi_tiet_loi](https://img.shields.io/badge/Chi%20tiết%20lỗi%20phát%20sinh-:-blue?style=for-the-badge&logo=github)

-  ![loi_benh_nhan](https://img.shields.io/badge/Chi%20tiết%20bệnh%20nhân%20Toa%20Tủ%20trực-:-blue?style=plastic&logo=github)
   > _**MaBN**_: `2023010615` - _**MaKB**_: `2302013895` - _**MaBA**_: `004203` _**NgayKCB**_: `21/02/2023` - _**MaPhong**_: `169` - _**MaDV**_: `37` - _**ThangKT**_: `02` - _**NamKT**_: `2023`
   > _**SoHD**_: `182.X23.0213.154218` - _**Tutruc**_: `T18`

-  ![loi_benh_nhan](https://img.shields.io/badge/Chi%20tiết%20bệnh%20nhân%20toa%20VTYT-:-blue?style=plastic&logo=github)
   > _**MaBN**_: `2023011637` - _**MaKB**_: `2302017758` - _**MaBA**_: `004548` _**NgayKCB**_: `21/02/2023` - _**MaPhong**_: `NLN04` - _**MaDV**_: `42` - _**ThangKT**_: `02` - _**NamKT**_: `2023`
  > _**Macls**_: `BE139`

###### ![mo_ta_loi](https://img.shields.io/badge/Mô%20tả%20thông%20tin%20lỗi-:-blue?style=for-the-badge&logo=github)

```
1. Toa tủ trực: Toa thuốc 182.X23.0213.154218 ra toa thuộc tủ trực T18 nhưng khi xem lại thì hiển thị tủ trực khác.

2. Toa VTYT: cls đã check VTYT kèm theo và đã bật tham số nt.ksdinhmuccls nhưng chức năng ra toa VTYT bị ẩn

```
1 toa thuộc tủ trực T18 nhưng hiển thị tủ trực T51
![image](https://user-images.githubusercontent.com/96155021/220231375-c6a15078-7243-4b20-86a5-4ab5901f855d.png)

2 chức năng ra toa vtyt bị ẩn
![image](https://user-images.githubusercontent.com/96155021/220231457-d85e1cef-3aa7-478c-b60e-67b699dff45c.png)
![image](https://user-images.githubusercontent.com/96155021/220231481-44f36d10-ba0d-4e1a-ac81-86c14f0df2e3.png)
![image](https://user-images.githubusercontent.com/96155021/220231510-bde35eb4-c3f4-4d4e-ac31-d3778929fe51.png)

**Comment by vuongdh** [comment]
@le-an-87 Bảng cập nhật [Treat4.2023.02.22v1](http://www.fsend.vn/download/Pd5aVkFglZaxU5dztTxVoh0_yN87bwg2)

- Fix lỗi xem toa tủ trực (hiển thị sai tên tủ trực)
- Không ra toa được toa vật tư (do ngày diễn biến và ngày hệ thống không khớp), nhưng vẫn cho được cận lâm sàng là do chương trình lỗi (đã fix)

**Comment by le-an-87** [comment]
Không ra toa được toa vật tư (do ngày diễn biến và ngày hệ thống không khớp), nhưng vẫn cho được cận lâm sàng là do chương trình lỗi (đã fix)

chổ này làm sao để chỉ định toa VTYT của cls đã chỉ định ngày củ được hé anh!

**Comment by vuongdh** [comment]
chổ này làm sao để chỉ định toa VTYT của cls đã chỉ định ngày củ được hé anh! --> mặc định là không cho, nếu bệnh có yêu cầu thì làm

**Comment by le-an-87** [comment]
![image](https://user-images.githubusercontent.com/96155021/220807808-dd55127c-1394-47d7-8137-c57bd26d7547.png)
anh ơi sẳn cho em hỏi 2 cái tham số lùi ngày chỉ định này là áp dụng sao vậy anh.
cho phép chỉnh ngày hóa đơn, ngày thực hiện lại hay đăng nhập ngày củ để chỉ định vậy.
có cần đổi diễn biến hay chọn lại diễn biến gì không anh!

**Comment by vuongdh** [comment]
Tham số này cho lùi ngày: vô đúng ngày hiện tại, khi thêm thuốc hoặc cls thì chọn ngày thực hiện lùi theo ý (điều kiện không < ngày vào viện, hoặc ngày đầu tháng)
