### ISSUE TITLE
Lỗi - EPR - Lỗi qua ngày không gửi tiếp.

### ISSUE THREAD

**Issue by lqbinh1987** [dh-hos/dhg.hosptaltreatment#86]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.1: Phiếu ghi nhận lỗi phát sinh DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN LỖI PHÁT SINH</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **nguoi_ghi_nhan**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **ngay_tiep_nhan**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `mabvbh`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **khach_hang**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `ten_csdl`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`](link_csdl)

###### ![chi_tiet_loi](https://img.shields.io/badge/Chi%20tiết%20lỗi%20phát%20sinh-:-blue?style=for-the-badge&logo=github)

-  ![loi_benh_nhan](https://img.shields.io/badge/Chi%20tiết%20bệnh%20nhân-:-blue?style=plastic&logo=github)
   > _**MaBN**_: `MaBN` - _**MaKB**_: `MaKB` - _**MaBA**_: `MaBA` _**NgayKCB**_: `NgayKCB` - _**MaPhong**_: `MaPhong` - _**MaDV**_: `MaDV` - _**ThangKT**_: `ThangKT` - _**NamKT**_: `NamKT`
-  ![loi_thuoc](https://img.shields.io/badge/Chi%20tiết%20thuốc-:-blue?style=plastic&logo=github)
   > _**KhoChan**_: `KhoChan` - _**KhoLe**_: `KhoLe` - _**MaHH**_: `MaHH` - _**SoHD**_: `SoHD` - _**NgayHD**_: `NgayHD` - _**ThangKT**_: `ThangKT` - _**NamKT**_: `NamKT`
-  ![loi_cls](https://img.shields.io/badge/Chi%20tiết%20CLS-:-blue?style=plastic&logo=github)
   > _**MaCLS**_: `MaCLS` - _**PhieuYC**_: `PhieuYC`
-  ![loi_bo_sung](https://img.shields.io/badge/Chi%20tiết%20bổ%20sung-:-blue?style=plastic&logo=github)
   > _**Khac**_: `Khac`

###### ![mo_ta_loi](https://img.shields.io/badge/Mô%20tả%20thông%20tin%20lỗi-:-blue?style=for-the-badge&logo=github)

Hiện tại tất cả BV đều bị tình trạng khi qua ngày mới thì EPR Auto không gửi được nữa, nhờ a Vương coi có hướng giải quyết, vì BV nó phàn nàn quá.

**Comment by lqbinh1987** [comment]
Này sao rồi hé anh @vuongdh ?

**Comment by vuongdh** [comment]
@lqbinh1987 đang tìm cách khắc phục, không biết tại sao nó treo, tắt mở lại thì được

**Comment by lqbinh1987** [comment]
Thêm cái nữa là khi có 1 toa nào đó lỗi thì nó đứng lun, không bỏ qua toa lỗi đó mà gửi toa khác được.

**Comment by vuongdh** [comment]
@lqbinh1987 em xin dữ liệu 1 toa bị lỗi và một toa chưa gửi/đã gửi dùm anh hén (toa cùng cùng 1 ngày)

**Comment by lqbinh1987** [comment]
Anh @vuongdh:
Dữ liệu: binh_mat_full_t3, ngày 23/03/2023
Ghi nhận tại BV thì chỉ không tới 100 toa thuốc được gửi, còn lại là không gửi được, file log error thì phát hiện lỗi sau:

{"loai_don_thuoc":"c","ma_don_thuoc":"940290051242-c","ten_benh_nhan":"Lâm Thị Ngọc Thảo","ngay_sinh_benh_nhan":"17/11/2018","ma_dinh_danh_y_te":"","ma_dinh_danh_cong_dan":"","can_nang":16,"gioi_tinh":3,"ma_so_the_bao_hiem_y_te":"","thong_tin_nguoi_giam_ho":"Thạch Thị Oanh","dia_chi":"Phước Quới, Xã Phú Tân, Huyện Châu Thành, Tỉnh Sóc Trăng","chan_doan":[{"ma_chan_doan" : "J06", "ten_chan_doan" : "Nhiễm trùng đường hô hấp trên cấp ở nhiều nơi và vị trí không phân loại;ổn", "ket_luan" : "."}],"luu_y":"","hinh_thuc_dieu_tri":2,"dot_dung_thuoc":[{"dot" : 1, "tu_ngay" : "23/03/2023", "den_ngay" : "02/04/2023"}],"thong_tin_don_thuoc":null,"loi_dan":"","so_dien_thoai_nguoi_kham_benh":"0352865198","ngay_tai_kham":10,"ngay_gio_ke_don":"2023-03-23 07:03:52","chu_ky_so":""} lỗi: {
  "thong_tin_don_thuoc": [
    "Trường thông tin đơn thuốc không được bỏ trống"
  ]
} - Chứng từ: 428.00833/202303

**Comment by vuongdh** [comment]
@lqbinh1987 "Trường thông tin đơn thuốc không được bỏ trống" --> Em kiểm tra xem các thuốc đó đánh dấu thuốc mỹ phẩm không?
![image](https://user-images.githubusercontent.com/32563776/227453514-b4ff5d3d-52bb-4d8a-bb25-34fd6e7920ad.png)
