### ISSUE TITLE
Lỗi - EPR toa thuốc 4 giờ PM nhưng phần mềm gửi 4 giờ

### ISSUE THREAD

**Issue by le-an-87** [dh-hos/dhg.hosptaltreatment#87]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.1: Phiếu ghi nhận lỗi phát sinh DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN LỖI PHÁT SINH</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **ÂN**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **03/03/2023**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `Tất cả`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **Tất cả**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `an_donghai_epr_giotoathuoc`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`](link_csdl)

###### ![chi_tiet_loi](https://img.shields.io/badge/Chi%20tiết%20lỗi%20phát%20sinh-:-blue?style=for-the-badge&logo=github)

-  ![loi_benh_nhan](https://img.shields.io/badge/Chi%20tiết%20bệnh%20nhân-:-blue?style=plastic&logo=github)
   > _**MaBN**_: `2021008865` - _**MaKB**_: `2303000327` - _**NgayKCB**_: `01/03/2023 4:40:21 PM` - _**MaPhong**_: `T03` - _**MaDV**_: `01` - _**ThangKT**_: `03` - _**NamKT**_: `2023`
-  ![loi_thuoc](https://img.shields.io/badge/Chi%20tiết%20thuốc-:-blue?style=plastic&logo=github)
   > _**SoHD**_: `KB3.00027/202303` - _**NgayLap**_: `01/03/2023 4:40:21 PM` - _**ThangKT**_: `03` - _**NamKT**_: `2023`
> _**MaDonThuoc**_: `950070000652-C`

###### ![mo_ta_loi](https://img.shields.io/badge/Mô%20tả%20thông%20tin%20lỗi-:-blue?style=for-the-badge&logo=github)

```
Toa thuốc lập ngày 01/03/2023 4:40:21 PM
nhưng EPR gửi lên cổng ghi nhận ngày 01/03/2023 4:40:21

```

**Comment by le-an-87** [comment]
01/04/2023!

**Comment by vuongdh** [comment]
@le-an-87 Bảng cập nhật [2023.04.05v1](http://www.fsend.vn/download/4HAlcx0Xy_WvihocV3EGqbw3BK0eAKeY)
