### ISSUE TITLE
Lỗi - EPR không gửi được đơn thuốc lên cổng Đơn thuốc quốc gia

### ISSUE THREAD

**Issue by le-an-87** [dh-hos/dhg.hosptaltreatment#88]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.1: Phiếu ghi nhận lỗi phát sinh DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN LỖI PHÁT SINH</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Ân**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **07/03/2023**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `87015`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **BV Hồng Ngự**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `an_hongngu_epr`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`](link_csdl)

###### ![chi_tiet_loi](https://img.shields.io/badge/Chi%20tiết%20lỗi%20phát%20sinh-:-blue?style=for-the-badge&logo=github)

-  ![loi_thuoc](https://img.shields.io/badge/Chi%20tiết%20thuốc-:-blue?style=plastic&logo=github)
   > _**KhoChan**_: `14` - _**KhoLe**_: `01` -_**SoHD**_: `V01.00283/202303` - _**NgayHD**_: `07/03/2023` - _**ThangKT**_: `03` - _**NamKT**_: `2023`_**MaBN**_: `2019002343` - _**MaKB**_: `2303003428` - _**MaDonThuoc**_: `87015G074411-C`  - _**MaBS**_: `332` 

###### ![mo_ta_loi](https://img.shields.io/badge/Mô%20tả%20thông%20tin%20lỗi-:-blue?style=for-the-badge&logo=github)

```
Phần mềm gửi đơn thuốc điện tử EPR không gửi được toa thuốc đã in lên cổng donthuocquocgia.vn

```

**Comment by vuongdh** [comment]
@le-an-87 tài khoản đơn vị 87015 (HIS), tài khoản đăng ký EPR (87584): không khớp nên không gửi được

**Comment by vuongdh** [comment]
@le-an-87 còn một vấn đề nữa là bv chưa cập nhật pre mới để cấp mã toa thuốc theo mô tả mới, nên khi gửi lên có thể bị trùng toa
