### ISSUE TITLE
Lỗi - BV Tim Mạch: phiếu 6556 thống kê sai thành tiền khi có stent

### ISSUE THREAD

**Issue by chauthanhtra** [dh-hos/dhg.hosptaltreatment#89]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.1: Phiếu ghi nhận lỗi phát sinh DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN LỖI PHÁT SINH</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Châu Thanh Trà **
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **7/3/2023**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `92001`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **BV Tim Mạch CT**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `tra_timmachct_6556_stent`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`](link_csdl)

###### ![chi_tiet_loi](https://img.shields.io/badge/Chi%20tiết%20lỗi%20phát%20sinh-:-blue?style=for-the-badge&logo=github)

-  ![loi_benh_nhan](https://img.shields.io/badge/Chi%20tiết%20bệnh%20nhân-:-blue?style=plastic&logo=github)
   > _**MaBN**_: `23001732` - _**MaKB**_: `MaKB` - _**MaBA**_: `23000446` _**NgayKCB**_: `NgayKCB` - _**MaPhong**_: `MaPhong` - _**MaDV**_: `18` - _**ThangKT**_: `02` - _**NamKT**_: `2023`
-  ![loi_thuoc](https://img.shields.io/badge/Chi%20tiết%20thuốc-:-blue?style=plastic&logo=github)
   > _**KhoChan**_: `14` - _**KhoLe**_: `02` - _**MaHH**_: `460.202.109` - _**SoHD**_: `SoHD` - _**NgayHD**_: `NgayHD` - _**ThangKT**_: `ThangKT` - _**NamKT**_: `NamKT`
-  ![loi_cls](https://img.shields.io/badge/Chi%20tiết%20CLS-:-blue?style=plastic&logo=github)
   > _**MaCLS**_: `MaCLS` - _**PhieuYC**_: `PhieuYC`
-  ![loi_bo_sung](https://img.shields.io/badge/Chi%20tiết%20bổ%20sung-:-blue?style=plastic&logo=github)
   > _**Khac**_: `Khac`

###### ![mo_ta_loi](https://img.shields.io/badge/Mô%20tả%20thông%20tin%20lỗi-:-blue?style=for-the-badge&logo=github)

Treatment 2/3/2023 thống kê sai thành tiền BV trên phiếu 6556
- Mã hàng 460.202.109: Giá xuất 42 000 000, giá trần thanh toán 32 000 000, thành tiền bệnh viện trên bảng kê ghi 32 000 000 -> số đúng 42 000 000
![ảnh](https://user-images.githubusercontent.com/97272332/223369913-c601e526-70f6-4f36-9361-ae4fd8adcd53.png)
![ảnh](https://user-images.githubusercontent.com/97272332/223370151-5ea52668-02d6-47e1-9dc5-c11ae655e2d1.png)

- Tổng kết chi phí sai số tiền tổng chi phí 69 787 038 -> số đúng 75 787 038
![ảnh](https://user-images.githubusercontent.com/97272332/223370230-92b8f1a7-2b76-4ab7-aeb2-2521411fe368.png)
![ảnh](https://user-images.githubusercontent.com/97272332/223370275-06999416-09e0-456d-964c-66e0fe40e07a.png)

**Comment by chauthanhtra** [comment]
- Em có kiểm tra lại cách hướng dẫn áp trần thanh toán stent 1 thì thấy làm đúng rồi anh
- Phần tổng chi phí vẫn hiện sai số tiền. nó thống kê theo giá trần TT không phải giá xuất
![ảnh](https://user-images.githubusercontent.com/97272332/223888105-1feea33f-460a-4f0c-a244-23df68a3e3c3.png)

- Bảng kê cũng thống kê sai số tiền. tổng số tiền và thành tiền BV cũng sai. thành tiền BV là 42 000 000 và tổng tiền bảng kê phải là 42 000 000 mới đúng
![ảnh](https://user-images.githubusercontent.com/97272332/223888384-7e9e5043-b657-4976-8d93-60172bd636a5.png)

**Comment by vuongdh** [comment]
@chauthanhtra để dữ liệu này anh kiểm tra, hiện tại nó cũng không ảnh hưởng đến quá thanh toán bh và trả tiền của bn phải không?

**Comment by chauthanhtra** [comment]
Dạ Fees đúng, Reports đang lấy giá BH nên cũng gửi được
