### ISSUE TITLE
Lỗi - In toa ngoại trú của thuốc không theo đơn

### ISSUE THREAD

**Issue by chauthanhtra** [dh-hos/dhg.hosptaltreatment#9]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.1: Phiếu ghi nhận lỗi phát sinh DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hosptaltreatment/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN LỖI PHÁT SINH</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Châu Thanh Trà**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **01/08/2022**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `93102`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **Bệnh viện đa Khoa số 10**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `tra_so10_intoaxuatvien`

###### ![chi_tiet_loi](https://img.shields.io/badge/Chi%20tiết%20lỗi%20phát%20sinh-:-blue?style=for-the-badge&logo=github)

-  ![loi_benh_nhan](https://img.shields.io/badge/Chi%20tiết%20bệnh%20nhân-:-blue?style=plastic&logo=github)
   > _**MaBN**_: `2022046973` - _**MaKB**_: `MaKB` - _**MaBA**_: `2022003686` _**NgayKCB**_: `NgayKCB` - _**MaPhong**_: `MaPhong` - _**MaDV**_: `07` - _**ThangKT**_: `07` - _**NamKT**_: `2022`
-  ![loi_thuoc](https://img.shields.io/badge/Chi%20tiết%20thuốc-:-blue?style=plastic&logo=github)
   > _**KhoChan**_: `KhoChan` - _**KhoLe**_: `KhoLe` - _**MaHH**_: `MaHH` - _**SoHD**_: `SoHD` - _**NgayHD**_: `NgayHD` - _**ThangKT**_: `ThangKT` - _**NamKT**_: `NamKT`
-  ![loi_cls](https://img.shields.io/badge/Chi%20tiết%20CLS-:-blue?style=plastic&logo=github)
   > _**MaCLS**_: `MaCLS` - _**PhieuYC**_: `PhieuYC`
-  ![loi_bo_sung](https://img.shields.io/badge/Chi%20tiết%20bổ%20sung-:-blue?style=plastic&logo=github)
   > _**Khac**_: `Khac`

###### ![mo_ta_loi](https://img.shields.io/badge/Mô%20tả%20thông%20tin%20lỗi-:-blue?style=for-the-badge&logo=github)

Khi in toa ngoại trú trên Treatment có thuốc cấu hình không theo đơn thì không in được toa thuốc không theo đơn mà chỉ in được toa thuốc thường
![ảnh](https://user-images.githubusercontent.com/97272332/182116399-6a547cc7-016d-4bf2-90ab-88cf8ebf6017.png)
![ảnh](https://user-images.githubusercontent.com/97272332/182114791-bb5f38ed-0573-4634-9818-25497fbd84d1.png)
![ảnh](https://user-images.githubusercontent.com/97272332/182115127-3a0193f8-f28f-4578-9641-a03bb2b1e73e.png)
![ảnh](https://user-images.githubusercontent.com/97272332/182115219-b5bbb754-4c7a-44cd-b256-e98573af0627.png)

**Comment by vuongdh** [comment]
@nghivanbi Xem dùm lỗi này

**Comment by vuongdh** [comment]
@chauthanhtra em xin key @nghivanbi  rồi test đầy đủ xem

**Comment by vuongdh** [comment]
@nghivanbi xem lại hàm này dùm hén 
HospitalToaThuoc.XtraReports.ClsInToaThuoc.ViewToaThuocTT05_Treat(this, dsToaThuoc, admin, false); 
--> Thuốc không theo đơn

**Comment by vuongdh** [comment]
@nghivanbi xem lại hàm này dùm hén
HospitalToaThuoc.XtraReports.ClsInToaThuoc.ViewToaThuocTT05_Treat(this, dsToaThuoc, admin, false);
--> Thuốc không theo đơn

**Comment by vuongdh** [comment]
@nghivanbi

**Comment by vuongdh** [comment]
Trà xanh mới chịu hén @chauthanhtra
