### ISSUE TITLE
Yêu cầu - Xác định và sàng lọc bệnh án bất thường

### ISSUE THREAD

**Issue by le-an-87** [dh-hos/dhg.hosptaltreatment#90]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.2: Phiếu ghi nhận Yêu cầu mới DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN YÊU CẦU CHỨC NĂNG MỚI</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Ân**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **07/03/2023**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `92118`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **BV Phụ Sản TPCT**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `an_phusan_ct_dutru_tutruc`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`](link_csdl)

###### ![chi_tiet_yeu_cau](https://img.shields.io/badge/Chi%20tiết%20yêu%20cầu%20-:-blue?style=for-the-badge&logo=github)

```
Bổ sung chức năng xác định và sàng lọc bệnh án bất thường!
-> Mục tiêu: đáp ứng tiêu chí chấm điểm bệnh viện.
1. xác định bệnh án bất thường:
   - BS khám và xác định tại Form khám và điều trị.
2. Sàng lọc bệnh án bất thường: bao gồm bệnh đang điều trị và ra viện.
  Bệnh viện đề xuất: Danh sách bệnh nhân form khám và điều trị thay đổi màu đối với bênh án đã xác định bất thường.
-> Đề nghị thêm check lọc bệnh nhân bất thường!

* Chú ý: tiêu chí để xác định bệnh án bất thường do người dùng tự xác định!
```

**Comment by le-an-87** [comment]
Yêu cầu này hiện tại bệnh viện đang cần gấp để chấm điểm bệnh viện đó anh! 
Mấy anh coi có hỗ trợ được không để em báo lại bệnh viện!

**Comment by vuongdh** [comment]
@le-an-87 Yêu cầu ban đầu chỉ có số 1 thôi, em check yêu cầu với đơn vị lại xem sao hén

**Comment by le-an-87** [comment]
Bệnh viện đề xuất tô màu đối với bệnh bất thường thôi anh. em chỉ nói rộng ra chổ đó thôi!
- nếu không xác định được bệnh nhân bất thường thì đâu tô màu bệnh đó được -> 1.
- Việc tô màu bệnh nhân bất thường thì hiển thị ở đâu? -> mình cũng phải hiển thị ở danh sách điều trị để người dùng biết chứ anh. mà trong danh sách điều trị thì có các tab điều trị, ra viện.

*"Đề nghị thêm check lọc bệnh nhân bất thường"* chổ này là em đề xuất thêm cho tiện người dùng sử dụng!
Mấy anh thấy không cần thiết thì bỏ qua nhe!

**Comment by vuongdh** [comment]
[Vương - Mo ta ghi nhan BENH NANG trong noitru.docx](https://github.com/dh-hos/dhg.hosptaltreatment/files/10953428/V.ng.-.Mo.ta.ghi.nhan.BENH.NANG.trong.noitru.docx)

**Comment by nghivanbi** [comment]
Này ok, @vuongdh hỗ trợ theo mô tả nhé

**Comment by le-an-87** [comment]
01/04/2023!

**Comment by le-an-87** [comment]
![image](https://user-images.githubusercontent.com/96155021/230563370-64374596-46b5-4473-9252-e29ca76353ad.png)

Đã bổ sung chức năng xác nhận bệnh nặng và thay đổi trạng thái theo màu!
