### ISSUE TITLE
Lỗi - BV Ô Môn: Sai thông tin phiếu tử vong TT24

### ISSUE THREAD

**Issue by chauthanhtra** [dh-hos/dhg.hosptaltreatment#91]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.1: Phiếu ghi nhận lỗi phát sinh DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN LỖI PHÁT SINH</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Châu Thanh Trà **
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **15/3/2023**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `92007`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **BV Ô Môn**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `tra_timmachct_6556_stent`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`](link_csdl)

###### ![chi_tiet_loi](https://img.shields.io/badge/Chi%20tiết%20lỗi%20phát%20sinh-:-blue?style=for-the-badge&logo=github)

-  ![loi_benh_nhan](https://img.shields.io/badge/Chi%20tiết%20bệnh%20nhân-:-blue?style=plastic&logo=github)
   > _**MaBN**_: `23001733` - _**MaKB**_: `MaKB` - _**MaBA**_: `23000447` _**NgayKCB**_: `NgayKCB` - _**MaPhong**_: `MaPhong` - _**MaDV**_: `18` - _**ThangKT**_: `03` - _**NamKT**_: `2023`
-  ![loi_thuoc](https://img.shields.io/badge/Chi%20tiết%20thuốc-:-blue?style=plastic&logo=github)
   > _**KhoChan**_: `KhoChan` - _**KhoLe**_: `KhoLe` - _**MaHH**_: `MaHH` - _**SoHD**_: `SoHD` - _**NgayHD**_: `NgayHD` - _**ThangKT**_: `ThangKT` - _**NamKT**_: `NamKT`
-  ![loi_cls](https://img.shields.io/badge/Chi%20tiết%20CLS-:-blue?style=plastic&logo=github)
   > _**MaCLS**_: `MaCLS` - _**PhieuYC**_: `PhieuYC`
-  ![loi_bo_sung](https://img.shields.io/badge/Chi%20tiết%20bổ%20sung-:-blue?style=plastic&logo=github)
   > _**Khac**_: `Khac`

###### ![mo_ta_loi](https://img.shields.io/badge/Mô%20tả%20thông%20tin%20lỗi-:-blue?style=for-the-badge&logo=github)

(data test)

Phiếu Chẩn đoán nguyên nhân tử vong TT24 khi in ra bị lỗi:
- .14. Không lấy được Tôn giáo 
- .24. Ngày vào viện/TV (sai)-> Ngày ra viện/TV
- .24. Thời gian ra viện lấy thành thời gian vào viện
- .3. Hình thức tử vong khi chọn không biết thì tự check thêm Can thiệp pháp lý
- .4b. Nơi xảy ra nguyên nhân bên ngoài khi chọn Không biết thì tự check thêm Khu thương mại dịch vụ
- Các bảng bị thiếu đường kẻ khung khi in ra

![ảnh](https://user-images.githubusercontent.com/97272332/225196758-1aae3b2b-67be-4fb5-8398-c6c59f16bb17.png)

**Comment by vuongdh** [comment]
@chauthanhtra  ngày vào viện đúng là ngày nào?

**Comment by chauthanhtra** [comment]
Ngày ra viện/TV chứ không phải ngày vào viện anh

**Comment by chauthanhtra** [comment]
Mục số 24 sai cái nhãn Ngày ra viện/TV mới đúng
ngày ra viện là 15/03/02023 09:41

**Comment by chauthanhtra** [comment]
Treatment mới vẫn còn sai nha anh
- Mục 24: Ngày vào viên/TV là sai -> Ngày ra viện/TV mới đúng
- Mục 24: Ngày ra viện/ TV đang lấy ngày giờ in -> sai
- Đường kẻ khung khi in ra còn bị thiếu

![ảnh](https://user-images.githubusercontent.com/97272332/225808240-00763152-1d3f-471c-8824-13aeb25e430a.png)
