### ISSUE TITLE
Yêu cầu - Phiếu lĩnh thể hiện hạn dùng của thuốc.

### ISSUE THREAD

**Issue by lqbinh1987** [dh-hos/dhg.hosptaltreatment#94]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.2: Phiếu ghi nhận Yêu cầu mới DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN YÊU CẦU CHỨC NĂNG MỚI</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Bình**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **20/03/2023**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `mabvbh`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **BV Q12**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `binh_bvq12`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`](link_csdl)

###### ![chi_tiet_yeu_cau](https://img.shields.io/badge/Chi%20tiết%20yêu%20cầu%20-:-blue?style=for-the-badge&logo=github)

Dề nghị khi In mẫu Phiếu Lĩnh theo TT23 như hình bên dưới, trong cột **Mã số**, ngoài thông tin mã thuốc thì **thể hiện thêm hạn dùng của thuốc trong ngoặc** tương tự như mẫu này ở SecondStore.

SecondStore
![image](https://user-images.githubusercontent.com/99630883/226288666-4c744927-f1ef-4f60-bd91-d1e2dd2c517c.png)

Treatment
![image](https://user-images.githubusercontent.com/99630883/226288756-f570405e-798d-4b3a-b9be-f56696eaa446.png)

**Comment by vuongdh** [comment]
@nghivanbi secondstore thực hiện theo tham số nào vậy?

**Comment by vuongdh** [comment]
@lqbinh1987 test coi thực hiện theo tham số nào hén

**Comment by lqbinh1987** [comment]
@vuongdh tham số này nt.phieulinh=1 nhe anh.

**Comment by vuongdh** [comment]
@lqbinh1987 ý anh là tham số để có hạng dụng chung với mã hàng hóa

**Comment by lqbinh1987** [comment]
Này làm riêng theo BV nhe anh @vuongdh .
Nhờ anh hỗ trợ cho BV dùm em.

**Comment by vuongdh** [comment]
@lqbinh1987 khoa nào? tháng mấy? không thấy thông tin này để test

**Comment by lqbinh1987** [comment]
Khoa Nội, số tổng TH 000001, tháng kế toán hiện tại của dữ liệu.
Hình phía trên á anh @vuongdh

**Comment by vuongdh** [comment]
@lqbinh1987 anh gửi bản cập nhật qua zalo hén

**Comment by lqbinh1987** [comment]
Đã ok rồi anh @vuongdh , nhưng còn phiếu VTYT nữa nhe anh, sau khi show phiếu thuốc lên rồi, in xong nó hiện phiếu VTYT lên, trên mẫu VTYT chưa hiện hạng dùng. Do lúc đầu e yêu cầu thiếu, nhờ anh bổ sung thêm dùm em nhe, Thanks anh.
