### ISSUE TITLE
Lỗi - Tên thuốc trên toa giữa Treatment và Prescription không thống nhất với nhau

### ISSUE THREAD

**Issue by le-an-87** [dh-hos/dhg.hosptaltreatment#98]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.1: Phiếu ghi nhận lỗi phát sinh DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN LỖI PHÁT SINH</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Ân**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **27/03/2023**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `60152`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **BV Tâm Phúc**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `an_tamphuc_toathuoc_dachat`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`](link_csdl)

###### ![chi_tiet_loi](https://img.shields.io/badge/Chi%20tiết%20lỗi%20phát%20sinh-:-blue?style=for-the-badge&logo=github)

-  ![loi_benh_nhan](https://img.shields.io/badge/Chi%20tiết%20bệnh%20nhân-:-blue?style=plastic&logo=github)
   > _**MaBN**_: `2023010576` - _**MaKB**_: `2303004792` - _**MaBA**_: `2023001049` _**NgayKCB**_: `25/03/2023` - _**MaDV**_: `03` - _**ThangKT**_: `03` - _**NamKT**_: `2023`
-  ![loi_thuoc](https://img.shields.io/badge/Chi%20tiết%20thuốc-:-blue?style=plastic&logo=github)
   > _**KhoChan**_: `14` - _**KhoLe**_: `01` - _**MaHH**_: `KL03` - _**SoHD**_: `HS0.R23.0325.082040` - _**NgayHD**_: `25/03/2023` - _**ThangKT**_: `03` - _**NamKT**_: `2023`

###### ![mo_ta_loi](https://img.shields.io/badge/Mô%20tả%20thông%20tin%20lỗi-:-blue?style=for-the-badge&logo=github)

```
Tên thuốc trên toa không thống nhất giữa Treatment và Prescription
Tham số tt05 = 4
thuốc KL03 -> đa chất
 - Treatment hiển thị có tên hoạt chất
 - Prescription không hiển thị tên hoạt chất
```
![image](https://user-images.githubusercontent.com/96155021/227818672-77c11e1d-d448-4ada-a1c4-0ced43090849.png)

**Comment by nghivanbi** [comment]
Theo qui tắc đa chất không hiển thị hoạt chất nha @vuongdh .

**Comment by vuongdh** [comment]
@vuongdh còn xót chổ này chưa bắt theo đa chất

**Comment by vuongdh** [comment]
@le-an-87  bản fix [Treat4.20230327v1](http://www.fsend.vn/download/SOK2N8e6yoY2S3G0rwCrM_x39Q7DCopa)

**Comment by le-an-87** [comment]
đã fix!
